{$DEFINE DEBUG      }
{$DEFINE DEBUG1     }
{$DEFINE TEST       }
{$DEFINE TEST2      }
{$DEFINE TEST3      }
{$DEFINE TEST4      }

{$DEFINE HISIZE     }
{$DEFINE SBSIZE     }
{$DEFINE WANT_TIM   }

{$DEFINE WANT_SPC1   }   { activate SP over-/underrun handling 0000<->FFFF }
{$DEFINE WANT_PCC   }	{ activate PC overrun        handling FFFF->0000 }
{$DEFINE CNTL_C	    }	{ cntl-c will stop running emulation }
{$DEFINE CNTL_BS    }	{ cntl-\ will stop running emulation }
{$DEFINE WANT_TIM   }	{ activate runtime measurement }
{$DEFINE USR_COM    }
