'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1


                                ;--------------------------\            ; Vorspann fuer BIN-Datei
  0000*   EF                                DB      0EFH                ; Startbyte ---> 
  0001*                                     DS      12,0
  000D*   02                                DB      002H                ; HS-Bereich : 2
  000E*   8000                              DW      08000H              ; Ladeadresse: 8000H
                                ;--------------------------/
                                
                         C                  INCLUDE S21EQU1.MAC
  00E0                   C      S0.PROM     EQU     0E0H
  0050                   C      S0.SPANZ    EQU     80
  0018                   C      S0.ZANZ     EQU     24
  A000                   C      S0.BWSA     EQU     0A000H
  B7E0                   C      S0.PFFI     EQU     0B7E0H
  BBF0                   C      S0.PFFA     EQU     0BBF0H
                         C      ;
  B134                   C      K2.SKADR    EQU     0B134H
  B136                   C      K2.FRADR    EQU     0B136H
                         C      ;
  B18A                   C      MS.ZPOL     EQU     0B18AH
  B18B                   C      MS.SPOL     EQU     MS.ZPOL+1
  B18C                   C      MS.ZPOS     EQU     MS.SPOL+1
  B18D                   C      MS.SPOS     EQU     MS.ZPOS+1
  B18E                   C      MS.ZMIN     EQU     MS.SPOS+1
  B18F                   C      MS.SMIN     EQU     MS.ZMIN+1
  B190                   C      MS.ZMAX     EQU     MS.SMIN+1
  B191                   C      MS.SMAX     EQU     MS.ZMAX+1
  B192                   C      MS.ZANZ     EQU     MS.SMAX+1
  B193                   C      MS.SPANZ    EQU     MS.ZANZ+1
  B194                   C      MS.BWSA     EQU     MS.SPANZ+1
  B196                   C      MS.DIRDEL   EQU     MS.BWSA+2
  B197                   C      MS.DIRES    EQU     MS.DIRDEL+1
  B198                   C      MS.CMD      EQU     MS.DIRES+1
  B199                   C      MS.TK       EQU     MS.CMD+1
  B19A                   C      MS.RADR     EQU     MS.TK+1
  B19C                   C      MS.MCZ      EQU     MS.RADR+2
  B19D                   C      MS.MCUR     EQU     MS.MCZ+1
  B19E                   C      MS.CZEIT    EQU     MS.MCUR+1
                         C      ;
  B19F                   C      TS.TAB1     EQU     0B19FH
  B1FF                   C      TS.TAB2     EQU     TS.TAB1+60H
  B217                   C      TS.TAB3     EQU     TS.TAB2+18H
  B223                   C      TS.TAB4     EQU     TS.TAB3+0CH
  B22D                   C      TS.EINA     EQU     TS.TAB4+0AH
  B22F                   C      TS.TABU     EQU     TS.EINA+2
  B231                   C      TS.NEWL     EQU     TS.TABU+2
  B233                   C      TS.TAB5     EQU     TS.NEWL+2
  B23B                   C      TS.PTAST    EQU     TS.TAB5+8
  B23C                   C      TS.TK       EQU     TS.PTAST+1
  B23D                   C      TS.PTK      EQU     TS.TK+1
  B23E                   C      TS.EMERK    EQU     TS.PTK+1
  B23F                   C      TS.SPMER    EQU     TS.EMERK+1
  B240                   C      TS.UMERK    EQU     TS.SPMER+1
  B241                   C      TS.KGMER    EQU     TS.UMERK+1
  B242                   C      TS.ZSMER    EQU     TS.KGMER+1
  B243                   C      TS.ZEIT1    EQU     TS.ZSMER+1
  B244                   C      TS.ZEIT2    EQU     TS.ZEIT1+1
  B245                   C      TS.ZEI21    EQU     TS.ZEIT2+1
  B246                   C      TS.ZSTC     EQU     TS.ZEI21+1
  B247                   C      TS.MIO      EQU     TS.ZSTC+1
  B248                   C      TS.MBF      EQU     TS.MIO+1
  B249                   C      TS.BFOL1    EQU     TS.MBF+1
  B24B                   C      TS.BFOL2    EQU     TS.BFOL1+2
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-1


  B24D                   C      TS.STACK    EQU     TS.BFOL2+2
                         C      ;
  B262                   C      S2.ZZ       EQU     0B262H
  B263                   C      S2.CST      EQU     S2.ZZ+1
  B264                   C      S2.IOC      EQU     S2.CST+1
  B265                   C      S2.PRGN     EQU     S2.IOC+1
  B26B                   C      S2.DNR      EQU     S2.PRGN+6
  B26C                   C      S2.RBBR     EQU     S2.DNR+1
  B26E                   C      S2.AADR     EQU     S2.RBBR+2
  B270                   C      S2.KADR     EQU     S2.AADR+2
  B272                   C      S2.ZP       EQU     S2.KADR+2
  B273                   C      S2.SP1      EQU     S2.ZP+1
  B274                   C      S2.SP2      EQU     S2.SP1+1
  B275                   C      S2.SP3      EQU     S2.SP2+1
  B276                   C      S2.TRB      EQU     S2.SP3+1
  B28A                   C      S2.AFOR     EQU     S2.TRB+20
  B28B                   C      S2.BZ       EQU     S2.AFOR+1
  B28C                   C      S2.TE       EQU     S2.BZ+1
  B28E                   C      S2.DL       EQU     S2.TE+2
  B28F                   C      S2.DH       EQU     S2.DL+1
  B290                   C      S2.PAR1     EQU     S2.DH+1
  B292                   C      S2.DMANF    EQU     S2.PAR1+2           ;Pufferadresse? S0.PFFI
  B294                   C      S2.DMCUR    EQU     S2.DMANF+2
  B296                   C      S2.DMBA     EQU     S2.DMCUR+2
  B298                   C      S2.DMBE     EQU     S2.DMBA+2
  B29A                   C      S2.DM1      EQU     S2.DMBE+2
  B2AA                   C      S2.DM2      EQU     S2.DM1+16
  B2AB                   C      S2.DMH      EQU     S2.DM2+1
  B2AC                   C      S2.DML      EQU     S2.DMH+1
  B2AD                   C      S2.SMHL     EQU     S2.DML+1
  B2AF                   C      S2.S1       EQU     S2.SMHL+2
  B2B0                   C      S2.S2       EQU     S2.S1+1
  B2B8                   C      S2.DDEI     EQU     S2.S2+8
                         C      ;
                         C                  INCLUDE S21EQU2.MAC
  C02D                   C      S1.SM       EQU     0C02DH
  C82E                   C      S1.DB111    EQU     0C82EH
  C86E                   C      S1.EINDB    EQU     0C86EH
  C8B0                   C      S1.ANZU1    EQU     0C8B0H
  C8C0                   C      S1.ANZU2    EQU     0C8C0H
  C8CD                   C      S1.SYDB2    EQU     0C8CDH
  C114                   C      S1.SYSTB    EQU     0C114H
  C2B4                   C      S1.CNRS     EQU     0C2B4H
  C2D3                   C      S1.CNLS     EQU     0C2D3H
  C328                   C      S1.AEIN     EQU     0C328H
  C334                   C      S1.NN       EQU     0C334H
  C345                   C      S1.NNN      EQU     0C345H
  C3BF                   C      S1.ANZEI    EQU     0C3BFH
  C532                   C      S1.INPTR    EQU     0C532H
  C54E                   C      S1.HDI      EQU     0C54EH
  C592                   C      S1.IDH      EQU     0C592H
  C5CC                   C      S1.HBKON    EQU     0C5CCH
  C5FF                   C      S1.BHKON    EQU     0C5FFH
  C652                   C      S1.CHK      EQU     0C652H
  C935                   C      S1.MEAA     EQU     0C935H
  C995                   C      S1.HXN1     EQU     0C995H
  C9E4                   C      S1.MEAU2    EQU     0C9E4H
                         C      ;
  CB16                   C      MO.MONI     EQU     0CB16H
  CB45                   C      MO.BWSUS    EQU     0CB45H
  CD9F                   C      MO.ROLL     EQU     0CD9FH
  CF4B                   C      MO.BWSE     EQU     0CF4BH
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-2


  CF52                   C      MO.PNSP     EQU     0CF52H
                         C      ;
  D40E                   C      TA.LOE      EQU     0D40EH
  D426                   C      TA.LOES     EQU     0D426H
                         C      ;
  D551                   C      K1.ARMB     EQU     0D551H
  D5B7                   C      K1.ARBT     EQU     0D5B7H
  D5C2                   C      K1.BLKP     EQU     0D5C2H
  D5D0                   C      K1.BLKM     EQU     0D5D0H
  D5DE                   C      K1.RCZP     EQU     0D5DEH
  D5EC                   C      K1.RCZM     EQU     0D5ECH
  D5FA                   C      K1.RCZN     EQU     0D5FAH
  D602                   C      K1.LHLBC    EQU     0D602H
  D60F                   C      K1.BM       EQU     0D60FH
  D615                   C      K1.F17      EQU     0D615H
  D62D                   C      K1.RGL1     EQU     0D62DH
  D63E                   C      K1.RGL2     EQU     0D63EH
  D6F1                   C      K1.GNSTS    EQU     0D6F1H
  D748                   C      K1.GNRE     EQU     0D748H
  D765                   C      K1.GNRA     EQU     0D765H
  D780                   C      K1.GNRW     EQU     0D780H
  D7A5                   C      K1.GNRP     EQU     0D7A5H
  D7C0                   C      K1.GNRM     EQU     0D7C0H
  D7F1                   C      K1.GNLP     EQU     0D7F1H
  D7F3                   C      K1.GNLPN    EQU     0D7F3H
  D82B                   C      K1.GNLMN    EQU     0D82BH
  D89B                   C      K1.GNRD     EQU     0D89BH
  D8B0                   C      K1.PUFT     EQU     0D8B0H
  D90B                   C      K1.GNWR     EQU     0D90BH
  D92F                   C      K1.GNRWR    EQU     0D92FH
                         C      ;
  DF0C                   C      LO.EIN      EQU     0DF0CH
  E279                   C      LO.EIN1     EQU     0E279H
                         C      ;
  E697                   C      S9.CIN      EQU     0E697H
  E6CB                   C      S9.CSTSX    EQU     0E6CBH
  E6E6                   C      S9.CON      EQU     0E6E6H
  EE98                   C      S9.SAVE     EQU     0EE98H
  EEB8                   C      S9.LOAD     EQU     0EEB8H
                         C      ;
  F60F                   C      S0.BWSUS    EQU     0F60FH
                                
                                            .PHASE  08000H
                                ;           PN      D010
                                ;****************************************************************
                                ;*	             D  E  B  U  G   ---   Steuerprogramm           *
                                ;*  Version      -----------------------------------------------*
                                ;*               Programmierer: Marcus Herbote   --- IfR - OE-S *
                                ;*  V 1 . 0      -----------------------------------------------*
                                ;                Stand        : 11.Januar 1983                  *
                                ;****************************************************************
  8000    18 1A                             JR      D0.DD
  8002    56 31 2E 30                       DB      'V1.0/110183'
  8006    2F 31 31 30           
  800A    31 38 33              
  800D    800D                              DW      $
  800F    44 42 55 47                       DB      'DBUG'
  8013    F3                                DI
  8014    3E 05                             LD      A,5                 ;Zeile 1 bis 22 loeschen
  8016    32 B198                           LD      (MS.CMD),A
  8019    CD CB16                           CALL    MO.MONI
  801C    3E 02                 D0.DD:      LD      A,2
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-3


  801E    32 B198                           LD      (MS.CMD),A
  8021    CD CB16                           CALL    MO.MONI
  8024    21 8182                           LD      HL,D0.DDPTB-4       ;Anzeige der aktiven P-Tasten
  8027    11 809A                           LD      DE,D0.DDPT
  802A    01 0024                           LD      BC,36
  802D    CD 8C0C                           CALL    D0.TA02
  8030    21 0000                           LD      HL,0                ;ZPOS = 0 , SPOS = 0
  8033    22 B18C                           LD      (MS.ZPOS),HL
  8036    06 29                             LD      B,DD1-DD0
  8038    21 8040                           LD      HL,DD0
  803B    CD CB16                           CALL    MO.MONI             ;Anzeige der DEBUG-Version
  803E    18 29                             JR      DD1                 ;$+43
                                
  8040    44 45 42 55           DD0:        DB      'DEBUG ---  Version 1.0     '
  8044    47 20 2D 2D           
  8048    2D 20 20 56           
  804C    65 72 73 69           
  8050    6F 6E 20 31           
  8054    2E 30 20 20           
  8058    20 20 20              
  805B    41 75 73 77                       DB      'Auswahlanzeige'
  805F    61 68 6C 61           
  8063    6E 7A 65 69           
  8067    67 65                 
                                
  8069    3E 14                 DD1:        LD      A,20
  806B    32 B198                           LD      (MS.CMD),A
  806E    21 3412                           LD      HL,03412H           ;ZPOS = 18 , SPOS = 52
  8071    01 1A02                           LD      BC,01A02H           ;Laenge:26 , Breite: 2
  8074    CD 88A7                           CALL    D0.DDU18            ;Fensterrahmen fuer Eingabebereich aufb.
  8077    21 4014                           LD      HL,04014H           ;ZMIN = 20 , SMIN = 64
  807A    22 B18E                           LD      (MS.ZMIN),HL
  807D    21 4F15                           LD      HL,04F15H           ;ZMAX = 21 , SMAX = 79
  8080    22 B190                           LD      (MS.ZMAX),HL
  8083    21 3513                           LD      HL,03513H           ;ZPOS = 19 , SPOS = 53
  8086    22 B18C                           LD      (MS.ZPOS),HL
  8089    3E C0                             LD      A,0C0H
  808B    32 B197                           LD      (MS.DIRES),A
  808E    21 C114                           LD      HL,S1.SYSTB         ;SYS - Taste
  8091    22 B21D                           LD      (TS.TAB3+6),HL
  8094    3E 80                             LD      A,080H              ;Funktionstasten aktivieren
  8096    32 B23F                           LD      (TS.SPMER),A
  8099    C9                                RET
                                            TITLE    'Tastaturtabellen'
                                            PAGE
'Tastaturtabellen'	MACRO-80 3.44	09-Dec-81	PAGE	1-4


                                
                                ;****************************************************************
                                ;*	                     Tastaturtabellen                       *
                                ;****************************************************************
  809A    83C7                  D0.DDPT:    DW      D0.MEDC
  809C    8663                              DW      D0.RCDC
  809E    8664                              DW      D0.RGDC
  80A0    8663                              DW      D0.LOAD
  80A2    8663                              DW      D0.SAVE
  80A4    8664                              DW      D0.UCPU
  80A6    85EB                              DW      D0.RAMT
  80A8    840E                              DW      D0.ROMT
  80AA    8663                              DW      D0.REAS
  80AC    0000                              DW      0
  80AE    852A                              DW      D0.PROM
  80B0    0000                              DW      0
  80B2    8250                              DW      D0.IN
  80B4    82B6                              DW      D0.OUT
  80B6    0000                              DW      0
  80B8    8320                              DW      D0.ADD
  80BA    8376                              DW      D0.SUB
                                ;            
  80BC    8BE6                  D0.DDPT2:   DW      D0.AW
  80BE    8BE6                              DW      D0.AW
  80C0    8BE6                              DW      D0.AW
  80C2    8BE6                              DW      D0.AW
  80C4    8BE6                              DW      D0.AW
                                ;
  80C6    48 65 78 61           D0.DDPT3:   DB      'HexaDeziOct Bin Alfa----'
  80CA    44 65 7A 69           
  80CE    4F 63 74 20           
  80D2    42 69 6E 20           
  80D6    41 6C 66 61           
  80DA    2D 2D 2D 2D           
  80DE    2D 2D 2D 2D                       DB      '------------------------'
  80E2    2D 2D 2D 2D           
  80E6    2D 2D 2D 2D           
  80EA    2D 2D 2D 2D           
  80EE    2D 2D 2D 2D           
  80F2    2D 2D 2D 2D           
  80F6    2D 2D 2D 2D                       DB      '------------------------'
  80FA    2D 2D 2D 2D           
  80FE    2D 2D 2D 2D           
  8102    2D 2D 2D 2D           
  8106    2D 2D 2D 2D           
  810A    2D 2D 2D 2D           
  810E    2D 2D 2D 2D                       DB      '------------------------'
  8112    2D 2D 2D 2D           
  8116    2D 2D 2D 2D           
  811A    2D 2D 2D 2D           
  811E    2D 2D 2D 2D           
  8122    2D 2D 2D 2D           
  8126    2D 2D 2D 2D                       DB      '------------------------'
  812A    2D 2D 2D 2D           
  812E    2D 2D 2D 2D           
  8132    2D 2D 2D 2D           
  8136    2D 2D 2D 2D           
  813A    2D 2D 2D 2D           
  813E    2D 2D 2D 2D                       DB      '------------------------'
  8142    2D 2D 2D 2D           
  8146    2D 2D 2D 2D           
'Tastaturtabellen'	MACRO-80 3.44	09-Dec-81	PAGE	1-5


  814A    2D 2D 2D 2D           
  814E    2D 2D 2D 2D           
  8152    2D 2D 2D 2D           
  8156    2D 2D 2D 2D                       DB      '------------------------'
  815A    2D 2D 2D 2D           
  815E    2D 2D 2D 2D           
  8162    2D 2D 2D 2D           
  8166    2D 2D 2D 2D           
  816A    2D 2D 2D 2D           
  816E    2D 2D 2D 2D                       DB      '------------------------'
  8172    2D 2D 2D 2D           
  8176    2D 2D 2D 2D           
  817A    2D 2D 2D 2D           
  817E    2D 2D 2D 2D           
  8182    2D 2D 2D 2D           
                                ;
  8186    4D 65 44 43           D0.DDPTB:   DB      'MeDCRcDCRgDCLOADSAVEuCPU'
  818A    52 63 44 43           
  818E    52 67 44 43           
  8192    4C 4F 41 44           
  8196    53 41 56 45           
  819A    75 43 50 55           
  819E    52 41 4D 54                       DB      'RAMTROMTREAS----PROM----'
  81A2    52 4F 4D 54           
  81A6    52 45 41 53           
  81AA    2D 2D 2D 2D           
  81AE    50 52 4F 4D           
  81B2    2D 2D 2D 2D           
  81B6    49 4E 20 20                       DB      'IN  OUT ----ADD SUB ----'
  81BA    4F 55 54 20           
  81BE    2D 2D 2D 2D           
  81C2    41 44 44 20           
  81C6    53 55 42 20           
  81CA    2D 2D 2D 2D           
  81CE    2D 2D 2D 2D                       DB      '------------------------'
  81D2    2D 2D 2D 2D           
  81D6    2D 2D 2D 2D           
  81DA    2D 2D 2D 2D           
  81DE    2D 2D 2D 2D           
  81E2    2D 2D 2D 2D           
  81E6    2D 2D 2D 2D                       DB      '------------------------'
  81EA    2D 2D 2D 2D           
  81EE    2D 2D 2D 2D           
  81F2    2D 2D 2D 2D           
  81F6    2D 2D 2D 2D           
  81FA    2D 2D 2D 2D           
  81FE    2D 2D 2D 2D                       DB      '------------------------'
  8202    2D 2D 2D 2D           
  8206    2D 2D 2D 2D           
  820A    2D 2D 2D 2D           
  820E    2D 2D 2D 2D           
  8212    2D 2D 2D 2D           
  8216    2D 2D 2D 2D                       DB      '------------------------'
  821A    2D 2D 2D 2D           
  821E    2D 2D 2D 2D           
  8222    2D 2D 2D 2D           
  8226    2D 2D 2D 2D           
  822A    2D 2D 2D 2D           
  822E    2D 2D 2D 2D                       DB      '------------------------'
  8232    2D 2D 2D 2D           
  8236    2D 2D 2D 2D           
  823A    2D 2D 2D 2D           
'Tastaturtabellen'	MACRO-80 3.44	09-Dec-81	PAGE	1-6


  823E    2D 2D 2D 2D           
  8242    2D 2D 2D 2D           
                                
                                            TITLE   'Funktion : IN '
                                            PAGE
'Funktion : IN '	MACRO-80 3.44	09-Dec-81	PAGE	1-7


                                
                                ;****************************************************************
                                ;*	                     D E B U G   -   Funktion :  IN         *
                                ;****************************************************************
  8246    49 4E 20 2D           D0.TIN1:    DB      'IN -Adr '
  824A    41 64 72 20           
  824E    3A 20                 D0.TPQ:     DB      ': '
  8250    CD 8C29               D0.IN:      CALL    D0.TA03
  8253    21 8273                           LD      HL,D0.INPQ
  8256    11 8246                           LD      DE,D0.TIN1
                                ;            
  8259    22 B223               D0.IN1:     LD      (TS.TAB4),HL
  825C    ED 53 B28C                        LD      (S2.TE),DE
  8260    21 0000                           LD      HL ,0
  8263    22 B28E               D0.IN2:     LD      (S2.DL),HL
  8266    CD 8AB2                           CALL    D0.AL
  8269    CD 8BF3                           CALL    D0.TA01
  826C    21 801C                           LD      HL,D0.DD
  826F    22 B21D                           LD      (TS.TAB3+6),HL
  8272    C9                                RET
                                ;
                                ;
                                ;
  8273    06 08                 D0.INPQ:    LD      B,8
  8275    21 8246                           LD      HL,D0.TIN1
  8278    CD 8713                           CALL    D0.PQ14
  827B    21 B18D                           LD      HL,MS.SPOS
  827E    34                                INC     (HL)
  827F    34                                INC     (HL)
  8280    06 08                             LD      B,8
  8282    21 82AE                           LD      HL,D0.TIO1
  8285    CD CB16                           CALL    MO.MONI
  8288    06 02                             LD      B,2
  828A    21 824E                           LD      HL,D0.TPQ
  828D    CD CB16                           CALL    MO.MONI
                                ;
  8290    ED 4B B290                        LD      BC,(S2.PAR1)
  8294    ED 78                             IN      A,(C)
                                ;
  8296    21 B29A                           LD      HL,S2.DM1
  8299    CD C5FF                           CALL    S1.BHKON
  829C    06 02                             LD      B,2
  829E    21 B29A                           LD      HL,S2.DM1
  82A1    CD CB16                           CALL    MO.MONI
  82A4    18 AA                             JR      D0.IN
                                
                                            TITLE   'Funktion :   OUT '
                                            PAGE
'Funktion :   OUT '	MACRO-80 3.44	09-Dec-81	PAGE	1-8


                                
                                ;****************************************************************
                                ;*	                     D E B U G   -   Funktion :  OUT        *
                                ;****************************************************************
  82A6    4F 55 54 2D           D0.TOUT1:   DB      'OUT-Adr '
  82AA    41 64 72 20           
  82AE    44 61 74 65           D0.TIO1:    DB      'Daten   '
  82B2    6E 20 20 20           
  82B6    CD 8C29               D0.OUT:     CALL    D0.TA03
  82B9    21 82C1                           LD      HL,D0.OUPQ1
  82BC    11 82A6                           LD      DE,D0.TOUT1
  82BF    18 98                 D0.OUT1:    JR	    D0.IN1
                                ;
                                ;
                                ;
  82C1    06 08                 D0.OUPQ1:   LD      B,8
  82C3    21 82A6                           LD      HL,D0.TOUT1
  82C6    CD 8713                           CALL    D0.PQ14
  82C9    21 82E8                           LD      HL,D0.OUPQ2
  82CC    11 82AE                           LD      DE,D0.TIO1
  82CF    22 B223                           LD      (TS.TAB4),HL
  82D2    ED 53 B28C                        LD      (S2.TE),DE
  82D6    21 0000                           LD      HL,0
  82D9    22 B28E                           LD      (S2.DL),HL
  82DC    AF                                XOR     A
  82DD    32 B28A                           LD      (S2.AFOR),A
  82E0    3C                                INC     A
  82E1    32 B28B                           LD      (S2.BZ),A
  82E4    CD 8AB2                           CALL    D0.AL
  82E7    C9                                RET
                                ;
                                ;
                                ;
  82E8    CD 8A11               D0.OUPQ2:   CALL    D0.AS
  82EB    21 100A                           LD      HL,0100AH           ;ZPOS = 10 , SPOS = 16	
  82EE    CD 88D2                           CALL    D0.DDU19	
  82F1    06 08                             LD      B,8	
  82F3    21 82AE                           LD      HL,D0.TIO1	
  82F6    CD CB16                           CALL    MO.MONI	
  82F9    06 02                             LD      B,2	
  82FB    21 824E                           LD      HL,D0.TPQ	
  82FE    CD CB16                           CALL    MO.MONI
  8301    CD 8C57                           CALL    D0.AH1
                                ;
  8304    ED 4B B290                        LD      BC,(S2.PAR1)
  8308    3A B28E                           LD      A,(S2.DL)
  830B    ED 79                             OUT     (C),A
                                ;
  830D    18 A7                             JR      D0.OUT
                                
                                            TITLE   'Funktion :   ADD '
                                            PAGE
'Funktion :   ADD '	MACRO-80 3.44	09-Dec-81	PAGE	1-9


                                
                                ;****************************************************************
                                ;*	                     D E B U G   -   Funktion :  ADD        *
                                ;****************************************************************
  830F    41 44 44 20           D0.TAD1:    DB      'ADD    A'
  8313    20 20 20 41           
  8317    41 44 44 20           D0.TAD2:    DB      'ADD   +B='
  831B    20 20 2B 42           
  831F    3D                    
  8320    CD 8C29               D0.ADD:     CALL    D0.TA03
  8323    21 832B                           LD      HL,D0.ADPQ1
  8326    11 830F                           LD      DE,D0.TAD1
  8329    18 94                 D0.ADD1:    JR      D0.OUT1
                                ;
                                ;
                                ;
  832B    06 07                 D0.ADPQ1:   LD      B,7
  832D    21 830F                           LD      HL,D0.TAD1
  8330    CD 8713                           CALL    D0.PQ14
  8333    06 01                             LD      B,1
  8335    21 831D                           LD      HL,D0.TAD2+6
  8338    CD CB16                           CALL    MO.MONI
  833B    21 8343                           LD      HL,D0.ADPQ2
  833E    11 8317                           LD      DE,D0.TAD2
  8341    18 E6                             JR      D0.ADD1
                                ;
                                ;
                                ;
  8343    CD 8A11               D0.ADPQ2:   CALL    D0.AS
  8346    21 0E0A                           LD      HL,00E0AH           ;ZPOS = 10 , SPOS = 14
  8349    CD 88D2                           CALL    D0.DDU19
  834C    CD 8C69                           CALL    D0.AH2
  834F    06 01                             LD      B,1
  8351    21 831F                           LD      HL,D0.TAD2+8
  8354    CD CB16                           CALL    MO.MONI
                                ;
  8357    2A B290                           LD      HL,(S2.PAR1)
  835A    ED 5B B28E                        LD      DE,(S2.DL)
  835E    19                                ADD     HL,DE
  835F    22 B28E                           LD      (S2.DL),HL
                                ;
  8362    CD 8C69                           CALL    D0.AH2
  8365    18 B9                             JR      D0.ADD
                                
                                            TITLE   'Funktion :   SUB '
                                            PAGE
'Funktion :   SUB '	MACRO-80 3.44	09-Dec-81	PAGE	1-10


                                
                                ;****************************************************************
                                ;*	                     D E B U G   -   Funktion :  SUB        *
                                ;****************************************************************
  8367    53 55 42 20           D0.TSB1:    DB      'SUB     A'
  836B    20 20 20 20           
  836F    41                    
  8370    53 55 42 09           D0.TSB2:    DB      'SUB	-B'
  8374    2D 42                 
  8376    CD 8C29               D0.SUB:     CALL    D0.TA03
  8379    21 8381                           LD      HL,D0.SBPQ1
  837C    11 8367                           LD      DE,D0.TSB1
  837F    18 A8                 D0.SUB1:    JR      D0.ADD1
                                ;
                                ;
                                ;
  8381    06 07                 D0.SBPQ1:   LD      B,7
  8383    21 8367                           LD      HL,D0.TSB1
  8386    CD 8713                           CALL    D0.PQ14
  8389    06 01                             LD      B,1
  838B    21 8376                           LD      HL,D0.TSB2+6
  838E    CD CB16                           CALL    MO.MONI
  8391    21 8399                           LD      HL,D0.SBPQ2
  8394    11 8370                           LD      DE,D0.TSB2
  8397    18 E6                             JR      D0.SUB1
                                ;
                                ;
                                ;
  8399    CD 8A11               D0.SBPQ2:   CALL    D0.AS
  839C    21 0E0A                           LD      HL,00E0AH           ;ZPOS = 10 , SPOS = 14
  839F    CD 88D2                           CALL    D0.DDU19
  83A2    CD 8C69                           CALL    D0.AH2
  83A5    06 01                             LD      B,1
  83A7    21 831F                           LD      HL,D0.TAD2+8
  83AA    CD CB16                           CALL    MO.MONI
                                ;
  83AD    2A B290                           LD      HL,(S2.PAR1)
  83B0    ED 5B B28E                        LD      DE,(S2.DL)
  83B4    AF                                XOR     A
  83B5    ED 52                             SBC     HL,DE
  83B7    22 B28E                           LD      (S2.DL),HL
                                ;
  83BA    CD 8C69                           CALL    D0.AH2
  83BD    18 B7                             JR      D0.SUB
                                
                                            TITLE   'Funktionen :   MeDC und ROMT '
                                            PAGE
'Funktionen :   MeDC und ROMT '	MACRO-80 3.44	09-Dec-81	PAGE	1-11


                                
                                ;****************************************************************
                                ;*	                     D E B U G   -   Funktion :  MeDC       *
                                ;****************************************************************
  83BF    41 6E 66 2E           D0.TME:     DB      'Anf.Adr.'
  83C3    41 64 72 2E           
  83C7    CD 8C29               D0.MEDC:    CALL    D0.TA03
  83CA    21 83D2                           LD      HL,D0.MEPQ
  83CD    11 83BF                           LD      DE,D0.TME
  83D0    18 AD                 D0.MEDC1:   JR      D0.SUB1
                                ;
                                ;
                                ;
  83D2    CD 8A11               D0.MEPQ:    CALL    D0.AS
  83D5    3E 02                             LD      A,2                 ;Zeile  1 bis 22  loeschen            
  83D7    32 B198                           LD      (MS.CMD),A
  83DA    CD CB16                           CALL    MO.MONI
  83DD    3E 05                             LD      A,5
  83DF    32 B198                           LD      (MS.CMD),A	
  83E2    CD CB16                           CALL    MO.MONI
  83E5    ED 5B B28E                        LD      DE,(S2.DL)          ;DE <== Anfangsadresse fuer MEMO           
  83E9    3E 01                             LD      A,1
  83EB    C3 8CF3                           JP      D1.MEMO
                                
                                ;****************************************************************
                                ;*	                     D E B U G   -   Funktion :  ROMT       *
                                ;****************************************************************
  83EE    52 4F 4D 2D           D0.RT1:     DB      'ROM-Anf.'
  83F2    41 6E 66 2E           
  83F6    52 4F 4D 2D           D0.RT2:     DB      'ROM-Byte'
  83FA    42 79 74 65           
  83FE    20 20 4B 6F           D0.RT3:     DB      '  Kontrollsume: '
  8402    6E 74 72 6F           
  8406    6C 6C 73 75           
  840A    6D 65 3A 20           
  840E    CD 8C29               D0.ROMT:    CALL    D0.TA03
  8411    21 8419                           LD      HL,D0.RTPQ1
  8414    11 83EE                           LD      DE,D0.RT1
  8417    18 B7                 D0.ROM1:    JR      D0.MEDC1
                                ;
                                ;
                                ;
  8419    06 08                 D0.RTPQ1:   LD      B,8
  841B    21 83EE                           LD      HL,D0.RT1
  841E    CD 8713                           CALL    D0.PQ14
  8421    21 8434                           LD      HL,D0.RTPQ2
  8424    11 83F6                           LD      DE,D0.RT2
  8427    22 B223                           LD      (TS.TAB4),HL
  842A    ED 53 B28C                        LD      (S2.TE),DE
  842E    21 0400                           LD      HL,00400H
  8431    C3 8263                           JP      D0.IN2
                                ;
                                ;
                                ;
  8434    CD 8A11               D0.RTPQ2:   CALL    D0.AS
  8437    21 0F0A                           LD      HL,00F0AH           ;ZPOS = 10 , SPOS = 15
  843A    CD 88D2                           CALL    D0.DDU19
  843D    06 08                             LD      B,8
  843F    21 83F6                           LD      HL,D0.RT2
  8442    CD CB16                           CALL    MO.MONI
  8445    06 02                             LD      B,2
'Funktionen :   MeDC und ROMT '	MACRO-80 3.44	09-Dec-81	PAGE	1-12


  8447    21 824E                           LD      HL,D0.TPQ
  844A    CD CB16                           CALL    MO.MONI
  844D    CD 8C69                           CALL    D0.AH2
  8450    2A B290                           LD      HL,(S2.PAR1)
  8453    ED 4B B28E                        LD      BC,(S2.DL)
  8457    CD 866E                           CALL    D0.CHK
  845A    18 B2                             JR      D0.ROMT
                                
                                            TITLE   'Funktion :   PROM '
                                            PAGE
'Funktion :   PROM '	MACRO-80 3.44	09-Dec-81	PAGE	1-13


                                
                                ;****************************************************************
                                ;*	                     D E B U G   -   Funktion :  PROM       *
                                ;****************************************************************
  845C    50 52 4F 4D           D0.PR1:     DB      'PROMAnf.'
  8460    41 6E 66 2E           
  8464    4B 6F 6E 74           D0.PRT1:    DB      'KontLiesProg------------'
  8468    4C 69 65 73           
  846C    50 72 6F 67           
  8470    2D 2D 2D 2D           
  8474    2D 2D 2D 2D           
  8478    2D 2D 2D 2D           
  847C    2D 2D 2D 2D                       DB      '------------------------'
  8480    2D 2D 2D 2D           
  8484    2D 2D 2D 2D           
  8488    2D 2D 2D 2D           
  848C    2D 2D 2D 2D           
  8490    2D 2D 2D 2D           
  8494    2D 2D 2D 2D                       DB      '------------------------'
  8498    2D 2D 2D 2D           
  849C    2D 2D 2D 2D           
  84A0    2D 2D 2D 2D           
  84A4    2D 2D 2D 2D           
  84A8    2D 2D 2D 2D           
  84AC    2D 2D 2D 2D                       DB      '------------------------'
  84B0    2D 2D 2D 2D           
  84B4    2D 2D 2D 2D           
  84B8    2D 2D 2D 2D           
  84BC    2D 2D 2D 2D           
  84C0    2D 2D 2D 2D           
  84C4    2D 2D 2D 2D                       DB      '------------------------'
  84C8    2D 2D 2D 2D           
  84CC    2D 2D 2D 2D           
  84D0    2D 2D 2D 2D           
  84D4    2D 2D 2D 2D           
  84D8    2D 2D 2D 2D           
  84DC    2D 2D 2D 2D                       DB      '------------------------'
  84E0    2D 2D 2D 2D           
  84E4    2D 2D 2D 2D           
  84E8    2D 2D 2D 2D           
  84EC    2D 2D 2D 2D           
  84F0    2D 2D 2D 2D           
  84F4    2D 2D 2D 2D                       DB      '------------------------'
  84F8    2D 2D 2D 2D           
  84FC    2D 2D 2D 2D           
  8500    2D 2D 2D 2D           
  8504    2D 2D 2D 2D           
  8508    2D 2D 2D 2D           
  850C    2D 2D 2D 2D                       DB      '------------------------'
  8510    2D 2D 2D 2D           
  8514    2D 2D 2D 2D           
  8518    2D 2D 2D 2D           
  851C    2D 2D 2D 2D           
  8520    2D 2D 2D 2D           
  8524    8548                  D0.PRT2:    DW      D0.PRK
  8526    857C                              DW      D0.PRL
  8528    85B4                              DW      D0.PRP
  852A    21 8460               D0.PROM:    LD      HL,D0.PRT1-4
  852D    11 8524                           LD      DE,D0.PRT2
  8530    01 0006                           LD      BC,6            
  8533    CD 8C32                           CALL    D0.TA04
'Funktion :   PROM '	MACRO-80 3.44	09-Dec-81	PAGE	1-14


  8536    21 0000                           LD      HL,0
  8539    22 B18C                           LD      (MS.ZPOS),HL
  853C    21 801C                           LD      HL,D0.DD
  853F    22 B21D                           LD      (TS.TAB3+6),HL
  8542    3E 80                             LD      A,080H
  8544    32 B23F                           LD      (TS.SPMER),A
  8547    C9                                RET
                                ;
                                ;
                                ;            
  8548    CD 86A7               D0.PRK:     CALL    D0.PRUP1            ;EPROM - Kontrollieren
  854B    CD 86B4               D0.PRK1:    CALL    D0.PRUP2
  854E    20 15                             JR      NZ,D0.PRF
  8550    3C                                INC     A
  8551    20 12                             JR      NZ,D0.PRF
  8553    13                                INC     DE
  8554    CB 52                             BIT     2,D
  8556    28 F3                             JR      Z,D0.PRK1
                                ;
  8558    AF                    D0.PRR:     XOR     A                   ;Ende des PROM - Programmteiles
  8559    D3 E1                             OUT     (S0.PROM+1),A
  855B    18 CD                             JR      D0.PROM
                                ;
  855D    46 65 68 6C           D0.PRF1:    DB      'Fehler: '
  8561    65 72 3A 20           
  8565    21 000A               D0.PRF:     LD      HL,0000AH           ;Fehler anzeigen
  8568    ED 53 B28E                        LD      (S2.DL),DE
  856C    CD 88D2                           CALL    D0.DDU19
  856F    06 08                             LD      B,8
  8571    21 855D                           LD      HL,D0.PRF1
  8574    CD CB16                           CALL    MO.MONI
  8577    CD 8C69                           CALL    D0.AH2
  857A    18 DC                             JR      D0.PRR
                                
                                            PAGE
'Funktion :   PROM '	MACRO-80 3.44	09-Dec-81	PAGE	1-15


                                
  857C    CD 8C29               D0.PRL:     CALL    D0.TA03             ;EPROM - lesen
  857F    21 8588                           LD      HL,D0.PRPQ1
  8582    11 845C                           LD      DE,D0.PR1
  8585    C3 8259               D0.PRL1:    JP      D0.IN1
                                ;
  8588    06 08                 D0.PRPQ1:   LD      B,8
  858A    21 845C                           LD      HL,D0.PR1
  858D    CD 8713                           CALL    D0.PQ14
  8590    2A B28E                           LD      HL,(S2.DL)
  8593    CD 86A7                           CALL    D0.PRUP1
  8596    CD 86B4               D0.PRL2:    CALL    D0.PRUP2
  8599    20 CA                             JR      NZ,D0.PRF
  859B    77                                LD      (HL),A
  859C    BE                                CP      (HL)
  859D    20 11                             JR      NZ,D0.PRL3
  859F    23                                INC     HL
  85A0    13                                INC     DE
  85A1    CB 52                             BIT     2,D
  85A3    28 F1                             JR      Z,D0.PRL2
  85A5    01 0400                           LD      BC,00400H
  85A8    2A B28E                           LD      HL,(S2.DL)
  85AB    CD 866E                           CALL    D0.CHK
  85AE    18 A8                             JR      D0.PRR
                                ;            
  85B0    E5                    D0.PRL3:    PUSH    HL
  85B1    D1                                POP     DE
  85B2    18 B1                             JR      D0.PRF
                                ;
                                ;
                                ;
  85B4    CD 8C29               D0.PRP:     CALL    D0.TA03             ;EPROM - programmieren
  85B7    21 85BF                           LD      HL,D0.PRPQ2
  85BA    11 845C                           LD      DE,D0.PR1
  85BD    18 C6                             JR      D0.PRL1
                                ;
  85BF    06 08                 D0.PRPQ2:   LD      B,8
  85C1    21 845C                           LD      HL,D0.PR1
  85C4    CD 8713                           CALL    D0.PQ14
  85C7    2A B28E                           LD      HL,(S2.DL)
  85CA    0E 10                 	        LD      C,010H
  85CC    CD 86CE               D0.PRP2:    CALL    D0.PRUP3
  85CF    C5                                PUSH    BC
  85D0    CD 86FF                           CALL    D0.PRUP4
  85D3    C1                                POP     BC
  85D4    28 06                             JR      Z,D0.PRP3
  85D6    0D                                DEC     C
  85D7    20 F3                             JR      NZ,D0.PRP2
  85D9    C3 8565                           JP      D0.PRF              ;Fehlerauswertung
                                ;            
  85DC    CD 86CE               D0.PRP3:    CALL    D0.PRUP3
  85DF    01 0400                           LD      BC,00400H
  85E2    2A B28E                           LD      HL,(S2.DL)
  85E5    CD 866E                           CALL    D0.CHK
  85E8    C3 8558                           JP      D0.PRR
                                
                                            TITLE   'Funktion :   RAMT '
                                            PAGE
'Funktion :   RAMT '	MACRO-80 3.44	09-Dec-81	PAGE	1-16


                                
                                ;****************************************************************
                                ;*	                     D E B U G   -   Funktion :  RAMT       *
                                ;****************************************************************
  85EB    21 85F7               D0.RAMT:    LD      HL,D0.RAMT1
  85EE    22 B24B                           LD      (TS.BFOL2),HL
  85F1    3E FF                             LD      A,0FFH
  85F3    32 B247                           LD      (TS.MIO),A
  85F6    C9                                RET
                                ;            
  85F7    CD                    D0.RAMT1:   DB      0CDH                ;SYS-Taste
  85F8    4C 50 31                          DB      'LP1'
  85FB    B0                                DB      0B0H                ;POS QUIT
  85FC    52 41 4D 42                       DB      'RAMBUG'
  8600    55 47                 
  8602    B0                                DB      0B0H
  8603    52 41 4D 42                       DB      'RAMB'
  8607    B0                                DB      0B0H
                                ;
  8608    8608                              DW      $
  860A    52 41 4D 42                       DB      'RAMB'
  860E    F3                                DI
  860F    AF                                XOR     A
  8610    32 B247                           LD      (TS.MIO),A
  8613    21 CD9F                           LD      HL,MO.ROLL
  8616    22 B19A                           LD      (MS.RADR),HL
  8619    21 B197                           LD      HL,MS.DIRES
  861C    CB EE                             SET     5,(HL)
  861E    21 862C                           LD      HL,D0.RAMT2
  8621    11 0103                           LD      DE,00103H
  8624    01 0011                           LD      BC,17
  8627    ED B0                             LDIR
  8629    C3 0100                           JP      00100H
                                ;            
  862C    C3 863D               D0.RAMT2:   JP      D0.CON
  862F    C3 E697                           JP      S9.CIN
  8632    C3 E6CB                           JP      S9.CSTSX
  8635    C3 8641                           JP      D0.CADR
  8638    C3 8646                           JP      D0.CHOM
  863B    16                                DB      22
  863C    50                                DB      80
                                ;
  863D    4F                    D0.CON:     LD      C,A
  863E    C3 E6E6                           JP      S9.CON
                                ;
  8641    ED 53 B18C            D0.CADR:    LD      (MS.ZPOS),DE
  8645    C9                                RET
                                ;
  8646    CD EE98               D0.CHOM:    CALL    S9.SAVE
  8649    3E 05                             LD      A,5
  864B    32 B198                           LD      (MS.CMD),A
  864E    CD CB16                           CALL    MO.MONI
  8651    21 0000                           LD      HL,0
  8654    22 B18C                           LD      (MS.ZPOS),HL
  8657    3E 06                             LD      A,6
  8659    32 B198                           LD      (MS.CMD),A
  865C    CD CB16                           CALL    MO.MONI
  865F    CD EEB8                           CALL    S9.LOAD
  8662    C9                                RET
                                ;
  8663                          D0.RCDC     EQU     $
'Funktion :   RAMT '	MACRO-80 3.44	09-Dec-81	PAGE	1-17


  8663                          D0.LOAD     EQU     $
  8663                          D0.SAVE     EQU     $
  8663                          D0.REAS     EQU     $
  8663    C9                                RET
                                ;            
  8664                          D0.RGDC     EQU     $
  8664    CD 8972               D0.UCPU:    CALL    D0.DDU30
  8667    21 801C                           LD      HL,D0.DD
  866A    22 B21D                           LD      (TS.TAB3+6),HL
  866D    C9                                RET
                                
                                            TITLE 'Unterprogramme'
                                            PAGE
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-18


                                
                                ;****************************************************************
                                ;*	                     Kontrollsumme berechnen                *
                                ;****************************************************************
  866E    11 FFFF               D0.CHK:     LD      DE,0FFFFH
  8671    7E                    D0.CHK1:    LD      A,(HL)
  8672    AA                                XOR     D
  8673    57                                LD      D,A
  8674    0F                                RRCA
  8675    0F                                RRCA
  8676    0F                                RRCA
  8677    0F                                RRCA
  8678    E6 0F                             AND     00FH
  867A    AA                                XOR     D
  867B    57                                LD      D,A
  867C    0F                                RRCA
  867D    0F                                RRCA
  867E    0F                                RRCA
  867F    F5                                PUSH    AF
  8680    E6 1F                             AND     01FH
  8682    AB                                XOR     E
  8683    5F                                LD      E,A
  8684    F1                                POP     AF
  8685    F5                                PUSH    AF
  8686    0F                                RRCA
  8687    E6 F0                             AND     0F0H
  8689    AB                                XOR     E
  868A    5F                                LD      E,A
  868B    F1                                POP     AF
  868C    E6 E0                             AND     0E0H
  868E    AA                                XOR     D
  868F    53                                LD      D,E
  8690    5F                                LD      E,A
  8691    23                                INC     HL
  8692    0B                                DEC     BC
  8693    78                                LD      A,B
  8694    B1                                OR      C
  8695    20 DA                             JR      NZ,D0.CHK1          ; Ergebnis in < DE >
  8697    ED 53 B28E                        LD      (S2.DL),DE
  869B    06 11                             LD      B,17
  869D    21 83FE                           LD      HL,D0.RT3
  86A0    CD CB16                           CALL    MO.MONI
  86A3    CD 8C69                           CALL    D0.AH2
  86A6    C9                                RET
                                
                                            PAGE
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-19


                                
                                ;**********************************************************************
                                ;*	                     Unterprogramme fuer EPROM - Anschlusseinheit *
                                ;**********************************************************************
  86A7    3E 18                 D0.PRUP1:   LD      A,018H
  86A9    D3 E1                             OUT     (S0.PROM+1),A
  86AB    11 03E8                           LD      DE,003E8H
  86AE    1B                    D0.PRU11:   DEC     DE
  86AF    7A                                LD      A,D
  86B0    B3                                OR      E
  86B1    20 FB                             JR      NZ,D0.PRU11
  86B3    C9                                RET
                                ;
  86B4    7B                    D0.PRUP2:   LD      A,E
  86B5    D3 E2                             OUT     (S0.PROM+2),A
  86B7    7A                                LD      A,D
  86B8    0F                                RRCA
  86B9    0F                                RRCA
  86BA    F6 18                             OR      018H
  86BC    D3 E1                             OUT     (S0.PROM+1),A
  86BE    06 06                             LD      B,6
  86C0    10 03                 D0.PRU21:   DJNZ    D0.PRU22
  86C2    F6 01                             OR      1
  86C4    C9                                RET
                                ;
  86C5    DB E3                 D0.PRU22:   IN      A,(S0.PROM+3)
  86C7    4F                                LD      C,A
  86C8    DB E3                             IN      A,(S0.PROM+3)
  86CA    B9                                CP      C
  86CB    20 F3                             JR      NZ,D0.PRU21
  86CD    C9                                RET
                                ;
  86CE    06 0C                 D0.PRUP3:   LD      B,00CH
  86D0    2A B28E               D0.PRU31:   LD      HL,(S2.DL)
  86D3    11 0000                           LD      DE ,0
  86D6    7B                    D0.PRU32:   LD      A,E
  86D7    D3 E2                             OUT     (S0.PROM+2),A
  86D9    7A                                LD      A,D
  86DA    0F                                RRCA
  86DB    0F                                RRCA
  86DC    F6 1B                             OR      01BH
  86DE    D3 E1                             OUT     (S0.PROM+1),A
  86E0    F5                                PUSH    AF
  86E1    7E                                LD      A,(HL)
  86E2    D3 E3                             OUT     (S0.PROM+3),A
  86E4    F1                                POP     AF
  86E5    F5                                PUSH    AF
  86E6    F6 1F                             OR      01FH
  86E8    D3 E1                             OUT     (S0.PROM+1),A
  86EA    3E 18                             LD      A,018H
  86EC    3D                    D0.PRU33:   DEC     A
  86ED    20 FD                             JR      NZ,D0.PRU33
  86EF    F1                                POP     AF
  86F0    D3 E1                             OUT     (S0.PROM+1),A
  86F2    23                                INC     HL
  86F3    13                                INC     DE
  86F4    CB 52                             BIT     2,D
  86F6    28 DE                             JR      Z,D0.PRU32
  86F8    10 D6                             DJNZ    D0.PRU31
  86FA    E6 FD                             AND     0FDH
  86FC    D3 E1                             OUT     (S0.PROM+1),A
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-20


  86FE    C9                                RET
                                ;
  86FF    2A B28E               D0.PRUP4:   LD      HL,(S2.DL)
  8702    CD 86A7                           CALL    D0.PRUP1
  8705    CD 86B4               D0.PRU41:   CALL    D0.PRUP2
  8708    C0                                RET     NZ
  8709    BE                                CP      (HL)
  870A    C0                                RET     NZ
  870B    23                                INC     HL
  870C    13                                INC     DE
  870D    CB 52                             BIT     2,D
  870F    28 F4                             JR      Z,D0.PRU41
  8711    AF                                XOR     A
  8712    C9                                RET
                                            
                                            PAGE
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-21


                                
                                ;**********************************************************************
                                ;*                                                                    *
                                ;**********************************************************************
  8713    E5                    D0.PQ14:    PUSH    HL
  8714    C5                                PUSH    BC
  8715    CD 8A11                           CALL    D0.AS
  8718    2A B28E                           LD      HL,(S2.DL)
  871B    22 B290                           LD      (S2.PAR1),HL
  871E    21 000A                           LD      HL,0000AH           ;ZPOS = 10 , SPOS = 0
  8721    CD 88D2                           CALL    D0.DDU19
  8724    C1                                POP     BC
  8725    E1                                POP     HL
  8726    CD CB16                           CALL    MO.MONI
  8729    06 02                             LD      B,2
  872B    21 824E                           LD      HL,D0.TPQ
  872E    CD CB16                           CALL    MO.MONI
  8731    CD 8C69                           CALL    D0.AH2
  8734    C9                                RET
                                ;**********************************************************************
                                ;*	                     <B>-malige Anzeige von <A> in Richtung <C>   *
                                ;**********************************************************************
  8735    32 B199               D0.DDU01:   LD      (MS.TK),A
  8738    79                                LD      A,C
  8739    32 B197                           LD      (MS.DIRES),A
  873C    CD CB16               D0.DDU02:   CALL    MO.MONI
  873F    10 FB                             DJNZ    D0.DDU02
  8741    C9                                RET
                                
                                            PAGE
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-22


                                
                                ;**********************************************************************
                                ;*	                     Rahmengrundelemente                          *
                                ;**********************************************************************
                                ;           Anzeige :    $$$$$
  8742    22 B18C               D0.DDU03:   LD      (MS.ZPOS),HL
  8745    3E 81                             LD      A,081H              ;Zeichen : $   alt:001H   mitte   (03)
  8747    0E C0                             LD      C,0C0H              ;Richtung: Ost
  8749    CD 8735                           CALL    D0.DDU01
  874C    C9                                RET
                                ;           Anzeige :    $
                                ;                        $
                                ;                        $
  874D    22 B18C               D0.DDU04:   LD      (MS.ZPOS),HL
  8750    AF                                XOR     A                   ;Zeichen : $
  8751    0E C6                             LD      C,0C6H              ;Richtung: Sued
  8753    CD 8735                           CALL    D0.DDU01
  8756    C9                                RET
                                ;           Anzeige :    $$$$$
                                ;
                                ;
  8757    0E C0                 D0.DDU05:   LD      C,0C0H              ;Richtung: Ost
  8759    C5                                PUSH    BC
  875A    22 B18C                           LD      (MS.ZPOS),HL
  875D    3E 82                             LD      A,082H              ;Zeichen : $   alt:002H   links
  875F    06 01                             LD      B,1
  8761    CD 8735                           CALL    D0.DDU01
  8764    2A B18C                           LD      HL,(MS.ZPOS)
  8767    C1                                POP     BC
  8768    CD 8742                           CALL    D0.DDU03
  876B    3E 83                             LD      A,083H              ;Zeichen : $   alt:003H   rechts   (01)
  876D    01 0100                           LD      BC,00100H
  8770    CD 8735                           CALL    D0.DDU01
  8773    C9                                RET
                                ;
  8774    0E C0                 D0.DDU17:   LD      C,0C0H
  8776    C5                                PUSH    BC
  8777    22 B18C                           LD      (MS.ZPOS),HL
  877A    3E 8A                             LD      A,08AH
  877C    06 01                             LD      B,1
  877E    CD 8735                           CALL    D0.DDU01
  8781    2A B18C                           LD      HL,(MS.ZPOS)
  8784    C1                                POP     BC
  8785    CD 8742                           CALL    D0.DDU03
  8788    3E 8B                             LD      A,08BH
  878A    01 0100                           LD      BC,00100H
  878D    CD 8735                           CALL    D0.DDU01
  8790    C9                                RET
                                ;           Anzeige :    $
                                ;                        $
                                ;                        $
  8791    0E C6                 D0.DDU06:   LD      C,0C6H              ;Richtung: Sued
  8793    C5                                PUSH    BC
  8794    22 B18C                           LD      (MS.ZPOS),HL
  8797    3E 01                             LD      A,001H              ;Zeichen : $	           (05)
  8799    06 01                             LD      B,1
                                            ;CALL    D0.DDU01           ;???
  879B    2A B18C                           LD      HL,(MS.ZPOS)
  879E    2C                                INC     L
  879F    C1                                POP     BC
  87A0    CD 874D                           CALL    D0.DDU04
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-23


  87A3    3E 01                             LD      A,001H              ;Zeichen : $	           (04)
  87A5    01 0100                           LD      BC,00100H
                                            ;CALL    D0.DDU01           ;???
  87A8    C9                                RET
                                ;
  87A9    01 0E04               D0.DDU07:   LD      BC,00E04H           ;Rahmen Zeichnen   
  87AC    CD 88A7                           CALL    D0.DDU18
  87AF    2A B29A                           LD      HL,(S2.DM1)
  87B2    7C                                LD      A,H
  87B3    C6 05                             ADD     A,5
  87B5    67                                LD      H,A
  87B6    06 04                             LD      B,4
  87B8    CD 8791                           CALL    D0.DDU06
  87BB    2A B29A                           LD      HL,(S2.DM1)
  87BE    7C                                LD      A,H
  87BF    C6 0A                             ADD     A,10
  87C1    67                                LD      H,A
  87C2    06 04                             LD      B,4
  87C4    CD 8791                           CALL    D0.DDU06
  87C7    C9                                RET
                                ;
  87C8    3E 14                 D0.DDU08:   LD      A,20
  87CA    32 B198                           LD      (MS.CMD),A
  87CD    21 0203                           LD      HL,00203H           ;ZPOS = 3 , SPOS = 2
  87D0    CD 87A9                           CALL    D0.DDU07            ;                    Rahmen Ebene 0
  87D3    21 1603                           LD      HL,01603H           ;ZPOS = 3 , SPOS = 22
  87D6    CD 87A9                           CALL    D0.DDU07            ;                    Rahmen Ebene 1
  87D9    21 2A03                           LD      HL,02A03H           ;ZPOS = 3 , SPOS = 42
  87DC    CD 87A9                           CALL    D0.DDU07            ;                    Rahmen Ebene 2
  87DF    21 3E03                           LD      HL,03E03H           ;ZPOS = 3 , SPOS = 62
  87E2    CD 87A9                           CALL    D0.DDU07            ;                    Rahmen Ebene 3
  87E5    3E 18                             LD      A,24
  87E7    32 B198                           LD      (MS.CMD),A
  87EA    21 0602                           LD      HL,00602H           ;ZPOS = 2 , SPOS = 6
  87ED    CD 882A                           CALL    D0.DDU10
  87F0    21 1A02                           LD      HL,01A02H           ;ZPOS = 2 , SPOS = 26
  87F3    CD 882A                           CALL    D0.DDU10
  87F6    21 2E02                           LD      HL,02E02H           ;ZPOS = 2 , SPOS = 46
  87F9    CD 882A                           CALL    D0.DDU10
  87FC    21 4202                           LD      HL,04202H           ;ZPOS = 2 , SPOS = 66
  87FF    CD 882A                           CALL    D0.DDU10
  8802    3E 14                             LD      A,20
  8804    32 B198                           LD      (MS.CMD),A
  8807    3E 2F                             LD      A,'/'
  8809    32 B199                           LD      (MS.TK),A
  880C    21 0D02                           LD      HL,00D02H           ;ZPOS = 2 , SPOS = 13
  880F    CD 883B                           CALL    D0.DDU11
  8812    21 2102                           LD      HL,02102H           ;ZPOS = 2 , SPOS = 33
  8815    CD 883B                           CALL    D0.DDU11
  8818    21 3502                           LD      HL,03502H           ;ZPOS = 2 , SPOS = 53
  881B    CD 883B                           CALL    D0.DDU11
  881E    21 4902                           LD      HL,04902H           ;ZPOS = 2 , SPOS = 73
  8821    CD 883B                           CALL    D0.DDU11
  8824    C9                                RET
                                ;
  8825    45 62 65 6E           D0.DDU09:   DB      'Ebene'
  8829    65                    
  882A    22 B18C               D0.DDU10:   LD      (MS.ZPOS),HL
  882D    06 05                             LD      B,5
  882F    3E C0                             LD      A,0C0H              ;Richtung: Ost
  8831    32 B197                           LD      (MS.DIRES),A
  8834    21 8825                           LD      HL,D0.DDU09
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-24


  8837    CD CB16                           CALL    MO.MONI
  883A    C9                                RET
                                 ;
                                 ;
                                 ;
  883B    22 B18C                D0.DDU11:  LD      (MS.ZPOS),HL
  883E    21 B199                           LD      HL,MS.TK
  8841    34                                INC     (HL)
  8842    CD CB16                           CALL    MO.MONI
  8845    C9                                RET
                                ;
                                ;
                                ;
  8846    2A B29A               D0.DDU12:   LD      HL,(S2.DM1)
  8849    11 0004                           LD      DE,4
  884C    19                                ADD     HL,DE
  884D    22 B29A                           LD      (S2.DM1),HL
  8850    06 04                             LD      B,4
  8852    CD CB16                           CALL    MO.MONI
  8855    C9                                RET
                                ;
                                ;
                                ;
  8856    22 B18C               D0.DDU13:   LD      (MS.ZPOS),HL
  8859    06 04                             LD      B,4
  885B    C5                    D0.DDU14:   PUSH    BC
  885C    CD 8846                           CALL    D0.DDU12
  885F    DD 34 00                          INC     (IX)
  8862    CD 8846                           CALL    D0.DDU12
  8865    DD 34 00                          INC     (IX)
  8868    CD 8846                           CALL    D0.DDU12
  886B    FD 34 00                          INC     (IY)
  886E    06 0E                             LD      B,14
  8870    DD 35 00              D0.DDU15:   DEC     (IX)
  8873    10 FB                             DJNZ    D0.DDU15
  8875    C1                                POP     BC
  8876    10 E3                             DJNZ    D0.DDU14
  8878    C9                                RET
                                ;
                                ;
                                ;
  8879    3E 18                 D0.DDU16:   LD      A,24
  887B    32 B198                           LD      (MS.CMD),A
  887E    3E C0                             LD      A,0C0H
  8880    32 B197                           LD      (MS.DIRES),A
  8883    22 B29A                           LD      (S2.DM1),HL         ;Bedeutungstabelle
  8886    FD 21 B18C                        LD      IY,MS.ZPOS
  888A    DD 21 B18D                        LD      IX,MS.SPOS
  888E    21 0304                           LD      HL,00304H           ;ZPOS = 4 , SPOS = 3
  8891    CD 8856                           CALL    D0.DDU13
  8894    21 1704                           LD      HL,01704H           ;ZPOS = 4 , SPOS = 23
  8897    CD 8856                           CALL    D0.DDU13
  889A    21 2B04                           LD      HL,02B04H           ;ZPOS = 4 , SPOS = 43
  889D    CD 8856                           CALL    D0.DDU13
  88A0    21 3F04                           LD      HL,03F04H           ;ZPOS = 4 , SPOS = 63
  88A3    CD 8856                           CALL    D0.DDU13
  88A6    C9                                RET
                                
                                            PAGE
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-25


                                
  88A7    C5                    D0.DDU18:   PUSH    BC                  ; |---------|
  88A8    22 B29A                           LD      (S2.DM1),HL         ; |         | < C >   anzeigen
  88AB    CD 8757                           CALL    D0.DDU05            ; |---------|
  88AE    2A B18C                           LD      HL,(MS.ZPOS)        ;    < B >
  88B1    2C                                INC     L
  88B2    25                                DEC     H
  88B3    7C                                LD      A,H
  88B4    FE FF                             CP      0FFH
  88B6    20 02                             JR      NZ,DDU18A
  88B8    26 4F                             LD      H,79
  88BA    C1                    DDU18A:     POP     BC
  88BB    C5                                PUSH    BC
  88BC    41                                LD      B,C
  88BD    CD 874D                           CALL    D0.DDU04
  88C0    2A B29A                           LD      HL,(S2.DM1)
  88C3    2C                                INC     L
  88C4    C1                                POP     BC
  88C5    C5                                PUSH    BC
  88C6    41                                LD      B,C
  88C7    CD 874D                           CALL    D0.DDU04
  88CA    2A B18C                           LD      HL,(MS.ZPOS)
  88CD    C1                                POP     BC
  88CE    CD 8774                           CALL    D0.DDU17
  88D1    C9                                RET
                                ;
                                ;
                                ;
  88D2    E5                    D0.DDU19:   PUSH    HL
  88D3    3E 02                             LD      A,2
  88D5    32 B198                           LD      (MS.CMD),A
  88D8    CD CB16                           CALL    MO.MONI
  88DB    3E 18                             LD      A,24
  88DD    32 B198                           LD      (MS.CMD),A
  88E0    E1                                POP     HL
  88E1    22 B18C                           LD      (MS.ZPOS),HL
  88E4    C9                                RET
                                ;
                                ;
                                ;
  88E5    CD 87C8               D0.DDU20:   CALL    D0.DDU08
  88E8    21 8182                           LD      HL,D0.DDPTB-4
  88EB    CD 8879                           CALL    D0.DDU16
  88EE    C9                                RET
                                ;
                                ;
                                ;
  88EF    3A B28B               D0.DDU21:   LD      A,(S2.BZ)
  88F2    FE 02                             CP      2
  88F4    28 04                             JR      Z,D0.DDU22
  88F6    06 00                             LD      B,0
  88F8    18 02                             JR      D0.DDU23
                                ;            
  88FA    06 05                 D0.DDU22:   LD      B,5
  88FC    3A B28A               D0.DDU23:   LD      A,(S2.AFOR)
  88FF    80                                ADD     A,B
  8900    87                                ADD     A,A
  8901    4F                                LD      C,A
  8902    06 00                             LD      B,0
  8904    09                                ADD     HL,BC
  8905    7E                                LD      A,(HL)
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-26


  8906    23                                INC     HL
  8907    66                                LD      H,(HL)
  8908    6F                                LD      L,A
  8909    C9                                RET
                                ;
  890A    3E 2C                 D0.DDU24:   LD      A,44
  890C    32 B198                           LD      (MS.CMD),A
  890F    22 B18A                           LD      (MS.ZPOL),HL
  8912    21 B29A                           LD      HL,S2.DM1
  8915    CD CB16                           CALL    MO.MONI
  8918    C9                                RET
                                ;**********************************************************************
                                ;*	                     Eingabefeld loeschen und ":" anzeigen        *
                                ;**********************************************************************
  8919    CD 8C3F               D0.DDU25:   CALL    D0.MO01
  891C    3E 05                             LD      A,5
  891E    32 B198                           LD      (MS.CMD),A
  8921    CD CB16                           CALL    MO.MONI
  8924    3E 14                             LD      A,20
  8926    32 B198                           LD      (MS.CMD),A
  8929    3E 3A                             LD      A,':'
  892B    32 B199                           LD      (MS.TK),A
  892E    21 3D14                           LD      HL,03D14H           ;ZPOS = 20 , SPOS = 61
  8931    22 B18C                           LD      (MS.ZPOS),HL
  8934    CD CB16                           CALL    MO.MONI
  8937    21 3513                           LD      HL,03513H           ;ZPOS = 19 , SPOS = 53
  893A    22 B18C                           LD      (MS.ZPOS),HL
  893D    C9                                RET
                                ;**********************************************************************
                                ;*	                     Spaltennummern und Text anzeigen             *
                                ;**********************************************************************
  893E    78                    D0.DDU26:   LD      A,B
  893F    FE 0A                             CP      10
  8941    38 0C                             JR      C,D0.DDU27
  8943    3E 37                             LD      A,55
  8945    80                                ADD     A,B
  8946    32 B199                           LD      (MS.TK),A
  8949    CD CB16                           CALL    MO.MONI
  894C    05                                DEC     B
  894D    18 EF                             JR      D0.DDU26
                                ;
  894F    3E 2F                 D0.DDU27:   LD      A,'/'
  8951    80                                ADD     A,B
  8952    32 B199                           LD      (MS.TK),A
  8955    CD CB16               D0.DDU28:   CALL    MO.MONI
  8958    21 B199                           LD      HL,MS.TK
  895B    35                                DEC     (HL)
  895C    10 F7                             DJNZ    D0.DDU28
  895E    3E 18                             LD      A,24
  8960    32 B198                           LD      (MS.CMD),A
  8963    06 08                             LD      B,8
  8965    2A B28C                           LD      HL, (S2.TE)
  8968    CD CB16                           CALL    MO.MONI
  896B    21 4F15                           LD      HL,04F15H
  896E    22 B190                           LD      (MS.ZMAX),HL
  8971    C9                                RET
                                
                                            PAGE
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-27


                                
  8972    21 000B               D0.DDU30:   LD      HL,0000BH
  8975    22 B18E                           LD      (MS.ZMIN),HL
  8978    21 5016                           LD      HL,05016H
  897B    22 B190                           LD      (MS.ZMAX),HL
  897E    3E 05                             LD      A,5
  8980    32 B198                           LD      (MS.CMD),A
  8983    CD CB16                           CALL    MO.MONI
  8986    3E 02                             LD      A,2
  8988    32 B198                           LD      (MS.CMD),A
  898B    CD CB16                           CALL    MO.MONI
  898E    3E 14                             LD      A,20
  8990    32 B198                           LD      (MS.CMD),A
  8993    21 000A                           LD      HL,0000AH           ;ZPOS = 10 , SPOS = 0
  8996    01 4E0A                           LD      BC,04E0AH           ;Laenge:78 , Breite:10
  8999    CD 88A7                           CALL    D0.DDU18
  899C    21 0012                           LD      HL,00012H           ;ZPOS = 18 , SPOS = 0
  899F    06 4E                             LD      B,78                ;Laenge:78
  89A1    CD 8757                           CALL    D0.DDU05
  89A4    21 250A                           LD      HL,0250AH           ;ZPOS = 10 , SPOS = 37
  89A7    06 07                             LD      B,7
  89A9    CD 8791                           CALL    D0.DDU06
  89AC    21 3412                           LD      HL,03412H           ;ZPOS = 18 , SPOS = 52
  89AF    06 02                             LD      B,2
  89B1    CD 8791                           CALL    D0.DDU06
  89B4    21 000C                           LD      HL,0000CH           ;ZPOS = 12 , SPOS = 0
  89B7    06 24                             LD      B,36
  89B9    CD 8757                           CALL    D0.DDU05
  89BC    21 000F                           LD      HL,0000FH           ;ZPOS = 15 , SPOS = 0
  89BF    06 24                             LD      B,36
  89C1    CD 8757                           CALL    D0.DDU05
  89C4    21 0A0F                           LD      HL,00A0FH           ;ZPOS = 15 , SPOS = 10
  89C7    06 05                             LD      B,5
  89C9    CD 8791                           CALL    D0.DDU06
  89CC    21 0D0A                           LD      HL,00D0AH           ;ZPOS = 10 , SPOS = 13
  89CF    06 04                             LD      B,4
  89D1    CD 8791                           CALL    D0.DDU06
  89D4    21 150A                           LD      HL,0150AH           ;ZPOS = 10 , SPOS = 21
  89D7    06 04                             LD      B,4
  89D9    CD 8791                           CALL    D0.DDU06
  89DC    21 1D0A                           LD      HL,01D0AH           ;ZPOS = 10 , SPOS = 29
  89DF    06 04                             LD      B,4
  89E1    CD 8791                           CALL    D0.DDU06
  89E4    21 170F                           LD      HL,0170FH           ;ZPOS = 15 , SPOS = 23
  89E7    06 02                             LD      B,2
  89E9    CD 8791                           CALL    D0.DDU06
  89EC    21 090C                           LD      HL,0090CH           ;ZPOS = 12 , SPOS = 9
  89EF    CD 8A05                           CALL    D0.DDU31
  89F2    21 110C                           LD      HL,0110CH           ;ZPOS = 12 , SPOS = 17
  89F5    CD 8A05                           CALL    D0.DDU31
  89F8    21 190C                           LD      HL,0190CH           ;ZPOS = 12 , SPOS = 25
  89FB    CD 8A05                           CALL    D0.DDU31
  89FE    21 210C                           LD      HL,0210CH           ;ZPOS = 12 , SPOS = 33
  8A01    CD 8A05                           CALL    D0.DDU31
  8A04    C9                                RET
                                ;
  8A05    22 B18C               D0.DDU31:   LD      (MS.ZPOS),HL
  8A08    3E 7C                             LD      A,07CH
  8A0A    01 03C6                           LD      BC,003C6H
  8A0D    CD 8735                           CALL    D0.DDU01
  8A10    C9                                RET
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-28


                                
                                            PAGE
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-29


                                
                                ;**********************************************************************
                                ;*	                     Anzeige im Eingabebereich retten             *
                                ;**********************************************************************
  8A11    21 8A18               D0.AS:      LD      HL,D0.ASTAB
  8A14    CD 88EF                           CALL    D0.DDU21
  8A17    E9                                JP      (HL)
                                ;
                                ;
                                ;
  8A18    8A2C                  D0.ASTAB:   DW      D0.ASH1
  8A1A    8A5B                              DW      D0.ASD1
  8A1C    8AB1                              DW      D0.ASO1
  8A1E    8AB1                              DW      D0.ASB1
  8A20    8A89                              DW      D0.ASA1
                                ;
  8A22    8A42                              DW      D0.ASH2
  8A24    8A72                              DW      D0.ASD2
  8A26    8AB1                              DW      D0.ASO2
  8A28    8AB1                              DW      D0.ASB2
  8A2A    8A9C                              DW      D0.ASA2
                                ;
                                ;
                                ;
  8A2C    21 4D14               D0.ASH1:    LD      HL,04D14H
  8A2F    06 02                             LD      B,2
  8A31    CD 890A                           CALL    D0.DDU24
  8A34    21 B29A                           LD      HL,S2.DM1
  8A37    CD C5CC                           CALL    S1.HBKON
  8A3A    32 B28E                           LD      (S2.DL),A
  8A3D    AF                                XOR     A
  8A3E    32 B28F                           LD      (S2.DH),A
  8A41    C9                                RET
                                ;
  8A42    21 4B14               D0.ASH2:    LD      HL,04B14H
  8A45    06 04                             LD      B,4
  8A47    CD 890A                           CALL    D0.DDU24
  8A4A    21 B29A                           LD      HL,S2.DM1
  8A4D    CD C5CC                           CALL    S1.HBKON
  8A50    32 B28F                           LD      (S2.DH),A
  8A53    23                                INC     HL
  8A54    CD C5CC                           CALL    S1.HBKON
  8A57    32 B28E                           LD      (S2.DL),A
  8A5A    C9                                RET
                                ;
                                ;
                                ;
  8A5B    21 4C14               D0.ASD1:    LD      HL,04C14H
  8A5E    06 03                             LD      B,3
  8A60    CD 890A                           CALL    D0.DDU24
  8A63    3E 20                             LD      A,' '
  8A65    32 B29D                           LD      (S2.DM1+3),A
  8A68    11 B29A                           LD      DE,S2.DM1
  8A6B    CD C592                           CALL    S1.IDH
  8A6E    22 B28E                           LD      (S2.DL),HL
  8A71    C9                                RET
                                ;
  8A72    21 4A14               D0.ASD2:    LD      HL,04A14H
  8A75    06 05                             LD      B,5
  8A77    CD 890A                           CALL    D0.DDU24
  8A7A    3E 20                             LD      A,' '
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-30


  8A7C    32 B29F                           LD      (S2.DM1+5),A
  8A7F    11 B29A                           LD      DE,S2.DM1
  8A82    CD C592                           CALL    S1.IDH
  8A85    22 B28E                           LD      (S2.DL),HL
  8A88    C9                                RET
                                ;
                                ;
                                ;
  8A89    21 4E14               D0.ASA1:    LD      HL,04E14H
  8A8C    06 01                             LD      B,1
  8A8E    CD 890A                           CALL    D0.DDU24
  8A91    AF                                XOR     A
  8A92    32 B28F                           LD      (S2.DH),A
  8A95    3A B29A                           LD      A,(S2.DM1)
  8A98    32 B28E                           LD      (S2.DL),A
  8A9B    C9                                RET
                                ;
  8A9C    21 4D14               D0.ASA2:    LD      HL,04D14H
  8A9F    06 02                             LD      B,2
  8AA1    CD 890A                           CALL    D0.DDU24
  8AA4    3A B29A                           LD      A,(S2.DM1)
  8AA7    32 B28F                           LD      (S2.DH),A
  8AAA    3A B29B                           LD      A,(S2.DM1+1)
  8AAD    32 B28E                           LD      (S2.DL),A
  8AB0    C9                                RET
                                ;
                                ;
                                ;
  8AB1                          D0.ASO1     EQU     $
  8AB1                          D0.ASO2     EQU     $
  8AB1                          D0.ASB1     EQU     $
  8AB1                          D0.ASB2     EQU     $
  8AB1    C9                                RET
                                
                                            PAGE
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-31


                                
                                ;**********************************************************************
                                ;*	                     Anzeige im Eingabebereich laden              *
                                ;**********************************************************************
  8AB2    21 8AB9               D0.AL:      LD      HL,D0.ALTAB
  8AB5    CD 88EF                           CALL    D0.DDU21
  8AB8    E9                                JP      (HL)
                                ;
                                ;
                                ;
  8AB9    8ACD                  D0.ALTAB:   DW      D0.ALH1
  8ABB    8B23                              DW      D0.ALD1
  8ABD    8B79                              DW      D0.ALO1
  8ABF    8B79                              DW      D0.ALB1
  8AC1    8B7A                              DW      D0.ALA1
                                ;
  8AC3    8AFD                              DW      D0.ALH2
  8AC5    8B53                              DW      D0.ALD2
  8AC7    8B79                              DW      D0.ALO2
  8AC9    8B79                              DW      D0.ALB2
  8ACB    8BAF                              DW      D0.ALA2
                                ;
                                ;
                                ;
  8ACD    CD 8919               D0.ALH1:    CALL    D0.DDU25
  8AD0    3E 48                             LD      A,'H'
  8AD2    32 B199                           LD      (MS.TK),A
  8AD5    CD CB16                           CALL    MO.MONI
  8AD8    3E 4D                             LD      A,77
  8ADA    32 B18D                           LD      (MS.SPOS),A
  8ADD    06 02                             LD      B,2
  8ADF    CD 893E                           CALL    D0.DDU26
  8AE2    21 4E15                           LD      HL,04E15H
  8AE5    22 B18E                           LD      (MS.ZMIN),HL
  8AE8    21 4D14                           LD      HL,04D14H
  8AEB    22 B18C                           LD      (MS.ZPOS),HL
  8AEE    CD 8C57                           CALL    D0.AH1
  8AF1    21 8CAC               D0.ALH:     LD      HL,D0.HZEIN
  8AF4    22 B22D                           LD      (TS.EINA),HL
  8AF7    3E A8                             LD      A,0A8H
  8AF9    32 B23F                           LD      (TS.SPMER),A
  8AFC    C9                                RET
                                ;
  8AFD    CD 8919               D0.ALH2:    CALL    D0.DDU25
  8B00    3E 48                             LD      A,'H'
  8B02    32 B199                           LD      (MS.TK),A
  8B05    CD CB16                           CALL    MO.MONI
  8B08    3E 4B                             LD      A,75
  8B0A    32 B18D                           LD      (MS.SPOS),A
  8B0D    06 04                             LD      B,4
  8B0F    CD 893E                           CALL    D0.DDU26
  8B12    21 4C15                           LD      HL,04C15H
  8B15    22 B18E                           LD      (MS.ZMIN),HL
  8B18    21 4B14                           LD      HL,04B14H
  8B1B    22 B18C                           LD      (MS.ZPOS),HL
  8B1E    CD 8C69                           CALL    D0.AH2
  8B21    18 CE                             JR      D0.ALH
                                ;
                                ;
                                ;            
  8B23    CD 8919               D0.ALD1:    CALL    D0.DDU25
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-32


  8B26    3E 44                             LD      A,'D'
  8B28    32 B199                           LD      (MS.TK),A
  8B2B    CD CB16                           CALL    MO.MONI
  8B2E    3E 4C                             LD      A,76
  8B30    32 B18D                           LD      (MS.SPOS),A
  8B33    06 03                             LD      B,3
  8B35    CD 893E                           CALL    D0.DDU26
  8B38    21 4D15                           LD      HL,04D15H
  8B3B    22 B18E                           LD      (MS.ZMIN),HL
  8B3E    21 4C14                           LD      HL,04C14H
  8B41    22 B18C                           LD      (MS.ZPOS),HL
  8B44    CD 8C82                           CALL    D0.AD1
  8B47    21 8CBE               D0.ALD:     LD      HL,D0.DZEIN
  8B4A    22 B22D                           LD      (TS.EINA),HL
  8B4D    3E 88                             LD      A,088H
  8B4F    32 B23F                           LD      (TS.SPMER),A
  8B52    C9                                RET
                                ;
  8B53    CD 8919               D0.ALD2:    CALL    D0.DDU25
  8B56    3E 44                             LD      A,'D'
  8B58    32 B199                           LD      (MS.TK),A
  8B5B    CD CB16                           CALL    MO.MONI
  8B5E    3E 4A                             LD      A,74
  8B60    32 B18D                           LD      (MS.SPOS),A
  8B63    06 05                             LD      B,5
  8B65    CD 893E                           CALL    D0.DDU26
  8B68    21 4B15                           LD      HL,04B15H
  8B6B    22 B18E                           LD      (MS.ZMIN),HL
  8B6E    21 4A14                           LD      HL,04A14H
  8B71    22 B18C                           LD      (MS.ZPOS),HL
  8B74    CD 8C97                           CALL    D0.AD2
  8B77    18 CE                             JR      D0.ALD
                                ;
  8B79                          D0.ALO1     EQU     $
  8B79                          D0.ALO2     EQU     $
  8B79                          D0.ALB1     EQU     $
  8B79    C9                    D0.ALB2:    RET
                                ;
                                ;
                                ;
  8B7A    CD 8919               D0.ALA1:    CALL    D0.DDU25
  8B7D    3E 41                             LD      A,'A'
  8B7F    32 B199                           LD      (MS.TK),A
  8B82    CD CB16                           CALL    MO.MONI
  8B85    3E 4E                             LD      A,78
  8B87    32 B18D                           LD      (MS.SPOS),A
  8B8A    06 01                             LD      B,1
  8B8C    CD 893E                           CALL    D0.DDU26
  8B8F    21 4F15                           LD      HL,04F15H
  8B92    22 B18E                           LD      (MS.ZMIN),HL
  8B95    21 4E14                           LD      HL,04E14H
  8B98    22 B18C                           LD      (MS.ZPOS),HL
  8B9B    06 01                             LD      B,1
  8B9D    21 B28E                           LD      HL,S2.DL
  8BA0    CD CB16                           CALL    MO.MONI
  8BA3    21 8CBE               D0.ALA:     LD      HL,D0.AZEIN
  8BA6    22 B22D                           LD      (TS.EINA),HL
  8BA9    3E FF                             LD      A,0FFH
  8BAB    32 B23F                           LD      (TS.SPMER),A
  8BAE    C9                                RET
                                ;
  8BAF    CD 8919               D0.ALA2:    CALL    D0.DDU25
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-33


  8BB2    3E 41                             LD      A,'A'
  8BB4    32 B199                           LD      (MS.TK),A
  8BB7    CD CB16                           CALL    MO.MONI
  8BBA    3E 4D                             LD      A,77
  8BBC    32 B18D                           LD      (MS.SPOS),A
  8BBF    06 02                             LD      B,2
  8BC1    CD 893E                           CALL    D0.DDU26
  8BC4    21 4E15                           LD      HL,04E15H
  8BC7    22 B18E                           LD      (MS.ZMIN),HL
  8BCA    21 4D14                           LD      HL,04D14H
  8BCD    22 B18C                           LD      (MS.ZPOS),HL
  8BD0    3A B28F                           LD      A,(S2.DH)
  8BD3    32 B29A                           LD      (S2.DM1),A
  8BD6    3A B28E                           LD      A,(S2.DL)
  8BD9    32 B29B                           LD	    (S2.DM1+1),A
  8BDC    06 02                             LD      B,2
  8BDE    21 B29A                           LD      HL,S2.DM1
  8BE1    CD CB16                           CALL    MO.MONI
  8BE4    18 BD                             JR      D0.ALA
                                ;
                                ;
                                ;
  8BE6    CD 8A11               D0.AW:      CALL    D0.AS
  8BE9    3A B23C                           LD      A,(TS.TK)
  8BEC    32 B28A                           LD      (S2.AFOR),A
  8BEF    CD 8AB2                           CALL    D0.AL
  8BF2    C9                                RET
                                ;
                                ;
                                ;
  8BF3    21 C2D3               D0.TA01:    LD      HL,S1.CNLS
  8BF6    22 B20D                           LD      (TS.TAB2+14),HL
  8BF9    21 C2B4                           LD      HL,S1.CNRS
  8BFC    22 B211                           LD      (TS.TAB2+18),HL
  8BFF    21 C334                           LD      HL,S1.NN
  8C02    22 B217                           LD      (TS.TAB3),HL
  8C05    21 C345                           LD      HL,S1.NNN
  8C08    22 B219                           LD      (TS.TAB3+2),HL
  8C0B    C9                                RET
                                ;
                                ;
                                ;
  8C0C    C5                    D0.TA02:    PUSH    BC
  8C0D    D5                                PUSH    DE
  8C0E    E5                                PUSH    HL
  8C0F    CD D40E                           CALL    TA.LOE
  8C12    3E 02                             LD      A,2	
  8C14    32 B198                           LD      (MS.CMD),A	
  8C17    CD CB16                           CALL    MO.MONI
  8C1A    CD 87C8                           CALL    D0.DDU08            ;Rahmen P-Tasten anzeigen
  8C1D    E1                                POP     HL                  ;Rahmen fuellen
  8C1E    CD 8879                           CALL    D0.DDU16
  8C21    E1                                POP     HL
  8C22    11 B19F                           LD      DE,TS.TAB1
  8C25    C1                                POP     BC
  8C26    ED B0                             LDIR
  8C28    C9                                RET
                                ;
                                ;
                                ;
  8C29    21 80C2               D0.TA03:    LD      HL,D0.DDPT3-4
  8C2C    11 80BC                           LD      DE,D0.DDPT2
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-34


  8C2F    01 000A                           LD      BC,10
  8C32    CD 8C0C               D0.TA04:    CALL    D0.TA02
  8C35    AF                                XOR     A                   ;Anzeigeformat auf hexa
  8C36    32 B28A                           LD      (S2.AFOR),A
  8C39    3E 02                             LD      A,2                 ;Eingabe auf 2 Byte
  8C3B    32 B28B                           LD      (S2.BZ),A
  8C3E    C9                                RET
                                ;
                                ;
                                ;
                                ;**********************************************************************
                                ;*	                     Fenster gleich Eingabebereich definieren     *
                                ;**********************************************************************
  8C3F    21 3614               D0.MO01:    LD      HL,03614H           ;ZMIN = 20 , SMIN = 54
  8C42    22 B18E                           LD      (MS.ZMIN),HL
  8C45    21 4F15                           LD      HL,04F15H           ;ZMAX = 21 , SMAX = 79
  8C48    22 B190                           LD      (MS.ZMAX),HL
  8C4B    21 3513                           LD      HL,03513H           ;ZPOS = 19 , SPOS = 53
  8C4E    22 B18C                           LD      (MS.ZPOS),HL
  8C51    3E C0                             LD      A,0C0H
  8C53    32 B197                           LD      (MS.DIRES),A
  8C56    C9                                RET
                                ;**********************************************************************
                                ;*	                     Anzeige von   <S2.DL>   hexadezimal          *
                                ;**********************************************************************
  8C57    3A B28E               D0.AH1:     LD      A,(S2.DL)
  8C5A    21 B29A                           LD      HL,S2.DM1
  8C5D    CD C5FF                           CALL    S1.BHKON
  8C60    06 02                             LD      B,2
  8C62    21 B29A                           LD      HL,S2.DM1
  8C65    CD CB16                           CALL    MO.MONI
  8C68    C9                                RET
                                ;**********************************************************************
                                ;*	                     Anzeige von   <S2.DH,S2.DL>   hexadezimal    *
                                ;**********************************************************************
  8C69    3A B28F               D0.AH2:     LD      A,(S2.DH)
  8C6C    21 B29A                           LD      HL,S2.DM1
  8C6F    CD C5FF                           CALL    S1.BHKON
  8C72    3A B28E                           LD      A,(S2.DL)
  8C75    23                                INC     HL
  8C76    CD C5FF                           CALL    S1.BHKON
  8C79    06 04                             LD      B,4
  8C7B    21 B29A                           LD      HL,S2.DM1
  8C7E    CD CB16                           CALL    MO.MONI
  8C81    C9                                RET
                                ;
                                ;
                                ;
  8C82    2A B28E               D0.AD1:     LD      HL,(S2.DL)
  8C85    11 B29A                           LD      DE,S2.DM1
  8C88    3E 41                             LD      A,'A'
  8C8A    12                                LD      (DE) ,A
  8C8B    CD C54E                           CALL    S1.HDI
  8C8E    06 03                             LD      B,3
  8C90    21 B29D                           LD      HL,S2.DM1+3
  8C93    CD CB16                           CALL    MO.MONI
  8C96    C9                                RET
                                ;
  8C97    2A B28E               D0.AD2:     LD      HL,(S2.DL)
  8C9A    11 B29A                           LD      DE,S2.DM1
  8C9D    3E 41                             LD      A,'A'
  8C9F    12                                LD      (DE),A
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-35


  8CA0    CD C54E                           CALL    S1.HDI
  8CA3    06 05                             LD      B,5
  8CA5    21 B29B                           LD      HL,S2.DM1+1
  8CA8    CD CB16                           CALL    MO.MONI
  8CAB    C9                                RET
                                ;
                                ;
                                ;
  8CAC    3A B23C               D0.HZEIN:   LD      A,(TS.TK)
  8CAF    FE 47                             CP      'G'
  8CB1    D0                                RET     NC
  8CB2    FE 41                             CP      'A'
  8CB4    30 08                             JR      NC,D0.DZEIN
  8CB6    FE 3A                             CP      ':'
  8CB8    D0                                RET     NC
  8CB9    FE 30                             CP      '0'
  8CBB    30 01                             JR      NC,D0.DZEIN
  8CBD    C9                                RET
                                ;
  8CBE                          D0.AZEIN    EQU     $
  8CBE    CD C328               D0.DZEIN:   CALL    S1.AEIN
  8CC1    3E 01                             LD      A,1
  8CC3    32 B242                           LD      (TS.ZSMER),A
  8CC6    C9                                RET
                                ;
  8CC7    3A B23C               D0.OZEIN:   LD      A,(TS.TK)
  8CCA    FE 38                             CP      '8'
  8CCC    D0                                RET     NC
  8CCD    18 EF                             JR      D0.DZEIN
                                ;
  8CCF    3A B23C               D0.BZEIN:   LD      A,(TS.TK)
  8CD2    FE 32                             CP      '2'
  8CD4    D0                                RET     NC
  8CD5    18 E7                             JR      D0.DZEIN
                                ;
                                ;           PN      D103
                                ;****************************************************************
                                ;*                  D E B U G   ---   Programm   MEMO           '
                                ;*   Version        --------------------------------------------*
                                ;*                  Programmierer: Marcus Herbote--- IfR - OE-S *
                                ;*   V 1 . 0        --------------------------------------------*
                                ;*                  Stand        : 22.November 1982             *
                                ;****************************************************************
  8CD7    56 31 2E 30                       DB      'V1.0/22.11.82'
  8CDB    2F 32 32 2E           
  8CDF    31 31 2E 38           
  8CE3    32                    
  8CE4    8CE4                              DW      $
  8CE6    4D 45 4D 32                       DB      'MEM2'
  8CEA    CD C532                           CALL    S1.INPTR
  8CED    23                                INC     HL
  8CEE    CD C5CC                           CALL    S1.HBKON
  8CF1    5F                                LD      E,A
  8CF2    AF                                XOR     A                   ;Merker fuer Rueckkehr ins System
                                ;****************************************************************
                                ;*                  Eintrittspunkt vom DEBUG - Steuerprogramm   *
                                ;****************************************************************
  8CF3    F5                    D1.MEMO:    PUSH    AF
  8CF4    ED 53 B292                        LD      (S2.DMANF),DE
  8CF8    ED 53 B294                        LD      (S2.DMCUR),DE
  8CFC    AF                                XOR     A
  8CFD    32 B2AA                           LD      (S2.DM2),A
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-36


  8D00    21 0000                           LD      HL,0                ;Bereich auf 0000 bis 0000 setzen
  8D03    22 B296                           LD      (S2.DMBA),HL
  8D06    22 B298                           LD      (S2.DMBE),HL
  8D09    21 0B00                           LD      HL,00B00H           ;ZPOS = 0 , SPOS = 11
  8D0C    22 B18C                           LD      (MS.ZPOS),HL
  8D0F    3E 18                             LD      A,24
  8D11    32 B198                           LD      (MS.CMD),A
  8D14    06 26                             LD      B,38
  8D16    21 8D1E                           LD      HL,$+8
  8D19    CD CB16                           CALL    MO.MONI
  8D1C    18 26                             JR      $+40
                                ;
  8D1E    4D 65 6D 6F                       DB      'Memory Display and Change Version 1.0'
  8D22    72 79 20 44           
  8D26    69 73 70 6C           
  8D2A    61 79 20 61           
  8D2E    6E 64 20 43           
  8D32    68 61 6E 67           
  8D36    65 20 56 65           
  8D3A    72 73 69 6F           
  8D3E    6E 20 31 2E           
  8D42    30                    
  8D43    21 0015                           LD      HL,00015H           ;ZPOS = 21 , SPOS = 0
  8D46    22 B18C                           LD      (MS.ZPOS),HL
  8D49    06 3A                             LD      B,58
  8D4B    21 8D53                           LD      HL,$+8
  8D4E    CD CB16                           CALL    MO.MONI
  8D51    18 3A                             JR      $+60
                                ;
  8D53    43 75 72 73                       DB      'Cursorposition: .... '
  8D57    6F 72 70 6F           
  8D5B    73 69 74 69           
  8D5F    6F 6E 3A 20           
  8D63    2E 2E 2E 2E           
  8D67    20                    
  8D68    42 65 72 65                       DB      'Bereichanfang:	'
  8D6C    69 63 68 61           
  8D70    6E 66 61 6E           
  8D74    67 3A 09              
  8D77    42 65 72 65                       DB      'Bereichende: ....'
  8D7B    69 63 68 65           
  8D7F    6E 64 65 3A           
  8D83    20 2E 2E 2E           
  8D87    2E                    
  8D88    CD 91B8                           CALL    DMB
  8D8B    CD 920C                           CALL    DMCP
  8D8E    CD 9217                           CALL    DMBAP
  8D91    CD 9222                           CALL    DMBEP
  8D94    21 0802                           LD      HL,00802H           ;ZPOS = 2 , SPOS = 8
  8D97    22 B28E                           LD      (S2.DL),HL
  8D9A    21 B197                           LD      HL,MS.DIRES
  8D9D    CB EE                             SET     5, (HL)
  8D9F    CD 910D                           CALL    DMUP4
                                            TITLE   'Tastaturdefinitionen'
                                            PAGE
'Tastaturdefinitionen'	MACRO-80 3.44	09-Dec-81	PAGE	1-37


                                
                                ;****************************************************************
                                ;*                  Tastaturdefinitionen                        *
                                ;****************************************************************
  8DA2    CD D40E                           CALL    TA.LOE
  8DA5    21 922D                           LD      HL,DMP4
  8DA8    22 B1A5                           LD      (TS.TAB1+6),HL
  8DAB    21 923D                           LD      HL,DMP5
  8DAE    22 B1A7                           LD      (TS.TAB1+8),HL
  8DB1    21 8DE8                           LD      HL,DMTAB
  8DB4    11 B1FF                           LD      DE,TS.TAB2
  8DB7    01 0034                           LD      BC,52
  8DBA    ED B0                             LDIR
  8DBC    3E A8                             LD      A,0A8H
  8DBE    32 B23F                           LD      (TS.SPMER),A
  8DC1    F1                                POP     AF
  8DC2    FE 00                             CP      0
  8DC4    28 0C                             JR      Z,MEMS
  8DC6    FE 01                             CP      1
  8DC8    28 09                             JR      Z,MEMD
  8DCA    FE 02                             CP      2
  8DCC    28 0C                             JR      Z,MEMR
  8DCE    FE 03                             CP      3
  8DD0    28 0F                             JR      Z,MEMU
  8DD2    C9                    MEMS:       RET
  8DD3    21 801C               MEMD:       LD      HL,D0.DD
  8DD6    22 B21D                           LD      (TS.TAB3+6),HL
  8DD9    C9                                RET
  8DDA    21 8664               MEMR:       LD      HL,D0.RGDC
  8DDD    22 B21D                           LD      (TS.TAB3+6),HL
  8DE0    C9                                RET
  8DE1    21 8664               MEMU:       LD      HL,D0.UCPU
  8DE4    22 B21D                           LD      (TS.TAB3+6),HL
  8DE7    C9                                RET
                                ;****************************************************************
                                ;*                  Tastenroutinen-Adress-Tabelle               *
                                ;****************************************************************
  8DE8    8F73                  DMTAB:      DW      DMIM
  8DEA    0000                              DW      0
  8DEC    0000                              DW      0
  8DEE    0000                              DW      0
  8DF0    9077                              DW      DMSL                ;SCH LINKS
  8DF2    8E1C                              DW      DMCN
  8DF4    90AB                              DW      DMSR                ;SCH RECHTS
  8DF6    8E8D                              DW      DMCW
  8DF8    8EF5                              DW      DMHOM
  8DFA    8EC6                              DW      DMCO
  8DFC    8F0D                              DW      DMNZ
  8DFE    8E55                              DW      DMCS
  8E00    905A                              DW      DMN2H
  8E02    904B                              DW      DMN3H
  8E04    8F1C                              DW      DMNQU
  8E06    C114                              DW      S1.SYSTB
  8E08    0000                              DW      0
  8E0A    0000                              DW      0
  8E0C    8F51                              DW      DMPQU
  8E0E    0000                              DW      0
  8E10    0000                              DW      0
  8E12    0000                              DW      0
  8E14    0000                              DW      0
  8E16    8FC1                              DW      DMAH                ;EINA
'Tastaturdefinitionen'	MACRO-80 3.44	09-Dec-81	PAGE	1-38


  8E18    0000                              DW      0                   ;TABU
  8E1A    0000                              DW      0                   ;NEW LINE
                                
                                            TITLE   'Cursortastenroutinen'
                                            PAGE
'Cursortastenroutinen'	MACRO-80 3.44	09-Dec-81	PAGE	1-39


                                
                                ;****************************************************************
                                ;*                  Cursortastenroutine:	DMCN                *
                                ;****************************************************************
  8E1C    21 913D               DMCN:       LD      HL,DMRO
  8E1F    22 B19A                           LD      (MS.RADR),HL
  8E22    3E E2                             LD      A,0E2H
  8E24    32 B197                           LD      (MS.DIRES),A
  8E27    3E 15                             LD      A,21
  8E29    32 B198                           LD      (MS.CMD),A
  8E2C    CD CB16                           CALL    MO.MONI
  8E2F    3E E0                             LD      A,0E0H
  8E31    32 B197                           LD      (MS.DIRES),A
  8E34    CD 90F4                           CALL    DMUP3
  8E37    2A B294                           LD      HL,(S2.DMCUR)
  8E3A    3A B240               	        LD      A,(TS.UMERK)
  8E3D    B7                                OR      A
  8E3E    20 10                             JR      NZ,DMCN2
  8E40    11 0010                           LD      DE,10H
  8E43    ED 52                 DMCN1:      SBC     HL,DE
  8E45    22 B294                           LD      (S2.DMCUR),HL
  8E48    CD 920C                           CALL    DMCP
  8E4B    CD 910D                           CALL    DMUP4
  8E4E    18 36                             JR      DMCS3
                                ;
  8E50    11 0040               DMCN2:      LD      DE,40H
  8E53    18 EE                             JR      DMCN1
                                ;****************************************************************
                                ;*                  Cursortastenroutine:	DMCS                *
                                ;****************************************************************
  8E55    21 9167               DMCS:       LD      HL,DMRU
  8E58    22 B19A                           LD      (MS.RADR),HL
  8E5B    3E E6                             LD      A,0E6H
  8E5D    32 B197                           LD      (MS.DIRES),A
  8E60    3E 15                             LD      A,21
  8E62    32 B198                           LD      (MS.CMD),A
  8E65    CD CB16                           CALL    MO.MONI
  8E68    3E E0                             LD      A,0E0H
  8E6A    32 B197                           LD      (MS.DIRES),A
  8E6D    CD 90F4                           CALL    DMUP3
  8E70    2A B294                           LD      HL,(S2.DMCUR)
  8E73    3A B240                           LD      A,(TS.UMERK)
  8E76    B7                                OR      A
  8E77    20 0F                             JR      NZ,DMCS2
  8E79    11 0010                           LD      DE,10H
  8E7C    19                    DMCS1:      ADD     HL,DE
  8E7D    22 B294                           LD      (S2.DMCUR),HL
  8E80    CD 920C                           CALL    DMCP
  8E83    CD 910D                           CALL    DMUP4
  8E86    18 3C                 DMCS3:      JR      DMCW2
                                ;
  8E88    11 0040               DMCS2:      LD      DE,40H
  8E8B    18 EF                             JR      DMCS1
                                ;
                                            PAGE
'Cursortastenroutinen'	MACRO-80 3.44	09-Dec-81	PAGE	1-40


                                
                                ;****************************************************************
                                ;*                  Cursortastenroutine:	DMCW                *
                                ;****************************************************************
  8E8D    21 913D               DMCW:       LD      HL,DMRO
  8E90    22 B19A                           LD      (MS.RADR),HL
  8E93    3E E4                             LD      A,0E4H
  8E95    32 B197                           LD      (MS.DIRES),A
  8E98    3E 15                             LD      A,21
  8E9A    32 B198                           LD      (MS.CMD),A
  8E9D    CD CB16                           CALL    MO.MONI
  8EA0    3A B240                           LD      A,(TS.UMERK)
  8EA3    B7                                OR      A
  8EA4    20 09                             JR      NZ,DMCW1
  8EA6    CD CB16                           CALL    MO.MONI
  8EA9    CD CB16                           CALL    MO.MONI
  8EAC    CD CB16                           CALL    MO.MONI
  8EAF    3E E0                 DMCW1:      LD      A,0E0H
  8EB1    32 B197                           LD      (MS.DIRES),A
  8EB4    CD 90F4                           CALL    DMUP3
  8EB7    2A B294                           LD      HL,(S2.DMCUR)
  8EBA    2B                                DEC     HL
  8EBB    22 B294                           LD      (S2.DMCUR),HL
  8EBE    CD 920C                           CALL    DMCP
  8EC1    CD 910D                           CALL    DMUP4
  8EC4    18 2D                 DMCW2:      JR      DMCO2
                                ;****************************************************************
                                ;*                  Cursortastenroutine:	DMCO                *
                                ;****************************************************************
  8EC6    21 9167               DMCO:       LD      HL,DMRU
  8EC9    22 B19A                           LD      (MS.RADR),HL
  8ECC    3E 15                             LD      A,21
  8ECE    32 B198                           LD      (MS.CMD),A
  8ED1    CD CB16                           CALL    MO.MONI
  8ED4    3A B240                           LD      A,(TS.UMERK)
  8ED7    B7                                OR      A
  8ED8    20 09                             JR      NZ,DMCO1
  8EDA    CD CB16                           CALL    MO.MONI
  8EDD    CD CB16                           CALL    MO.MONI
  8EE0    CD CB16                           CALL    MO.MONI
  8EE3    CD 90F4               DMCO1:      CALL    DMUP3
  8EE6    2A B294                           LD      HL,(S2.DMCUR)
  8EE9    23                                INC     HL
  8EEA    22 B294                           LD      (S2.DMCUR),HL
  8EED    CD 920C                           CALL    DMCP
  8EF0    CD 910D                           CALL    DMUP4
  8EF3    18 54                 DMCO2:      JR      DMNQ4
                                ;
                                            PAGE
'Cursortastenroutinen'	MACRO-80 3.44	09-Dec-81	PAGE	1-41


                                
                                ;****************************************************************
                                ;*                  Cursortastenroutine:	DMHOM               *
                                ;****************************************************************
  8EF5    3E 16                 DMHOM:      LD      A,22
  8EF7    32 B198                           LD      (MS.CMD),A
  8EFA    CD CB16                           CALL    MO.MONI
  8EFD    CD 90F4                           CALL    DMUP3
  8F00    2A B292                           LD      HL,(S2.DMANF)
  8F03    22 B294                           LD      (S2.DMCUR),HL
  8F06    CD 920C                           CALL    DMCP
  8F09    CD 910D                           CALL    DMUP4
  8F0C    C9                                RET
                                ;****************************************************************
                                ;*                  Cursortastenroutine:	DMNZ                *
                                ;****************************************************************
  8F0D    3E 17                 DMNZ:       LD      A,23
  8F0F    32 B198                           LD      (MS.CMD),A
  8F12    CD CB16                           CALL    MO.MONI
  8F15    CD 90F4                           CALL    DMUP3
  8F18    2A B292                           LD      HL,(S2.DMANF)
  8F1B    C9                                RET
                                ;            
                                            TITLE   'Tastenroutinen : PQU / NQU '
                                            PAGE
'Tastenroutinen : PQU / NQU '	MACRO-80 3.44	09-Dec-81	PAGE	1-42


                                
                                ;****************************************************************
                                ;*                  Tastenroutine negative Quittierung          *
                                ;****************************************************************
  8F1C    CD 90F4               DMNQU:      CALL    DMUP3
  8F1F    2A B18C                           LD      HL,(MS.ZPOS)
  8F22    E5                                PUSH    HL
  8F23    3A B240                           LD      A,(TS.UMERK)
  8F26    B7                                OR      A
  8F27    20 23                             JR      NZ,DMNQ2
  8F29    11 0100                           LD      DE,100H
  8F2C    2A B292               DMNQ1:      LD      HL,(S2.DMANF)
  8F2F    ED 52                             SBC     HL,DE
  8F31    22 B292                           LD      (S2.DMANF),HL
  8F34    2A B294                           LD      HL,(S2.DMCUR)
  8F37    ED 52                             SBC     HL,DE
  8F39    22 B294               DMNQ3:      LD      (S2.DMCUR),HL
  8F3C    CD 91B8                           CALL    DMB
  8F3F    CD 920C                           CALL    DMCP
  8F42    E1                                POP     HL
  8F43    22 B18C                           LD      (MS.ZPOS),HL
  8F46    CD 910D                           CALL    DMUP4
  8F49    C3 8FE3               DMNQ4:      JP      DMAH3
                                ;
  8F4C    11 0400               DMNQ2:      LD      DE,400H
  8F4F    18 DB                             JR      DMNQ1
                                ;****************************************************************
                                ;*                  Tastenroutine positive Quittierung          *
                                ;****************************************************************
  8F51    CD 90F4               DMPQU:      CALL    DMUP3
  8F54    2A B18C                           LD      HL,(MS.ZPOS)
  8F57    E5                                PUSH    HL
  8F58    3A B240                           LD      A,(TS.UMERK)
  8F5B    B7                                OR      A
  8F5C    20 10                             JR      NZ,DMPQ2
  8F5E    11 0100                           LD      DE,100H
  8F61    2A B292               DMPQ1:      LD      HL,(S2.DMANF)
  8F64    19                                ADD     HL,DE
  8F65    22 B292                           LD      (S2.DMANF),HL
  8F68    2A B294                           LD      HL,(S2.DMCUR)
  8F6B    19                                ADD     HL,DE
  8F6C    18 CB                             JR      DMNQ3
  8F6E    11 0400               DMPQ2:      LD      DE,400H
  8F71    18 EE                             JR      DMPQ1
                                ;
                                            TITLE   'Tastenroutine: DMIM '
                                            PAGE
'Tastenroutine: DMIM '	MACRO-80 3.44	09-Dec-81	PAGE	1-43


                                
                                ;****************************************************************
                                ;*                  Tastenroutine   insert mode                 *
                                ;****************************************************************
  8F73    CD 90F4               DMIM:       CALL    DMUP3               ;Umschalten alpha <==> hexa
  8F76    2A B294                           LD      HL,(S2.DMCUR)
  8F79    22 B292                           LD      (S2.DMANF),HL
  8F7C    CD 91B8                           CALL    DMB
  8F7F    CD 920C                           CALL    DMCP
  8F82    21 0802                           LD      HL,00802H           ;ZPOS = 2 , SPOS = 8
  8F85    22 B28E                           LD      (S2.DL),HL
  8F88    CD 910D                           CALL    DMUP4
  8F8B    3A B240                           LD      A,(TS.UMERK)
  8F8E    B7                                OR      A
  8F8F    20 18                             JR      NZ,DMIM1
  8F91    21 8FC1                           LD      HL,DMAH
  8F94    22 B22D                           LD      (TS.EINA),HL
  8F97    21 905A                           LD      HL,DMN2H
  8F9A    22 B217                           LD      (TS.TAB3),HL
  8F9D    21 904B                           LD      HL,DMN3H
  8FA0    22 B219                           LD      (TS.TAB3+2),HL
  8FA3    3E A8                             LD      A,0A8H
  8FA5    32 B23F                           LD      (TS.SPMER),A
  8FA8    C9                                RET
                                ;
  8FA9    21 9030               DMIM1:      LD      HL,DMAA
  8FAC    22 B22D                           LD      (TS.EINA),HL
  8FAF    21 9070                           LD      HL,DMN2A
  8FB2    22 B217                           LD      (TS.TAB3),HL
  8FB5    21 9061                           LD      HL,DMN3A
  8FB8    22 B219                           LD      (TS.TAB3+2),HL
  8FBB    3E FF                             LD      A,0FFH
  8FBD    32 B23F                           LD      (TS.SPMER),A
  8FC0    C9                                RET
                                ;
                                            TITLE   'Tastenroutinen: DMAH/DMAA '
                                            PAGE
'Tastenroutinen: DMAH/DMAA '	MACRO-80 3.44	09-Dec-81	PAGE	1-44


                                
                                ;****************************************************************
                                ;*                  Tastenroutinen fuer alphanumerische Tasten  *
                                ;****************************************************************
  8FC1    3A B23C               DMAH:       LD      A,(TS.TK)
  8FC4    FE 47                             CP      'G'
  8FC6    D0                                RET     NC
  8FC7    FE 41                             CP      'A'
  8FC9    30 08                             JR      NC,DMAH1
  8FCB    FE 3A                             CP      ':'
  8FCD    D0                                RET     NC
  8FCE    FE 30                             CP      '0'
  8FD0    30 01                             JR      NC,DMAH1
  8FD2    C9                                RET
                                ;
  8FD3    3A B2AA               DMAH1:      LD      A,(S2.DM2)
  8FD6    B7                                OR      A
  8FD7    20 10                             JR      NZ,DMAH4
  8FD9    3C                                INC     A
  8FDA    32 B2AA                           LD      (S2.DM2),A
  8FDD    3A B23C                           LD      A,(TS.TK)
  8FE0    32 B2AB                           LD      (S2.DMH),A
  8FE3    3E 01                 DMAH3:      LD      A,1
  8FE5    32 B242                           LD      (TS.ZSMER),A
  8FE8    C9                                RET
                                ;
  8FE9    3A B23C               DMAH4:      LD      A,(TS.TK)
  8FEC    32 B2AC                           LD      (S2.DML),A
  8FEF    21 B2AB                           LD      HL,S2.DMH
  8FF2    CD C5CC                           CALL    S1.HBKON
  8FF5    2A B294                           LD      HL,(S2.DMCUR)
  8FF8    77                                LD      (HL),A
  8FF9    7E                                LD      A,(HL)              ;???
  8FFA    21 B2AB                           LD      HL,S2.DMH
  8FFD    CD C5FF                           CALL    S1.BHKON
  9000    21 9167                           LD      HL,DMRU
  9003    22 B19A                           LD      (MS.RADR),HL
  9006    3E 18                             LD      A,24
  9008    32 B198                           LD      (MS.CMD),A
  900B    21 B2AB                           LD      HL,S2.DMH
  900E    06 02                             LD      B,2
  9010    CD CB16                           CALL    MO.MONI
  9013    3E 15                             LD      A,21
  9015    32 B198                           LD      (MS.CMD),A
  9018    CD CB16                           CALL    MO.MONI
  901B    CD CB16                           CALL    MO.MONI
  901E    2A B294               DMAH5:      LD      HL,(S2.DMCUR)
  9021    23                                INC     HL
  9022    22 B294                           LD      (S2.DMCUR),HL
  9025    CD 90F4                           CALL    DMUP3
  9028    CD 920C                           CALL    DMCP
  902B    CD 910D                           CALL    DMUP4
  902E    18 B3                             JR      DMAH3
                                            PAGE
'Tastenroutinen: DMAH/DMAA '	MACRO-80 3.44	09-Dec-81	PAGE	1-45


                                
                                ;****************************************************************
                                ;*                                                              *
                                ;****************************************************************
  9030    2A B294               DMAA:       LD      HL,(S2.DMCUR)
  9033    3A B199                           LD      A,(MS.TK)
  9036    77                                LD      (HL),A
  9037    7E                                LD      A,(HL)              ;???
  9038    32 B199                           LD      (MS.TK),A
  903B    3E 14                             LD      A,20
  903D    32 B198                           LD      (MS.CMD),A
  9040    21 9167                           LD      HL,DMRU
  9043    22 B19A                           LD      (MS.RADR),HL
  9046    CD CB16                           CALL    MO.MONI
  9049    18 D3                             JR      DMAH5
                                ;****************************************************************
                                ;*                                                              *
                                ;****************************************************************
  904B    3E 30                 DMN3H:      LD      A,'0'
  904D    32 B23C                           LD      (TS.TK),A
  9050    CD 8FC1                           CALL    DMAH
  9053    CD 8FC1               DMN31:      CALL    DMAH
  9056    CD 8FC1                           CALL    DMAH
  9059    C9                                RET
                                ;
  905A    3E 30                 DMN2H:      LD      A,'0'
  905C    32 B23C                           LD      (TS.TK),A
  905F    18 F2                             JR      DMN31
                                ;****************************************************************
                                ;*                                                              *
                                ;****************************************************************
  9061    3E 30                 DMN3A:      LD      A,'0'
  9063    32 B23C                           LD      (TS.TK),A
  9066    CD 9030                           CALL    DMAA
  9069    CD 9030               DMN32:      CALL    DMAA
  906C    CD 9030                           CALL    DMAA
  906F    C9                                RET
                                ;
  9070    3E 30                 DMN2A:      LD      A,'0'
  9072    32 B23C                           LD      (TS.TK),A
  9075    18 F2                             JR      DMN32
                                            TITLE   'Tastenroutinen: DMSL/DMSR '
                                            PAGE
'Tastenroutinen: DMSL/DMSR '	MACRO-80 3.44	09-Dec-81	PAGE	1-46


                                
                                ;****************************************************************
                                ;*                  Tastenroutine Schieben links                *
                                ;****************************************************************
  9077    2A B298               DMSL:       LD      HL,(S2.DMBE)
  907A    ED 5B B296                        LD      DE,(S2.DMBA)
  907E    B7                                OR      A
  907F    ED 52                             SBC     HL,DE
  9081    F8                                RET     M
  9082    23                                INC     HL
  9083    E5                                PUSH    HL
  9084    C1                                POP     BC
  9085    2A B296                           LD      HL,(S2.DMBA)
  9088    1B                                DEC     DE
  9089    ED B0                             LDIR
  908B    2A B296                           LD      HL,(S2.DMBA)
  908E    2B                                DEC     HL
  908F    22 B296                           LD      (S2.DMBA),HL
  9092    2A B298                           LD      HL, (S2.DMBE)
  9095    2B                                DEC     HL
  9096    22 B298                           LD      (S2.DMBE),HL
  9099    CD 90F4               DMSL1:      CALL    DMUP3
  909C    CD 91B8                           CALL    DMB
  909F    CD 9217                           CALL    DMBAP
  90A2    CD 9222                           CALL    DMBEP
  90A5    CD 910D                           CALL    DMUP4
  90A8    C3 8FE3                           JP      DMAH3
                                ;****************************************************************
                                ;*                  Tastenroutine Schieben rechts               *
                                ;****************************************************************
  90AB    2A B298               DMSR:       LD      HL,(S2.DMBE)
  90AE    ED 5B B296                        LD      DE,(S2.DMBA)
  90B2    B7                                OR      A
  90B3    ED 52                             SBC     HL,DE
  90B5    F8                                RET     M
  90B6    23                                INC     HL
  90B7    E5                                PUSH    HL
  90B8    C1                                POP     BC
  90B9    2A B298                           LD      HL,(S2.DMBE)
  90BC    ED 5B B298                        LD      DE,(S2.DMBE)
  90C0    13                                INC     DE
  90C1    ED B8                             LDDR
  90C3    2A B296                           LD      HL,(S2.DMBA)
  90C6    23                                INC     HL
  90C7    22 B296                           LD      (S2.DMBA),HL
  90CA    2A B298                           LD      HL,(S2.DMBE)
  90CD    23                                INC     HL
  90CE    22 B298                           LD      (S2.DMBE),HL
  90D1    18 C6                             JR      DMSL1
                                ;
                                            TITLE   'MEMO -- Unterprogramme'
                                            PAGE
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-47


                                
                                ;****************************************************************
                                ;*                                                              *
                                ;****************************************************************
  90D3    E5                    DMUP1:      PUSH    HL                  ;Zieladresse   Zeile loeschen
  90D4    D1                                POP     DE
  90D5    D5                                PUSH    DE
  90D6    13                                INC     DE
  90D7    36 20                             LD      (HL),' '
  90D9    ED 4B B193                        LD      BC,(MS.SPANZ)
  90DD    06 00                             LD      B,0
  90DF    ED B0                             LDIR
  90E1    E1                                POP     HL
  90E2    ED 5B B29A                        LD      DE,(S2.DM1)         ;Zeilenadresse aufbereiten
  90E6    7A                                LD      A,D
  90E7    CD C5FF                           CALL    S1.BHKON
  90EA    23                                INC     HL
  90EB    7B                                LD      A,E
  90EC    CD C5FF                           CALL    S1.BHKON
  90EF    01 0005                           LD      BC,5
  90F2    09                                ADD     HL,BC
  90F3    C9                                RET
                                ;****************************************************************
                                ;*                                                              *
                                ;****************************************************************
  90F4    21 B197               DMUP3:      LD      HL,MS.DIRES
  90F7    CB AE                             RES     5,(HL)
  90F9    2A B18C                           LD      HL,(MS.ZPOS)
  90FC    22 B28E                           LD      (S2.DL),HL
  90FF    3E 02                             LD      A,2
  9101    32 B198                           LD      (MS.CMD),A
  9104    CD CB16                           CALL    MO.MONI
  9107    3E 18                             LD      A,24
  9109    32 B198                           LD      (MS.CMD),A
  910C    C9                                RET
                                ;****************************************************************
                                ;*                                                              *
                                ;****************************************************************
  910D    3A B240               DMUP4:      LD      A,(TS.UMERK)
  9110    B7                                OR      A
  9111    20 22                             JR      NZ,DMU2
  9113    21 0903                           LD      HL,00903H           ;ZMIN =  3 , SMIN =  9
  9116    11 4812                           LD      DE,04812H           ;ZMAX = 18 , SMAX = 72
  9119    22 B18E               DMU1:       LD      (MS.ZMIN),HL
  911C    ED 53 B190                        LD      (MS.ZMAX),DE
  9120    3E 18                             LD      A,24
  9122    32 B198                           LD      (MS.CMD),A
  9125    AF                                XOR     A
  9126    32 B2AA                           LD      (S2.DM2),A
  9129    2A B28E                           LD      HL,(S2.DL)
  912C    22 B18C                           LD      (MS.ZPOS),HL
  912F    21 B197                           LD      HL,MS.DIRES
  9132    CB EE                             SET     5, (HL)
  9134    C9                                RET
                                ;
  9135    21 0903               DMU2:       LD      HL,00903H           ;ZMIN =  3 , SMIN =  9
  9138    11 4812                           LD      DE,04812H           ;ZMAX = 18 , SMAX = 72
  913B    18 DC                             JR      DMU1
                                            PAGE
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-48


                                
                                ;****************************************************************
                                ;*                  Anschlussroutine Rollfunktion oben raus     *
                                ;****************************************************************
  913D    E5                    DMRO:       PUSH    HL
  913E    2A B292                           LD      HL,(S2.DMANF)
  9141    3A B240                           LD      A,(TS.UMERK)
  9144    B7                                OR      A
  9145    20 10                             JR      NZ,DMRO1
  9147    11 0010                           LD      DE,10H
  914A    ED 52                             SBC     HL,DE
  914C    22 B292                           LD      (S2.DMANF),HL
  914F    22 B29A                           LD      (S2.DM1),HL
  9152    E1                                POP     HL
  9153    CD 9197                           CALL    DMZH
  9156    C9                                RET
                                ;
  9157    11 0040               DMRO1:      LD      DE,40H
  915A    ED 52                             SBC     HL,DE
  915C    22 B292                           LD      (S2.DMANF),HL
  915F    22 B29A                           LD      (S2.DM1),HL
  9162    E1                                POP     HL
  9163    CD 91AB                           CALL    DMZA
  9166    C9                                RET
                                ;****************************************************************
                                ;*                  Anschlussroutine Rollfunktion unten raus    *
                                ;****************************************************************
  9167    E5                    DMRU:       PUSH    HL
  9168    2A B292                           LD      HL,(S2.DMANF)
  916B    3A B240                           LD      A,(TS.UMERK)
  916E    B7                                OR      A
  916F    20 13                             JR      NZ,DMRU1
  9171    11 0010                           LD      DE,10H
  9174    19                                ADD     HL,DE
  9175    22 B292                           LD      (S2.DMANF),HL
  9178    11 00F0                           LD      DE,0F0H
  917B    19                                ADD     HL,DE
  917C    22 B29A                           LD      (S2.DM1),HL
  917F    E1                                POP     HL
  9180    CD 9197                           CALL    DMZH
  9183    C9                                RET
                                ;
  9184    11 0040               DMRU1:      LD      DE,40H
  9187    19                                ADD     HL,DE
  9188    22 B292                           LD      (S2.DMANF),HL
  918B    11 03C0                           LD      DE,03C0H
  918E    19                                ADD     HL,DE
  918F    22 B29A                           LD      (S2.DM1),HL
  9192    E1                                POP     HL
  9193    CD 91AB                           CALL    DMZA
  9196    C9                                RET
                                            PAGE
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-49


                                
                                ;****************************************************************
                                ;*                  16 Byte hexadezimal aufbereiten             *
                                ;****************************************************************
  9197    CD 90D3               DMZH:       CALL    DMUP1
  919A    06 10                             LD      B,16
  919C    1A                    DMZH1:      LD      A,(DE)
  919D    CD C5FF                           CALL    S1.BHKON
  91A0    23                                INC     HL
  91A1    23                                INC     HL
  91A2    23                                INC     HL
  91A3    13                                INC     DE
  91A4    10 F6                             DJNZ    DMZH1
  91A6    ED 53 B29A                        LD      (S2.DM1),DE
  91AA    C9                                RET
                                ;****************************************************************
                                ;*                  64 Byte alphanumerisch aufbereiten          *
                                ;****************************************************************
  91AB    CD 90D3               DMZA:       CALL    DMUP1
  91AE    EB                                EX      DE,HL
  91AF    01 0040                           LD      BC,64
  91B2    ED B0                             LDIR
  91B4    22 B29A                           LD      (S2.DM1),HL
  91B7    C9                                RET
                                ;****************************************************************
                                ;*                  gesamtes Bild aufbauen                      *
                                ;****************************************************************
  91B8    21 0002               DMB:        LD      HL,00002H
  91BB    22 B18C                           LD      (MS.ZPOS),HL
  91BE    ED 5B B292                        LD      DE,(S2.DMANF)
  91C2    ED 53 B29A                        LD      (S2.DM1),DE
  91C6    06 10                             LD      B,16
  91C8    C5                    DMB1:       PUSH    BC
  91C9    CD CF4B                           CALL    MO.BWSE
  91CC    23                                INC     HL
  91CD    3A B240                           LD      A,(TS.UMERK)
  91D0    B7                                OR      A
  91D1    20 12                             JR      NZ,DMB3
  91D3    CD 9197                           CALL    DMZH
  91D6    CD CF4B               DMB2:       CALL    MO.BWSE
  91D9    23                                INC     HL
  91DA    3A B193                           LD      A,(MS.SPANZ)
  91DD    47                                LD      B,A
  91DE    CD CB16                           CALL    MO.MONI
  91E1    C1                                POP     BC
  91E2    10 E4                             DJNZ    DMB1
  91E4    C9                                RET
                                ;
  91E5    CD 91AB               DMB3:       CALL    DMZA
  91E8    18 EC                             JR      DMB2
                                            PAGE
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-50


                                
                                ;****************************************************************
                                ;*                  Anzeige einer Adresse                       *
                                ;****************************************************************
  91EA    ED 53 B29A            DMADR:      LD      (S2.DM1),DE
  91EE    22 B18C                           LD      (MS.ZPOS),HL
  91F1    CD CF4B                           CALL    MO.BWSE
  91F4    23                                INC     HL
  91F5    ED 5B B29A                        LD      DE,(S2.DM1)
  91F9    7A                                LD      A,D
  91FA    CD C5FF                           CALL    S1.BHKON
  91FD    23                                INC     HL
  91FE    7B                                LD      A,E
  91FF    CD C5FF                           CALL    S1.BHKON
  9202    CD CF4B                           CALL    MO.BWSE
  9205    23                                INC     HL
  9206    06 04                             LD      B,4
  9208    CD CB16                           CALL    MO.MONI
  920B    C9                                RET
                                ;****************************************************************
                                ;*                  Anzeige der Cursorposition                  *
                                ;****************************************************************
  920C    ED 5B B294            DMCP:       LD      DE, (S2.DMCUR)
  9210    21 1015                           LD      HL,01015H           ;ZPOS = 21 , SPOS = 16
  9213    CD 91EA                           CALL    DMADR
  9216    C9                                RET
                                ;****************************************************************
                                ;*                  Anzeige des Bereichanfangs                  *
                                ;****************************************************************
  9217    ED 5B B296            DMBAP:      LD      DE,(S2.DMBA)
  921B    21 2415                           LD      HL,02415H           ;ZPOS = 21 , SPOS = 36
  921E    CD 91EA                           CALL    DMADR
  9221    C9                                RET
                                ;****************************************************************
                                ;*                  Anzeige des Bereichendes                    *
                                ;****************************************************************
  9222    ED 5B B298            DMBEP:      LD      DE, (S2.DMBE)
  9226    21 3615                           LD      HL,03615H           ;ZPOS = 21 , SPOS = 54
  9229    CD 91EA                           CALL    DMADR
  922C    C9                                RET
                                ;****************************************************************
                                ;*                                                              *
                                ;****************************************************************
  922D    2A B294               DMP4:       LD      HL,(S2.DMCUR)
  9230    22 B296                           LD      (S2.DMBA),HL
  9233    CD 90F4                           CALL    DMUP3
  9236    CD 9217                           CALL    DMBAP
  9239    CD 910D                           CALL    DMUP4
  923C    C9                                RET
                                ;
  923D    2A B294               DMP5:       LD      HL,(S2.DMCUR)
  9240    22 B298                           LD      (S2.DMBE),HL
  9243    CD 90F4                           CALL    DMUP3
  9246    CD 9222                           CALL    DMBEP
  9249    CD 910D                           CALL    DMUP4
  924C    C9                                RET
                                ;
                                ;
                                ;
                                ;           END
                                            .DEPHASE
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-51


                                ;
                                            END
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	S


Macros:

Symbols:
8C82 	D0.AD1          8C97 	D0.AD2          8320 	D0.ADD          
8329 	D0.ADD1         832B 	D0.ADPQ1        8343 	D0.ADPQ2        
8C57 	D0.AH1          8C69 	D0.AH2          8AB2 	D0.AL           
8BA3 	D0.ALA          8B7A 	D0.ALA1         8BAF 	D0.ALA2         
8B79 	D0.ALB1         8B79 	D0.ALB2         8B47 	D0.ALD          
8B23 	D0.ALD1         8B53 	D0.ALD2         8AF1 	D0.ALH          
8ACD 	D0.ALH1         8AFD 	D0.ALH2         8B79 	D0.ALO1         
8B79 	D0.ALO2         8AB9 	D0.ALTAB        8A11 	D0.AS           
8A89 	D0.ASA1         8A9C 	D0.ASA2         8AB1 	D0.ASB1         
8AB1 	D0.ASB2         8A5B 	D0.ASD1         8A72 	D0.ASD2         
8A2C 	D0.ASH1         8A42 	D0.ASH2         8AB1 	D0.ASO1         
8AB1 	D0.ASO2         8A18 	D0.ASTAB        8BE6 	D0.AW           
8CBE 	D0.AZEIN        8CCF 	D0.BZEIN        8641 	D0.CADR         
866E 	D0.CHK          8671 	D0.CHK1         8646 	D0.CHOM         
863D 	D0.CON          801C 	D0.DD           809A 	D0.DDPT         
80BC 	D0.DDPT2        80C6 	D0.DDPT3        8186 	D0.DDPTB        
8735 	D0.DDU01        873C 	D0.DDU02        8742 	D0.DDU03        
874D 	D0.DDU04        8757 	D0.DDU05        8791 	D0.DDU06        
87A9 	D0.DDU07        87C8 	D0.DDU08        8825 	D0.DDU09        
882A 	D0.DDU10        883B 	D0.DDU11        8846 	D0.DDU12        
8856 	D0.DDU13        885B 	D0.DDU14        8870 	D0.DDU15        
8879 	D0.DDU16        8774 	D0.DDU17        88A7 	D0.DDU18        
88D2 	D0.DDU19        88E5 	D0.DDU20        88EF 	D0.DDU21        
88FA 	D0.DDU22        88FC 	D0.DDU23        890A 	D0.DDU24        
8919 	D0.DDU25        893E 	D0.DDU26        894F 	D0.DDU27        
8955 	D0.DDU28        8972 	D0.DDU30        8A05 	D0.DDU31        
8CBE 	D0.DZEIN        8CAC 	D0.HZEIN        8250 	D0.IN           
8259 	D0.IN1          8263 	D0.IN2          8273 	D0.INPQ         
8663 	D0.LOAD         83C7 	D0.MEDC         83D0 	D0.MEDC1        
83D2 	D0.MEPQ         8C3F 	D0.MO01         82C1 	D0.OUPQ1        
82E8 	D0.OUPQ2        82B6 	D0.OUT          82BF 	D0.OUT1         
8CC7 	D0.OZEIN        8713 	D0.PQ14         845C 	D0.PR1          
8565 	D0.PRF          855D 	D0.PRF1         8548 	D0.PRK          
854B 	D0.PRK1         857C 	D0.PRL          8585 	D0.PRL1         
8596 	D0.PRL2         85B0 	D0.PRL3         852A 	D0.PROM         
85B4 	D0.PRP          85CC 	D0.PRP2         85DC 	D0.PRP3         
8588 	D0.PRPQ1        85BF 	D0.PRPQ2        8558 	D0.PRR          
8464 	D0.PRT1         8524 	D0.PRT2         86AE 	D0.PRU11        
86C0 	D0.PRU21        86C5 	D0.PRU22        86D0 	D0.PRU31        
86D6 	D0.PRU32        86EC 	D0.PRU33        8705 	D0.PRU41        
86A7 	D0.PRUP1        86B4 	D0.PRUP2        86CE 	D0.PRUP3        
86FF 	D0.PRUP4        85EB 	D0.RAMT         85F7 	D0.RAMT1        
862C 	D0.RAMT2        8663 	D0.RCDC         8663 	D0.REAS         
8664 	D0.RGDC         8417 	D0.ROM1         840E 	D0.ROMT         
83EE 	D0.RT1          83F6 	D0.RT2          83FE 	D0.RT3          
8419 	D0.RTPQ1        8434 	D0.RTPQ2        8663 	D0.SAVE         
8381 	D0.SBPQ1        8399 	D0.SBPQ2        8376 	D0.SUB          
837F 	D0.SUB1         8BF3 	D0.TA01         8C0C 	D0.TA02         
8C29 	D0.TA03         8C32 	D0.TA04         830F 	D0.TAD1         
8317 	D0.TAD2         8246 	D0.TIN1         82AE 	D0.TIO1         
83BF 	D0.TME          82A6 	D0.TOUT1        824E 	D0.TPQ          
8367 	D0.TSB1         8370 	D0.TSB2         8664 	D0.UCPU         
8CF3 	D1.MEMO         8040 	DD0             8069 	DD1             
88BA 	DDU18A          9030 	DMAA            91EA 	DMADR           
8FC1 	DMAH            8FD3 	DMAH1           8FE3 	DMAH3           
8FE9 	DMAH4           901E 	DMAH5           91B8 	DMB             
91C8 	DMB1            91D6 	DMB2            91E5 	DMB3            
9217 	DMBAP           9222 	DMBEP           8E1C 	DMCN            
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	S-1


8E43 	DMCN1           8E50 	DMCN2           8EC6 	DMCO            
8EE3 	DMCO1           8EF3 	DMCO2           920C 	DMCP            
8E55 	DMCS            8E7C 	DMCS1           8E88 	DMCS2           
8E86 	DMCS3           8E8D 	DMCW            8EAF 	DMCW1           
8EC4 	DMCW2           8EF5 	DMHOM           8F73 	DMIM            
8FA9 	DMIM1           9070 	DMN2A           905A 	DMN2H           
9053 	DMN31           9069 	DMN32           9061 	DMN3A           
904B 	DMN3H           8F2C 	DMNQ1           8F4C 	DMNQ2           
8F39 	DMNQ3           8F49 	DMNQ4           8F1C 	DMNQU           
8F0D 	DMNZ            922D 	DMP4            923D 	DMP5            
8F61 	DMPQ1           8F6E 	DMPQ2           8F51 	DMPQU           
913D 	DMRO            9157 	DMRO1           9167 	DMRU            
9184 	DMRU1           9077 	DMSL            9099 	DMSL1           
90AB 	DMSR            8DE8 	DMTAB           9119 	DMU1            
9135 	DMU2            90D3 	DMUP1           90F4 	DMUP3           
910D 	DMUP4           91AB 	DMZA            9197 	DMZH            
919C 	DMZH1           D5B7 	K1.ARBT         D551 	K1.ARMB         
D5D0 	K1.BLKM         D5C2 	K1.BLKP         D60F 	K1.BM           
D615 	K1.F17          D82B 	K1.GNLMN        D7F1 	K1.GNLP         
D7F3 	K1.GNLPN        D765 	K1.GNRA         D89B 	K1.GNRD         
D748 	K1.GNRE         D7C0 	K1.GNRM         D7A5 	K1.GNRP         
D780 	K1.GNRW         D92F 	K1.GNRWR        D6F1 	K1.GNSTS        
D90B 	K1.GNWR         D602 	K1.LHLBC        D8B0 	K1.PUFT         
D5EC 	K1.RCZM         D5FA 	K1.RCZN         D5DE 	K1.RCZP         
D62D 	K1.RGL1         D63E 	K1.RGL2         B136 	K2.FRADR        
B134 	K2.SKADR        DF0C 	LO.EIN          E279 	LO.EIN1         
8DD3 	MEMD            8DDA 	MEMR            8DD2 	MEMS            
8DE1 	MEMU            CF4B 	MO.BWSE         CB45 	MO.BWSUS        
CB16 	MO.MONI         CF52 	MO.PNSP         CD9F 	MO.ROLL         
B194 	MS.BWSA         B198 	MS.CMD          B19E 	MS.CZEIT        
B196 	MS.DIRDEL       B197 	MS.DIRES        B19D 	MS.MCUR         
B19C 	MS.MCZ          B19A 	MS.RADR         B191 	MS.SMAX         
B18F 	MS.SMIN         B193 	MS.SPANZ        B18B 	MS.SPOL         
B18D 	MS.SPOS         B199 	MS.TK           B192 	MS.ZANZ         
B190 	MS.ZMAX         B18E 	MS.ZMIN         B18A 	MS.ZPOL         
B18C 	MS.ZPOS         A000 	S0.BWSA         F60F 	S0.BWSUS        
BBF0 	S0.PFFA         B7E0 	S0.PFFI         00E0 	S0.PROM         
0050 	S0.SPANZ        0018 	S0.ZANZ         C328 	S1.AEIN         
C3BF 	S1.ANZEI        C8B0 	S1.ANZU1        C8C0 	S1.ANZU2        
C5FF 	S1.BHKON        C652 	S1.CHK          C2D3 	S1.CNLS         
C2B4 	S1.CNRS         C82E 	S1.DB111        C86E 	S1.EINDB        
C5CC 	S1.HBKON        C54E 	S1.HDI          C995 	S1.HXN1         
C592 	S1.IDH          C532 	S1.INPTR        C935 	S1.MEAA         
C9E4 	S1.MEAU2        C334 	S1.NN           C345 	S1.NNN          
C02D 	S1.SM           C8CD 	S1.SYDB2        C114 	S1.SYSTB        
B26E 	S2.AADR         B28A 	S2.AFOR         B28B 	S2.BZ           
B263 	S2.CST          B2B8 	S2.DDEI         B28F 	S2.DH           
B28E 	S2.DL           B29A 	S2.DM1          B2AA 	S2.DM2          
B292 	S2.DMANF        B296 	S2.DMBA         B298 	S2.DMBE         
B294 	S2.DMCUR        B2AB 	S2.DMH          B2AC 	S2.DML          
B26B 	S2.DNR          B264 	S2.IOC          B270 	S2.KADR         
B290 	S2.PAR1         B265 	S2.PRGN         B26C 	S2.RBBR         
B2AF 	S2.S1           B2B0 	S2.S2           B2AD 	S2.SMHL         
B273 	S2.SP1          B274 	S2.SP2          B275 	S2.SP3          
B28C 	S2.TE           B276 	S2.TRB          B272 	S2.ZP           
B262 	S2.ZZ           E697 	S9.CIN          E6E6 	S9.CON          
E6CB 	S9.CSTSX        EEB8 	S9.LOAD         EE98 	S9.SAVE         
D40E 	TA.LOE          D426 	TA.LOES         B249 	TS.BFOL1        
B24B 	TS.BFOL2        B22D 	TS.EINA         B23E 	TS.EMERK        
B241 	TS.KGMER        B248 	TS.MBF          B247 	TS.MIO          
B231 	TS.NEWL         B23B 	TS.PTAST        B23D 	TS.PTK          
B23F 	TS.SPMER        B24D 	TS.STACK        B19F 	TS.TAB1         
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	S-2


B1FF 	TS.TAB2         B217 	TS.TAB3         B223 	TS.TAB4         
B233 	TS.TAB5         B22F 	TS.TABU         B23C 	TS.TK           
B240 	TS.UMERK        B245 	TS.ZEI21        B243 	TS.ZEIT1        
B244 	TS.ZEIT2        B242 	TS.ZSMER        B246 	TS.ZSTC         



No Fatal error(s)


