'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1


                                ;--------------------------\            ; Vorspann fuer BIN-Datei
  0000*   EF                                DB      0EFH                ; Startbyte ---> 
  0001*                                     DS      12,0
  000D*   02                                DB      002H                ; HS-Bereich : 2
  000E*   8000                              DW      08000H              ; Ladeadresse: 9000H
                                ;--------------------------/
                                
                         C                  INCLUDE S21EQU1.MAC
  00E0                   C      S0.PROM     EQU     0E0H
  0050                   C      S0.SPANZ    EQU     80
  0018                   C      S0.ZANZ     EQU     24
  A000                   C      S0.BWSA     EQU     0A000H
  B7E0                   C      S0.PFFI     EQU     0B7E0H
  BBF0                   C      S0.PFFA     EQU     0BBF0H
                         C      ;
  B136                   C      K2.FRADR    EQU     0B136H
  B134                   C      K2.SKADR    EQU     0B134H
                         C      ;
  B18A                   C      MS.ZPOL     EQU     0B18AH
  B18B                   C      MS.SPOL     EQU     MS.ZPOL+1
  B18C                   C      MS.ZPOS     EQU     MS.SPOL+1
  B18D                   C      MS.SPOS     EQU     MS.ZPOS+1
  B18E                   C      MS.ZMIN     EQU     MS.SPOS+1
  B18F                   C      MS.SMIN     EQU     MS.ZMIN+1
  B190                   C      MS.ZMAX     EQU     MS.SMIN+1
  B191                   C      MS.SMAX     EQU     MS.ZMAX+1
  B192                   C      MS.ZANZ     EQU     MS.SMAX+1
  B193                   C      MS.SPANZ    EQU     MS.ZANZ+1
  B194                   C      MS.BWSA     EQU     MS.SPANZ+1
  B196                   C      MS.DIRDEL   EQU     MS.BWSA+2
  B197                   C      MS.DIRES    EQU     MS.DIRDEL+1
  B198                   C      MS.CMD      EQU     MS.DIRES+1
  B199                   C      MS.TK       EQU     MS.CMD+1
  B19A                   C      MS.RADR     EQU     MS.TK+1
  B19C                   C      MS.MCZ      EQU     MS.RADR+2
  B19D                   C      MS.MCUR     EQU     MS.MCZ+1
  B19E                   C      MS.CZEIT    EQU     MS.MCUR+1
                         C      ;
  B19F                   C      TS.TAB1     EQU     0B19FH
  B1FF                   C      TS.TAB2     EQU     TS.TAB1+60H
  B217                   C      TS.TAB3     EQU     TS.TAB2+18H
  B223                   C      TS.TAB4     EQU     TS.TAB3+0CH
  B22D                   C      TS.EINA     EQU     TS.TAB4+0AH
  B22F                   C      TS.TABU     EQU     TS.EINA+2
  B231                   C      TS.NEWL     EQU     TS.TABU+2
  B233                   C      TS.TAB5     EQU     TS.NEWL+2
  B23B                   C      TS.PTAST    EQU     TS.TAB5+8
  B23C                   C      TS.TK       EQU     TS.PTAST+1
  B23D                   C      TS.PTK      EQU     TS.TK+1
  B23E                   C      TS.EMERK    EQU     TS.PTK+1
  B23F                   C      TS.SPMER    EQU     TS.EMERK+1
  B240                   C      TS.UMERK    EQU     TS.SPMER+1
  B241                   C      TS.KGMER    EQU     TS.UMERK+1
  B242                   C      TS.ZSMER    EQU     TS.KGMER+1
  B243                   C      TS.ZEIT1    EQU     TS.ZSMER+1
  B244                   C      TS.ZEIT2    EQU     TS.ZEIT1+1
  B245                   C      TS.ZEI21    EQU     TS.ZEIT2+1
  B246                   C      TS.ZSTC     EQU     TS.ZEI21+1
  B247                   C      TS.MIO      EQU     TS.ZSTC+1
  B248                   C      TS.MBF      EQU     TS.MIO+1
  B249                   C      TS.BFOL1    EQU     TS.MBF+1
  B24B                   C      TS.BFOL2    EQU     TS.BFOL1+2
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-1


  B24D                   C      TS.STACK    EQU     TS.BFOL2+2
                         C      ;
  B262                   C      S2.ZZ       EQU     0B262H
  B263                   C      S2.CST      EQU     S2.ZZ+1
  B264                   C      S2.IOC      EQU     S2.CST+1
  B265                   C      S2.PRGN     EQU     S2.IOC+1
  B26B                   C      S2.DNR      EQU     S2.PRGN+6
  B26C                   C      S2.RBBR     EQU     S2.DNR+1
  B26E                   C      S2.AADR     EQU     S2.RBBR+2
  B270                   C      S2.KADR     EQU     S2.AADR+2
  B272                   C      S2.ZP       EQU     S2.KADR+2
  B273                   C      S2.SP1      EQU     S2.ZP+1
  B274                   C      S2.SP2      EQU     S2.SP1+1
  B275                   C      S2.SP3      EQU     S2.SP2+1
  B276                   C      S2.TRB      EQU     S2.SP3+1
  B28A                   C      S2.AFOR     EQU     S2.TRB+20
  B28B                   C      S2.BZ       EQU     S2.AFOR+1
  B28C                   C      S2.TE       EQU     S2.BZ+1
  B28E                   C      S2.DL       EQU     S2.TE+2
  B28F                   C      S2.DH       EQU     S2.DL+1
  B290                   C      S2.PAR1     EQU     S2.DH+1
  B292                   C      S2.DMANF    EQU     S2.PAR1+2
  B294                   C      S2.DMCUR    EQU     S2.DMANF+2
  B296                   C      S2.DMBA     EQU     S2.DMCUR+2
  B298                   C      S2.DMBE     EQU     S2.DMBA+2
  B29A                   C      S2.DM1      EQU     S2.DMBE+2
  B2AA                   C      S2.DM2      EQU     S2.DM1+16
  B2AB                   C      S2.DMH      EQU     S2.DM2+1
  B2AC                   C      S2.DML      EQU     S2.DMH+1
  B2AD                   C      S2.SMHL     EQU     S2.DML+1
  B2AF                   C      S2.S1       EQU     S2.SMHL+2
  B2B0                   C      S2.S2       EQU     S2.S1+1
  B2B8                   C      S2.DDEI     EQU     S2.S2+8
                         C      ;
                         C                  INCLUDE S21EQU2.MAC
  C02D                   C      S1.SM       EQU     0C02DH
  C82E                   C      S1.DB111    EQU     0C82EH
  C86E                   C      S1.EINDB    EQU     0C86EH
  C8B0                   C      S1.ANZU1    EQU     0C8B0H
  C8C0                   C      S1.ANZU2    EQU     0C8C0H
  C8CD                   C      S1.SYDB2    EQU     0C8CDH
  C114                   C      S1.SYSTB    EQU     0C114H
  C2B4                   C      S1.CNRS     EQU     0C2B4H
  C2D3                   C      S1.CNLS     EQU     0C2D3H
  C328                   C      S1.AEIN     EQU     0C328H
  C334                   C      S1.NN       EQU     0C334H
  C345                   C      S1.NNN      EQU     0C345H
  C3BF                   C      S1.ANZEI    EQU     0C3BFH
  C532                   C      S1.INPTR    EQU     0C532H
  C54E                   C      S1.HDI      EQU     0C54EH
  C592                   C      S1.IDH      EQU     0C592H
  C5CC                   C      S1.HBKON    EQU     0C5CCH
  C5FF                   C      S1.BHKON    EQU     0C5FFH
  C652                   C      S1.CHK      EQU     0C652H
  C935                   C      S1.MEAA     EQU     0C935H
  C995                   C      S1.HXN1     EQU     0C995H
  C9E4                   C      S1.MEAU2    EQU     0C9E4H
                         C      ;
  CB10                   C      MO.MONI     EQU     0CB10H
  CB3F                   C      MO.BWSUS    EQU     0CB3FH
  CD99                   C      MO.ROLL     EQU     0CD99H
  CF45                   C      MO.BWSE     EQU     0CF45H
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-2


  CF4C                   C      MO.PNSP     EQU     0CF4CH
                         C      ;
  D408                   C      TA.LOE      EQU     0D408H
  D420                   C      TA.LOES     EQU     0D420H
                         C      ;
  E657                   C      S9.CIN      EQU     0E657H
  E68B                   C      S9.CSTSX    EQU     0E68BH
  E6A6                   C      S9.CON      EQU     0E6A6H
  EE58                   C      S9.SAVE     EQU     0EE58H
  EE78                   C      S9.LOAD     EQU     0EE78H
                         C      ;
  D548                   C      K1.ARMB     EQU     0D548H
  D576                   C      K1.ARBT     EQU     0D576H
  D581                   C      K1.BLKP     EQU     0D581H
  D58F                   C      K1.BLKM     EQU     0D58FH
  D59D                   C      K1.RCZP     EQU     0D59DH
  D5AB                   C      K1.RCZM     EQU     0D5ABH
  D5B9                   C      K1.RCZN     EQU     0D5B9H
  D5C1                   C      K1.LHLBC    EQU     0D5C1H
  D5CE                   C      K1.BM       EQU     0D5CEH
  D5D5                   C      K1.F17      EQU     0D5D5H
  D5ED                   C      K1.RGL1     EQU     0D5EDH
  D5FE                   C      K1.RGL2     EQU     0D5FEH
  D6B1                   C      K1.GNSTS    EQU     0D6B1H
  D708                   C      K1.GNRE     EQU     0D708H
  D725                   C      K1.GNRA     EQU     0D725H
  D740                   C      K1.GNRW     EQU     0D740H
  D765                   C      K1.GNRP     EQU     0D765H
  D780                   C      K1.GNRM     EQU     0D780H
  D7B1                   C      K1.GNLP     EQU     0D7B1H
  D7B3                   C      K1.GNLPN    EQU     0D7B3H
  D7EB                   C      K1.GNLMN    EQU     0D7EBH
  D870                   C      K1.PUFT     EQU     0D870H
  D85B                   C      K1.GNRD     EQU     0D85BH
  D8CB                   C      K1.GNWR     EQU     0D8CBH
  D8EF                   C      K1.GNRWR    EQU     0D8EFH
                         C      ;
  DECC                   C      LO.EIN      EQU     0DECCH
  E239                   C      LO.EIN1     EQU     0E239H
                         C      ;
  F5CF                   C      S0.BWSUS    EQU     0F5CFH
                                
                                            .PHASE  08000H
                                ;           PN      D010
                                ;****************************************************************
                                ;*	             D  E  B  U  G   ---   Steuerprogramm           *
                                ;*  Version      -----------------------------------------------*
                                ;*               Programmierer: Marcus Herbote   --- IfR - OE-S *
                                ;*  V 1 . 0      -----------------------------------------------*
                                ;                Stand        : 11.Januar 1983                  *
                                ;****************************************************************
  8000    18 1A                             JR      D0.DD
  8002    56 31 2E 30                       DB      'V1.0/110183'
  8006    2F 31 31 30           
  800A    31 38 33              
  800D    800D                              DW      $
  800F    44 42 55 47                       DB      'DBUG'
  8013    F3                                DI
  8014    3E 05                             LD      A,5                 ;Zeile 1 bis 22 loeschen
  8016    32 B198                           LD      (MS.CMD),A
  8019    CD CB10                           CALL    MO.MONI
  801C    3E 02                 D0.DD:      LD      A,2
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-3


  801E    32 B198                           LD      (MS.CMD),A
  8021    CD CB10                           CALL    MO.MONI
  8024    21 8181                           LD      HL,D0.DDPTB-4       ;Anzeige der aktiven P-Tasten
  8027    11 8099                           LD      DE,D0.DDPT
  802A    01 0024                           LD      BC,36
  802D    CD 8C04                           CALL    D0.TA02
  8030    21 0000                           LD      HL,0                ;ZPOS = 0 , SPOS = 0
  8033    22 B18C                           LD      (MS.ZPOS),HL
  8036    06 29                             LD      B,41
  8038    21 8040                           LD      HL,$+8
  803B    CD CB10                           CALL    MO.MONI             ;Anzeige der DEBUG-Version
  803E    18 28                             JR      DD1                 ;$+43
  8040    44 45 42 55                       DB      'DEBUG --- Version 1.0     '
  8044    47 20 2D 2D           
  8048    2D 20 56 65           
  804C    72 73 69 6F           
  8050    6E 20 31 2E           
  8054    30 20 20 20           
  8058    20 20                 
  805A    41 75 73 77                       DB      'Auswahlanzeige'
  805E    61 68 6C 61           
  8062    6E 7A 65 69           
  8066    67 65                 
  8068    3E 14                 DD1:        LD      A,20
  806A    32 B198                           LD      (MS.CMD),A
  806D    21 3412                           LD      HL,03412H           ;ZPOS = 18 , SPOS = 52
  8070    01 1A02                           LD      BC,01A02H           ;Laenge:26 , Breite: 2
  8073    CD 88A6                           CALL    D0.DDU18            ;Fensterrahmen fuer Eingabebereich aufb.
  8076    21 4014                           LD      HL,04014H           ;ZMIN = 20 , SMIN = 64
  8079    22 B18E                           LD      (MS.ZMIN),HL
  807C    21 4F15                           LD      HL,04F15H           ;ZMAX = 21 , SMAX = 79
  807F    22 B190                           LD      (MS.ZMAX),HL
  8082    21 3513                           LD      HL,03513H           ;ZPOS = 19 , SPOS = 53
  8085    22 B18C                           LD      (MS.ZPOS),HL
  8088    3E C0                             LD      A,0C0H
  808A    32 B197                           LD      (MS.DIRES),A
  808D    21 C114                           LD      HL,S1.SYSTB         ;SYS - Taste
  8090    22 B21D                           LD      (TS.TAB3+6),HL
  8093    3E 80                             LD      A,080H              ;Funktionstasten aktivieren
  8095    32 B23F                           LD      (TS.SPMER),A
  8098    C9                                RET
                                            TITLE    'Tastaturtabellen'
                                            PAGE
'Tastaturtabellen'	MACRO-80 3.44	09-Dec-81	PAGE	1-4


                                
                                ;****************************************************************
                                ;*	                     Tastaturtabellen                       *
                                ;****************************************************************
  8099    83C6                  D0.DDPT:    DW      D0.MEDC
  809B    8662                              DW      D0.RCDC
  809D    8663                              DW      D0.RGDC
  809F    8662                              DW      D0.LOAD
  80A1    8662                              DW      D0.SAVE
  80A3    8663                              DW      D0.UCPU
  80A5    85EA                              DW      D0.RAMT
  80A7    840D                              DW      D0.ROMT
  80A9    8662                              DW      D0.REAS
  80AB    0000                              DW      0
  80AD    8529                              DW      D0.PROM
  80AF    0000                              DW      0
  80B1    824F                              DW      D0.IN
  80B3    82B5                              DW      D0.OUT
  80B5    0000                              DW      0
  80B7    831F                              DW      D0.ADD
  80B9    8375                              DW      D0.SUB
                                ;            
  80BB    8BDE                  D0.DDPT2:   DW      D0.AW
  80BD    8BDE                              DW      D0.AW
  80BF    8BDE                              DW      D0.AW
  80C1    8BDE                              DW      D0.AW
  80C3    8BDE                              DW      D0.AW
                                ;
  80C5    48 65 78 61           D0.DDPT3:   DB      'HexaDeziOct Bin Alfa----'
  80C9    44 65 7A 69           
  80CD    4F 63 74 20           
  80D1    42 69 6E 20           
  80D5    41 6C 66 61           
  80D9    2D 2D 2D 2D           
  80DD    2D 2D 2D 2D                       DB      '------------------------'
  80E1    2D 2D 2D 2D           
  80E5    2D 2D 2D 2D           
  80E9    2D 2D 2D 2D           
  80ED    2D 2D 2D 2D           
  80F1    2D 2D 2D 2D           
  80F5    2D 2D 2D 2D                       DB      '------------------------'
  80F9    2D 2D 2D 2D           
  80FD    2D 2D 2D 2D           
  8101    2D 2D 2D 2D           
  8105    2D 2D 2D 2D           
  8109    2D 2D 2D 2D           
  810D    2D 2D 2D 2D                       DB      '------------------------'
  8111    2D 2D 2D 2D           
  8115    2D 2D 2D 2D           
  8119    2D 2D 2D 2D           
  811D    2D 2D 2D 2D           
  8121    2D 2D 2D 2D           
  8125    2D 2D 2D 2D                       DB      '------------------------'
  8129    2D 2D 2D 2D           
  812D    2D 2D 2D 2D           
  8131    2D 2D 2D 2D           
  8135    2D 2D 2D 2D           
  8139    2D 2D 2D 2D           
  813D    2D 2D 2D 2D                       DB      '------------------------'
  8141    2D 2D 2D 2D           
  8145    2D 2D 2D 2D           
'Tastaturtabellen'	MACRO-80 3.44	09-Dec-81	PAGE	1-5


  8149    2D 2D 2D 2D           
  814D    2D 2D 2D 2D           
  8151    2D 2D 2D 2D           
  8155    2D 2D 2D 2D                       DB      '------------------------'
  8159    2D 2D 2D 2D           
  815D    2D 2D 2D 2D           
  8161    2D 2D 2D 2D           
  8165    2D 2D 2D 2D           
  8169    2D 2D 2D 2D           
  816D    2D 2D 2D 2D                       DB      '------------------------'
  8171    2D 2D 2D 2D           
  8175    2D 2D 2D 2D           
  8179    2D 2D 2D 2D           
  817D    2D 2D 2D 2D           
  8181    2D 2D 2D 2D           
                                ;
  8185    4D 65 44 43           D0.DDPTB:   DB      'MeDCRcDCRgDCLOADSAVEuCPU'
  8189    52 63 44 43           
  818D    52 67 44 43           
  8191    4C 4F 41 44           
  8195    53 41 56 45           
  8199    75 43 50 55           
  819D    52 41 4D 54                       DB      'RAMTROMTREAS----PROM----'
  81A1    52 4F 4D 54           
  81A5    52 45 41 53           
  81A9    2D 2D 2D 2D           
  81AD    50 52 4F 4D           
  81B1    2D 2D 2D 2D           
  81B5    49 4E 20 20                       DB      'IN  OUT ----ADD SUB ----'
  81B9    4F 55 54 20           
  81BD    2D 2D 2D 2D           
  81C1    41 44 44 20           
  81C5    53 55 42 20           
  81C9    2D 2D 2D 2D           
  81CD    2D 2D 2D 2D                       DB      '------------------------'
  81D1    2D 2D 2D 2D           
  81D5    2D 2D 2D 2D           
  81D9    2D 2D 2D 2D           
  81DD    2D 2D 2D 2D           
  81E1    2D 2D 2D 2D           
  81E5    2D 2D 2D 2D                       DB      '------------------------'
  81E9    2D 2D 2D 2D           
  81ED    2D 2D 2D 2D           
  81F1    2D 2D 2D 2D           
  81F5    2D 2D 2D 2D           
  81F9    2D 2D 2D 2D           
  81FD    2D 2D 2D 2D                       DB      '------------------------'
  8201    2D 2D 2D 2D           
  8205    2D 2D 2D 2D           
  8209    2D 2D 2D 2D           
  820D    2D 2D 2D 2D           
  8211    2D 2D 2D 2D           
  8215    2D 2D 2D 2D                       DB      '------------------------'
  8219    2D 2D 2D 2D           
  821D    2D 2D 2D 2D           
  8221    2D 2D 2D 2D           
  8225    2D 2D 2D 2D           
  8229    2D 2D 2D 2D           
  822D    2D 2D 2D 2D                       DB      '------------------------'
  8231    2D 2D 2D 2D           
  8235    2D 2D 2D 2D           
  8239    2D 2D 2D 2D           
'Tastaturtabellen'	MACRO-80 3.44	09-Dec-81	PAGE	1-6


  823D    2D 2D 2D 2D           
  8241    2D 2D 2D 2D           
                                
                                            TITLE   'Funktion : IN '
                                            PAGE
'Funktion : IN '	MACRO-80 3.44	09-Dec-81	PAGE	1-7


                                
                                ;****************************************************************
                                ;*	                     D E B U G   -   Funktion :  IN         *
                                ;****************************************************************
  8245    49 4E 20 2D           D0.TIN1:    DB      'IN -Adr '
  8249    41 64 72 20           
  824D    3A 20                 D0.TPQ:     DB      ': '
  824F    CD 8C21               D0.IN:      CALL    D0.TA03
  8252    21 8272                           LD      HL,D0.INPQ
  8255    11 8245                           LD      DE,D0.TIN1
                                ;            
  8258    22 B223               D0.IN1:     LD      (TS.TAB4),HL
  825B    ED 53 B28C                        LD      (S2.TE),DE
  825F    21 0000                           LD      HL ,0
  8262    22 B28E               D0.IN2:     LD      (S2.DL),HL
  8265    CD 8AAA                           CALL    D0.AL
  8268    CD 8BEB                           CALL    D0.TA01
  826B    21 801C                           LD      HL,D0.DD
  826E    22 B21D                           LD      (TS.TAB3+6),HL
  8271    C9                                RET
                                ;
                                ;
                                ;
  8272    06 08                 D0.INPQ:    LD      B,8
  8274    21 8245                           LD      HL,D0.TIN1
  8277    CD 8712                           CALL    D0.PQ14
  827A    21 B18D                           LD      HL,MS.SPOS
  827D    34                                INC     (HL)
  827E    34                                INC     (HL)
  827F    06 08                             LD      B,8
  8281    21 82AD                           LD      HL,D0.TIO1
  8284    CD CB10                           CALL    MO.MONI
  8287    06 02                             LD      B,2
  8289    21 824D                           LD      HL,D0.TPQ
  828C    CD CB10                           CALL    MO.MONI
                                ;
  828F    ED 4B B290                        LD      BC,(S2.PAR1)
  8293    ED 78                             IN      A,(C)
                                ;
  8295    21 B29A                           LD      HL,S2.DM1
  8298    CD C5FF                           CALL    S1.BHKON
  829B    06 02                             LD      B,2
  829D    21 B29A                           LD      HL,S2.DM1
  82A0    CD CB10                           CALL    MO.MONI
  82A3    18 AA                             JR      D0.IN
                                
                                            TITLE   'Funktion :   OUT '
                                            PAGE
'Funktion :   OUT '	MACRO-80 3.44	09-Dec-81	PAGE	1-8


                                
                                ;****************************************************************
                                ;*	                     D E B U G   -   Funktion :  OUT        *
                                ;****************************************************************
  82A5    4F 55 54 2D           D0.TOUT1:   DB      'OUT-Adr '
  82A9    41 64 72 20           
  82AD    44 61 74 65           D0.TIO1:    DB      'Daten   '
  82B1    6E 20 20 20           
  82B5    CD 8C21               D0.OUT:     CALL    D0.TA03
  82B8    21 82C0                           LD      HL,D0.OUPQ1
  82BB    11 82A5                           LD      DE,D0.TOUT1
  82BE    18 98                 D0.OUT1:    JR	    D0.IN1
                                ;
                                ;
                                ;
  82C0    06 08                 D0.OUPQ1:   LD      B,8
  82C2    21 82A5                           LD      HL,D0.TOUT1
  82C5    CD 8712                           CALL    D0.PQ14
  82C8    21 82E7                           LD      HL,D0.OUPQ2
  82CB    11 82AD                           LD      DE,D0.TIO1
  82CE    22 B223                           LD      (TS.TAB4),HL
  82D1    ED 53 B28C                        LD      (S2.TE),DE
  82D5    21 0000                           LD      HL,0
  82D8    22 B28E                           LD      (S2.DL),HL
  82DB    AF                                XOR     A
  82DC    32 B28A                           LD      (S2.AFOR),A
  82DF    3C                                INC     A
  82E0    32 B28B                           LD      (S2.BZ),A
  82E3    CD 8AAA                           CALL    D0.AL
  82E6    C9                                RET
                                ;
                                ;
                                ;
  82E7    CD 8A09               D0.OUPQ2:   CALL    D0.AS               ;ZPOS = 10 , SPOS = 16
  82EA    21 100A                           LD      HL,0100AH	
  82ED    CD 88CA                           CALL    D0.DDU19	
  82F0    06 08                             LD      B,8	
  82F2    21 82AD                           LD      HL,D0.TIO1	
  82F5    CD CB10                           CALL    MO.MONI	
  82F8    06 02                             LD      B,2	
  82FA    21 824D                           LD      HL,D0.TPQ	
  82FD    CD CB10                           CALL    MO.MONI
  8300    CD 8C4F                           CALL    D0.AH1
                                ;
  8303    ED 4B B290                        LD      BC,(S2.PAR1)
  8307    3A B28E                           LD      A,(S2.DL)
  830A    ED 79                             OUT     (C),A
                                ;
  830C    18 A7                             JR      D0.OUT
                                
                                            TITLE   'Funktion :   ADD '
                                            PAGE
'Funktion :   ADD '	MACRO-80 3.44	09-Dec-81	PAGE	1-9


                                
                                ;****************************************************************
                                ;*	                     D E B U G   -   Funktion :  ADD        *
                                ;****************************************************************
  830E    41 44 44 20           D0.TAD1:    DB      'ADD    A'
  8312    20 20 20 41           
  8316    41 44 44 20           D0.TAD2:    DB      'ADD   +B='
  831A    20 20 2B 42           
  831E    3D                    
  831F    CD 8C21               D0.ADD:     CALL    D0.TA03
  8322    21 832A                           LD      HL,D0.ADPQ1
  8325    11 830E                           LD      DE,D0.TAD1
  8328    18 94                 D0.ADD1:    JR      D0.OUT1
                                ;
                                ;
                                ;
  832A    06 07                 D0.ADPQ1:   LD      B,7
  832C    21 830E                           LD      HL,D0.TAD1
  832F    CD 8712                           CALL    D0.PQ14
  8332    06 01                             LD      B,1
  8334    21 831C                           LD      HL,D0.TAD2+6
  8337    CD CB10                           CALL    MO.MONI
  833A    21 8342                           LD      HL,D0.ADPQ2
  833D    11 8316                           LD      DE,D0.TAD2
  8340    18 E6                             JR      D0.ADD1
                                ;
                                ;
                                ;
  8342    CD 8A09               D0.ADPQ2:   CALL    D0.AS               ;ZPOS = 10 , SPOS = 14
  8345    21 0E0A                           LD      HL,00E0AH
  8348    CD 88CA                           CALL    D0.DDU19
  834B    CD 8C61                           CALL    D0.AH2
  834E    06 01                             LD      B,1
  8350    21 831E                           LD      HL,D0.TAD2+8
  8353    CD CB10                           CALL    MO.MONI
                                ;
  8356    2A B290                           LD      HL,(S2.PAR1)
  8359    ED 5B B28E                        LD      DE,(S2.DL)
  835D    19                                ADD     HL,DE
  835E    22 B28E                           LD      (S2.DL),HL
                                ;
  8361    CD 8C61                           CALL    D0.AH2
  8364    18 B9                             JR      D0.ADD
                                
                                            TITLE   'Funktion :   SUB '
                                            PAGE
'Funktion :   SUB '	MACRO-80 3.44	09-Dec-81	PAGE	1-10


                                
                                ;****************************************************************
                                ;*	                     D E B U G   -   Funktion :  SUB        *
                                ;****************************************************************
  8366    53 55 42 20           D0.TSB1:    DB      'SUB     A'
  836A    20 20 20 20           
  836E    41                    
  836F    53 55 42 09           D0.TSB2:    DB      'SUB	-B'
  8373    2D 42                 
  8375    CD 8C21               D0.SUB:     CALL    D0.TA03
  8378    21 8380                           LD      HL,D0.SBPQ1
  837B    11 8366                           LD      DE,D0.TSB1
  837E    18 A8                 D0.SUB1:    JR      D0.ADD1
                                ;
                                ;
                                ;
  8380    06 07                 D0.SBPQ1:   LD      B,7
  8382    21 8366                           LD      HL,D0.TSB1
  8385    CD 8712                           CALL    D0.PQ14
  8388    06 01                             LD      B,1
  838A    21 8375                           LD      HL,D0.TSB2+6
  838D    CD CB10                           CALL    MO.MONI
  8390    21 8398                           LD      HL,D0.SBPQ2
  8393    11 836F                           LD      DE,D0.TSB2
  8396    18 E6                             JR      D0.SUB1
                                ;
                                ;
                                ;
  8398    CD 8A09               D0.SBPQ2:   CALL    D0.AS
  839B    21 0E0A                           LD      HL,00E0AH           ;ZPOS = 10 , SPOS = 14
  839E    CD 88CA                           CALL    D0.DDU19
  83A1    CD 8C61                           CALL    D0.AH2
  83A4    06 01                             LD      B,1
  83A6    21 831E                           LD      HL,D0.TAD2+8
  83A9    CD CB10                           CALL    MO.MONI
                                ;
  83AC    2A B290                           LD      HL,(S2.PAR1)
  83AF    ED 5B B28E                        LD      DE,(S2.DL)
  83B3    AF                                XOR     A
  83B4    ED 52                             SBC     HL,DE
  83B6    22 B28E                           LD      (S2.DL),HL
                                ;
  83B9    CD 8C61                           CALL    D0.AH2
  83BC    18 B7                             JR      D0.SUB
                                
                                            TITLE   'Funktionen :   MeDC und ROMT '
                                            PAGE
'Funktionen :   MeDC und ROMT '	MACRO-80 3.44	09-Dec-81	PAGE	1-11


                                
                                ;****************************************************************
                                ;*	                     D E B U G   -   Funktion :  MeDC       *
                                ;****************************************************************
  83BE    41 6E 66 2E           D0.TME:     DB      'Anf.Adr.'
  83C2    41 64 72 2E           
  83C6    CD 8C21               D0.MEDC:    CALL    D0.TA03
  83C9    21 83D1                           LD      HL,D0.MEPQ
  83CC    11 83BE                           LD      DE,D0.TME
  83CF    18 AD                 D0.MEDC1:   JR      D0.SUB1
                                ;
                                ;
                                ;
  83D1    CD 8A09               D0.MEPQ:    CALL    D0.AS
  83D4    3E 02                             LD      A,2                 ;Zeile  1 bis 22  loeschen            
  83D6    32 B198                           LD      (MS.CMD),A
  83D9    CD CB10                           CALL    MO.MONI
  83DC    3E 05                             LD      A,5
  83DE    32 B198                           LD      (MS.CMD),A	
  83E1    CD CB10                           CALL    MO.MONI
  83E4    ED 5B B28E                        LD      DE,(S2.DL)          ;DE <== Anfangsadresse fuer MEMO           
  83E8    3E 01                             LD      A,1
  83EA    C3 8CEB                           JP      D1.MEMO
                                
                                ;****************************************************************
                                ;*	                     D E B U G   -   Funktion :  ROMT       *
                                ;****************************************************************
  83ED    52 4F 4D 2D           D0.RT1:     DB      'ROM-Anf.'
  83F1    41 6E 66 2E           
  83F5    52 4F 4D 2D           D0.RT2:     DB      'ROM-Byte'
  83F9    42 79 74 65           
  83FD    20 20 4B 6F           D0.RT3:     DB      '  Kontrollsume: '
  8401    6E 74 72 6F           
  8405    6C 6C 73 75           
  8409    6D 65 3A 20           
  840D    CD 8C21               D0.ROMT:    CALL    D0.TA03
  8410    21 8418                           LD      HL,D0.RTPQ1
  8413    11 83ED                           LD      DE,D0.RT1
  8416    18 B7                 D0.ROM1:    JR      D0.MEDC1
                                ;
                                ;
                                ;
  8418    06 08                 D0.RTPQ1:   LD      B,8
  841A    21 83ED                           LD      HL,D0.RT1
  841D    CD 8712                           CALL    D0.PQ14
  8420    21 8433                           LD      HL,D0.RTPQ2
  8423    11 83F5                           LD      DE,D0.RT2
  8426    22 B223                           LD      (TS.TAB4),HL
  8429    ED 53 B28C                        LD      (S2.TE),DE
  842D    21 0400                           LD      HL,00400H
  8430    C3 8262                           JP      D0.IN2
                                ;
                                ;
                                ;
  8433    CD 8A09               D0.RTPQ2:   CALL    D0.AS
  8436    21 0F0A                           LD      HL,00F0AH           ;ZPOS = 10 , SPOS = 15
  8439    CD 88CA                           CALL    D0.DDU19
  843C    06 08                             LD      B,8
  843E    21 83F5                           LD      HL,D0.RT2
  8441    CD CB10                           CALL    MO.MONI
  8444    06 02                             LD      B,2
'Funktionen :   MeDC und ROMT '	MACRO-80 3.44	09-Dec-81	PAGE	1-12


  8446    21 824D                           LD      HL,D0.TPQ
  8449    CD CB10                           CALL    MO.MONI
  844C    CD 8C61                           CALL    D0.AH2
  844F    2A B290                           LD      HL,(S2.PAR1)
  8452    ED 4B B28E                        LD      BC,(S2.DL)
  8456    CD 866D                           CALL    D0.CHK
  8459    18 B2                             JR      D0.ROMT
                                
                                            TITLE   'Funktion :   PROM '
                                            PAGE
'Funktion :   PROM '	MACRO-80 3.44	09-Dec-81	PAGE	1-13


                                
                                ;****************************************************************
                                ;*	                     D E B U G   -   Funktion :  PROM       *
                                ;****************************************************************
  845B    50 52 4F 4D           D0.PR1:     DB      'PROMAnf.'
  845F    41 6E 66 2E           
  8463    4B 6F 6E 74           D0.PRT1:    DB      'KontLiesProg------------'
  8467    4C 69 65 73           
  846B    50 72 6F 67           
  846F    2D 2D 2D 2D           
  8473    2D 2D 2D 2D           
  8477    2D 2D 2D 2D           
  847B    2D 2D 2D 2D                       DB      '------------------------'
  847F    2D 2D 2D 2D           
  8483    2D 2D 2D 2D           
  8487    2D 2D 2D 2D           
  848B    2D 2D 2D 2D           
  848F    2D 2D 2D 2D           
  8493    2D 2D 2D 2D                       DB      '------------------------'
  8497    2D 2D 2D 2D           
  849B    2D 2D 2D 2D           
  849F    2D 2D 2D 2D           
  84A3    2D 2D 2D 2D           
  84A7    2D 2D 2D 2D           
  84AB    2D 2D 2D 2D                       DB      '------------------------'
  84AF    2D 2D 2D 2D           
  84B3    2D 2D 2D 2D           
  84B7    2D 2D 2D 2D           
  84BB    2D 2D 2D 2D           
  84BF    2D 2D 2D 2D           
  84C3    2D 2D 2D 2D                       DB      '------------------------'
  84C7    2D 2D 2D 2D           
  84CB    2D 2D 2D 2D           
  84CF    2D 2D 2D 2D           
  84D3    2D 2D 2D 2D           
  84D7    2D 2D 2D 2D           
  84DB    2D 2D 2D 2D                       DB      '------------------------'
  84DF    2D 2D 2D 2D           
  84E3    2D 2D 2D 2D           
  84E7    2D 2D 2D 2D           
  84EB    2D 2D 2D 2D           
  84EF    2D 2D 2D 2D           
  84F3    2D 2D 2D 2D                       DB      '------------------------'
  84F7    2D 2D 2D 2D           
  84FB    2D 2D 2D 2D           
  84FF    2D 2D 2D 2D           
  8503    2D 2D 2D 2D           
  8507    2D 2D 2D 2D           
  850B    2D 2D 2D 2D                       DB      '------------------------'
  850F    2D 2D 2D 2D           
  8513    2D 2D 2D 2D           
  8517    2D 2D 2D 2D           
  851B    2D 2D 2D 2D           
  851F    2D 2D 2D 2D           
  8523    8547                  D0.PRT2:    DW      D0.PRK
  8525    857B                              DW      D0.PRL
  8527    85B3                              DW      D0.PRP
  8529    21 845F               D0.PROM:    LD      HL,D0.PRT1-4
  852C    11 8523                           LD      DE,D0.PRT2
  852F    01 0006                           LD      BC,6            
  8532    CD 8C2A                           CALL    D0.TA04
'Funktion :   PROM '	MACRO-80 3.44	09-Dec-81	PAGE	1-14


  8535    21 0000                           LD      HL,0
  8538    22 B18C                           LD      (MS.ZPOS),HL
  853B    21 801C                           LD      HL,D0.DD
  853E    22 B21D                           LD      (TS.TAB3+6),HL
  8541    3E 80                             LD      A,080H
  8543    32 B23F                           LD      (TS.SPMER),A
  8546    C9                                RET
                                ;
                                ;
                                ;            
  8547    CD 86A6               D0.PRK:     CALL    D0.PRUP1            ;EPROM - Kontrollieren
  854A    CD 86B3               D0.PRK1:    CALL    D0.PRUP2
  854D    20 15                             JR      NZ,D0.PRF
  854F    3C                                INC     A
  8550    20 12                             JR      NZ,D0.PRF
  8552    13                                INC     DE
  8553    CB 52                             BIT     2,D
  8555    28 F3                             JR      Z,D0.PRK1
                                ;
  8557    AF                    D0.PRR:     XOR     A                   ;Ende des PROM - Programmteiles
  8558    D3 E1                             OUT     (S0.PROM+1),A
  855A    18 CD                             JR      D0.PROM
                                ;
  855C    46 65 68 6C           D0.PRF1:    DB      'Fehler: '
  8560    65 72 3A 20           
  8564    21 000A               D0.PRF:     LD      HL,0000AH           ;Fehler anzeigen
  8567    ED 53 B28E                        LD      (S2.DL),DE
  856B    CD 88CA                           CALL    D0.DDU19
  856E    06 08                             LD      B,8
  8570    21 855C                           LD      HL,D0.PRF1
  8573    CD CB10                           CALL    MO.MONI
  8576    CD 8C61                           CALL    D0.AH2
  8579    18 DC                             JR      D0.PRR
                                
                                            PAGE
'Funktion :   PROM '	MACRO-80 3.44	09-Dec-81	PAGE	1-15


                                
  857B    CD 8C21               D0.PRL:     CALL    D0.TA03             ;EPROM - lesen
  857E    21 8587                           LD      HL,D0.PRPQ1
  8581    11 845B                           LD      DE,D0.PR1
  8584    C3 8258               D0.PRL1:    JP      D0.IN1
                                ;
  8587    06 08                 D0.PRPQ1:   LD      B,8
  8589    21 845B                           LD      HL,D0.PR1
  858C    CD 8712                           CALL    D0.PQ14
  858F    2A B28E                           LD      HL,(S2.DL)
  8592    CD 86A6                           CALL    D0.PRUP1
  8595    CD 86B3               D0.PRL2:    CALL    D0.PRUP2
  8598    20 CA                             JR      NZ,D0.PRF
  859A    77                                LD      (HL),A
  859B    BE                                CP      (HL)
  859C    20 DD                             JR      NZ,D0.PRL
  859E    23                                INC     HL
  859F    13                                INC     DE
  85A0    CB 52                             BIT     2,D
  85A2    28 F1                             JR      Z,D0.PRL2
  85A4    01 0400                           LD      BC,00400H
  85A7    2A B28E                           LD      HL,(S2.DL)
  85AA    CD 866D                           CALL    D0.CHK
  85AD    18 A8                             JR      D0.PRR
                                ;            
  85AF    E5                    D0.PRL3:    PUSH    HL
  85B0    D1                                POP     DE
  85B1    18 B1                             JR      D0.PRF
                                ;
                                ;
                                ;
  85B3    CD 8C21               D0.PRP:     CALL    D0.TA03             ;EPROM - programmieren
  85B6    21 85BE                           LD      HL,D0.PRPQ2
  85B9    11 845B                           LD      DE,D0.PR1
  85BC    18 C6                             JR      D0.PRL1
                                ;
  85BE    06 08                 D0.PRPQ2:   LD      B,8
  85C0    21 845B                           LD      HL,D0.PR1
  85C3    CD 8712                           CALL    D0.PQ14
  85C6    2A B28E                           LD      HL,(S2.DL)
  85C9    0E 10                 	        LD      C,010H
  85CB    CD 86CD               D0.PRP2:    CALL    D0.PRUP3
  85CE    C5                                PUSH    BC
  85CF    CD 86FE                           CALL    D0.PRUP4
  85D2    C1                                POP     BC
  85D3    28 06                             JR      Z,D0.PRP3
  85D5    0D                                DEC     C
  85D6    20 F3                             JR      NZ,D0.PRP2
  85D8    C3 8564                           JP      D0.PRF              ;Fehlerauswertung
                                ;            
  85DB    CD 86CD               D0.PRP3:    CALL    D0.PRUP3
  85DE    01 0400                           LD      BC,00400H
  85E1    2A B28E                           LD      HL,(S2.DL)
  85E4    CD 866D                           CALL    D0.CHK
  85E7    C3 8557                           JP      D0.PRR
                                
                                            TITLE   'Funktion :   RAMT '
                                            PAGE
'Funktion :   RAMT '	MACRO-80 3.44	09-Dec-81	PAGE	1-16


                                
                                ;****************************************************************
                                ;*	                     D E B U G   -   Funktion :  RAMT       *
                                ;****************************************************************
  85EA    21 85F6               D0.RAMT:    LD      HL,D0.RAMT1
  85ED    22 B24B                           LD      (TS.BFOL2),HL
  85F0    3E FF                             LD      A,0FFH
  85F2    32 B247                           LD      (TS.MIO),A
  85F5    C9                                RET
                                ;            
  85F6    CD                    D0.RAMT1:   DB      0CDH                ;SYS-Taste
  85F7    4C 50 31                          DB      'LP1'
  85FA    B0                                DB      0B0H                ;POS QUIT
  85FB    52 41 4D 42                       DB      'RAMBUG'
  85FF    55 47                 
  8601    B0                                DB      0B0H
  8602    52 41 4D 42                       DB      'RAMB'
  8606    B0                                DB      0B0H
                                ;
  8607    8607                              DW      $
  8609    52 41 4D 42                       DB      'RAMB'
  860D    F3                                DI
  860E    AF                                XOR     A
  860F    32 B247                           LD      (TS.MIO),A
  8612    21 CD99                           LD      HL,MO.ROLL
  8615    22 B19A                           LD      (MS.RADR),HL
  8618    21 B197                           LD      HL,MS.DIRES
  861B    CB EE                             SET     5,(HL)
  861D    21 862B                           LD      HL,D0.RAMT2
  8620    11 0103                           LD      DE,00103H
  8623    01 0011                           LD      BC,17
  8626    ED B0                             LDIR
  8628    C3 0100                           JP      00100H
                                ;            
  862B    C3 863C               D0.RAMT2:   JP      D0.CON
  862E    C3 E657                           JP      S9.CIN
  8631    C3 E68B                           JP      S9.CSTSX
  8634    C3 8640                           JP      D0.CADR
  8637    C3 8645                           JP      D0.CHOM
  863A    16                                DB      22
  863B    50                                DB      80
                                ;
  863C    4F                    D0.CON:     LD      C,A
  863D    C3 E6A6                           JP      S9.CON
                                ;
  8640    ED 53 B18C            D0.CADR:    LD      (MS.ZPOS),DE
  8644    C9                                RET
                                ;
  8645    CD EE58               D0.CHOM:    CALL    S9.SAVE
  8648    3E 05                             LD      A,5
  864A    32 B198                           LD      (MS.CMD),A
  864D    CD CB10                           CALL    MO.MONI
  8650    21 0000                           LD      HL,0
  8653    22 B18C                           LD      (MS.ZPOS),HL
  8656    3E 06                             LD      A,6
  8658    32 B198                           LD      (MS.CMD),A
  865B    CD CB10                           CALL    MO.MONI
  865E    CD EE78                           CALL    S9.LOAD
  8661    C9                                RET
                                ;
  8662                          D0.RCDC     EQU     $
'Funktion :   RAMT '	MACRO-80 3.44	09-Dec-81	PAGE	1-17


  8662                          D0.LOAD     EQU     $
  8662                          D0.SAVE     EQU     $
  8662                          D0.REAS     EQU     $
  8662    C9                                RET
                                ;            
  8663                          D0.RGDC     EQU     $
  8663    CD 896A               D0.UCPU:    CALL    D0.DDU30
  8666    21 801C                           LD      HL,D0.DD
  8669    22 B21D                           LD      (TS.TAB3+6),HL
  866C    C9                                RET
                                
                                            TITLE 'Unterprogramme'
                                            PAGE
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-18


                                
                                ;****************************************************************
                                ;*	                     Kontrollsumme berechnen                *
                                ;****************************************************************
  866D    11 FFFF               D0.CHK:     LD      DE,0FFFFH
  8670    7E                    D0.CHK1:    LD      A,(HL)
  8671    AA                                XOR     D
  8672    57                                LD      D,A
  8673    0F                                RRCA
  8674    0F                                RRCA
  8675    0F                                RRCA
  8676    0F                                RRCA
  8677    E6 0F                             AND     00FH
  8679    AA                                XOR     D
  867A    57                                LD      D,A
  867B    0F                                RRCA
  867C    0F                                RRCA
  867D    0F                                RRCA
  867E    F5                                PUSH    AF
  867F    E6 1F                             AND     01FH
  8681    AB                                XOR     E
  8682    5F                                LD      E,A
  8683    F1                                POP     AF
  8684    F5                                PUSH    AF
  8685    0F                                RRCA
  8686    E6 F0                             AND     0F0H
  8688    AB                                XOR     E
  8689    5F                                LD      E,A
  868A    F1                                POP     AF
  868B    E6 E0                             AND     0E0H
  868D    AA                                XOR     D
  868E    53                                LD      D,E
  868F    5F                                LD      E,A
  8690    23                                INC     HL
  8691    0B                                DEC     BC
  8692    78                                LD      A,B
  8693    B1                                OR      C
  8694    20 DA                             JR      NZ,D0.CHK1          ; Ergebnis in < DE >
  8696    ED 53 B28E                        LD      (S2.DL),DE
  869A    06 11                             LD      B,17
  869C    21 83FD                           LD      HL,D0.RT3
  869F    CD CB10                           CALL    MO.MONI
  86A2    CD 8C61                           CALL    D0.AH2
  86A5    C9                                RET
                                
                                            PAGE
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-19


                                
                                ;**********************************************************************
                                ;*	                     Unterprogramme fuer EPROM - Anschlusseinheit *
                                ;**********************************************************************
  86A6    3E 18                 D0.PRUP1:   LD      A,018H
  86A8    D3 E1                             OUT     (S0.PROM+1),A
  86AA    11 03E8                           LD      DE,003E8H
  86AD    1B                    D0.PRU11:   DEC     DE
  86AE    7A                                LD      A,D
  86AF    B3                                OR      E
  86B0    20 FB                             JR      NZ,D0.PRU11
  86B2    C9                                RET
                                ;
  86B3    7B                    D0.PRUP2:   LD      A,E
  86B4    D3 E2                             OUT     (S0.PROM+2),A
  86B6    7A                                LD      A,D
  86B7    0F                                RRCA
  86B8    0F                                RRCA
  86B9    F6 18                             OR      018H
  86BB    D3 E1                             OUT     (S0.PROM+1),A
  86BD    06 06                             LD      B,6
  86BF    10 03                 D0.PRU21:   DJNZ    D0.PRU22
  86C1    F6 01                             OR      1
  86C3    C9                                RET
                                ;
  86C4    DB E3                 D0.PRU22:   IN      A,(S0.PROM+3)
  86C6    4F                                LD      C,A
  86C7    DB E3                             IN      A,(S0.PROM+3)
  86C9    B9                                CP      C
  86CA    20 F3                             JR      NZ,D0.PRU21
  86CC    C9                                RET
                                ;
  86CD    06 0C                 D0.PRUP3:   LD      B,00CH
  86CF    2A B28E               D0.PRU31:   LD      HL,(S2.DL)
  86D2    11 0000                           LD      DE ,0
  86D5    7B                    D0.PRU32:   LD      A,E
  86D6    D3 E2                             OUT     (S0.PROM+2),A
  86D8    7A                                LD      A,D
  86D9    0F                                RRCA
  86DA    0F                                RRCA
  86DB    F6 1B                             OR      01BH
  86DD    D3 E1                             OUT     (S0.PROM+1),A
  86DF    F5                                PUSH    AF
  86E0    7E                                LD      A,(HL)
  86E1    D3 E3                             OUT     (S0.PROM+3),A
  86E3    F1                                POP     AF
  86E4    F5                                PUSH    AF
  86E5    F6 1F                             OR      01FH
  86E7    D3 E1                             OUT     (S0.PROM+1),A
  86E9    3E 18                             LD      A,018H
  86EB    3D                    D0.PRU33:   DEC     A
  86EC    20 FD                             JR      NZ,D0.PRU33
  86EE    F1                                POP     AF
  86EF    D3 E1                             OUT     (S0.PROM+1),A
  86F1    23                                INC     HL
  86F2    13                                INC     DE
  86F3    CB 52                             BIT     2,D
  86F5    28 DE                             JR      Z,D0.PRU32
  86F7    10 D6                             DJNZ    D0.PRU31
  86F9    E6 FD                             AND     0FDH
  86FB    D3 E1                             OUT     (S0.PROM+1),A
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-20


  86FD    C9                                RET
                                ;
  86FE    2A B28E               D0.PRUP4:   LD      HL,(S2.DL)
  8701    CD 86A6                           CALL    D0.PRUP1
  8704    CD 86B3               D0.PRU41:   CALL    D0.PRUP2
  8707    C0                                RET     NZ
  8708    BE                                CP      (HL)
  8709    C0                                RET     NZ
  870A    23                                INC     HL
  870B    13                                INC     DE
  870C    CB 52                             BIT     2,D
  870E    28 F4                             JR      Z,D0.PRU41
  8710    AF                                XOR     A
  8711    C9                                RET
                                            
                                            PAGE
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-21


                                
                                ;**********************************************************************
                                ;*                                                                    *
                                ;**********************************************************************
  8712    E5                    D0.PQ14:    PUSH    HL
  8713    C5                                PUSH    BC
  8714    CD 8A09                           CALL    D0.AS
  8717    2A B28E                           LD      HL,(S2.DL)
  871A    22 B290                           LD      (S2.PAR1),HL
  871D    21 000A                           LD      HL,0000AH           ;ZPOS = 10 , SPOS = 0
  8720    CD 88CA                           CALL    D0.DDU19
  8723    C1                                POP     BC
  8724    E1                                POP     HL
  8725    CD CB10                           CALL    MO.MONI
  8728    06 02                             LD      B,2
  872A    21 824D                           LD      HL,D0.TPQ
  872D    CD CB10                           CALL    MO.MONI
  8730    CD 8C61                           CALL    D0.AH2
  8733    C9                                RET
                                ;**********************************************************************
                                ;*	                     <B>-malige Anzeige von <A> in Richtung <C>   *
                                ;**********************************************************************
  8734    32 B199               D0.DDU01:   LD      (MS.TK),A
  8737    79                                LD      A,C
  8738    32 B197                           LD      (MS.DIRES),A
  873B    CD CB10               D0.DDU02:   CALL    MO.MONI
  873E    10 FB                             DJNZ    D0.DDU02
  8740    C9                                RET
                                
                                            PAGE
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-22


                                
                                ;**********************************************************************
                                ;*	                     Rahmengrundelemente                          *
                                ;**********************************************************************
                                ;           Anzeige :    $$$$$
  8741    22 B18C               D0.DDU03:   LD      (MS.ZPOS),HL
  8744    3E 81                             LD      A,081H              ;Zeichen : $   alt:001H   mitte   (03)
  8746    0E C0                             LD      C,0C0H              ;Richtung: Ost
  8748    CD 8734                           CALL    D0.DDU01
  874B    C9                                RET
                                ;           Anzeige :    $
                                ;                        $
                                ;                        $
  874C    22 B18C               D0.DDU04:   LD      (MS.ZPOS),HL
  874F    AF                                XOR     A                   ;Zeichen : $
  8750    0E C6                             LD      C,0C6H              ;Richtung: Sued
  8752    CD 8734                           CALL    D0.DDU01
  8755    C9                                RET
                                ;           Anzeige :    $$$$$
  8756    0E C0                 D0.DDU05:   LD      C,0C0H              ;Richtung: Ost
  8758    C5                                PUSH    BC
  8759    22 B18C                           LD      (MS.ZPOS),HL
  875C    3E 82                             LD      A,082H              ;Zeichen : $   alt:002H   links
  875E    06 01                             LD      B,1
  8760    CD 8734                           CALL    D0.DDU01
  8763    2A B18C                           LD      HL,(MS.ZPOS)
  8766    C1                                POP     BC
  8767    CD 8741                           CALL    D0.DDU03
  876A    3E 83                             LD      A,083H              ;Zeichen : $   alt:003H   rechts   (01)
  876C    01 0100                           LD      BC,00100H
  876F    CD 8734                           CALL    D0.DDU01
  8772    C9                                RET
                                ;
  8773    0E C0                 D0.DDU17:   LD      C,0C0H
  8775    C5                                PUSH    BC
  8776    22 B18C                           LD      (MS.ZPOS),HL
  8779    3E 8A                             LD      A,08AH
  877B    06 01                             LD      B,1
  877D    CD 8734                           CALL    D0.DDU01
  8780    2A B18C                           LD      HL,(MS.ZPOS)
  8783    C1                                POP     BC
  8784    CD 8741                           CALL    D0.DDU03
  8787    3E 8B                             LD      A,08BH
  8789    01 0100                           LD      BC,00100H
  878C    CD 8734                           CALL    D0.DDU01
  878F    C9                                RET
                                ;           Anzeige :    $
                                ;                        $
                                ;                        $
  8790    0E C6                 D0.DDU06:   LD      C,0C6H              ;Richtung: Sued
  8792    C5                                PUSH    BC
  8793    22 B18C                           LD      (MS.ZPOS),HL
  8796    3E 01                             LD      A,001H              ;Zeichen : $	           (05)
  8798    06 01                             LD      B,1
                                            ;CALL    D0.DDU01
  879A    2A B18C                           LD      HL,(MS.ZPOS)
  879D    2C                                INC     L
  879E    C1                                POP     BC
  879F    CD 874C                           CALL    D0.DDU04
  87A2    3E 01                             LD      A,001H              ;Zeichen : $	           (04)
  87A4    01 0100                           LD      BC,00100H
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-23


                                            ;CALL    D0.DDU01
  87A7    C9                                RET
                                ;
  87A8    01 0E04               D0.DDU07:   LD      BC,00E04H           ;Rahmen Zeichnen   
  87AB    CD 88A6                           CALL    D0.DDU18
  87AE    2A B29A                           LD      HL,(S2.DM1)
  87B1    7C                                LD      A,H
  87B2    C6 05                             ADD     A,5
  87B4    67                                LD      H,A
  87B5    06 04                             LD      B,4
  87B7    CD 8790                           CALL    D0.DDU06
  87BA    2A B29A                           LD      HL,(S2.DM1)
  87BD    7C                                LD      A,H
  87BE    C6 0A                             ADD     A,10
  87C0    67                                LD      H,A
  87C1    06 04                             LD      B,4
  87C3    CD 8790                           CALL    D0.DDU06
  87C6    C9                                RET
                                ;
  87C7    3E 14                 D0.DDU08:   LD      A,20
  87C9    32 B198                           LD      (MS.CMD),A
  87CC    21 0203                           LD      HL,00203H           ;ZPOS = 3 , SPOS = 2
  87CF    CD 87A8                           CALL    D0.DDU07            ;                    Rahmen Ebene 0
  87D2    21 1603                           LD      HL,01603H           ;ZPOS = 3 , SPOS = 22
  87D5    CD 87A8                           CALL    D0.DDU07            ;                    Rahmen Ebene 1
  87D8    21 2A03                           LD      HL,02A03H           ;ZPOS = 3 , SPOS = 42
  87DB    CD 87A8                           CALL    D0.DDU07            ;                    Rahmen Ebene 2
  87DE    21 3E03                           LD      HL,03E03H           ;ZPOS = 3 , SPOS = 62
  87E1    CD 87A8                           CALL    D0.DDU07            ;                    Rahmen Ebene 3
  87E4    3E 18                             LD      A,24
  87E6    32 B198                           LD      (MS.CMD),A
  87E9    21 0602                           LD      HL,00602H           ;ZPOS = 2 , SPOS = 6
  87EC    CD 8829                           CALL    D0.DDU10
  87EF    21 1A02                           LD      HL,01A02H           ;ZPOS = 2 , SPOS = 26
  87F2    CD 8829                           CALL    D0.DDU10
  87F5    21 2E02                           LD      HL,02E02H           ;ZPOS = 2 , SPOS = 46
  87F8    CD 8829                           CALL    D0.DDU10
  87FB    21 4202                           LD      HL,04202H           ;ZPOS = 2 , SPOS = 66
  87FE    CD 8829                           CALL    D0.DDU10
  8801    3E 14                             LD      A,20
  8803    32 B198                           LD      (MS.CMD),A
  8806    3E 2F                             LD      A,'/'
  8808    32 B199                           LD      (MS.TK),A
  880B    21 0D02                           LD      HL,00D02H           ;ZPOS = 2 , SPOS = 13
  880E    CD 883A                           CALL    D0.DDU11
  8811    21 2102                           LD      HL,02102H           ;ZPOS = 2 , SPOS = 33
  8814    CD 883A                           CALL    D0.DDU11
  8817    21 3502                           LD      HL,03502H           ;ZPOS = 2 , SPOS = 53
  881A    CD 883A                           CALL    D0.DDU11
  881D    21 4902                           LD      HL,04902H           ;ZPOS = 2 , SPOS = 73
  8820    CD 883A                           CALL    D0.DDU11
  8823    C9                                RET
                                ;
  8824    45 62 65 6E           D0.DDU09:   DB      'Ebene'
  8828    65                    
  8829    22 B18C               D0.DDU10:   LD      (MS.ZPOS),HL
  882C    06 05                             LD      B,5
  882E    3E C0                             LD      A,0C0H              ;Richtung: Ost
  8830    32 B197                           LD      (MS.DIRES),A
  8833    21 8824                           LD      HL,D0.DDU09
  8836    CD CB10                           CALL    MO.MONI
  8839    C9                                RET
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-24


                                 ;
                                 ;
                                 ;
  883A    22 B18C                D0.DDU11:  LD      (MS.ZPOS),HL
  883D    21 B199                           LD      HL,MS.TK
  8840    34                                INC     (HL)
  8841    CD CB10                           CALL    MO.MONI
  8844    C9                                RET
                                ;
                                ;
                                ;
  8845    2A B29A               D0.DDU12:   LD      HL,(S2.DM1)
  8848    11 0004                           LD      DE,4
  884B    19                                ADD     HL,DE
  884C    22 B29A                           LD      (S2.DM1),HL
  884F    06 04                             LD      B,4
  8851    CD CB10                           CALL    MO.MONI
  8854    C9                                RET
                                ;
                                ;
                                ;
  8855    22 B18C               D0.DDU13:   LD      (MS.ZPOS),HL
  8858    06 04                             LD      B,4
  885A    C5                    D0.DDU14:   PUSH    BC
  885B    CD 8845                           CALL    D0.DDU12
  885E    DD 34 00                          INC     (IX)
  8861    CD 8845                           CALL    D0.DDU12
  8864    DD 34 00                          INC     (IX)
  8867    CD 8845                           CALL    D0.DDU12
  886A    FD 34 00                          INC     (IY)
  886D    06 0E                             LD      B,14
  886F    DD 35 00              D0.DDU15:   DEC     (IX)
  8872    10 FB                             DJNZ    D0.DDU15
  8874    C1                                POP     BC
  8875    10 E3                             DJNZ    D0.DDU14
  8877    C9                                RET
                                ;
                                ;
                                ;
  8878    3E 18                 D0.DDU16:   LD      A,24
  887A    32 B198                           LD      (MS.CMD),A
  887D    3E C0                             LD      A,0C0H
  887F    32 B197                           LD      (MS.DIRES),A
  8882    22 B29A                           LD      (S2.DM1),HL         ;Bedeutungstabelle
  8885    FD 21 B18C                        LD      IY,MS.ZPOS
  8889    DD 21 B18D                        LD      IX,MS.SPOS
  888D    21 0304                           LD      HL,00304H           ;ZPOS = 4 , SPOS = 3
  8890    CD 8855                           CALL    D0.DDU13
  8893    21 1704                           LD      HL,01704H           ;ZPOS = 4 , SPOS = 23
  8896    CD 8855                           CALL    D0.DDU13
  8899    21 2B04                           LD      HL,02B04H           ;ZPOS = 4 , SPOS = 43
  889C    CD 8855                           CALL    D0.DDU13
  889F    21 3F04                           LD      HL,03F04H           ;ZPOS = 4 , SPOS = 63
  88A2    CD 8855                           CALL    D0.DDU13
  88A5    C9                                RET
                                
                                            PAGE
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-25


                                
  88A6    C5                    D0.DDU18:   PUSH    BC                  ; |---------|
  88A7    22 B29A                           LD      (S2.DM1),HL         ; |         | < C >   anzeigen
  88AA    CD 8756                           CALL    D0.DDU05            ; |---------|
  88AD    2A B18C                           LD      HL,(MS.ZPOS)        ;    < B >
  88B0    2C                                INC     L
  88B1    25                                DEC     H
  88B2    C1                                POP     BC
  88B3    C5                                PUSH    BC
  88B4    41                                LD      B,C
  88B5    CD 874C                           CALL    D0.DDU04
  88B8    2A B29A                           LD      HL,(S2.DM1)
  88BB    2C                                INC     L
  88BC    C1                                POP     BC
  88BD    C5                                PUSH    BC
  88BE    41                                LD      B,C
  88BF    CD 874C                           CALL    D0.DDU04
  88C2    2A B18C                           LD      HL,(MS.ZPOS)
  88C5    C1                                POP     BC
  88C6    CD 8773                           CALL    D0.DDU17
  88C9    C9                                RET
                                ;
                                ;
                                ;
  88CA    E5                    D0.DDU19:   PUSH    HL
  88CB    3E 02                             LD      A,2
  88CD    32 B198                           LD      (MS.CMD),A
  88D0    CD CB10                           CALL    MO.MONI
  88D3    3E 18                             LD      A,24
  88D5    32 B198                           LD      (MS.CMD),A
  88D8    E1                                POP     HL
  88D9    22 B18C                           LD      (MS.ZPOS),HL
  88DC    C9                                RET
                                ;
                                ;
                                ;
  88DD    CD 87C7               D0.DDU20:   CALL    D0.DDU08
  88E0    21 8181                           LD      HL,D0.DDPTB-4
  88E3    CD 8878                           CALL    D0.DDU16
  88E6    C9                                RET
                                ;
                                ;
                                ;
  88E7    3A B28B               D0.DDU21:   LD      A,(S2.BZ)
  88EA    FE 02                             CP      2
  88EC    28 04                             JR      Z,D0.DDU22
  88EE    06 00                             LD      B,0
  88F0    18 02                             JR      D0.DDU23
                                ;            
  88F2    06 05                 D0.DDU22:   LD      B,5
  88F4    3A B28A               D0.DDU23:   LD      A,(S2.AFOR)
  88F7    80                                ADD     A,B
  88F8    87                                ADD     A,A
  88F9    4F                                LD      C,A
  88FA    06 00                             LD      B,0
  88FC    09                                ADD     HL,BC
  88FD    7E                                LD      A,(HL)
  88FE    23                                INC     HL
  88FF    66                                LD      H,(HL)
  8900    6F                                LD      L,A
  8901    C9                                RET
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-26


                                ;
  8902    3E 2C                 D0.DDU24:   LD      A,44
  8904    32 B198                           LD      (MS.CMD),A
  8907    22 B18A                           LD      (MS.ZPOL),HL
  890A    21 B29A                           LD      HL,S2.DM1
  890D    CD CB10                           CALL    MO.MONI
  8910    C9                                RET
                                ;**********************************************************************
                                ;*	                     Eingabefeld loeschen und ":" anzeigen        *
                                ;**********************************************************************
  8911    CD 8C37               D0.DDU25:   CALL    D0.MO01
  8914    3E 05                             LD      A,5
  8916    32 B198                           LD      (MS.CMD),A
  8919    CD CB10                           CALL    MO.MONI
  891C    3E 14                             LD      A,20
  891E    32 B198                           LD      (MS.CMD),A
  8921    3E 3A                             LD      A,':'
  8923    32 B199                           LD      (MS.TK),A
  8926    21 3D14                           LD      HL,03D14H           ;ZPOS = 20 , SPOS = 61
  8929    22 B18C                           LD      (MS.ZPOS),HL
  892C    CD CB10                           CALL    MO.MONI
  892F    21 3513                           LD      HL,03513H           ;ZPOS = 19 , SPOS = 53
  8932    22 B18C                           LD      (MS.ZPOS),HL
  8935    C9                                RET
                                ;**********************************************************************
                                ;*	                     Spaltennummern und Text anzeigen             *
                                ;**********************************************************************
  8936    78                    D0.DDU26:   LD      A,B
  8937    FE 0A                             CP      10
  8939    38 0C                             JR      C,D0.DDU27
  893B    3E 37                             LD      A,55
  893D    80                                ADD     A,B
  893E    32 B199                           LD      (MS.TK),A
  8941    CD CB10                           CALL    MO.MONI
  8944    05                                DEC     B
  8945    18 EF                             JR      D0.DDU26
                                ;
  8947    3E 2F                 D0.DDU27:   LD      A,'/'
  8949    80                                ADD     A,B
  894A    32 B199                           LD      (MS.TK),A
  894D    CD CB10               D0.DDU28:   CALL    MO.MONI
  8950    21 B199                           LD      HL,MS.TK
  8953    35                                DEC     (HL)
  8954    10 F7                             DJNZ    D0.DDU28
  8956    3E 18                             LD      A,24
  8958    32 B198                           LD      (MS.CMD),A
  895B    06 08                             LD      B,8
  895D    2A B28C                           LD      HL, (S2.TE)
  8960    CD CB10                           CALL    MO.MONI
  8963    21 4F15                           LD      HL,04F15H
  8966    22 B190                           LD      (MS.ZMAX),HL
  8969    C9                                RET
                                
                                            PAGE
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-27


                                
  896A    21 000B               D0.DDU30:   LD      HL,0000BH
  896D    22 B18E                           LD      (MS.ZMIN),HL
  8970    21 5016                           LD      HL,05016H
  8973    22 B190                           LD      (MS.ZMAX),HL
  8976    3E 05                             LD      A,5
  8978    32 B198                           LD      (MS.CMD),A
  897B    CD CB10                           CALL    MO.MONI
  897E    3E 02                             LD      A,2
  8980    32 B198                           LD      (MS.CMD),A
  8983    CD CB10                           CALL    MO.MONI
  8986    3E 14                             LD      A,20
  8988    32 B198                           LD      (MS.CMD),A
  898B    21 000A                           LD      HL,0000AH           ;ZPOS = 10 , SPOS = 0
  898E    01 4E0A                           LD      BC,04E0AH           ;Laenge:78 , Breite:10
  8991    CD 88A6                           CALL    D0.DDU18
  8994    21 0012                           LD      HL,00012H           ;ZPOS = 18 , SPOS = 0
  8997    06 4E                             LD      B,78                ;Laenge:78
  8999    CD 8756                           CALL    D0.DDU05
  899C    21 250A                           LD      HL,0250AH           ;ZPOS = 10 , SPOS = 37
  899F    06 07                             LD      B,7
  89A1    CD 8790                           CALL    D0.DDU06
  89A4    21 3412                           LD      HL,03412H           ;ZPOS = 18 , SPOS = 52
  89A7    06 02                             LD      B,2
  89A9    CD 8790                           CALL    D0.DDU06
  89AC    21 000C                           LD      HL,0000CH           ;ZPOS = 12 , SPOS = 0
  89AF    06 24                             LD      B,36
  89B1    CD 8756                           CALL    D0.DDU05
  89B4    21 000F                           LD      HL,0000FH           ;ZPOS = 15 , SPOS = 0
  89B7    06 24                             LD      B,36
  89B9    CD 8756                           CALL    D0.DDU05
  89BC    21 0A0F                           LD      HL,00A0FH           ;ZPOS = 15 , SPOS = 10
  89BF    06 05                             LD      B,5
  89C1    CD 8790                           CALL    D0.DDU06
  89C4    21 0D0A                           LD      HL,00D0AH           ;ZPOS = 10 , SPOS = 13
  89C7    06 04                             LD      B,4
  89C9    CD 8790                           CALL    D0.DDU06
  89CC    21 150A                           LD      HL,0150AH           ;ZPOS = 10 , SPOS = 21
  89CF    06 04                             LD      B,4
  89D1    CD 8790                           CALL    D0.DDU06
  89D4    21 1D0A                           LD      HL,01D0AH           ;ZPOS = 10 , SPOS = 29
  89D7    06 04                             LD      B,4
  89D9    CD 8790                           CALL    D0.DDU06
  89DC    21 170F                           LD      HL,0170FH           ;ZPOS = 15 , SPOS = 23
  89DF    06 02                             LD      B,2
  89E1    CD 8790                           CALL    D0.DDU06
  89E4    21 090C                           LD      HL,0090CH           ;ZPOS = 12 , SPOS = 9
  89E7    CD 89FD                           CALL    D0.DDU31
  89EA    21 110C                           LD      HL,0110CH           ;ZPOS = 12 , SPOS = 17
  89ED    CD 89FD                           CALL    D0.DDU31
  89F0    21 190C                           LD      HL,0190CH           ;ZPOS = 12 , SPOS = 25
  89F3    CD 89FD                           CALL    D0.DDU31
  89F6    21 210C                           LD      HL,0210CH           ;ZPOS = 12 , SPOS = 33
  89F9    CD 89FD                           CALL    D0.DDU31
  89FC    C9                                RET
                                ;
  89FD    22 B18C               D0.DDU31:   LD      (MS.ZPOS),HL
  8A00    3E 7C                             LD      A,07CH
  8A02    01 03C6                           LD      BC,003C6H
  8A05    CD 8734                           CALL    D0.DDU01
  8A08    C9                                RET
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-28


                                
                                            PAGE
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-29


                                
                                ;**********************************************************************
                                ;*	                     Anzeige im Eingabebereich retten             *
                                ;**********************************************************************
  8A09    21 8A10               D0.AS:      LD      HL,D0.ASTAB
  8A0C    CD 88E7                           CALL    D0.DDU21
  8A0F    E9                                JP      (HL)
                                ;
                                ;
                                ;
  8A10    8A24                  D0.ASTAB:   DW      D0.ASH1
  8A12    8A53                              DW      D0.ASD1
  8A14    8AA9                              DW      D0.ASO1
  8A16    8AA9                              DW      D0.ASB1
  8A18    8A81                              DW      D0.ASA1
                                ;
  8A1A    8A3A                              DW      D0.ASH2
  8A1C    8A6A                              DW      D0.ASD2
  8A1E    8AA9                              DW      D0.ASO2
  8A20    8AA9                              DW      D0.ASB2
  8A22    8A94                              DW      D0.ASA2
                                ;
                                ;
                                ;
  8A24    21 4D14               D0.ASH1:    LD      HL,04D14H
  8A27    06 02                             LD      B,2
  8A29    CD 8902                           CALL    D0.DDU24
  8A2C    21 B29A                           LD      HL,S2.DM1
  8A2F    CD C5CC                           CALL    S1.HBKON
  8A32    32 B28E                           LD      (S2.DL),A
  8A35    AF                                XOR     A
  8A36    32 B28F                           LD      (S2.DH),A
  8A39    C9                                RET
                                ;
  8A3A    21 4B14               D0.ASH2:    LD      HL,04B14H
  8A3D    06 04                             LD      B,4
  8A3F    CD 8902                           CALL    D0.DDU24
  8A42    21 B29A                           LD      HL,S2.DM1
  8A45    CD C5CC                           CALL    S1.HBKON
  8A48    32 B28F                           LD      (S2.DH),A
  8A4B    23                                INC     HL
  8A4C    CD C5CC                           CALL    S1.HBKON
  8A4F    32 B28E                           LD      (S2.DL),A
  8A52    C9                                RET
                                ;
                                ;
                                ;
  8A53    21 4C14               D0.ASD1:    LD      HL,04C14H
  8A56    06 03                             LD      B,3
  8A58    CD 8902                           CALL    D0.DDU24
  8A5B    3E 20                             LD      A,' '
  8A5D    32 B29D                           LD      (S2.DM1+3),A
  8A60    11 B29A                           LD      DE,S2.DM1
  8A63    CD C592                           CALL    S1.IDH
  8A66    22 B28E                           LD      (S2.DL),HL
  8A69    C9                                RET
                                ;
  8A6A    21 4A14               D0.ASD2:    LD      HL,04A14H
  8A6D    06 05                             LD      B,5
  8A6F    CD 8902                           CALL    D0.DDU24
  8A72    3E 20                             LD      A,' '
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-30


  8A74    32 B29F                           LD      (S2.DM1+5),A
  8A77    11 B29A                           LD      DE,S2.DM1
  8A7A    CD C592                           CALL    S1.IDH
  8A7D    22 B28E                           LD      (S2.DL),HL
  8A80    C9                                RET
                                ;
                                ;
                                ;
  8A81    21 4E14               D0.ASA1:    LD      HL,04E14H
  8A84    06 01                             LD      B,1
  8A86    CD 8902                           CALL    D0.DDU24
  8A89    AF                                XOR     A
  8A8A    32 B28F                           LD      (S2.DH),A
  8A8D    3A B29A                           LD      A,(S2.DM1)
  8A90    32 B28E                           LD      (S2.DL),A
  8A93    C9                                RET
                                ;
  8A94    21 4D14               D0.ASA2:    LD      HL,04D14H
  8A97    06 02                             LD      B,2
  8A99    CD 8902                           CALL    D0.DDU24
  8A9C    3A B29A                           LD      A,(S2.DM1)
  8A9F    32 B28F                           LD      (S2.DH),A
  8AA2    3A B29B                           LD      A,(S2.DM1+1)
  8AA5    32 B28E                           LD      (S2.DL),A
  8AA8    C9                                RET
                                ;
                                ;
                                ;
  8AA9                          D0.ASO1     EQU     $
  8AA9                          D0.ASO2     EQU     $
  8AA9                          D0.ASB1     EQU     $
  8AA9                          D0.ASB2     EQU     $
  8AA9    C9                                RET
                                
                                            PAGE
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-31


                                
                                ;**********************************************************************
                                ;*	                     Anzeige im Eingabebereich laden              *
                                ;**********************************************************************
  8AAA    21 8AB1               D0.AL:      LD      HL,D0.ALTAB
  8AAD    CD 88E7                           CALL    D0.DDU21
  8AB0    E9                                JP      (HL)
                                ;
                                ;
                                ;
  8AB1    8AC5                  D0.ALTAB:   DW      D0.ALH1
  8AB3    8B1B                              DW      D0.ALD1
  8AB5    8B71                              DW      D0.ALO1
  8AB7    8B71                              DW      D0.ALB1
  8AB9    8B72                              DW      D0.ALA1
                                ;
  8ABB    8AF5                              DW      D0.ALH2
  8ABD    8B4B                              DW      D0.ALD2
  8ABF    8B71                              DW      D0.ALO2
  8AC1    8B71                              DW      D0.ALB2
  8AC3    8BA7                              DW      D0.ALA2
                                ;
                                ;
                                ;
  8AC5    CD 8911               D0.ALH1:    CALL    D0.DDU25
  8AC8    3E 48                             LD      A,'H'
  8ACA    32 B199                           LD      (MS.TK),A
  8ACD    CD CB10                           CALL    MO.MONI
  8AD0    3E 4D                             LD      A,77
  8AD2    32 B18D                           LD      (MS.SPOS),A
  8AD5    06 02                             LD      B,2
  8AD7    CD 8936                           CALL    D0.DDU26
  8ADA    21 4E15                           LD      HL,04E15H
  8ADD    22 B18E                           LD      (MS.ZMIN),HL
  8AE0    21 4D14                           LD      HL,04D14H
  8AE3    22 B18C                           LD      (MS.ZPOS),HL
  8AE6    CD 8C4F                           CALL    D0.AH1
  8AE9    21 8CA4               D0.ALH:     LD      HL,D0.HZEIN
  8AEC    22 B22D                           LD      (TS.EINA),HL
  8AEF    3E A8                             LD      A,0A8H
  8AF1    32 B23F                           LD      (TS.SPMER),A
  8AF4    C9                                RET
                                ;
  8AF5    CD 8911               D0.ALH2:    CALL    D0.DDU25
  8AF8    3E 48                             LD      A,'H'
  8AFA    32 B199                           LD      (MS.TK),A
  8AFD    CD CB10                           CALL    MO.MONI
  8B00    3E 4B                             LD      A,75
  8B02    32 B18D                           LD      (MS.SPOS),A
  8B05    06 04                             LD      B,4
  8B07    CD 8936                           CALL    D0.DDU26
  8B0A    21 4C15                           LD      HL,04C15H
  8B0D    22 B18E                           LD      (MS.ZMIN),HL
  8B10    21 4B14                           LD      HL,04B14H
  8B13    22 B18C                           LD      (MS.ZPOS),HL
  8B16    CD 8C61                           CALL    D0.AH2
  8B19    18 CE                             JR      D0.ALH
                                ;
                                ;
                                ;            
  8B1B    CD 8911               D0.ALD1:    CALL    D0.DDU25
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-32


  8B1E    3E 44                             LD      A,'D'
  8B20    32 B199                           LD      (MS.TK),A
  8B23    CD CB10                           CALL    MO.MONI
  8B26    3E 4C                             LD      A,76
  8B28    32 B18D                           LD      (MS.SPOS),A
  8B2B    06 03                             LD      B,3
  8B2D    CD 8936                           CALL    D0.DDU26
  8B30    21 4D15                           LD      HL,04D15H
  8B33    22 B18E                           LD      (MS.ZMIN),HL
  8B36    21 4C14                           LD      HL,04C14H
  8B39    22 B18C                           LD      (MS.ZPOS),HL
  8B3C    CD 8C7A                           CALL    D0.AD1
  8B3F    21 8CB6               D0.ALD:     LD      HL,D0.DZEIN
  8B42    22 B22D                           LD      (TS.EINA),HL
  8B45    3E 88                             LD      A,088H
  8B47    32 B23F                           LD      (TS.SPMER),A
  8B4A    C9                                RET
                                ;
  8B4B    CD 8911               D0.ALD2:    CALL    D0.DDU25
  8B4E    3E 44                             LD      A,'D'
  8B50    32 B199                           LD      (MS.TK),A
  8B53    CD CB10                           CALL    MO.MONI
  8B56    3E 4A                             LD      A,74
  8B58    32 B18D                           LD      (MS.SPOS),A
  8B5B    06 05                             LD      B,5
  8B5D    CD 8936                           CALL    D0.DDU26
  8B60    21 4B15                           LD      HL,04B15H
  8B63    22 B18E                           LD      (MS.ZMIN),HL
  8B66    21 4A14                           LD      HL,04A14H
  8B69    22 B18C                           LD      (MS.ZPOS),HL
  8B6C    CD 8C8F                           CALL    D0.AD2
  8B6F    18 CE                             JR      D0.ALD
                                ;
  8B71                          D0.ALO1     EQU     $
  8B71                          D0.ALO2     EQU     $
  8B71                          D0.ALB1     EQU     $
  8B71    C9                    D0.ALB2:    RET
                                ;
                                ;
                                ;
  8B72    CD 8911               D0.ALA1:    CALL    D0.DDU25
  8B75    3E 41                             LD      A,'A'
  8B77    32 B199                           LD      (MS.TK),A
  8B7A    CD CB10                           CALL    MO.MONI
  8B7D    3E 4E                             LD      A,78
  8B7F    32 B18D                           LD      (MS.SPOS),A
  8B82    06 01                             LD      B,1
  8B84    CD 8936                           CALL    D0.DDU26
  8B87    21 4F15                           LD      HL,04F15H
  8B8A    22 B18E                           LD      (MS.ZMIN),HL
  8B8D    21 4E14                           LD      HL,04E14H
  8B90    22 B18C                           LD      (MS.ZPOS),HL
  8B93    06 01                             LD      B,1
  8B95    21 B28E                           LD      HL,S2.DL
  8B98    CD CB10                           CALL    MO.MONI
  8B9B    21 8CB6               D0.ALA:     LD      HL,D0.AZEIN
  8B9E    22 B22D                           LD      (TS.EINA),HL
  8BA1    3E FF                             LD      A,0FFH
  8BA3    32 B23F                           LD      (TS.SPMER),A
  8BA6    C9                                RET
                                ;
  8BA7    CD 8911               D0.ALA2:    CALL    D0.DDU25
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-33


  8BAA    3E 41                             LD      A,'A'
  8BAC    32 B199                           LD      (MS.TK),A
  8BAF    CD CB10                           CALL    MO.MONI
  8BB2    3E 4D                             LD      A,77
  8BB4    32 B18D                           LD      (MS.SPOS),A
  8BB7    06 02                             LD      B,2
  8BB9    CD 8936                           CALL    D0.DDU26
  8BBC    21 4E15                           LD      HL,04E15H
  8BBF    22 B18E                           LD      (MS.ZMIN),HL
  8BC2    21 4D14                           LD      HL,04D14H
  8BC5    22 B18C                           LD      (MS.ZPOS),HL
  8BC8    3A B28F                           LD      A,(S2.DH)
  8BCB    32 B29A                           LD      (S2.DM1),A
  8BCE    3A B28E                           LD      A,(S2.DL)
  8BD1    32 B29B                           LD	    (S2.DM1+1),A
  8BD4    06 02                             LD      B,2
  8BD6    21 B29A                           LD      HL,S2.DM1
  8BD9    CD CB10                           CALL    MO.MONI
  8BDC    18 BD                             JR      D0.ALA
                                ;
                                ;
                                ;
  8BDE    CD 8A09               D0.AW:      CALL    D0.AS
  8BE1    3A B23C                           LD      A,(TS.TK)
  8BE4    32 B28A                           LD      (S2.AFOR),A
  8BE7    CD 8AAA                           CALL    D0.AL
  8BEA    C9                                RET
                                ;
                                ;
                                ;
  8BEB    21 C2D3               D0.TA01:    LD      HL,S1.CNLS
  8BEE    22 B20D                           LD      (TS.TAB2+14),HL
  8BF1    21 C2B4                           LD      HL,S1.CNRS
  8BF4    22 B211                           LD      (TS.TAB2+18),HL
  8BF7    21 C334                           LD      HL,S1.NN
  8BFA    22 B217                           LD      (TS.TAB3),HL
  8BFD    21 C345                           LD      HL,S1.NNN
  8C00    22 B219                           LD      (TS.TAB3+2),HL
  8C03    C9                                RET
                                ;
                                ;
                                ;
  8C04    C5                    D0.TA02:    PUSH    BC
  8C05    D5                                PUSH    DE
  8C06    E5                                PUSH    HL
  8C07    CD D408                           CALL    TA.LOE
  8C0A    3E 02                             LD      A,2	
  8C0C    32 B198                           LD      (MS.CMD),A	
  8C0F    CD CB10                           CALL    MO.MONI
  8C12    CD 87C7                           CALL    D0.DDU08            ;Rahmen P-Tasten anzeigen
  8C15    E1                                POP     HL                  ;Rahmen fuellen
  8C16    CD 8878                           CALL    D0.DDU16
  8C19    E1                                POP     HL
  8C1A    11 B19F                           LD      DE,TS.TAB1
  8C1D    C1                                POP     BC
  8C1E    ED B0                             LDIR
  8C20    C9                                RET
                                ;
                                ;
                                ;
  8C21    21 80C1               D0.TA03:    LD      HL,D0.DDPT3-4
  8C24    11 80BB                           LD      DE,D0.DDPT2
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-34


  8C27    01 000A                           LD      BC,10
  8C2A    CD 8C04               D0.TA04:    CALL    D0.TA02
  8C2D    AF                                XOR     A                   ;Anzeigeformat auf hexa
  8C2E    32 B28A                           LD      (S2.AFOR),A
  8C31    3E 02                             LD      A,2                 ;Eingabe auf 2 Byte
  8C33    32 B28B                           LD      (S2.BZ),A
  8C36    C9                                RET
                                ;
                                ;
                                ;
                                ;**********************************************************************
                                ;*	                     Fenster gleich Eingabebereich definieren     *
                                ;**********************************************************************
  8C37    21 3614               D0.MO01:    LD      HL,03614H           ;ZMIN = 20 , SMIN = 54
  8C3A    22 B18E                           LD      (MS.ZMIN),HL
  8C3D    21 4F15                           LD      HL,04F15H           ;ZMAX = 21 , SMAX = 79
  8C40    22 B190                           LD      (MS.ZMAX),HL
  8C43    21 3513                           LD      HL,03513H           ;ZPOS = 19 , SPOS = 53
  8C46    22 B18C                           LD      (MS.ZPOS),HL
  8C49    3E C0                             LD      A,0C0H
  8C4B    32 B197                           LD      (MS.DIRES),A
  8C4E    C9                                RET
                                ;**********************************************************************
                                ;*	                     Anzeige von   <S2.DL>   hexadezimal          *
                                ;**********************************************************************
  8C4F    3A B28E               D0.AH1:     LD      A,(S2.DL)
  8C52    21 B29A                           LD      HL,S2.DM1
  8C55    CD C5FF                           CALL    S1.BHKON
  8C58    06 02                             LD      B,2
  8C5A    21 B29A                           LD      HL,S2.DM1
  8C5D    CD CB10                           CALL    MO.MONI
  8C60    C9                                RET
                                ;**********************************************************************
                                ;*	                     Anzeige von   <S2.DH,S2.DL>   hexadezimal    *
                                ;**********************************************************************
  8C61    3A B28F               D0.AH2:     LD      A,(S2.DH)
  8C64    21 B29A                           LD      HL,S2.DM1
  8C67    CD C5FF                           CALL    S1.BHKON
  8C6A    3A B28E                           LD      A,(S2.DL)
  8C6D    23                                INC     HL
  8C6E    CD C5FF                           CALL    S1.BHKON
  8C71    06 04                             LD      B,4
  8C73    21 B29A                           LD      HL,S2.DM1
  8C76    CD CB10                           CALL    MO.MONI
  8C79    C9                                RET
                                ;
                                ;
                                ;
  8C7A    2A B28E               D0.AD1:     LD      HL,(S2.DL)
  8C7D    11 B29A                           LD      DE,S2.DM1
  8C80    3E 41                             LD      A,'A'
  8C82    12                                LD      (DE) ,A
  8C83    CD C54E                           CALL    S1.HDI
  8C86    06 03                             LD      B,3
  8C88    21 B29D                           LD      HL,S2.DM1+3
  8C8B    CD CB10                           CALL    MO.MONI
  8C8E    C9                                RET
                                ;
  8C8F    2A B28E               D0.AD2:     LD      HL,(S2.DL)
  8C92    11 B29A                           LD      DE,S2.DM1
  8C95    3E 41                             LD      A,'A'
  8C97    12                                LD      (DE),A
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-35


  8C98    CD C54E                           CALL    S1.HDI
  8C9B    06 05                             LD      B,5
  8C9D    21 B29B                           LD      HL,S2.DM1+1
  8CA0    CD CB10                           CALL    MO.MONI
  8CA3    C9                                RET
                                ;
                                ;
                                ;
  8CA4    3A B23C               D0.HZEIN:   LD      A,(TS.TK)
  8CA7    FE 47                             CP      'G'
  8CA9    D0                                RET     NC
  8CAA    FE 41                             CP      'A'
  8CAC    30 08                             JR      NC,D0.DZEIN
  8CAE    FE 3A                             CP      ':'
  8CB0    D0                                RET     NC
  8CB1    FE 30                             CP      '0'
  8CB3    30 01                             JR      NC,D0.DZEIN
  8CB5    C9                                RET
                                ;
  8CB6                          D0.AZEIN    EQU     $
  8CB6    CD C328               D0.DZEIN:   CALL    S1.AEIN
  8CB9    3E 01                             LD      A,1
  8CBB    32 B242                           LD      (TS.ZSMER),A
  8CBE    C9                                RET
                                ;
  8CBF    3A B23C               D0.OZEIN:   LD      A,(TS.TK)
  8CC2    FE 38                             CP      '8'
  8CC4    D0                                RET     NC
  8CC5    18 EF                             JR      D0.DZEIN
                                ;
  8CC7    3A B23C               D0.BZEIN:   LD      A,(TS.TK)
  8CCA    FE 32                             CP      '2'
  8CCC    D0                                RET     NC
  8CCD    18 E7                             JR      D0.DZEIN
                                ;
                                ;           PN      D103
                                ;****************************************************************
                                ;*                  D E B U G   ---   Programm   MEMO           '
                                ;*   Version        --------------------------------------------*
                                ;*                  Programmierer: Marcus Herbote--- IfR - OE-S *
                                ;*   V 1 . 0        --------------------------------------------*
                                ;*                  Stand        : 22.November 1982             *
                                ;****************************************************************
  8CCF    56 31 2E 30                       DB      'V1.0/22.11.82'
  8CD3    2F 32 32 2E           
  8CD7    31 31 2E 38           
  8CDB    32                    
  8CDC    8CDC                              DW      $
  8CDE    4D 45 4D 32                       DB      'MEM2'
  8CE2    CD C532                           CALL    S1.INPTR
  8CE5    23                                INC     HL
  8CE6    CD C5CC                           CALL    S1.HBKON
  8CE9    5F                                LD      E,A
  8CEA    AF                                XOR     A                   ;Merker fuer Rueckkehr ins System
                                ;****************************************************************
                                ;*                  Eintrittspunkt vom DEBUG - Steuerprogramm   *
                                ;****************************************************************
  8CEB    F5                    D1.MEMO:    PUSH    AF
  8CEC    ED 53 B292                        LD      (S2.DMANF),DE
  8CF0    ED 53 B294                        LD      (S2.DMCUR),DE
  8CF4    AF                                XOR     A
  8CF5    32 B2AA                           LD      (S2.DM2),A
'Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-36


  8CF8    21 0000                           LD      HL,0                ;Bereich auf 0000 bis 0000 setzen
  8CFB    22 B296                           LD      (S2.DMBA),HL
  8CFE    22 B298                           LD      (S2.DMBE),HL
  8D01    21 0B00                           LD      HL,00B00H           ;ZPOS = 0 , SPOS = 11
  8D04    22 B18C                           LD      (MS.ZPOS),HL
  8D07    3E 18                             LD      A,24
  8D09    32 B198                           LD      (MS.CMD),A
  8D0C    06 26                             LD      B,38
  8D0E    21 8D16                           LD      HL,$+8
  8D11    CD CB10                           CALL    MO.MONI
  8D14    18 26                             JR      $+40
                                ;
  8D16    4D 65 6D 6F                       DB      'Memory Display and Change Version 1.0'
  8D1A    72 79 20 44           
  8D1E    69 73 70 6C           
  8D22    61 79 20 61           
  8D26    6E 64 20 43           
  8D2A    68 61 6E 67           
  8D2E    65 20 56 65           
  8D32    72 73 69 6F           
  8D36    6E 20 31 2E           
  8D3A    30                    
  8D3B    21 0015                           LD      HL,00015H           ;ZPOS = 21 , SPOS = 0
  8D3E    22 B18C                           LD      (MS.ZPOS),HL
  8D41    06 3A                             LD      B,58
  8D43    21 8D4B                           LD      HL,$+8
  8D46    CD CB10                           CALL    MO.MONI
  8D49    18 3A                             JR      $+60
                                ;
  8D4B    43 75 72 73                       DB      'Cursorposition: .... '
  8D4F    6F 72 70 6F           
  8D53    73 69 74 69           
  8D57    6F 6E 3A 20           
  8D5B    2E 2E 2E 2E           
  8D5F    20                    
  8D60    42 65 72 65                       DB      'Bereichanfang:	'
  8D64    69 63 68 61           
  8D68    6E 66 61 6E           
  8D6C    67 3A 09              
  8D6F    42 65 72 65                       DB      'Bereichende: ....'
  8D73    69 63 68 65           
  8D77    6E 64 65 3A           
  8D7B    20 2E 2E 2E           
  8D7F    2E                    
  8D80    CD 91B0                           CALL    DMB
  8D83    CD 9204                           CALL    DMCP
  8D86    CD 920F                           CALL    DMBAP
  8D89    CD 921A                           CALL    DMBEP
  8D8C    21 0802                           LD      HL,00802H           ;ZPOS = 2 , SPOS = 8
  8D8F    22 B28E                           LD      (S2.DL),HL
  8D92    21 B197                           LD      HL,MS.DIRES
  8D95    CB EE                             SET     5, (HL)
  8D97    CD 9105                           CALL    DMUP4
                                            TITLE   'Tastaturdefinitionen'
                                            PAGE
'Tastaturdefinitionen'	MACRO-80 3.44	09-Dec-81	PAGE	1-37


                                
                                ;****************************************************************
                                ;*                  Tastaturdefinitionen                        *
                                ;****************************************************************
  8D9A    CD D408                           CALL    TA.LOE
  8D9D    21 9225                           LD      HL,DMP4
  8DA0    22 B1A5                           LD      (TS.TAB1+6),HL
  8DA3    21 9235                           LD      HL,DMP5
  8DA6    22 B1A7                           LD      (TS.TAB1+8),HL
  8DA9    21 8DE0                           LD      HL,DMTAB
  8DAC    11 B1FF                           LD      DE,TS.TAB2
  8DAF    01 0034                           LD      BC,52
  8DB2    ED B0                             LDIR
  8DB4    3E A8                             LD      A,0A8H
  8DB6    32 B23F                           LD      (TS.SPMER),A
  8DB9    F1                                POP     AF
  8DBA    FE 00                             CP      0
  8DBC    28 0C                             JR      Z,MEMS
  8DBE    FE 01                             CP      1
  8DC0    28 09                             JR      Z,MEMD
  8DC2    FE 02                             CP      2
  8DC4    28 0C                             JR      Z,MEMR
  8DC6    FE 03                             CP      3
  8DC8    28 0F                             JR      Z,MEMU
  8DCA    C9                    MEMS:       RET
  8DCB    21 801C               MEMD:       LD      HL,D0.DD
  8DCE    22 B21D                           LD      (TS.TAB3+6),HL
  8DD1    C9                                RET
  8DD2    21 8663               MEMR:       LD      HL,D0.RGDC
  8DD5    22 B21D                           LD      (TS.TAB3+6),HL
  8DD8    C9                                RET
  8DD9    21 8663               MEMU:       LD      HL,D0.UCPU
  8DDC    22 B21D                           LD      (TS.TAB3+6),HL
  8DDF    C9                                RET
                                ;****************************************************************
                                ;*                  Tastenroutinen-Adress-Tabelle               *
                                ;****************************************************************
  8DE0    8F6B                  DMTAB:      DW      DMIM
  8DE2    0000                              DW      0
  8DE4    0000                              DW      0
  8DE6    0000                              DW      0
  8DE8    906F                              DW      DMSL                ;SCH LINKS
  8DEA    8E14                              DW      DMCN
  8DEC    90A3                              DW      DMSR                ;SCH RECHTS
  8DEE    8E85                              DW      DMCW
  8DF0    8EED                              DW      DMHOM
  8DF2    8EBE                              DW      DMCO
  8DF4    8F05                              DW      DMNZ
  8DF6    8E4D                              DW      DMCS
  8DF8    9052                              DW      DMN2H
  8DFA    9043                              DW      DMN3H
  8DFC    8F14                              DW      DMNQU
  8DFE    C114                              DW      S1.SYSTB
  8E00    0000                              DW      0
  8E02    0000                              DW      0
  8E04    8F49                              DW      DMPQU
  8E06    0000                              DW      0
  8E08    0000                              DW      0
  8E0A    0000                              DW      0
  8E0C    0000                              DW      0
  8E0E    8FB9                              DW      DMAH                ;EINA
'Tastaturdefinitionen'	MACRO-80 3.44	09-Dec-81	PAGE	1-38


  8E10    0000                              DW      0                   ;TABU
  8E12    0000                              DW      0                   ;NEW LINE
                                
                                            TITLE   'Cursortastenroutinen'
                                            PAGE
'Cursortastenroutinen'	MACRO-80 3.44	09-Dec-81	PAGE	1-39


                                
                                ;****************************************************************
                                ;*                  Cursortastenroutine:	DMCN                *
                                ;****************************************************************
  8E14    21 9135               DMCN:       LD      HL,DMRO
  8E17    22 B19A                           LD      (MS.RADR),HL
  8E1A    3E E2                             LD      A,0E2H
  8E1C    32 B197                           LD      (MS.DIRES),A
  8E1F    3E 15                             LD      A,21
  8E21    32 B198                           LD      (MS.CMD),A
  8E24    CD CB10                           CALL    MO.MONI
  8E27    3E E0                             LD      A,0E0H
  8E29    32 B197                           LD      (MS.DIRES),A
  8E2C    CD 90EC                           CALL    DMUP3
  8E2F    2A B294                           LD      HL,(S2.DMCUR)
  8E32    3A B240               	        LD      A,(TS.UMERK)
  8E35    B7                                OR      A
  8E36    20 10                             JR      NZ,DMCN2
  8E38    11 0010                           LD      DE,10H
  8E3B    ED 52                 DMCN1:      SBC     HL,DE
  8E3D    22 B294                           LD      (S2.DMCUR),HL
  8E40    CD 9204                           CALL    DMCP
  8E43    CD 9105                           CALL    DMUP4
  8E46    18 36                             JR      DMCS3
                                ;
  8E48    11 0040               DMCN2:      LD      DE,40H
  8E4B    18 EE                             JR      DMCN1
                                ;****************************************************************
                                ;*                  Cursortastenroutine:	DMCS                *
                                ;****************************************************************
  8E4D    21 915F               DMCS:       LD      HL,DMRU
  8E50    22 B19A                           LD      (MS.RADR),HL
  8E53    3E E6                             LD      A,0E6H
  8E55    32 B197                           LD      (MS.DIRES),A
  8E58    3E 15                             LD      A,21
  8E5A    32 B198                           LD      (MS.CMD),A
  8E5D    CD CB10                           CALL    MO.MONI
  8E60    3E E0                             LD      A,0E0H
  8E62    32 B197                           LD      (MS.DIRES),A
  8E65    CD 90EC                           CALL    DMUP3
  8E68    2A B294                           LD      HL,(S2.DMCUR)
  8E6B    3A B240                           LD      A,(TS.UMERK)
  8E6E    B7                                OR      A
  8E6F    20 0F                             JR      NZ,DMCS2
  8E71    11 0010                           LD      DE,10H
  8E74    19                    DMCS1:      ADD     HL,DE
  8E75    22 B294                           LD      (S2.DMCUR),HL
  8E78    CD 9204                           CALL    DMCP
  8E7B    CD 9105                           CALL    DMUP4
  8E7E    18 3C                 DMCS3:      JR      DMCW2
                                ;
  8E80    11 0040               DMCS2:      LD      DE,40H
  8E83    18 EF                             JR      DMCS1
                                ;
                                            PAGE
'Cursortastenroutinen'	MACRO-80 3.44	09-Dec-81	PAGE	1-40


                                
                                ;****************************************************************
                                ;*                  Cursortastenroutine:	DMCW                *
                                ;****************************************************************
  8E85    21 9135               DMCW:       LD      HL,DMRO
  8E88    22 B19A                           LD      (MS.RADR),HL
  8E8B    3E E4                             LD      A,0E4H
  8E8D    32 B197                           LD      (MS.DIRES),A
  8E90    3E 15                             LD      A,21
  8E92    32 B198                           LD      (MS.CMD),A
  8E95    CD CB10                           CALL    MO.MONI
  8E98    3A B240                           LD      A,(TS.UMERK)
  8E9B    B7                                OR      A
  8E9C    20 09                             JR      NZ,DMCW1
  8E9E    CD CB10                           CALL    MO.MONI
  8EA1    CD CB10                           CALL    MO.MONI
  8EA4    CD CB10                           CALL    MO.MONI
  8EA7    3E E0                 DMCW1:      LD      A,0E0H
  8EA9    32 B197                           LD      (MS.DIRES),A
  8EAC    CD 90EC                           CALL    DMUP3
  8EAF    2A B294                           LD      HL,(S2.DMCUR)
  8EB2    2B                                DEC     HL
  8EB3    22 B294                           LD      (S2.DMCUR),HL
  8EB6    CD 9204                           CALL    DMCP
  8EB9    CD 9105                           CALL    DMUP4
  8EBC    18 2D                 DMCW2:      JR      DMCO2
                                ;****************************************************************
                                ;*                  Cursortastenroutine:	DMCO                *
                                ;****************************************************************
  8EBE    21 915F               DMCO:       LD      HL,DMRU
  8EC1    22 B19A                           LD      (MS.RADR),HL
  8EC4    3E 15                             LD      A,21
  8EC6    32 B198                           LD      (MS.CMD),A
  8EC9    CD CB10                           CALL    MO.MONI
  8ECC    3A B240                           LD      A,(TS.UMERK)
  8ECF    B7                                OR      A
  8ED0    20 09                             JR      NZ,DMCO1
  8ED2    CD CB10                           CALL    MO.MONI
  8ED5    CD CB10                           CALL    MO.MONI
  8ED8    CD CB10                           CALL    MO.MONI
  8EDB    CD 90EC               DMCO1:      CALL    DMUP3
  8EDE    2A B294                           LD      HL,(S2.DMCUR)
  8EE1    23                                INC     HL
  8EE2    22 B294                           LD      (S2.DMCUR),HL
  8EE5    CD 9204                           CALL    DMCP
  8EE8    CD 9105                           CALL    DMUP4
  8EEB    18 54                 DMCO2:      JR      DMNQ4
                                ;
                                            PAGE
'Cursortastenroutinen'	MACRO-80 3.44	09-Dec-81	PAGE	1-41


                                
                                ;****************************************************************
                                ;*                  Cursortastenroutine:	DMHOM               *
                                ;****************************************************************
  8EED    3E 16                 DMHOM:      LD      A,22
  8EEF    32 B198                           LD      (MS.CMD),A
  8EF2    CD CB10                           CALL    MO.MONI
  8EF5    CD 90EC                           CALL    DMUP3
  8EF8    2A B292                           LD      HL,(S2.DMANF)
  8EFB    22 B294                           LD      (S2.DMCUR),HL
  8EFE    CD 9204                           CALL    DMCP
  8F01    CD 9105                           CALL    DMUP4
  8F04    C9                                RET
                                ;****************************************************************
                                ;*                  Cursortastenroutine:	DMNZ                *
                                ;****************************************************************
  8F05    3E 17                 DMNZ:       LD      A,23
  8F07    32 B198                           LD      (MS.CMD),A
  8F0A    CD CB10                           CALL    MO.MONI
  8F0D    CD 90EC                           CALL    DMUP3
  8F10    2A B292                           LD      HL,(S2.DMANF)
  8F13    C9                                RET
                                ;            
                                            TITLE   'Tastenroutinen : PQU / NQU '
                                            PAGE
'Tastenroutinen : PQU / NQU '	MACRO-80 3.44	09-Dec-81	PAGE	1-42


                                
                                ;****************************************************************
                                ;*                  Tastenroutine negative Quittierung          *
                                ;****************************************************************
  8F14    CD 90EC               DMNQU:      CALL    DMUP3
  8F17    2A B18C                           LD      HL,(MS.ZPOS)
  8F1A    E5                                PUSH    HL
  8F1B    3A B240                           LD      A,(TS.UMERK)
  8F1E    B7                                OR      A
  8F1F    20 23                             JR      NZ,DMNQ2
  8F21    11 0100                           LD      DE,100H
  8F24    2A B292               DMNQ1:      LD      HL,(S2.DMANF)
  8F27    ED 52                             SBC     HL,DE
  8F29    22 B292                           LD      (S2.DMANF),HL
  8F2C    2A B294                           LD      HL,(S2.DMCUR)
  8F2F    ED 52                             SBC     HL,DE
  8F31    22 B294               DMNQ3:      LD      (S2.DMCUR),HL
  8F34    CD 91B0                           CALL    DMB
  8F37    CD 9204                           CALL    DMCP
  8F3A    E1                                POP     HL
  8F3B    22 B18C                           LD      (MS.ZPOS),HL
  8F3E    CD 9105                           CALL    DMUP4
  8F41    C3 8FDB               DMNQ4:      JP      DMAH3
                                ;
  8F44    11 0400               DMNQ2:      LD      DE,400H
  8F47    18 DB                             JR      DMNQ1
                                ;****************************************************************
                                ;*                  Tastenroutine positive Quittierung          *
                                ;****************************************************************
  8F49    CD 90EC               DMPQU:      CALL    DMUP3
  8F4C    2A B18C                           LD      HL,(MS.ZPOS)
  8F4F    E5                                PUSH    HL
  8F50    3A B240                           LD      A,(TS.UMERK)
  8F53    B7                                OR      A
  8F54    20 10                             JR      NZ,DMPQ2
  8F56    11 0100                           LD      DE,100H
  8F59    2A B292               DMPQ1:      LD      HL,(S2.DMANF)
  8F5C    19                                ADD     HL,DE
  8F5D    22 B292                           LD      (S2.DMANF),HL
  8F60    2A B294                           LD      HL,(S2.DMCUR)
  8F63    19                                ADD     HL,DE
  8F64    18 CB                             JR      DMNQ3
  8F66    11 0400               DMPQ2:      LD      DE,400H
  8F69    18 EE                             JR      DMPQ1
                                ;
                                            TITLE   'Tastenroutine: DMIM '
                                            PAGE
'Tastenroutine: DMIM '	MACRO-80 3.44	09-Dec-81	PAGE	1-43


                                
                                ;****************************************************************
                                ;*                  Tastenroutine   insert mode                 *
                                ;****************************************************************
  8F6B    CD 90EC               DMIM:       CALL    DMUP3               ;Umschalten alpha <==> hexa
  8F6E    2A B294                           LD      HL,(S2.DMCUR)
  8F71    22 B292                           LD      (S2.DMANF),HL
  8F74    CD 91B0                           CALL    DMB
  8F77    CD 9204                           CALL    DMCP
  8F7A    21 0802                           LD      HL,00802H           ;ZPOS = 2 , SPOS = 8
  8F7D    22 B28E                           LD      (S2.DL),HL
  8F80    CD 9105                           CALL    DMUP4
  8F83    3A B240                           LD      A,(TS.UMERK)
  8F86    B7                                OR      A
  8F87    20 18                             JR      NZ,DMIM1
  8F89    21 8FB9                           LD      HL,DMAH
  8F8C    22 B22D                           LD      (TS.EINA),HL
  8F8F    21 9052                           LD      HL,DMN2H
  8F92    22 B217                           LD      (TS.TAB3),HL
  8F95    21 9043                           LD      HL,DMN3H
  8F98    22 B219                           LD      (TS.TAB3+2),HL
  8F9B    3E A8                             LD      A,0A8H
  8F9D    32 B23F                           LD      (TS.SPMER),A
  8FA0    C9                                RET
                                ;
  8FA1    21 9028               DMIM1:      LD      HL,DMAA
  8FA4    22 B22D                           LD      (TS.EINA),HL
  8FA7    21 9068                           LD      HL,DMN2A
  8FAA    22 B217                           LD      (TS.TAB3),HL
  8FAD    21 9059                           LD      HL,DMN3A
  8FB0    22 B219                           LD      (TS.TAB3+2),HL
  8FB3    3E FF                             LD      A,0FFH
  8FB5    32 B23F                           LD      (TS.SPMER),A
  8FB8    C9                                RET
                                ;
                                            TITLE   'Tastenroutinen: DMAH/DMAA '
                                            PAGE
'Tastenroutinen: DMAH/DMAA '	MACRO-80 3.44	09-Dec-81	PAGE	1-44


                                
                                ;****************************************************************
                                ;*                  Tastenroutinen fuer alphanumerische Tasten  *
                                ;****************************************************************
  8FB9    3A B23C               DMAH:       LD      A,(TS.TK)
  8FBC    FE 47                             CP      'G'
  8FBE    D0                                RET     NC
  8FBF    FE 41                             CP      'A'
  8FC1    30 08                             JR      NC,DMAH1
  8FC3    FE 3A                             CP      ':'
  8FC5    D0                                RET     NC
  8FC6    FE 30                             CP      '0'
  8FC8    30 01                             JR      NC,DMAH1
  8FCA    C9                                RET
                                ;
  8FCB    3A B2AA               DMAH1:      LD      A,(S2.DM2)
  8FCE    B7                                OR      A
  8FCF    20 10                             JR      NZ,DMAH4
  8FD1    3C                                INC     A
  8FD2    32 B2AA                           LD      (S2.DM2),A
  8FD5    3A B23C                           LD      A,(TS.TK)
  8FD8    32 B2AB                           LD      (S2.DMH),A
  8FDB    3E 01                 DMAH3:      LD      A,1
  8FDD    32 B242                           LD      (TS.ZSMER),A
  8FE0    C9                                RET
                                ;
  8FE1    3A B23C               DMAH4:      LD      A,(TS.TK)
  8FE4    32 B2AC                           LD      (S2.DML),A
  8FE7    21 B2AB                           LD      HL,S2.DMH
  8FEA    CD C5CC                           CALL    S1.HBKON
  8FED    2A B294                           LD      HL,(S2.DMCUR)
  8FF0    77                                LD      (HL),A
  8FF1    7E                                LD      A,(HL)              ;???
  8FF2    21 B2AB                           LD      HL,S2.DMH
  8FF5    CD C5FF                           CALL    S1.BHKON
  8FF8    21 915F                           LD      HL,DMRU
  8FFB    22 B19A                           LD      (MS.RADR),HL
  8FFE    3E 18                             LD      A,24
  9000    32 B198                           LD      (MS.CMD),A
  9003    21 B2AB                           LD      HL,S2.DMH
  9006    06 02                             LD      B,2
  9008    CD CB10                           CALL    MO.MONI
  900B    3E 15                             LD      A,21
  900D    32 B198                           LD      (MS.CMD),A
  9010    CD CB10                           CALL    MO.MONI
  9013    CD CB10                           CALL    MO.MONI
  9016    2A B294               DMAH5:      LD      HL,(S2.DMCUR)
  9019    23                                INC     HL
  901A    22 B294                           LD      (S2.DMCUR),HL
  901D    CD 90EC                           CALL    DMUP3
  9020    CD 9204                           CALL    DMCP
  9023    CD 9105                           CALL    DMUP4
  9026    18 B3                             JR      DMAH3
                                            PAGE
'Tastenroutinen: DMAH/DMAA '	MACRO-80 3.44	09-Dec-81	PAGE	1-45


                                
                                ;****************************************************************
                                ;*                                                              *
                                ;****************************************************************
  9028    2A B294               DMAA:       LD      HL,(S2.DMCUR)
  902B    3A B199                           LD      A,(MS.TK)
  902E    77                                LD      (HL),A
  902F    7E                                LD      A,(HL)              ;???
  9030    32 B199                           LD      (MS.TK),A
  9033    3E 14                             LD      A,20
  9035    32 B198                           LD      (MS.CMD),A
  9038    21 915F                           LD      HL,DMRU
  903B    22 B19A                           LD      (MS.RADR),HL
  903E    CD CB10                           CALL    MO.MONI
  9041    18 D3                             JR      DMAH5
                                ;****************************************************************
                                ;*                                                              *
                                ;****************************************************************
  9043    3E 30                 DMN3H:      LD      A,'0'
  9045    32 B23C                           LD      (TS.TK),A
  9048    CD 8FB9                           CALL    DMAH
  904B    CD 8FB9               DMN31:      CALL    DMAH
  904E    CD 8FB9                           CALL    DMAH
  9051    C9                                RET
                                ;
  9052    3E 30                 DMN2H:      LD      A,'0'
  9054    32 B23C                           LD      (TS.TK),A
  9057    18 F2                             JR      DMN31
                                ;****************************************************************
                                ;*                                                              *
                                ;****************************************************************
  9059    3E 30                 DMN3A:      LD      A,'0'
  905B    32 B23C                           LD      (TS.TK),A
  905E    CD 9028                           CALL    DMAA
  9061    CD 9028               DMN32:      CALL    DMAA
  9064    CD 9028                           CALL    DMAA
  9067    C9                                RET
                                ;
  9068    3E 30                 DMN2A:      LD      A,'0'
  906A    32 B23C                           LD      (TS.TK),A
  906D    18 F2                             JR      DMN32
                                            TITLE   'Tastenroutinen: DMSL/DMSR '
                                            PAGE
'Tastenroutinen: DMSL/DMSR '	MACRO-80 3.44	09-Dec-81	PAGE	1-46


                                
                                ;****************************************************************
                                ;*                  Tastenroutine Schieben links                *
                                ;****************************************************************
  906F    2A B298               DMSL:       LD      HL,(S2.DMBE)
  9072    ED 5B B296                        LD      DE,(S2.DMBA)
  9076    B7                                OR      A
  9077    ED 52                             SBC     HL,DE
  9079    F8                                RET     M
  907A    23                                INC     HL
  907B    E5                                PUSH    HL
  907C    C1                                POP     BC
  907D    2A B296                           LD      HL,(S2.DMBA)
  9080    1B                                DEC     DE
  9081    ED B0                             LDIR
  9083    2A B296                           LD      HL,(S2.DMBA)
  9086    2B                                DEC     HL
  9087    22 B296                           LD      (S2.DMBA),HL
  908A    2A B298                           LD      HL, (S2.DMBE)
  908D    2B                                DEC     HL
  908E    22 B298                           LD      (S2.DMBE),HL
  9091    CD 90EC               DMSL1:      CALL    DMUP3
  9094    CD 91B0                           CALL    DMB
  9097    CD 920F                           CALL    DMBAP
  909A    CD 921A                           CALL    DMBEP
  909D    CD 9105                           CALL    DMUP4
  90A0    C3 8FDB                           JP      DMAH3
                                ;****************************************************************
                                ;*                  Tastenroutine Schieben rechts               *
                                ;****************************************************************
  90A3    2A B298               DMSR:       LD      HL,(S2.DMBE)
  90A6    ED 5B B296                        LD      DE,(S2.DMBA)
  90AA    B7                                OR      A
  90AB    ED 52                             SBC     HL,DE
  90AD    F8                                RET     M
  90AE    23                                INC     HL
  90AF    E5                                PUSH    HL
  90B0    C1                                POP     BC
  90B1    2A B298                           LD      HL,(S2.DMBE)
  90B4    ED 5B B298                        LD      DE,(S2.DMBE)
  90B8    13                                INC     DE
  90B9    ED B8                             LDDR
  90BB    2A B296                           LD      HL,(S2.DMBA)
  90BE    23                                INC     HL
  90BF    22 B296                           LD      (S2.DMBA),HL
  90C2    2A B298                           LD      HL,(S2.DMBE)
  90C5    23                                INC     HL
  90C6    22 B298                           LD      (S2.DMBE),HL
  90C9    18 C6                             JR      DMSL1
                                ;
                                            TITLE   'MEMO -- Unterprogramme'
                                            PAGE
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-47


                                
                                ;****************************************************************
                                ;*                                                              *
                                ;****************************************************************
  90CB    E5                    DMUP1:      PUSH    HL                  ;Zieladresse   Zeile loeschen
  90CC    D1                                POP     DE
  90CD    D5                                PUSH    DE
  90CE    13                                INC     DE
  90CF    36 20                             LD      (HL),' '
  90D1    ED 4B B193                        LD      BC,(MS.SPANZ)
  90D5    06 00                             LD      B,0
  90D7    ED B0                             LDIR
  90D9    E1                                POP     HL
  90DA    ED 5B B29A                        LD      DE,(S2.DM1)         ;Zeilenadresse aufbereiten
  90DE    7A                                LD      A,D
  90DF    CD C5FF                           CALL    S1.BHKON
  90E2    23                                INC     HL
  90E3    7B                                LD      A,E
  90E4    CD C5FF                           CALL    S1.BHKON
  90E7    01 0005                           LD      BC,5
  90EA    09                                ADD     HL,BC
  90EB    C9                                RET
                                ;****************************************************************
                                ;*                                                              *
                                ;****************************************************************
  90EC    21 B197               DMUP3:      LD      HL,MS.DIRES
  90EF    CB AE                             RES     5,(HL)
  90F1    2A B18C                           LD      HL,(MS.ZPOS)
  90F4    22 B28E                           LD      (S2.DL),HL
  90F7    3E 02                             LD      A,2
  90F9    32 B198                           LD      (MS.CMD),A
  90FC    CD CB10                           CALL    MO.MONI
  90FF    3E 18                             LD      A,24
  9101    32 B198                           LD      (MS.CMD),A
  9104    C9                                RET
                                ;****************************************************************
                                ;*                                                              *
                                ;****************************************************************
  9105    3A B240               DMUP4:      LD      A,(TS.UMERK)
  9108    B7                                OR      A
  9109    20 22                             JR      NZ,DMU2
  910B    21 0903                           LD      HL,00903H           ;ZMIN =  3 , SMIN =  9
  910E    11 4812                           LD      DE,04812H           ;ZMAX = 18 , SMAX = 72
  9111    22 B18E               DMU1:       LD      (MS.ZMIN),HL
  9114    ED 53 B190                        LD      (MS.ZMAX),DE
  9118    3E 18                             LD      A,24
  911A    32 B198                           LD      (MS.CMD),A
  911D    AF                                XOR     A
  911E    32 B2AA                           LD      (S2.DM2),A
  9121    2A B28E                           LD      HL,(S2.DL)
  9124    22 B18C                           LD      (MS.ZPOS),HL
  9127    21 B197                           LD      HL,MS.DIRES
  912A    CB EE                             SET     5, (HL)
  912C    C9                                RET
                                ;
  912D    21 0903               DMU2:       LD      HL,00903H           ;ZMIN =  3 , SMIN =  9
  9130    11 4812                           LD      DE,04812H           ;ZMAX = 18 , SMAX = 72
  9133    18 DC                             JR      DMU1
                                            PAGE
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-48


                                
                                ;****************************************************************
                                ;*                  Anschlussroutine Rollfunktion oben raus     *
                                ;****************************************************************
  9135    E5                    DMRO:       PUSH    HL
  9136    2A B292                           LD      HL,(S2.DMANF)
  9139    3A B240                           LD      A,(TS.UMERK)
  913C    B7                                OR      A
  913D    20 10                             JR      NZ,DMRO1
  913F    11 0010                           LD      DE,10H
  9142    ED 52                             SBC     HL,DE
  9144    22 B292                           LD      (S2.DMANF),HL
  9147    22 B29A                           LD      (S2.DM1),HL
  914A    E1                                POP     HL
  914B    CD 918F                           CALL    DMZH
  914E    C9                                RET
                                ;
  914F    11 0040               DMRO1:      LD      DE,40H
  9152    ED 52                             SBC     HL,DE
  9154    22 B292                           LD      (S2.DMANF),HL
  9157    22 B29A                           LD      (S2.DM1),HL
  915A    E1                                POP     HL
  915B    CD 91A3                           CALL    DMZA
  915E    C9                                RET
                                ;****************************************************************
                                ;*                  Anschlussroutine Rollfunktion unten raus    *
                                ;****************************************************************
  915F    E5                    DMRU:       PUSH    HL
  9160    2A B292                           LD      HL,(S2.DMANF)
  9163    3A B240                           LD      A,(TS.UMERK)
  9166    B7                                OR      A
  9167    20 13                             JR      NZ,DMRU1
  9169    11 0010                           LD      DE,10H
  916C    19                                ADD     HL,DE
  916D    22 B292                           LD      (S2.DMANF),HL
  9170    11 00F0                           LD      DE,0F0H
  9173    19                                ADD     HL,DE
  9174    22 B29A                           LD      (S2.DM1),HL
  9177    E1                                POP     HL
  9178    CD 918F                           CALL    DMZH
  917B    C9                                RET
                                ;
  917C    11 0040               DMRU1:      LD      DE,40H
  917F    19                                ADD     HL,DE
  9180    22 B292                           LD      (S2.DMANF),HL
  9183    11 03C0                           LD      DE,03C0H
  9186    19                                ADD     HL,DE
  9187    22 B29A                           LD      (S2.DM1),HL
  918A    E1                                POP     HL
  918B    CD 91A3                           CALL    DMZA
  918E    C9                                RET
                                            PAGE
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-49


                                
                                ;****************************************************************
                                ;*                  16 Byte hexadezimal aufbereiten             *
                                ;****************************************************************
  918F    CD 90CB               DMZH:       CALL    DMUP1
  9192    06 10                             LD      B,16
  9194    1A                    DMZH1:      LD      A,(DE)
  9195    CD C5FF                           CALL    S1.BHKON
  9198    23                                INC     HL
  9199    23                                INC     HL
  919A    23                                INC     HL
  919B    13                                INC     DE
  919C    10 F6                             DJNZ    DMZH1
  919E    ED 53 B29A                        LD      (S2.DM1),DE
  91A2    C9                                RET
                                ;****************************************************************
                                ;*                  64 Byte alphanumerisch aufbereiten          *
                                ;****************************************************************
  91A3    CD 90CB               DMZA:       CALL    DMUP1
  91A6    EB                                EX      DE,HL
  91A7    01 0040                           LD      BC,64
  91AA    ED B0                             LDIR
  91AC    22 B29A                           LD      (S2.DM1),HL
  91AF    C9                                RET
                                ;****************************************************************
                                ;*                  gesamtes Bild aufbauen                      *
                                ;****************************************************************
  91B0    21 0002               DMB:        LD      HL,00002H
  91B3    22 B18C                           LD      (MS.ZPOS),HL
  91B6    ED 5B B292                        LD      DE,(S2.DMANF)
  91BA    ED 53 B29A                        LD      (S2.DM1),DE
  91BE    06 10                             LD      B,16
  91C0    C5                    DMB1:       PUSH    BC
  91C1    CD CF45                           CALL    MO.BWSE
  91C4    23                                INC     HL
  91C5    3A B240                           LD      A,(TS.UMERK)
  91C8    B7                                OR      A
  91C9    20 12                             JR      NZ,DMB3
  91CB    CD 918F                           CALL    DMZH
  91CE    CD CF45               DMB2:       CALL    MO.BWSE
  91D1    23                                INC     HL
  91D2    3A B193                           LD      A,(MS.SPANZ)
  91D5    47                                LD      B,A
  91D6    CD CB10                           CALL    MO.MONI
  91D9    C1                                POP     BC
  91DA    10 E4                             DJNZ    DMB1
  91DC    C9                                RET
                                ;
  91DD    CD 91A3               DMB3:       CALL    DMZA
  91E0    18 EC                             JR      DMB2
                                            PAGE
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-50


                                
                                ;****************************************************************
                                ;*                  Anzeige einer Adresse                       *
                                ;****************************************************************
  91E2    ED 53 B29A            DMADR:      LD      (S2.DM1),DE
  91E6    22 B18C                           LD      (MS.ZPOS),HL
  91E9    CD CF45                           CALL    MO.BWSE
  91EC    23                                INC     HL
  91ED    ED 5B B29A                        LD      DE,(S2.DM1)
  91F1    7A                                LD      A,D
  91F2    CD C5FF                           CALL    S1.BHKON
  91F5    23                                INC     HL
  91F6    7B                                LD      A,E
  91F7    CD C5FF                           CALL    S1.BHKON
  91FA    CD CF45                           CALL    MO.BWSE
  91FD    23                                INC     HL
  91FE    06 04                             LD      B,4
  9200    CD CB10                           CALL    MO.MONI
  9203    C9                                RET
                                ;****************************************************************
                                ;*                  Anzeige der Cursorposition                  *
                                ;****************************************************************
  9204    ED 5B B294            DMCP:       LD      DE, (S2.DMCUR)
  9208    21 1015                           LD      HL,01015H           ;ZPOS = 21 , SPOS = 16
  920B    CD 91E2                           CALL    DMADR
  920E    C9                                RET
                                ;****************************************************************
                                ;*                  Anzeige des Bereichanfangs                  *
                                ;****************************************************************
  920F    ED 5B B296            DMBAP:      LD      DE,(S2.DMBA)
  9213    21 2415                           LD      HL,02415H           ;ZPOS = 21 , SPOS = 36
  9216    CD 91E2                           CALL    DMADR
  9219    C9                                RET
                                ;****************************************************************
                                ;*                  Anzeige des Bereichendes                    *
                                ;****************************************************************
  921A    ED 5B B298            DMBEP:      LD      DE, (S2.DMBE)
  921E    21 3615                           LD      HL,03615H           ;ZPOS = 21 , SPOS = 54
  9221    CD 91E2                           CALL    DMADR
  9224    C9                                RET
                                ;****************************************************************
                                ;*                                                              *
                                ;****************************************************************
  9225    2A B294               DMP4:       LD      HL,(S2.DMCUR)
  9228    22 B296                           LD      (S2.DMBA),HL
  922B    CD 90EC                           CALL    DMUP3
  922E    CD 920F                           CALL    DMBAP
  9231    CD 9105                           CALL    DMUP4
  9234    C9                                RET
                                ;
  9235    2A B294               DMP5:       LD      HL,(S2.DMCUR)
  9238    22 B298                           LD      (S2.DMBE),HL
  923B    CD 90EC                           CALL    DMUP3
  923E    CD 921A                           CALL    DMBEP
  9241    CD 9105                           CALL    DMUP4
  9244    C9                                RET
                                ;
                                ;
                                ;
                                ;           END
                                            .DEPHASE
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	1-51


                                ;
                                            END
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	S


Macros:

Symbols:
8C7A 	D0.AD1          8C8F 	D0.AD2          831F 	D0.ADD          
8328 	D0.ADD1         832A 	D0.ADPQ1        8342 	D0.ADPQ2        
8C4F 	D0.AH1          8C61 	D0.AH2          8AAA 	D0.AL           
8B9B 	D0.ALA          8B72 	D0.ALA1         8BA7 	D0.ALA2         
8B71 	D0.ALB1         8B71 	D0.ALB2         8B3F 	D0.ALD          
8B1B 	D0.ALD1         8B4B 	D0.ALD2         8AE9 	D0.ALH          
8AC5 	D0.ALH1         8AF5 	D0.ALH2         8B71 	D0.ALO1         
8B71 	D0.ALO2         8AB1 	D0.ALTAB        8A09 	D0.AS           
8A81 	D0.ASA1         8A94 	D0.ASA2         8AA9 	D0.ASB1         
8AA9 	D0.ASB2         8A53 	D0.ASD1         8A6A 	D0.ASD2         
8A24 	D0.ASH1         8A3A 	D0.ASH2         8AA9 	D0.ASO1         
8AA9 	D0.ASO2         8A10 	D0.ASTAB        8BDE 	D0.AW           
8CB6 	D0.AZEIN        8CC7 	D0.BZEIN        8640 	D0.CADR         
866D 	D0.CHK          8670 	D0.CHK1         8645 	D0.CHOM         
863C 	D0.CON          801C 	D0.DD           8099 	D0.DDPT         
80BB 	D0.DDPT2        80C5 	D0.DDPT3        8185 	D0.DDPTB        
8734 	D0.DDU01        873B 	D0.DDU02        8741 	D0.DDU03        
874C 	D0.DDU04        8756 	D0.DDU05        8790 	D0.DDU06        
87A8 	D0.DDU07        87C7 	D0.DDU08        8824 	D0.DDU09        
8829 	D0.DDU10        883A 	D0.DDU11        8845 	D0.DDU12        
8855 	D0.DDU13        885A 	D0.DDU14        886F 	D0.DDU15        
8878 	D0.DDU16        8773 	D0.DDU17        88A6 	D0.DDU18        
88CA 	D0.DDU19        88DD 	D0.DDU20        88E7 	D0.DDU21        
88F2 	D0.DDU22        88F4 	D0.DDU23        8902 	D0.DDU24        
8911 	D0.DDU25        8936 	D0.DDU26        8947 	D0.DDU27        
894D 	D0.DDU28        896A 	D0.DDU30        89FD 	D0.DDU31        
8CB6 	D0.DZEIN        8CA4 	D0.HZEIN        824F 	D0.IN           
8258 	D0.IN1          8262 	D0.IN2          8272 	D0.INPQ         
8662 	D0.LOAD         83C6 	D0.MEDC         83CF 	D0.MEDC1        
83D1 	D0.MEPQ         8C37 	D0.MO01         82C0 	D0.OUPQ1        
82E7 	D0.OUPQ2        82B5 	D0.OUT          82BE 	D0.OUT1         
8CBF 	D0.OZEIN        8712 	D0.PQ14         845B 	D0.PR1          
8564 	D0.PRF          855C 	D0.PRF1         8547 	D0.PRK          
854A 	D0.PRK1         857B 	D0.PRL          8584 	D0.PRL1         
8595 	D0.PRL2         85AF 	D0.PRL3         8529 	D0.PROM         
85B3 	D0.PRP          85CB 	D0.PRP2         85DB 	D0.PRP3         
8587 	D0.PRPQ1        85BE 	D0.PRPQ2        8557 	D0.PRR          
8463 	D0.PRT1         8523 	D0.PRT2         86AD 	D0.PRU11        
86BF 	D0.PRU21        86C4 	D0.PRU22        86CF 	D0.PRU31        
86D5 	D0.PRU32        86EB 	D0.PRU33        8704 	D0.PRU41        
86A6 	D0.PRUP1        86B3 	D0.PRUP2        86CD 	D0.PRUP3        
86FE 	D0.PRUP4        85EA 	D0.RAMT         85F6 	D0.RAMT1        
862B 	D0.RAMT2        8662 	D0.RCDC         8662 	D0.REAS         
8663 	D0.RGDC         8416 	D0.ROM1         840D 	D0.ROMT         
83ED 	D0.RT1          83F5 	D0.RT2          83FD 	D0.RT3          
8418 	D0.RTPQ1        8433 	D0.RTPQ2        8662 	D0.SAVE         
8380 	D0.SBPQ1        8398 	D0.SBPQ2        8375 	D0.SUB          
837E 	D0.SUB1         8BEB 	D0.TA01         8C04 	D0.TA02         
8C21 	D0.TA03         8C2A 	D0.TA04         830E 	D0.TAD1         
8316 	D0.TAD2         8245 	D0.TIN1         82AD 	D0.TIO1         
83BE 	D0.TME          82A5 	D0.TOUT1        824D 	D0.TPQ          
8366 	D0.TSB1         836F 	D0.TSB2         8663 	D0.UCPU         
8CEB 	D1.MEMO         8068 	DD1             9028 	DMAA            
91E2 	DMADR           8FB9 	DMAH            8FCB 	DMAH1           
8FDB 	DMAH3           8FE1 	DMAH4           9016 	DMAH5           
91B0 	DMB             91C0 	DMB1            91CE 	DMB2            
91DD 	DMB3            920F 	DMBAP           921A 	DMBEP           
8E14 	DMCN            8E3B 	DMCN1           8E48 	DMCN2           
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	S-1


8EBE 	DMCO            8EDB 	DMCO1           8EEB 	DMCO2           
9204 	DMCP            8E4D 	DMCS            8E74 	DMCS1           
8E80 	DMCS2           8E7E 	DMCS3           8E85 	DMCW            
8EA7 	DMCW1           8EBC 	DMCW2           8EED 	DMHOM           
8F6B 	DMIM            8FA1 	DMIM1           9068 	DMN2A           
9052 	DMN2H           904B 	DMN31           9061 	DMN32           
9059 	DMN3A           9043 	DMN3H           8F24 	DMNQ1           
8F44 	DMNQ2           8F31 	DMNQ3           8F41 	DMNQ4           
8F14 	DMNQU           8F05 	DMNZ            9225 	DMP4            
9235 	DMP5            8F59 	DMPQ1           8F66 	DMPQ2           
8F49 	DMPQU           9135 	DMRO            914F 	DMRO1           
915F 	DMRU            917C 	DMRU1           906F 	DMSL            
9091 	DMSL1           90A3 	DMSR            8DE0 	DMTAB           
9111 	DMU1            912D 	DMU2            90CB 	DMUP1           
90EC 	DMUP3           9105 	DMUP4           91A3 	DMZA            
918F 	DMZH            9194 	DMZH1           D576 	K1.ARBT         
D548 	K1.ARMB         D58F 	K1.BLKM         D581 	K1.BLKP         
D5CE 	K1.BM           D5D5 	K1.F17          D7EB 	K1.GNLMN        
D7B1 	K1.GNLP         D7B3 	K1.GNLPN        D725 	K1.GNRA         
D85B 	K1.GNRD         D708 	K1.GNRE         D780 	K1.GNRM         
D765 	K1.GNRP         D740 	K1.GNRW         D8EF 	K1.GNRWR        
D6B1 	K1.GNSTS        D8CB 	K1.GNWR         D5C1 	K1.LHLBC        
D870 	K1.PUFT         D5AB 	K1.RCZM         D5B9 	K1.RCZN         
D59D 	K1.RCZP         D5ED 	K1.RGL1         D5FE 	K1.RGL2         
B136 	K2.FRADR        B134 	K2.SKADR        DECC 	LO.EIN          
E239 	LO.EIN1         8DCB 	MEMD            8DD2 	MEMR            
8DCA 	MEMS            8DD9 	MEMU            CF45 	MO.BWSE         
CB3F 	MO.BWSUS        CB10 	MO.MONI         CF4C 	MO.PNSP         
CD99 	MO.ROLL         B194 	MS.BWSA         B198 	MS.CMD          
B19E 	MS.CZEIT        B196 	MS.DIRDEL       B197 	MS.DIRES        
B19D 	MS.MCUR         B19C 	MS.MCZ          B19A 	MS.RADR         
B191 	MS.SMAX         B18F 	MS.SMIN         B193 	MS.SPANZ        
B18B 	MS.SPOL         B18D 	MS.SPOS         B199 	MS.TK           
B192 	MS.ZANZ         B190 	MS.ZMAX         B18E 	MS.ZMIN         
B18A 	MS.ZPOL         B18C 	MS.ZPOS         A000 	S0.BWSA         
F5CF 	S0.BWSUS        BBF0 	S0.PFFA         B7E0 	S0.PFFI         
00E0 	S0.PROM         0050 	S0.SPANZ        0018 	S0.ZANZ         
C328 	S1.AEIN         C3BF 	S1.ANZEI        C8B0 	S1.ANZU1        
C8C0 	S1.ANZU2        C5FF 	S1.BHKON        C652 	S1.CHK          
C2D3 	S1.CNLS         C2B4 	S1.CNRS         C82E 	S1.DB111        
C86E 	S1.EINDB        C5CC 	S1.HBKON        C54E 	S1.HDI          
C995 	S1.HXN1         C592 	S1.IDH          C532 	S1.INPTR        
C935 	S1.MEAA         C9E4 	S1.MEAU2        C334 	S1.NN           
C345 	S1.NNN          C02D 	S1.SM           C8CD 	S1.SYDB2        
C114 	S1.SYSTB        B26E 	S2.AADR         B28A 	S2.AFOR         
B28B 	S2.BZ           B263 	S2.CST          B2B8 	S2.DDEI         
B28F 	S2.DH           B28E 	S2.DL           B29A 	S2.DM1          
B2AA 	S2.DM2          B292 	S2.DMANF        B296 	S2.DMBA         
B298 	S2.DMBE         B294 	S2.DMCUR        B2AB 	S2.DMH          
B2AC 	S2.DML          B26B 	S2.DNR          B264 	S2.IOC          
B270 	S2.KADR         B290 	S2.PAR1         B265 	S2.PRGN         
B26C 	S2.RBBR         B2AF 	S2.S1           B2B0 	S2.S2           
B2AD 	S2.SMHL         B273 	S2.SP1          B274 	S2.SP2          
B275 	S2.SP3          B28C 	S2.TE           B276 	S2.TRB          
B272 	S2.ZP           B262 	S2.ZZ           E657 	S9.CIN          
E6A6 	S9.CON          E68B 	S9.CSTSX        EE78 	S9.LOAD         
EE58 	S9.SAVE         D408 	TA.LOE          D420 	TA.LOES         
B249 	TS.BFOL1        B24B 	TS.BFOL2        B22D 	TS.EINA         
B23E 	TS.EMERK        B241 	TS.KGMER        B248 	TS.MBF          
B247 	TS.MIO          B231 	TS.NEWL         B23B 	TS.PTAST        
B23D 	TS.PTK          B23F 	TS.SPMER        B24D 	TS.STACK        
B19F 	TS.TAB1         B1FF 	TS.TAB2         B217 	TS.TAB3         
'MEMO -- Unterprogramme'	MACRO-80 3.44	09-Dec-81	PAGE	S-2


B223 	TS.TAB4         B233 	TS.TAB5         B22F 	TS.TABU         
B23C 	TS.TK           B240 	TS.UMERK        B245 	TS.ZEI21        
B243 	TS.ZEIT1        B244 	TS.ZEIT2        B242 	TS.ZSMER        
B246 	TS.ZSTC         



No Fatal error(s)


