        MACRO-80 3.44   09-Dec-81       PAGE    1


  0000                          false   equ     0
  FFFF                          true    equ     not false
  000D                          cr      equ     0dh
  000A                          lf      equ     0ah
                                  
  FFFF                          s1eq    equ     true            ; generierung der datei "S1.COM"
  FFFF                          pipeq   equ     true            ; generierung der datei "A:PIP.SUB"
                                ;
                                 if s1eq
                                 s1g    macro
                                 ;                                      ;       .phase 0000H
                                        ld      hl,0116H        ; LD    HL,MEM1
                                        ld      bc,005C0H       ; LD    BC,005C0H
                                        otir                    ; OTIR
                                        ld      hl,011BH        ; LD    HL,COPS
                                        ld      de,08000H       ; LD    DE,08000H
                                        ld      bc,0000FH       ; LD    BC,MEM3-B1
                                        jp      08000H          ; JP    08000H
                                ;                                       ;MEM1:
                                         defb   0F0H
                                         defb   001H    ; einen Bereich umschalten
                                         defb   008H    ; HS Bereich 
                                         defb   001H    ; Standardbereich
                                         defb   0FFH
                                ;                                       ;COPS:  .phase 08000H
                                ;                                       ;B1 EQU $
                                        ld      hl,0800BH       ; LD    HL,MEM2
                                        ld      bc,004C0H       ; LD    BC,004C0H
                                        otir                    ; OTIR
                                        jp      0000H           ; Sprung zur Version 1.2
                                ;                                       ;B2 EQU $
                                ;                                       ;MEM2:
                                        defb    0F0H
                                        defb    003H    ; Bereichsumschaltung
                                        defb    4               ; Sys_12
                                        defb    0FFH
                                        endm
                                 endif
                                ; 
                                 if pipeq
                                dirg    macro
                                        defb    '$1:pip p:=$1:xsub.com',cr,lf
                                        defb    'go p:s.com=$1:submit.com',cr,lf
                                        defb    'go p:=$1:kini.com',cr,lf
                                        defb    'go p:=$1:power.com',cr,lf
                                        defb    'go o:=$1:m80.com',cr,lf
                                        defb    'go o:=$1:l80.com',cr,lf
                                        defb    'era pip.sub',cr,lf
                                        defb    01ah
                                        endm
                                 endif
                                ;
                                
                                
                                
  0000*   21 8000                       ld      hl,8000h
  0003*   11 8001                       ld      de,8001h
  0006*   01 07FF                       ld      bc,7ffh
  0009*   36 E5                         ld      (hl),0e5h
  000B*   E5                            push    hl
  000C*   E5                            push    hl
  000D*   ED B0                         ldir    
        MACRO-80 3.44   09-Dec-81       PAGE    1-1


  000F*   E1                            pop     hl              ; verzeichnis fuer GO.COM (PIP.SUB)
  0010*   E5                            push    hl
  0011*   E5                            push    hl
  0012*   D1                            pop     de
  0013*   13                            inc     de
                                 if s1eq and pipeq
  0014*   01 005F                       ld      bc,5fh 
                                 endif
                                 if s1eq and not pipeq
                                        ld      bc,3fh
                                 endif
                                 if pipeq and not s1eq
                                        ld      bc,3fh
                                 endif
                                 if not s1eq and not pipeq
                                        ld      bc,1fh
                                 endif
  0017*   36 00                         ld      (hl),0
  0019*   ED B0                         ldir
                                
                                ; ===
  001B*   D1                            pop     de
  001C*   D5                            push    de
  001D*   21 006E*                      ld      hl,dirgo        ;Verzeichniseintrag fC<r 'GO.COM'
  0020*   01 000C                       ld      bc,12
  0023*   ED B0                         ldir
  0025*   E1                            pop     hl
                                
                                 if s1eq        ;Verzeichniseintrag fC<r 'S1.COM'
  0026*   11 0020                       ld      de,32
  0029*   19                            add     hl,de
  002A*   E5                            push    hl
  002B*   EB                            ex      de,hl   
  002C*   21 007A*                      ld      hl,dirs1
  002F*   01 0011                       ld      bc,17
  0032*   ED B0                         ldir
  0034*   E1                            pop     hl
                                 endif
                                
                                 if pipeq       ;Verzeichniseintrag fC<r 'PIP.SUB'
  0035*   11 0020                       ld      de,32
  0038*   19                            add     hl,de
  0039*   E5                            push    hl
  003A*   EB                            ex      de,hl
  003B*   21 00B3*                      ld      hl,dirgo1
  003E*   01 0011                       ld      bc,17
  0041*   ED B0                         ldir
  0043*   E1                            pop     hl
                                 endif
                                ; ===
  0044*   76                            halt
  0045*   11 0800                       ld      de,800h
                                 if s1eq        ;Daten fC<r 'S1.COM'
  0048*   E1                            pop     hl
  0049*   19                            add     hl,de
  004A*   E5                            push    hl
  004B*   EB                            ex      de,hl
  004C*   21 008B*                      ld      hl,dirs11
  004F*   01 0028                       ld      bc,dirs12-dirs11
  0052*   ED B0                         ldir
  0054*   3A 008A*                      ld      a,(dirs1+16)
  0057*   47                            ld      b,a
        MACRO-80 3.44   09-Dec-81       PAGE    1-2


  0058*   21 0000                       ld      hl,0
  005B*   11 0080                       ld      de,80H
  005E*                         s1a:
  005E*   19                            add     hl,de
  005F*   10 FD                         djnz    s1a
  0061*   EB                            ex      de,hl
                                 endif
                                
                                 if pipeq       ;Daten fC<r 'PIP.SUB'
  0062*   E1                            pop     hl
  0063*   19                            add     hl,de
  0064*   EB                            ex      de,hl
  0065*   21 00C4*                      ld      hl,dirg11
  0068*   01 008A                       ld      bc,dirg12-dirg11
  006B*   ED B0                         ldir
                                 endif
  006D*   76                            halt
                                ;
  006E*   00 47 4F 20           dirgo:  defb    0,'GO      ',0c3h,'OM'
  0072*   20 20 20 20           
  0076*   20 C3 4F 4D           
                                 if s1eq 
  007A*   00 53 31 20           dirs1:  defb    0,'S1      COM',0,0,0,2,2
  007E*   20 20 20 20           
  0082*   20 43 4F 4D           
  0086*   00 00 00 02           
  008A*   02                    
  008B*                         dirs11: s1g
  008B*   21 0116         +             ld      hl,0116H        ; LD    HL,MEM1
  008E*   01 05C0         +             ld      bc,005C0H       ; LD    BC,005C0H
  0091*   ED B3           +             otir                    ; OTIR
  0093*   21 011B         +             ld      hl,011BH        ; LD    HL,COPS
  0096*   11 8000         +             ld      de,08000H       ; LD    DE,08000H
  0099*   01 000F         +             ld      bc,0000FH       ; LD    BC,MEM3-B1
  009C*   C3 8000         +             jp      08000H          ; JP    08000H
  009F*   F0              +              defb   0F0H
  00A0*   01              +              defb   001H    ; einen Bereich umschalten
  00A1*   08              +              defb   008H    ; HS Bereich 
  00A2*   01              +              defb   001H    ; Standardbereich
  00A3*   FF              +              defb   0FFH
  00A4*   21 800B         +             ld      hl,0800BH       ; LD    HL,MEM2
  00A7*   01 04C0         +             ld      bc,004C0H       ; LD    BC,004C0H
  00AA*   ED B3           +             otir                    ; OTIR
  00AC*   C3 0000         +             jp      0000H           ; Sprung zur Version 1.2
  00AF*   F0              +             defb    0F0H
  00B0*   03              +             defb    003H    ; Bereichsumschaltung
  00B1*   04              +             defb    4               ; Sys_12
  00B2*   FF              +             defb    0FFH
  00B3*                         dirs12:
                                 endif
                                ;
                                 if pipeq
  00B3*   00 50 49 50           dirgo1: defb    0,'PIP     SUB',0,0,0,2,2
  00B7*   20 20 20 20           
  00BB*   20 53 55 42           
  00BF*   00 00 00 02           
  00C3*   02                    
  00C4*                         dirg11: dirg
  00C4*   24 31 3A 70     +             defb    '$1:pip p:=$1:xsub.com',cr,lf
  00C8*   69 70 20 70     +     
  00CC*   3A 3D 24 31     +     
  00D0*   3A 78 73 75     +     
        MACRO-80 3.44   09-Dec-81       PAGE    1-3


  00D4*   62 2E 63 6F     +     
  00D8*   6D 0D 0A        +     
  00DB*   67 6F 20 70     +             defb    'go p:s.com=$1:submit.com',cr,lf
  00DF*   3A 73 2E 63     +     
  00E3*   6F 6D 3D 24     +     
  00E7*   31 3A 73 75     +     
  00EB*   62 6D 69 74     +     
  00EF*   2E 63 6F 6D     +     
  00F3*   0D 0A           +     
  00F5*   67 6F 20 70     +             defb    'go p:=$1:kini.com',cr,lf
  00F9*   3A 3D 24 31     +     
  00FD*   3A 6B 69 6E     +     
  0101*   69 2E 63 6F     +     
  0105*   6D 0D 0A        +     
  0108*   67 6F 20 70     +             defb    'go p:=$1:power.com',cr,lf
  010C*   3A 3D 24 31     +     
  0110*   3A 70 6F 77     +     
  0114*   65 72 2E 63     +     
  0118*   6F 6D 0D 0A     +     
  011C*   67 6F 20 6F     +             defb    'go o:=$1:m80.com',cr,lf
  0120*   3A 3D 24 31     +     
  0124*   3A 6D 38 30     +     
  0128*   2E 63 6F 6D     +     
  012C*   0D 0A           +     
  012E*   67 6F 20 6F     +             defb    'go o:=$1:l80.com',cr,lf
  0132*   3A 3D 24 31     +     
  0136*   3A 6C 38 30     +     
  013A*   2E 63 6F 6D     +     
  013E*   0D 0A           +     
  0140*   65 72 61 20     +             defb    'era pip.sub',cr,lf
  0144*   70 69 70 2E     +     
  0148*   73 75 62 0D     +     
  014C*   0A              +     
  014D*   1A              +             defb    01ah
  014E*                         dirg12:
                                 endif
                                
                                    end
        MACRO-80 3.44   09-Dec-81       PAGE    S


Macros:
DIRG            S1G             

Symbols:
000D    CR              00C4*   DIRG11          014E*   DIRG12          
006E*   DIRGO           00B3*   DIRGO1          007A*   DIRS1           
008B*   DIRS11          00B3*   DIRS12          0000    FALSE           
000A    LF              FFFF    PIPEQ           005E*   S1A             
FFFF    S1EQ            FFFF    TRUE            



No Fatal error(s)

