;--------------------------\            ; Vorspann fuer BIN-Datei
            DB      0F0H                ; Startbyte ---> weitere BIN-Datei
            DB      'S21'               ;                Name der BIN-Datei
            DS      25,0
            DB      002H                ; HS-Bereich : 2
            DW      00000H              ; Ladeadresse: B000H
;--------------------------/

;	PN	BC11
;****************************************************************
;*               B  A  S  I  C   -   I n t e r p r e t e r      *
;*               -----------------------------------------------*
;*               reassembliert: M. Herbote --- K EAW  ZFT (WFT) *
;*               -----------------------------------------------*
;*               Stand        : 07.Juni 1984                    *
;****************************************************************

            PAGE    87
            INCLUDE incBC11a.MAC

            PAGE
            .PHASE  00000H
            INCLUDE incBC11b.MAC
            PAGE
;****************************************************************
;*               Systemroutinen - Sprungverteiler               *
;****************************************************************
BC.INIT:    JP      BC.J118
BC.RECOV:   JP      BC.J006
BC.USR:     JP      BC.J033
BC.CIN:     JP      0
BC.RIV:     JP      0
BC.CON:     JP      0
BC.WRTV:    JP      0
BC.LISTX:   JP      0
BC.CSTSX:   JP      0
BC.IOCHX:   JP      0
BC.IOSTX:   JP      0
BC.MEMCK:   JP      0
BC.TRAPX:   JP      0
BC.PAR:     JP      BC.C043
BC.RUCK:    JP      BC.J050
;****************************************************************
;*               T O K E N  -  Adresstabellen                   *
;****************************************************************
BC.TB1:     DW      BC.SGN
            DW      BC.INT
            DW      BC.ABS
            DW      BC.USR
            DW      BC.FRE
            DW      BC.INP
            DW      BC.POS
            DW      BC.SQR
            DW      BC.RND
            DW      BC.LOG
            DW      BC.EXP
            DW      BC.COS
            DW      BC.SIN
            DW      BC.TAN
            DW      BC.ATN
            DW      BC.PEEK
            DW      BC.LEN
            DW      BC.STRD
            DW      BC.VAL
            DW      BC.ASC
            DW      BC.CHRD
            DW      BC.LEFTD
            DW      BC.RGHTD
            DW      BC.MIDD
            DW      BC.LPOS
            DW      BC.INSTR

BC.TB2:     DB      79H                 ;TAB
            DW      24A7H
            DB      79H                 ;TO
            DW      1F8DH
            DB      7CH                 ;FN
            DW      213BH
            DB      7CH                 ;SPC
            DW      21BFH
            DB      7FH                 ;THEN
            DW      2A17H
            DB      50H                 ;NOT
            DW      0FBDH
            DB      46H                 ;STEP
            DW      0FBCH

BC.TB3:     DW      BC.END
            DW      BC.FOR
            DW      BC.NEXT
            DW      BC.DATA
            DW      BC.INPUT
            DW      BC.DIM
            DW      BC.READ
            DW      BC.LET
            DW      BC.GOTO
            DW      BC.FNEND
            DW      BC.IF
            DW      BC.REST
            DW      BC.GOSUB
            DW      BC.RETRN
            DW      BC.DATA+2           ;REM
            DW      BC.STOP
            DW      BC.OUT
            DW      BC.ON
            DW      BC.NULL
            DW      BC.WAIT
            DW      BC.DEF
            DW      BC.POKE
            DW      BC.PRINT
            DW      BC.PRINT            ;"?"
BC.GRF1:    DW      BC.INPUT            ;LISTEN
            DW      BC.CLEAR
            DW      BC.FNRTN
            DW      BC.SAVE
            DW      BC.DATA+2           ;"!"

BC.TB4:     DW      BC.DATA+2
            DW      BC.LPRNT
            DW      BC.TRACE
            DW      BC.LTRCE
            DW      BC.RANDO
            DW      BC.SWTCH
            DW      BC.LWDTH
            DW      BC.LNULL
            DW      BC.WIDTH
            DW      BC.LVAR
            DW      BC.LLVAR
BC.SVC1:    DW      BC.PRINT            ;SPEAK
            DW      BC.J004             ;"'"
            DW      BC.PREC
            DW      BC.CALL
            DW      BC.KILL
            DW      BC.EXCH
            DW      BC.LINE
            DW      BC.LOADG
            DW      BC.RUN
            DW      BC.LOAD
            DW      BC.NEW
            DW      BC.AUTO
            DW      BC.COPY
            DW      BC.ALODC
            DW      BC.AMRGC
            DW      BC.ALOAD
            DW      BC.AMRG
            DW      BC.ASAVE
            DW      BC.LIST
            DW      BC.LLIST
            DW      BC.RENB
            DW      BC.DELET
            DW      BC.EDIT
            DW      BC.CONT

            PAGE
BC.C001:    LD      HL,4
            ADD     HL,SP
            LD      BC,17
            LD      A,M
            INC     HL
            CP      081H
            RET     NZ
            LD      A,M
            INC     HL
            PUSH    HL
            LD      H,M
            LD      L,A
            LD      A,D
            OR      E
            EX      DE,HL
            JR      Z,$+09
            EX      DE,HL
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            POP     HL
            INC     HL
            RET     Z
            ADD     HL,BC
            JR      $-26

BC.C002:    CALL    BC.C005
            PUSH    BC
            EX      (SP),HL
            POP     BC
BC.C003:    OR      A
            PUSH    HL
            SBC     HL,DE
            PUSH    BC
            EX      (SP),HL
            POP     BC
            EX      DE,HL
            EX      (SP),HL
            INC     BC
            LDDR
            INC     HL
            INC     DE
            LD      B,D
            LD      C,E
            POP     DE
            RET

BC.C004:    PUSH    HL
            LD      HL,(BC.D026)
            LD      B,000H
            ADD     HL,BC
            ADD     HL,BC
            CALL    BC.C005
            POP     HL
            RET

BC.C005:    PUSH    DE
            EX      DE,HL
            LD      HL,0FFD8H
            ADD     HL,SP
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            EX      DE,HL
            POP     DE
            RET     NC
BC.J002:    LD      E,007H
            JR      $+47

BC.C006:    CP      M
            JP      Z,BC.C031
            JR      $+24

BC.J003:    LD      A,(BC.D016)
            OR      A
            JR      NZ,$+12
            POP     BC
            LD      HL,BC.D126
            CALL    BC.C027
            JP      BC.J018
            LD      HL,(BC.D014)
            LD      (BC.D019),HL
BC.J004:    LD      E,2
            DB      1
BC.J005:    LD      E,11
            DB      1
BC.J006:    LD      E,22
            DB      1
BC.J007:    LD      E,10
            DB      1
BC.J008:    LD      E,18
            DB      1
BC.J009:    LD      E,1
BC.J010:    CALL    BC.C014
            CALL    BC.C015
            CALL    BC.C048
            LD      HL,BC.D123
            DEC     E
            JR      Z,$+09
            BIT     7,M
            INC     HL
            JR      Z,$-03
            JR      $-08

BC.J011:    CALL    BC.C027
            LD      HL,(BC.D019)
            LD      A,H
            AND     L
            INC     A
            CALL    NZ,BC.C146
BC.J012:    CALL    BC.C015
            LD      (BC.D058),A
            CALL    BC.C047             ;"READY" ausgeben
BC.J013:    LD      HL,0FFFFH
            LD      (BC.D019),HL
            LD      A,(BC.D058)
            OR      A
            JR      Z,$+39
            LD      HL,(BC.D047)
            JP      M,BC.J068
            LD      DE,(BC.D048)
            ADD     HL,DE
            JP      C,BC.J049
BC.J014:    LD      (BC.D047),HL
            PUSH    HL
            CALL    BC.C147
            CALL    BC.C023
            CALL    BC.C022
            CALL    BC.C031
            POP     DE
            OR      A
            JR      Z,$-53
            SCF
            JR      $+12

            CALL    BC.C022             ;Zeile eingeben
            CALL    BC.C031
            INC     A
            DEC     A
            JR      Z,$-57
            PUSH    AF
            CP      003H
            JP      Z,BC.J031
            EXX
            LD      HL,BC.D058
            INC     M
            DEC     M
            EXX
BC.D067     EQU     $+2
BC.J015:    CALL    Z,BC.C045
            CP      ' '
            JR      NZ,$+03
            INC     HL
BC.J016:    PUSH    DE
            CALL    BC.C017             ;TOKEN  comprimieren
            LD      B,A
            POP     DE
            POP     AF
            JP      NC,BC.J025
            PUSH    DE
            PUSH    BC
            INC     HL
            LD      A,M
            OR      A
            JR      Z,$+14
            CP      020H
            JR      Z,$-07
            CP      009H
            JR      Z,$-11
            CP      00AH
            JR      Z,$-15
            PUSH    AF
            CALL    BC.C009
            PUSH    BC
            JR      NC,$+22
            EX      DE,HL
            LD      HL,(BC.D024)
            LD      A,(DE)
            LD      (BC),A
            INC     BC
            INC     DE
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            JR      NZ,$-10
            LD      (BC.D024),BC
            POP     DE
            POP     AF
            JR      Z,$+35
            LD      BC,(BC.D024)
            POP     HL
            ADD     HL,BC
            PUSH    HL
            CALL    BC.C002
            POP     HL
            LD      (BC.D024),HL
            EX      DE,HL
            LD      M,H
            INC     HL
            INC     HL
            POP     DE
            LD      M,E
            INC     HL
            LD      M,D
            INC     HL
            LD      DE,BC.D063
            LD      A,(DE)
            LD      M,A
            INC     HL
            INC     DE
            OR      A
            JR      NZ,$-05
BC.D068     EQU     $
BC.J017:    CALL    BC.C012
            INC     HL
            EX      DE,HL
            LD      HL,BC.J013
            PUSH    HL
BC.C007:    LD      H,D
            LD      L,E
            LD      A,M
            INC     HL
            OR      M
            RET     Z
            INC     HL
            INC     HL
            INC     HL
            XOR     A
            CP      M
            INC     HL
            JR      NZ,$-02
            EX      DE,HL
            LD      M,E
            INC     HL
            LD      M,D
            JR      $-18

BC.C008:    LD      DE,0
            PUSH    DE
            JR      Z,$+14
            POP     DE
            CALL    BC.C034
            PUSH    DE
            JR      Z,$+16
            LD      A,0A6H
            CALL    BC.C006
            LD      DE,0FFFFH
            CALL    NZ,BC.C034
            JP      NZ,BC.J004
            EX      DE,HL
            POP     DE
            EX      (SP),HL
            PUSH    HL
BC.C009:    LD      HL,(BC.D023)
BC.C010:    LD      B,H
            LD      C,L
            LD      A,M
            INC     HL
            OR      M
            DEC     HL
            RET     Z
            INC     HL
            INC     HL
            LD      A,M
            INC     HL
            LD      H,M
            LD      L,A
            SBC     HL,DE
            LD      H,B
            LD      L,C
            LD      A,M
            INC     HL
            LD      H,M
            LD      L,A
            CCF
            RET     Z
            CCF
            RET     NC
            EXX
            ADD     HL,DE
            EXX
            JR      $-28

            PAGE
;****************************************************************
;*               TOKEN - Routine:  N  E  W                      *
;****************************************************************
BC.NEW:     RET     NZ
BC.C011:    LD      HL,(BC.D023)        ;Quelltext-Anfang
            XOR     A
            LD      (BC.D052),A         ;(L)TRACE - Schalter
            LD      M,A
            INC     HL
            LD      M,A
            INC     HL
            LD      (BC.D024),HL        ;hochz. Adr. des Quellt.
                                        ;zeigt auf  3x 00H
BC.C012:    LD      HL,(BC.D023)
            DEC     HL
BC.C013:    LD      (BC.D017),HL        ;akt. Unterbrechungsadresse
            LD      HL,(BC.D006)        ;init. mit Beginn Zeichenkettenber.
            LD      (BC.D012),HL        ;-------------  "  --------------
            CALL    BC.C033
            LD      HL,(BC.D024)
            LD      (BC.D025),HL        ;1.freie Byte einf. Var.,Beginn dim. Var.
            LD      (BC.D026),HL        ;1.freie Byte dim.  Var.
BC.C014:    POP     BC
            LD      SP,(BC.D022)        ;akt. Stackpointer
            LD      HL,BC.D008
            LD      (BC.D007),HL
            XOR     A
            LD      H,A
            LD      L,A
            LD      (BC.D021),HL
            LD      (BC.D015),A
            LD      (BC.D055),A
            PUSH    HL
            PUSH    BC
BC.J018:    LD      HL,(BC.D017)
            RET

BC.C015:    XOR     A
            LD      (BC.D002),A         ;<>0  CON-Unterdr. bei CIN
BC.D069     EQU     $
BC.C016:    LD      IY,BC.CON
            LD      (BC.D040),IY        ;evtl. akt. L-Geraet
            LD      IY,BC.D041
            RET

BC.C017:    XOR     A                   ;Ersetzung Sprachelemente durch
            LD      (BC.D005),A         ;TOKEN
            LD      C,005H              ;HL  zeigt auf Eingabezeile
            LD      DE,BC.D063          ;DE  verkuerzte Zeile
BC.J019:    LD      A,M
            LD      B,A
            OR      A
            JP      Z,BC.J020
            CP      021H
            JR      C,$+81
            CP      022H
            JR      Z,$+125
            LD      A,(BC.D005)
            OR      A
            LD      B,A
            LD      A,M
            JR      NZ,$+69
            CP      030H
            JR      C,$+06
            CP      03AH
            JR      C,$+61
            PUSH    DE
            LD      DE,BC.D121
            PUSH    HL
            JR      $+04
            INC     HL
            INC     DE
            LD      A,(DE)
            OR      A
            JR      Z,$+39
            CP      020H
            JR      NZ,$+11
            INC     DE
            LD      A,M
            CP      020H
            JR      NZ,$+05
            INC     HL
            JR      $-06
            EX      DE,HL
            LD      A,(DE)
            CP      060H
            JR      C,$+04
            AND     05FH
            XOR     M
            AND     07FH
            EX      DE,HL
            JR      NZ,$+75
            LD      A,(DE)
            RLA
            JR      NC,$-35
            POP     AF
            LD      A,B
            OR      080H
            JR      $+10
            POP     HL
            LD      A,M
            CP      060H
            JR      C,$+04
            AND     05FH
            POP     DE
            EX      DE,HL
            CP      0C9H
            LD      M,03AH
            JR      NZ,$+04
            INC     C
            INC     HL
            EX      DE,HL
            INC     HL
            LD      (DE),A
            INC     DE
            INC     C
            SUB     03AH
            JR      Z,$+12
            CP      09BH
            LD      B,03AH
            JR      Z,$+19
            CP      049H
            JR      NZ,$+05
            LD      (BC.D005),A
            SUB     054H
            JR      Z,$+07
            SUB     00EH
            JP      NZ,BC.J019
            LD      B,A
            LD      A,M
            OR      A
            JR      Z,$+23
            CP      B
            JR      Z,$-46
            INC     HL
            LD      (DE),A
            INC     C
            INC     DE
            JR      $-11
            POP     HL
            PUSH    HL
            INC     B
            EX      DE,HL
            BIT     7,M
            INC     HL
            JR      Z,$-03
            EX      DE,HL
            JR      $-114

BC.J020:    LD      HL,BC.D062
            LD      (DE),A
            INC     DE
            LD      (DE),A
            INC     DE
            LD      (DE),A
            RET
            LD      A,B
            DEC     A
            OR      (IY+00)
            JR      Z,$+76
            CALL    BC.C025
            DJNZ    $+10
            CALL    BC.C025
            CALL    BC.C025
            JR      $+60
            DEC     HL
            LD      A,M
            CALL    BC.C024
            CALL    BC.C028
            CP      07FH
            JR      Z,$-20
            PUSH    AF
            CALL    BC.C025
            POP     AF
            JR      $+56

BC.C018:    LD      A,03FH
            CALL    BC.C026
BC.C019:    LD      A,03FH
            CALL    BC.C026
            CALL    BC.C023
            CALL    BC.C022
            INC     HL
            LD      A,M
            DEC     HL
            CP      003H
            RET

BC.C020:    CALL    BC.C016
BC.C021:    PUSH    AF
            LD      A,05EH
            CALL    BC.C026
            POP     AF
            OR      040H
            JR      $+115
            CALL    BC.C021
            CALL    BC.C050
BC.C022:    LD      HL,BC.D063          ;Eingabeschleife
            LD      B,001H              ;1B1H  ...  Eingabepuffer
            LD      A,B
            LD      (BC.D055),A
            CALL    BC.C028
            CP      007H
            JR      Z,$+62
            CP      00DH
            JP      Z,BC.J040
            CP      003H
            JP      Z,BC.J039
            CP      015H
            JR      Z,$-34
            CP      07FH
            JR      Z,$-113
            CP      012H
            JR      NZ,$+22
            CALL    BC.C021
            CALL    BC.C050
            LD      HL,BC.D063
            LD      C,B
            DEC     C
            JR      Z,$-40
            LD      A,M
            INC     HL
            CALL    BC.C024
            JR      $-08
            CP      009H
            JR      Z,$+16
            CP      00AH
            JR      NZ,$+08
            DEC     B
            JR      Z,$-67
            INC     B
            JR      $+06
            CP      020H
            JR      C,$-65
            LD      C,A
            LD      A,B
            CP      0FDH
            LD      A,007H
            JR      NC,$+06
            LD      A,C
            LD      M,A
            INC     HL
            INC     B
            CALL    BC.C024
            JR      $-82

BC.C023:    LD      A,' '               ;Zeichen ==> BWS
BC.C024:    CP      00AH
            JR      NZ,$+10
            CALL    BC.C048
            LD      A,00AH
            RET

BC.C025:    LD      A,'\'               ;'
BC.C026:    PUSH    BC
            LD      C,A
            LD      A,(BC.D002)
            OR      A
            JR      NZ,$+65
            LD      A,C
            CP      009H
            JR      NZ,$+41
            LD      A,(IY+01)
            AND     0F8H
            DEC     A
            CP      (IY+00)
            JR      C,$+25
            LD      A,(IY+00)
            AND     007H
            CPL
            ADD     A,009H
            LD      B,A
            LD      C,020H
            CALL    BC.D039
            INC     (IY+00)
            DJNZ    $-06
            LD      C,009H
            JR      $+26
            CALL    BC.C048
            JR      $-07
            CP      020H
            JR      C,$+14
            LD      A,(IY+00)
            CP      (IY+01)
            CALL    Z,BC.C048
            INC     (IY+00)
            CALL    BC.D039
            LD      A,C
            POP     BC
            OR      A
            RET

BC.D070     EQU     $
BC.C027:    LD      A,M
            RES     7,A
            CALL    BC.C024
            BIT     7,M
            RET     NZ
            INC     HL
            JR      $-10

BC.C028:    CALL    BC.CIN
            AND     07FH
            CP      018H
            JR      Z,$+17
            CP      00FH
            RET     NZ
            CALL    BC.C020
            LD      A,(BC.D002)
            CPL
            LD      (BC.D002),A
            XOR     A
            RET
            CALL    BC.C020
            CALL    BC.C048
            CALL    BC.TRAPX
            XOR     A
            RET

            PAGE
;****************************************************************
;*               TOKEN - Routinen:  L L I S T , L I S T         *
;****************************************************************
BC.LLIST:   CALL    BC.C098
BC.LIST:    POP     BC
            CALL    BC.C008
            PUSH    BC
BC.D071:    CALL    BC.C048
            POP     HL
            POP     DE
            LD      C,M
            INC     HL
            LD      B,M
            INC     HL
            LD      A,B
            OR      C
            JR      Z,$+53
            CALL    BC.C036
            PUSH    BC
            LD      C,M
            INC     HL
            LD      B,M
            INC     HL
            PUSH    BC
            EX      (SP),HL
            EX      DE,HL
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            POP     BC
            JR      C,$+32
            EX      (SP),HL
            PUSH    HL
            PUSH    BC
            EX      DE,HL
            CALL    BC.C147
            POP     HL
            CALL    BC.C023
            CALL    BC.C030
            LD      HL,BC.D063
            LD      BC,BC.D071
            PUSH    BC
BC.C029:    DEC     HL
            LD      B,000H
            CALL    BC.C072
            JP      BC.C076
            POP     BC
            JP      BC.J012

BC.C030:    LD      BC,BC.D062
            DB      03EH                ;LD  A,0E1H
BC.J021:    POP     HL
BC.J022:    LD      A,M
            INC     BC
            OR      A
            INC     HL
            LD      (BC),A
            RET     Z
            JP      P,BC.J022
            CP      0C9H
            JR      NZ,$+03
            DEC     BC
            SUB     080H
            PUSH    HL
            LD      HL,BC.D121
            JR      Z,$+10
            BIT     7,M
            INC     HL
            JR      Z,$-03
            DEC     A
            JR      NZ,$-06
            LD      A,M
            CP      020H
            JR      Z,$+10
            OR      A
            RES     7,A
            LD      (BC),A
            JP      M,BC.J021
            INC     BC
            INC     HL
            JR      $-14

            PAGE
;****************************************************************
;*               TOKEN - Routine:  F O R                        *
;****************************************************************
BC.FOR:     LD      A,029H
            LD      (BC.D015),A
            CALL    BC.LET
            EX      (SP),HL
            CALL    BC.C001
            POP     DE
            JR      NZ,$+04
            ADD     HL,BC
            LD      SP,HL
            EX      DE,HL
            LD      C,00AH
            CALL    BC.C004
            PUSH    HL
            CALL    BC.DATA
            EX      (SP),HL
            PUSH    HL
            LD      HL,(BC.D019)
            EX      (SP),HL
            LD      A,09FH
            CALL    BC.C006
            CALL    BC.C053
            CALL    BC.C052
            PUSH    HL
            CALL    BC.C131
            POP     HL
            PUSH    BC
            PUSH    IX
            PUSH    DE
            LD      BC,08100H
            LD      IX,00000H
            LD      D,C
            LD      E,C
            LD      A,M
            CP      0A4H
            LD      A,001H
            JR      NZ,$+16
            CALL    BC.C031
            CALL    BC.C052
            PUSH    HL
            CALL    BC.C131
            CALL    BC.C125
            POP     HL
            PUSH    BC
            PUSH    IX
            PUSH    DE
            PUSH    AF
            INC     SP
            PUSH    HL
            LD      HL,(BC.D017)
            EX      (SP),HL
BC.J023:    LD      B,081H
            PUSH    BC
            INC     SP
BC.D072     EQU     $
BC.J024:    CALL    BC.CSTSX            ;nach Ausfuehrung eines TOKEN, Weiterarbeit
            INC     A                   ;HL  ==>  :  bzw.  00H
            CALL    Z,BC.C037
            LD      (BC.D017),HL
            LD      A,M
            CP      03AH
            JR      Z,$+59
            OR      A
            JP      NZ,BC.J004
            INC     HL
            LD      A,M
            INC     HL
            OR      M
            INC     HL
            JP      Z,BC.J032
            LD      E,M
            INC     HL
            LD      D,M
            LD      (BC.D019),DE
            LD      A,(BC.D052)
            OR      A
            JR      Z,$+34
            PUSH    AF
            CALL    M,BC.C098
            PUSH    DE
            PUSH    HL
            LD      A,03CH
            CALL    BC.C026
BC.D073:    EX      DE,HL
            CALL    BC.C147
            LD      A,03EH
            CALL    BC.C026
            POP     HL
            POP     DE
            POP     AF
            ADD     A,A
            JR      NC,$+08
            CALL    BC.C016
            ADD     A,A
            JR      C,$-30
BC.J025:    CALL    BC.C031             ;bei Ausfuehrung  Zeile
            LD      DE,BC.D072
            PUSH    DE
BC.J026:    RET     Z
BC.J027:    SUB     080H                ;TOKEN -Auswertung
            JP      C,BC.J036           ;kein TOKEN
            CP      046H                ;MID$
            JP      Z,BC.J038
            CP      01DH                ;USING
            JR      C,$+17
            SUB     049H
            JP      C,BC.J004           ;"SYNTAX ERROR"
            CP      023H                ;nicht belegte TOKEN:  ECH ...
            JP      NC,BC.J004          ;"SYNTAX ERROR"
            LD      DE,BC.TB4
            JR      $+05

            LD      DE,BC.TB3
            RLCA
            LD      C,A
            LD      B,000H
            EX      DE,HL
            ADD     HL,BC
            LD      C,M
            INC     HL
            LD      B,M
            PUSH    BC
            EX      DE,HL
BC.C031:    INC     HL
BC.C032:    LD      A,M
            CP      0D5H
            JR      NZ,$+10
            INC     HL
            LD      A,M
            CP      03AH
            RET     Z
            OR      A
            JR      NZ,$-06
            CP      03AH
            RET     NC
            CP      020H
            JR      Z,$-19
            CP      009H
            JR      Z,$-23
            CP      00AH
            JR      Z,$-27
            CP      030H
            CCF
            INC     A
            DEC     A
            RET

BC.REST:    JR      Z,$+17              ;TOKEN:  R E S T O R E
            CALL    BC.C034
            PUSH    HL
            CALL    BC.C009
            POP     DE
            JP      NC,BC.J035
            LD      H,B
            LD      L,C
            JR      $+06

BC.C033:    EX      DE,HL
            LD      HL,(BC.D023)
            DEC     HL
BC.J028:    LD      (BC.D027),HL
            EX      DE,HL
            RET

BC.C034:    DEC     HL
BC.C035:    CALL    BC.C031
            CALL    BC.C045
            JR      $-68

BC.J029:    POP     BC
BC.J030:    POP     BC
BC.J031:    OR      A
            JR      $+54

BC.C036:    CALL    BC.CSTSX
            INC     A
            RET     NZ
BC.C037:    CALL    BC.C028
            CP      014H
            JR      NZ,$+14
            PUSH    HL
            LD      HL,(BC.D019)
            LD      A,H
            AND     L
            INC     A
            CALL    NZ,BC.C100
            POP     HL
            RET
            CP      013H
            JR      NZ,$+13
            CALL    BC.C028
            CP      003H
            JR      Z,$+06
            CP      011H
            JR      NZ,$-09
            CP      003H
            RET     NZ
            CALL    BC.C020
            DB      03EH                ;LD  A,0C0H

BC.STOP:    RET     NZ                  ;TOKEN:  S T O P
            DB      0F6H                ;OR  0C0H

BC.END:     RET     NZ                  ;TOKEN:  E N D
            LD      (BC.D017),HL
BC.EDQ:     POP     BC
BC.J032:    PUSH    AF
            LD      HL,(BC.D019)
            LD      A,L
            AND     H
            INC     A
            JR      Z,$+11
            LD      (BC.D020),HL
            LD      HL,(BC.D017)
            LD      (BC.D021),HL
            CALL    BC.C015
            POP     AF
            LD      HL,BC.D130
            JP      NZ,BC.J011
            JP      BC.J012

BC.CONT:    LD      E,011H              ;TOKEN:  C O N T I N U E
            LD      HL,(BC.D021)
            LD      A,H
            OR      L
            JR      Z,$+88
            EX      DE,HL
            LD      HL,(BC.D020)
            LD      (BC.D019),HL
            EX      DE,HL
            RET

BC.LNULL:   CALL    BC.C097             ;TOKEN:  L N U L L
BC.NULL:    CALL    BC.C091             ;TOKEN:  N U L L
            CP      032H
            JR      NC,$+67
            LD      (IY+03),A
            LD      A,02CH
            CP      M
            RET     NZ
            CALL    BC.C031
            CALL    BC.C091
            LD      (IY+04),A
            RET

BC.C038:    LD      A,M
            CP      'A'
            RET     C
            CP      '['
            CCF
            RET

BC.D074     EQU     $+2
BC.C039:    CALL    BC.C053
            JR      $+14

BC.C040:    CALL    BC.C031
BC.C041:    CALL    BC.C052
BC.C042:    CALL    BC.C125
            JP      M,BC.J033
BC.C043:    LD      A,(BC.D032)
            CP      091H
            JP      C,BC.C139
            LD      BC,09180H
            DW      21DDH
BC.C044:    DW      0
            LD      DE,0
            CALL    BC.C136
            LD      D,C
            RET     Z
BC.J033:    LD      E,005H
            JP      BC.J010

BC.C045:    DEC     HL                  ;Zeilennummer umwandeln
            LD      DE,0
            INC     HL
            LD      A,M
            OR      A
            RET     Z
            CP      '0'
            CCF
            RET     NC
            CP      ':'
            RET     NC
            PUSH    HL
            LD      HL,BC.D096
            OR      A
            SBC     HL,DE
            JP      C,BC.J004
            LD      H,D
            LD      L,E
            ADD     HL,DE
            ADD     HL,HL
            ADD     HL,DE
            ADD     HL,HL
            SUB     030H
            LD      E,A
            LD      D,000H
            ADD     HL,DE
            EX      DE,HL
            POP     HL
            JR      $-35

BC.CLEAR:   JR      Z,$+40              ;TOKEN:  C L E A R
            CALL    BC.C041
            CALL    BC.C032
            RET     NZ
            PUSH    HL
            LD      HL,(BC.D006)
            SBC     HL,DE
            EX      DE,HL
            JP      C,BC.J004
            LD      HL,(BC.D024)
            LD      BC,00028H
            ADD     HL,BC
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            JP      NC,BC.J002
            EX      DE,HL
            LD      (BC.D022),HL
            POP     HL
            JP      BC.C013

BC.RUN:     JP      Z,BC.C012           ;TOKEN:  R U N
            CALL    BC.C013
            LD      BC,BC.D072
            JR      $+30

BC.GOSUB:   LD      C,003H              ;TOKEN:  G O S U B
            CALL    BC.C004
            POP     BC
            PUSH    HL
            LD      DE,(BC.D019)
            PUSH    DE
            LD      A,D
            OR      E
            INC     A
            LD      A,(BC.D055)
            LD      D,A
            JR      NZ,$+06
            XOR     A
            LD      (BC.D055),A
            LD      E,08CH
            PUSH    DE
            PUSH    BC
BC.GOTO:    CALL    BC.C045             ;TOKEN:  G O T O
            CALL    BC.DATA+2
            PUSH    HL
            LD      HL,(BC.D019)
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            POP     HL
            INC     HL
            CALL    C,BC.C010
BC.J034:    CALL    NC,BC.C009
            LD      H,B
            LD      L,C
            DEC     HL
            RET     C
BC.J035:    LD      E,8
            JP      BC.J010

BC.RETRN:   RET     NZ                  ;TOKEN:  R E T U R N
            LD      D,0FFH
            CALL    BC.C001
            LD      D,M
            INC     HL
            LD      SP,HL
            CP      08CH
            LD      E,003H
            JR      NZ,$-16
            POP     HL
            LD      (BC.D019),HL
            LD      A,H
            AND     L
            INC     A
            LD      HL,BC.D055
            LD      A,M
            LD      M,D
            JR      NZ,$+06
            OR      A
            JP      NZ,BC.J053
            LD      HL,BC.D072
            EX      (SP),HL
BC.DATA:    LD      BC,BC.D078          ;TOKEN:  D A T A
            NOP
            LD      B,000H
            LD      A,C
            LD      C,B
            LD      B,A
            LD      A,M
            OR      A
            RET     Z
            CP      B
            RET     Z
            INC     HL
            CP      022H
            JR      Z,$-11
BC.D075:    SUB     08AH
            JR      NZ,$-12
            CP      B
            ADC     A,D
            LD      D,A
            JR      $-17

BC.LET:     CP      0C6H                ;TOKEN:  L E T
            JR      Z,$+98
BC.J036:    CALL    BC.C060
            LD      A,0ADH
            CALL    BC.C006
BC.C046:    PUSH    DE
            LD      A,(BC.D004)
            PUSH    AF
            CALL    BC.C056
            POP     AF
            EX      (SP),HL
            LD      (BC.D017),HL
            RRA
            CALL    BC.C054
            JR      NZ,$+09
            PUSH    HL
            CALL    BC.C133
            POP     DE
            POP     HL
            RET

BC.J037:    PUSH    HL
            LD      HL,(BC.D029)
            PUSH    HL
            INC     HL
            INC     HL
            LD      E,M
            INC     HL
            LD      D,M
            LD      HL,BC.D064
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            JR      NC,$+26
            LD      HL,(BC.D022)
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            POP     DE
            JR      NC,$+22
            LD      HL,(BC.D024)
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            JR      NC,$+11
            LD      A,0D1H
            CALL    BC.C086
            EX      DE,HL
            CALL    BC.C067
            CALL    BC.C086
            POP     HL
            CALL    BC.C134
            POP     HL
            RET

BC.J038:    CALL    BC.C031
            LD      A,028H
            CALL    BC.C006
            CALL    BC.C060
            CALL    BC.C053+1
            LD      A,02CH
            CALL    BC.C006
            PUSH    DE
            CALL    BC.C091
            OR      A
            JP      Z,BC.J033
            PUSH    AF
            LD      E,0FFH
            LD      A,M
            CP      029H
            JR      Z,$+10
            LD      A,02CH
            CALL    BC.C006
            CALL    BC.C091
            LD      A,029H
            CALL    BC.C006
            LD      A,0ADH
            CALL    BC.C006
            POP     AF
            EX      (SP),HL
            DEC     A
            CP      M
            LD      B,000H
            JR      NC,$+10
            LD      C,A
            LD      A,M
            SUB     C
            CP      E
            LD      B,A
            JR      C,$+03
            LD      B,E
            PUSH    BC
            INC     HL
            INC     HL
            LD      B,M
            INC     HL
            LD      H,M
            LD      L,B
            LD      B,000H
            ADD     HL,BC
            POP     BC
            EX      (SP),HL
            PUSH    BC
            CALL    BC.C055
            POP     BC
            POP     DE
            PUSH    HL
            LD      HL,(BC.D029)
            LD      A,B
            SUB     M
            PUSH    AF
            LD      A,B
            JR      C,$+03
            LD      A,M
            INC     HL
            INC     HL
            LD      C,M
            INC     HL
            LD      B,M
            CALL    BC.C081
            POP     AF
            JR      C,$+11
            JR      Z,$+09
            EX      DE,HL
            LD      M,020H
            INC     HL
            DEC     A
            JR      NZ,$-04
            CALL    BC.C083
            POP     HL
            RET

BC.ON:      CALL    BC.C091             ;TOKEN:  O N
            LD      A,M
            LD      B,A
            CP      08CH                ;GOSUB
            JR      Z,$+08
            LD      A,088H              ;GOTO
            CALL    BC.C006
            DEC     HL
            LD      C,E
            DEC     C
            LD      A,B
            JP      Z,BC.J027
            CALL    BC.C035
            CP      02CH
            RET     NZ
            JR      $-11

BC.IF:      CALL    BC.C056             ;TOKEN:  I F
            LD      A,M
            CP      02CH
            CALL    Z,BC.C031
            CP      088H
            JR      Z,$+08
            LD      A,0A2H
            CALL    BC.C006
            DEC     HL
            PUSH    HL
            CALL    BC.C125
            POP     HL
            JR      Z,$+11
            CALL    BC.C031
            JP      C,BC.GOTO
            JP      BC.J026
            LD      D,001H
            CALL    BC.DATA
            OR      A
            RET     Z
            CALL    BC.C031
            CP      0C9H
            JR      NZ,$-10
            DEC     D
            JR      NZ,$-13
            JR      $-26

BC.LPRNT:   CALL    BC.C097             ;TOKEN:  L P R I N T
BC.PRINT:   JP      Z,BC.C048           ;TOKEN:  P R I N T
            CP      09DH
            JP      Z,BC.J104
            CP      09EH
            JR      Z,$+80
            CP      0A1H
            JR      Z,$+75
            PUSH    HL
            CP      02CH
            JR      Z,$+52
            CP      03BH
            JR      Z,$+97
            POP     BC
            CALL    BC.C056
            PUSH    HL
            LD      A,(BC.D004)
            OR      A
            JR      NZ,$+28
            CALL    BC.C148
            CALL    BC.C070
            LD      HL,(BC.D029)
            LD      A,(IY+00)
            ADD     A,M
            CP      (IY+01)
            CALL    NC,BC.C048
            CALL    BC.C076
            CALL    BC.C023
            XOR     A
            CALL    NZ,BC.C076
            POP     HL
            CALL    BC.C032
            JR      $-69
            LD      A,(IY+00)
            CP      (IY+02)
            CALL    NC,BC.C048
            JR      NC,$+40
            SUB     00EH
            JR      NC,$-02
            CPL
            JR      $+26
            SCF
            PUSH    AF
            CALL    BC.C090
            LD      A,029H
            CALL    BC.C006
            DEC     HL
            POP     AF
            PUSH    HL
            LD      A,0FFH
            JR      C,$+06
            LD      A,(IY+00)
            CPL
            ADD     A,E
            JR      NC,$+09
            INC     A
            LD      B,A
            CALL    BC.C023
            DJNZ    $-03
            POP     HL
            CALL    BC.C031
            RET     Z
            JR      $-125

BC.C047:    LD      HL,BC.D128
            JP      BC.AKJPB

BC.J039:    LD      HL,BC.D063
            LD      M,A
            INC     HL
            CALL    BC.C021
BC.J040:    LD      M,0
            LD      HL,BC.D062
BC.C048:    LD      A,00DH
            LD      (IY+00),A
            CALL    BC.C026
            LD      A,00AH
            CALL    BC.C026
BC.C049:    LD      A,(IY+03)
            INC     A
            DEC     A
            LD      (IY+00),A
            RET     Z
            PUSH    AF
            LD      A,(IY+04)
            CALL    BC.C026
            POP     AF
            JR      $-13

BC.C050:    CALL    BC.C048
            LD      A,(BC.D058)
            OR      A
            RET     Z
            PUSH    HL
            PUSH    BC
            LD      HL,(BC.D047)
            CALL    BC.C147
            CALL    BC.C023
            POP     BC
            POP     HL
            RET

BC.AUTO:    POP     DE                  ;TOKEN:  A U T O
            LD      DE,0000AH
            PUSH    DE
            CALL    C,BC.C034
            EX      DE,HL
            EX      (SP),HL
            EX      DE,HL
            CP      02CH
            JR      NZ,$+08
            CALL    BC.C031
            CALL    C,BC.C034
            OR      A
            JP      NZ,BC.J004
            LD      (BC.D048),DE
            LD      A,D
            OR      E
            JP      Z,BC.J004
            LD      A,001H
            LD      (BC.D058),A
            POP     HL
            JP      BC.J014

BC.LINE:    LD      A,084H              ;TOKEN:  L I N E
            CALL    BC.C006
            DB      0F6H                ;OR  0AFH

BC.INPUT:   XOR     A                   ;TOKEN:  I N P U T
            PUSH    AF
            LD      A,M
            CP      022H
            LD      A,000H
            LD      (BC.D002),A
            JR      NZ,$+15
            CALL    BC.C071
            LD      A,03BH
            CALL    BC.C006
            PUSH    HL
            CALL    BC.C076
            POP     HL
            EX      (SP),HL
            PUSH    HL
            CALL    BC.C065
            CALL    BC.C019
            JP      Z,BC.J029
            POP     AF
            JR      Z,$+49
            EX      (SP),HL
            CALL    BC.C060
            CALL    BC.C053+1
            EX      (SP),HL
            PUSH    DE
            LD      B,000H
            CALL    BC.C072
            EX      DE,HL
            LD      HL,BC.D076
            EX      (SP),HL
            PUSH    DE
            JP      BC.J037

BC.D076:    POP     HL
            CALL    BC.C032
            RET     Z
            LD      A,02CH
            CALL    BC.C006
            PUSH    HL
            CALL    BC.C018
            JP      Z,BC.J030
            JR      $-40

BC.READ:    PUSH    HL                  ;TOKEN:  R E A D
            LD      HL,(BC.D027)
            OR      0AFH
            LD      (BC.D016),A
            EX      (SP),HL
            JR      $+07
            LD      A,02CH
            CALL    BC.C006
            CALL    BC.C060
            EX      (SP),HL
            PUSH    DE
            LD      A,M
            CP      02CH
            JR      Z,$+14
            LD      A,(BC.D016)
            OR      A
            JR      NZ,$+86
            CALL    BC.C018
            JP      Z,BC.J029
BC.J041:    LD      A,(BC.D004)
            OR      A
            JR      Z,$+28
            CALL    BC.C031
            LD      D,A
            LD      B,A
            CP      022H
            JR      Z,$+07
            LD      D,03AH
            LD      B,02CH
            DEC     HL
            CALL    BC.C073
            EX      DE,HL
            LD      HL,BC.D077
            EX      (SP),HL
            PUSH    DE
            JP      BC.J037

            CALL    BC.C031
            CALL    BC.C141
            EX      (SP),HL
            CALL    BC.C133
            POP     HL
BC.D077:    CALL    BC.C032
            JR      Z,$+07
            CP      02CH
            JP      NZ,BC.J003
            EX      (SP),HL
            CALL    BC.C032
            JR      NZ,$-84
            POP     DE
            LD      A,(BC.D016)
            OR      A
            EX      DE,HL
            JP      NZ,BC.J028
            OR      M
            LD      HL,BC.D129
            PUSH    DE
            CALL    NZ,BC.C027
            POP     HL
            RET
            CALL    BC.DATA
            OR      A
            JR      NZ,$+18
            INC     HL
            LD      A,M
            INC     HL
            OR      M
            LD      E,004H
            JR      Z,$+107
            INC     HL
            LD      E,M
            INC     HL
            LD      D,M
            LD      (BC.D014),DE
            CALL    BC.C031
            CP      083H
            JR      NZ,$-27
BC.D078     EQU     $+2
            JP      BC.J041

BC.NEXT:    LD      DE,0                ;TOKEN:  N E X T
BC.C051:    CALL    NZ,BC.C060
            LD      (BC.D017),HL
            CALL    BC.C001
            JP      NZ,BC.J009
            LD      SP,HL
            PUSH    DE
            LD      A,M
            INC     HL
            PUSH    AF
            PUSH    DE
            CALL    BC.C129
            EX      (SP),HL
            PUSH    HL
            CALL    BC.C106
            POP     HL
            CALL    BC.C133
            POP     HL
            CALL    BC.C132
            PUSH    HL
            CALL    BC.C136
            POP     HL
            POP     BC
            SUB     B
            CALL    BC.C138
            JR      Z,$+11
            EX      DE,HL
            LD      (BC.D019),HL
            LD      L,C
            LD      H,B
            JP      BC.J023
            LD      SP,HL
            LD      HL,(BC.D017)
            LD      A,M
            CP      02CH
            JP      NZ,BC.J024
            CALL    BC.C031
            CALL    BC.C051
BC.C052:    CALL    BC.C056
BC.C053:    OR      037H
BC.C054:    LD      A,(BC.D004)
            ADC     A,A
            OR      A
            RET     PE
BC.J042:    LD      E,00DH
            JP      BC.J010

BC.C055:    CALL    BC.C056
            JR      $-15

BC.C056:    DEC     HL
            LD      D,0
BC.C057:    PUSH    DE
            LD      C,1
            CALL    BC.C004
            CALL    BC.C058
            LD      (BC.D018),HL
BC.D079     EQU     $
BC.J043:    LD      HL,(BC.D018)
BC.D080:    POP     BC
            LD      A,B
            CP      078H
            CALL    NC,BC.C053
            LD      A,M
            LD      D,000H
            SUB     0ACH
            JR      C,$+23
            CP      003H
            JR      NC,$+19
            CP      001H
            RLA
            XOR     D
            CP      D
            LD      D,A
            JP      C,BC.J004
            LD      (BC.D013),HL
            CALL    BC.C031
            JR      $-23
            LD      A,D
            OR      A
            JP      NZ,BC.J045
            LD      A,M
            LD      (BC.D013),HL
            SUB     0A5H
            RET     C
            CP      007H
            RET     NC
            LD      E,A
            LD      A,(BC.D004)
            DEC     A
            OR      E
            LD      A,E
            JP      Z,BC.J057
            RLCA
            ADD     A,E
            LD      E,A
            LD      HL,BC.TB2
            ADD     HL,DE
            LD      A,B
            LD      D,M
            CP      D
            RET     NC
            INC     HL
            CALL    BC.C053
BC.J044:    PUSH    BC
            LD      BC,BC.D079
            PUSH    BC
            LD      BC,(BC.D029)
            PUSH    BC
            LD      BC,(BC.D030)
            PUSH    BC
            LD      BC,(BC.D031)
            PUSH    BC
            LD      C,M
            INC     HL
            LD      B,M
            PUSH    BC
            LD      HL,(BC.D013)
            JR      $-117

BC.C058:    XOR     A
            LD      (BC.D004),A
            CALL    BC.C031
            JP      C,BC.J084
            CALL    BC.C038
            JR      NC,$+70
            CP      0A5H                ;  +
            JR      Z,$-17
            CP      '.'
            JP      Z,BC.J084
            CP      0A6H                ;  -
            JR      Z,$+40
            CP      022H                ;  "
            JP      Z,BC.C071
            CP      0A3H                ;  NOT
            JP      Z,BC.J046
            CP      0A0H                ;  FN
            JP      Z,BC.J052
            CP      '&'
            JP      Z,BC.J086
            SUB     0AFH
            JR      NC,$+50
BC.C059:    LD      A,'('
            CALL    BC.C006
            CALL    BC.C056
            LD      A,')'
            CALL    BC.C006
            RET

            LD      D,07DH
            CALL    BC.C057
            LD      HL,(BC.D018)
            PUSH    HL
            CALL    BC.C126
BC.D081:    CALL    BC.C053
            POP     HL
            RET

            CALL    BC.C060
BC.D082:    PUSH    HL
            EX      DE,HL
            LD      (BC.D029),HL
            LD      A,(BC.D004)
            OR      A
            CALL    Z,BC.C129
            POP     HL
            RET
            LD      B,000H
            RLCA
            LD      C,A
            PUSH    BC
            CALL    BC.C031
            LD      A,C
            CP      029H
            JR      C,$+40
            CP      030H
            JR      Z,$+36
            CP      032H
            JR      Z,$+29
            JP      NC,BC.J033
            LD      A,028H
            CALL    BC.C006
            CALL    BC.C055
            LD      A,02CH
            CALL    BC.C006
            EX      DE,HL
            LD      HL,(BC.D029)
            EX      (SP),HL
            PUSH    HL
            EX      DE,HL
            CALL    BC.C091
            EX      DE,HL
            EX      (SP),HL
            JR      $+10
            CALL    BC.C059
            EX      (SP),HL
            LD      DE,BC.D081
            PUSH    DE
            LD      BC,BC.TB1
            ADD     HL,BC
            LD      C,M
            INC     HL
            LD      H,M
            LD      L,C
            JP      (HL)

            OR      0AFH
            PUSH    AF
            CALL    BC.C039
            POP     AF
            EX      DE,HL
            POP     BC
            POP     IX
            EX      (SP),HL
            EX      DE,HL
            CALL    BC.C130
            PUSH    AF
            CALL    BC.C043
            POP     AF
            POP     BC
            LD      A,C
            LD      HL,BC.D087
            JR      NZ,$+07
            AND     E
            LD      C,A
BC.D083:    LD      A,B
            AND     D
            JP      (HL)

            OR      E
            LD      C,A
            LD      A,B
            OR      D
            JP      (HL)

BC.J045:    LD      HL,BC.D084
            LD      A,(BC.D004)
            RRA
            LD      A,D
            RLA
            LD      E,A
            LD      D,064H
            LD      A,B
            CP      D
            RET     NC
            JP      BC.J044

BC.D084:    OR      00FH
            LD      A,C
            OR      A
            RRA
            POP     BC
            POP     IX
            POP     DE
            PUSH    AF
            CALL    BC.C054
            LD      HL,BC.D085
            PUSH    HL
            JP      Z,BC.C136
            XOR     A
            LD      (BC.D004),A
            PUSH    DE
            CALL    BC.C083
            POP     DE
            LD      C,M
            INC     HL
            LD      B,M
            INC     HL
            PUSH    BC
            LD      C,M
            INC     HL
            LD      B,M
            PUSH    BC
            CALL    BC.C085
            CALL    BC.C138
            POP     HL
            EX      (SP),HL
            LD      D,L
            POP     HL
            LD      A,E
            OR      D
            RET     Z
            LD      A,D
            SUB     001H
            RET     C
            XOR     A
            CP      E
            INC     A
            RET     NC
            DEC     D
            DEC     E
            LD      A,(BC)
            CP      M
            INC     HL
            INC     BC
            JR      Z,$-17
            CCF
            JP      BC.J082

BC.D085:    INC     A
            ADC     A,A
            POP     BC
            AND     B
            ADD     A,0FFH
            SBC     A,A
            JP      BC.C123

BC.J046:    LD      D,05AH
            CALL    BC.C057
            CALL    BC.C053
            CALL    BC.C043
            LD      A,E
            CPL
            LD      C,A
            LD      A,D
            CPL
            CALL    BC.C063
            POP     BC
            JP      BC.J043

BC.D086:    CALL    BC.C032
            RET     Z
            LD      A,02CH
            CALL    BC.C006
BC.DIM:     LD      BC,BC.D086          ;TOKEN:  D I M
            PUSH    BC
            DB      0F6H
BC.C060:    XOR     A
            LD      (BC.D003),A
            LD      B,M
BC.J047:    CALL    BC.C038
            JP      C,BC.J004
            XOR     A
            LD      C,A
            LD      (BC.D004),A
            CALL    BC.C031
            JR      C,$+07
            CALL    BC.C038
            JR      C,$+13
            LD      C,A
            CALL    BC.C031
            JR      C,$-03
            CALL    BC.C038
            JR      NC,$-08
            SUB     024H
            JR      NZ,$+11
            INC     A
            LD      (BC.D004),A
            SET     7,C
            CALL    BC.C031
            LD      A,(BC.D015)
            DEC     A
            JP      Z,BC.J048
            ADD     A,M
            SUB     027H
            JR      Z,$+110
            XOR     A
            LD      (BC.D015),A
            PUSH    HL
            LD      HL,(BC.D025)
            EX      DE,HL
            LD      HL,(BC.D024)
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            JR      Z,$+20
            LD      A,C
            SUB     M
            INC     HL
            JR      NZ,$+04
            LD      A,B
            SUB     M
            INC     HL
            JR      Z,$+66
            INC     HL
            INC     HL
            INC     HL
            INC     HL
            INC     HL
            INC     HL
            JR      $-24
            POP     HL
            EX      (SP),HL
            PUSH    DE
            LD      DE,BC.D082
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            POP     DE
            JR      Z,$+46
            EX      (SP),HL
            PUSH    HL
            PUSH    BC
            LD      BC,00008H
            LD      HL,(BC.D026)
            PUSH    HL
            ADD     HL,BC
            POP     BC
            PUSH    HL
            CALL    BC.C002
            POP     HL
            LD      (BC.D026),HL
            LD      H,B
            LD      L,C
            LD      (BC.D025),HL
            DEC     HL
            LD      M,000H
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            JR      NZ,$-09
            POP     DE
            LD      M,E
            INC     HL
            LD      M,D
            INC     HL
            EX      DE,HL
            POP     HL
            RET
            LD      (BC.D032),A
            LD      HL,BC.D066
            LD      (BC.D029),HL
            POP     HL
            RET
            PUSH    HL
            LD      HL,(BC.D003)
            EX      (SP),HL
            LD      D,A
            PUSH    DE
            PUSH    BC
            CALL    BC.C040
            POP     BC
            POP     AF
            EX      DE,HL
            EX      (SP),HL
            PUSH    HL
            EX      DE,HL
            INC     A
            LD      D,A
            LD      A,M
            CP      02CH
            JR      Z,$-16
            LD      A,029H
            CALL    BC.C006
            LD      (BC.D018),HL
            POP     HL
            LD      (BC.D003),HL
            LD      E,000H
            PUSH    DE
            DB      11H
BC.J048:    PUSH    HL
            PUSH    AF
            LD      HL,(BC.D025)
            LD      A,019H
            LD      DE,(BC.D026)
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            JR      Z,$+35
            LD      A,M
            CP      C
            INC     HL
            JR      NZ,$+04
            LD      A,M
            CP      B
            INC     HL
            LD      E,M
            INC     HL
            LD      D,M
            INC     HL
            JR      NZ,$-25
            LD      A,(BC.D003)
            OR      A
            JP      NZ,BC.J007
            POP     AF
            JP      Z,BC.J069
            SUB     M
            JR      Z,$+99
BC.J049:    LD      E,9
            JP      BC.J010

            LD      DE,6
            POP     AF
            JP      Z,BC.J070
            LD      M,C
            INC     HL
            LD      M,B
            INC     HL
            LD      C,A
            CALL    BC.C004
            INC     HL
            INC     HL
            LD      (BC.D013),HL
            LD      M,C
            INC     HL
            LD      A,(BC.D003)
            RLA
            LD      A,C
            LD      BC,0000BH
            JR      NC,$+04
            POP     BC
            INC     BC
            LD      M,C
            INC     HL
            LD      M,B
            INC     HL
            PUSH    AF
            PUSH    HL
            CALL    BC.C140
            EX      DE,HL
            POP     HL
            POP     AF
            DEC     A
            JR      NZ,$-20
            PUSH    AF
            LD      B,D
            LD      C,E
            EX      DE,HL
            ADD     HL,DE
            JR      C,$-59
            CALL    BC.C005
            LD      (BC.D026),HL
            DEC     HL
            LD      M,000H
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            JR      NZ,$-09
            INC     BC
            LD      D,A
            LD      HL,(BC.D013)
            LD      E,M
            EX      DE,HL
            ADD     HL,HL
            ADD     HL,BC
            EX      DE,HL
            DEC     HL
            DEC     HL
            LD      M,E
            INC     HL
            LD      M,D
            INC     HL
            POP     AF
            JR      C,$+40
            LD      B,A
            LD      C,A
            LD      A,M
            INC     HL
            LD      D,0E1H
            LD      E,M
            INC     HL
            LD      D,M
            INC     HL
            EX      (SP),HL
            PUSH    AF
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            JR      NC,$-115
            PUSH    HL
            CALL    BC.C140
            POP     DE
            ADD     HL,DE
            POP     AF
            DEC     A
            LD      B,H
            LD      C,L
            JR      NZ,$-25
            ADD     HL,HL
            ADD     HL,BC
            ADD     HL,HL
            POP     BC
            ADD     HL,BC
            EX      DE,HL
            LD      HL,(BC.D018)
            RET

BC.FRE:     LD      HL,(BC.D026)        ;TOKEN:  F R E
            EX      DE,HL
            LD      HL,00000H
            ADD     HL,SP
            LD      A,(BC.D004)
            OR      A
            JR      Z,$+15
            CALL    BC.C083
            CALL    BC.C078
            LD      HL,(BC.D022)
            EX      DE,HL
            LD      HL,(BC.D012)
            XOR     A
            LD      (BC.D004),A
            SBC     HL,DE
BC.C061:    EX      DE,HL
BC.C062:    XOR     A
            LD      B,098H
            JR      $+12

BC.D087     EQU     $
BC.C063:    LD      B,C
BC.D088     EQU     $
BC.J050:    LD      D,B
            LD      E,000H
            LD      HL,BC.D004
            LD      M,E
            LD      B,090H
            JP      BC.C124

BC.LPOS:    LD      A,(BC.D044)         ;TOKEN:  L P O S
            JR      $+05

BC.POS:     LD      A,(BC.D041)         ;TOKEN:  P O S
BC.D089     EQU     $
BC.C064:    LD      B,A
            XOR     A
            JR      $-22

BC.DEF:     CALL    BC.C066             ;TOKEN:  D E F
            CALL    BC.C065
            EX      DE,HL
            LD      M,E
            INC     HL
            LD      M,D
            EX      DE,HL
            DEC     HL
            CALL    BC.C031
            JR      Z,$+09
            CP      0ADH
            JR      NZ,$-07
            JP      BC.DATA
            OR      A
            JR      NZ,$+17
            INC     HL
            LD      A,M
            INC     HL
            OR      M
            JP      Z,BC.J004
            INC     HL
            LD      E,M
            INC     HL
            LD      D,M
            LD      (BC.D019),DE
BC.J051:    CALL    BC.C031
            JR      Z,$-21
            CP      089H
            JR      Z,$-28
            JP      BC.J051

BC.J052:    CALL    BC.C066
            LD      A,(BC.D004)
            OR      A
            PUSH    AF
            LD      (BC.D018),HL
            EX      DE,HL
            LD      A,M
            INC     HL
            LD      H,M
            LD      L,A
            OR      H
            JP      Z,BC.J008
            LD      A,M
            CP      028H
            JR      NZ,$+115
            CALL    BC.C031
            LD      (BC.D013),HL
            JR      $+07
            LD      A,02CH
            CALL    BC.C006
            LD      C,005H
            CALL    BC.C004
            LD      A,029H
            LD      (BC.D015),A
            CALL    BC.C060
            EX      DE,HL
            LD      A,(BC.D004)
            OR      A
            SCF
            JR      NZ,$+18
            LD      C,M
            INC     HL
            LD      B,M
            PUSH    BC
            INC     HL
            LD      C,M
            INC     HL
            LD      B,M
            PUSH    BC
            INC     HL
            LD      C,M
            INC     HL
            LD      B,M
            PUSH    BC
            JR      $+10
            PUSH    AF
            PUSH    DE
            EX      DE,HL
            CALL    BC.C074
            POP     DE
            POP     AF
            PUSH    HL
            PUSH    AF
            EX      DE,HL
            LD      A,M
            CP      029H
            JR      NZ,$-56
            LD      HL,(BC.D018)
            LD      A,028H
            CALL    BC.C006
            PUSH    HL
            LD      HL,(BC.D013)
            CALL    BC.C060
            EX      (SP),HL
            CALL    BC.C046
            LD      A,M
            CP      029H
            JR      Z,$+15
            LD      A,02CH
            CALL    BC.C006
            EX      (SP),HL
            LD      A,02CH
            CALL    BC.C006
            JR      $-23
            CALL    BC.C031
            EX      (SP),HL
            LD      A,029H
            CALL    BC.C006
            LD      A,0D5H
            CALL    BC.C032
            JR      Z,$+18
            LD      A,0ADH
            CALL    BC.C006
            CALL    BC.C056
            CALL    BC.C032
            JP      NZ,BC.J004
            JR      $+60
            LD      C,002H
            CALL    BC.C004
            LD      DE,(BC.D019)
            PUSH    DE
            LD      D,0A0H
            PUSH    DE
            INC     SP
            JP      BC.J024

BC.FNRTN    EQU     $                   ;TOKEN  F N R E T U R N
BC.FNEND:   JR      NZ,$+14             ;TOKEN:  F N E N D
            CALL    BC.C112
            LD      (BC.D010),A
            CPL
            LD      (BC.D004),A
            JR      $+11
            CALL    BC.C056
            CALL    BC.C032
            JP      NZ,BC.J004
            LD      D,0FFH
            CALL    BC.C001
            LD      SP,HL
            CP      0A0H
            LD      E,017H
            JP      NZ,BC.J010
            POP     DE
            LD      (BC.D019),DE
            LD      A,(BC.D004)
            INC     A
            JR      Z,$+05
            DEC     A
            JR      NZ,$+48
            POP     DE
            POP     AF
            JR      NC,$+21
            JR      NZ,$+57
            POP     HL
            POP     BC
            LD      M,B
            DEC     HL
            LD      M,C
            DEC     HL
            POP     BC
            LD      M,B
            DEC     HL
            LD      M,C
            DEC     HL
            POP     BC
            LD      M,B
            DEC     HL
            LD      M,C
            JR      $-20
            PUSH    AF
            PUSH    DE
            LD      HL,BC.D004
            BIT     7,M
            JR      Z,$+03
            LD      M,A
            OR      A
            LD      DE,BC.D010
            CALL    NZ,BC.C074
            POP     HL
            POP     AF
            RRA
            JP      BC.C054
            LD      DE,(BC.D029)
            CALL    BC.C086
            LD      HL,BC.D010
            CALL    BC.C134
            JR      $-59
            CALL    BC.C086
            LD      A,M
            LD      (BC.D007),HL
            POP     HL
            LD      M,A
            INC     HL
            INC     HL
            LD      M,C
            INC     HL
            LD      M,B
            JR      $-74

BC.C065:    PUSH    HL
            LD      HL,(BC.D019)
            INC     HL
            LD      A,H
            OR      L
            POP     HL
            RET     NZ
BC.J053:    LD      E,12
            JP      BC.J010

BC.C066:    LD      A,0A0H
            CALL    BC.C006
            OR      080H
            LD      B,A
            LD      A,029H
            LD      (BC.D015),A
            JP      BC.J047

BC.STRD:    CALL    BC.C053             ;TOKEN:  S T R $
            CALL    BC.C148
            CALL    BC.C070
            CALL    BC.C083
            LD      BC,BC.D093
            PUSH    BC
BC.C067:    LD      A,M
            INC     HL
            INC     HL
            PUSH    HL
            CALL    BC.C077
            POP     HL
            LD      C,M
            INC     HL
            LD      B,M
            CALL    BC.C069
            PUSH    HL
            CALL    BC.C081
            POP     DE
            RET

BC.C068:    CALL    BC.C077
BC.C069:    LD      HL,BC.D010
            PUSH    HL
            LD      M,A
            INC     HL
            INC     HL
            LD      M,E
            INC     HL
            LD      M,D
            POP     HL
            RET

BC.C070:    DEC     HL
BC.C071:    LD      B,022H
BC.C072:    LD      D,B
BC.C073:    PUSH    HL
            LD      C,0FFH
            INC     HL
            LD      A,M
            INC     C
            OR      A
            JR      Z,$+08
            CP      D
            JR      Z,$+05
            CP      B
            JR      NZ,$-10
            CP      022H
            CALL    Z,BC.C031
            EX      (SP),HL
            INC     HL
            EX      DE,HL
            LD      A,C
            CALL    BC.C069
BC.J054:    LD      DE,BC.D010
            DB      3EH
BC.C074:    PUSH    DE
            LD      HL,(BC.D007)
            LD      (BC.D029),HL
            LD      A,001H
            LD      (BC.D004),A
            CALL    BC.C134
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            LD      (BC.D007),HL
            POP     HL
            LD      A,M
            RET     NZ
            LD      E,16
            JP      BC.J010

BC.J055:    INC     HL
BC.C075:    CALL    BC.C070
BC.C076:    CALL    BC.C083
            CALL    BC.C138
            INC     E
            DEC     E
            RET     Z
            LD      A,(BC)
            CALL    BC.C024
            CP      00DH
            CALL    Z,BC.C049
            INC     BC
            JR      $-12

BC.C077:    OR      A
BC.D090     EQU     $+1
            LD      C,0F1H
            PUSH    AF
            LD      HL,(BC.D022)
            EX      DE,HL
            LD      HL,(BC.D012)
            LD      C,A
            XOR     A
            LD      B,A
            SBC     HL,BC
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            JR      C,$+09
            LD      (BC.D012),HL
            INC     HL
            EX      DE,HL
            POP     AF
            RET
            POP     AF
            LD      E,00EH
            JR      Z,$-62
            CP      A
            PUSH    AF
            LD      BC,BC.D090
            PUSH    BC
BC.C078:    LD      HL,(BC.D006)
BC.J056:    LD      (BC.D012),HL
            XOR     A
            EX      AF,AF'              ;'
            LD      DE,(BC.D022)
            EXX
            LD      HL,BC.D008
BC.D091:    LD      DE,(BC.D007)
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            LD      BC,BC.D091
            JR      NZ,$+65
            LD      HL,(BC.D024)
            LD      DE,(BC.D025)
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            JR      Z,$+12
            BIT     7,M
            INC     HL
            INC     HL
            CALL    BC.C079
            JR      $-19
            POP     BC
            EX      DE,HL
            LD      HL,(BC.D026)
            SBC     HL,DE
            EX      DE,HL
            JR      Z,$+70
            CALL    BC.C138
            BIT     7,E
            PUSH    HL
            ADD     HL,BC
            JR      Z,$-17
            EX      (SP),HL
            LD      C,M
            LD      B,000H
            ADD     HL,BC
            ADD     HL,BC
            INC     HL
BC.D092:    POP     DE
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            JR      Z,$-32
            PUSH    DE
            LD      BC,BC.D092
            PUSH    BC
BC.C079:    LD      A,M
            INC     HL
            INC     HL
            LD      E,M
            INC     HL
            LD      D,M
            INC     HL
            INC     HL
            INC     HL
            RET     Z
            OR      A
            RET     Z
            PUSH    DE
            EXX
            POP     BC
            LD      HL,(BC.D012)
            SBC     HL,BC
            EXX
            RET     C
            EXX
            LD      H,D
            LD      L,E
            SBC     HL,BC
            EXX
            RET     NC
            EXX
            LD      D,B
            LD      E,C
            EXX
            EX      AF,AF'              ;'
            PUSH    HL
            POP     IX
            RET
            EX      AF,AF'              ;'
            RET     NC
            EXX
            LD      HL,(BC.D012)
            EX      DE,HL
            LD      C,A
            LD      B,000H
            ADD     HL,BC
            DEC     HL
            LDDR
            LD      H,D
            LD      L,E
            INC     DE
            LD      (IX-03),D
            LD      (IX-04),E
            JP      BC.J056

BC.J057:    PUSH    BC
            PUSH    HL
            LD      HL,(BC.D029)
            EX      (SP),HL
            CALL    BC.C058
            EX      (SP),HL
            CALL    BC.C053+1
            LD      A,M
            PUSH    HL
            LD      HL,(BC.D029)
            PUSH    HL
            ADD     A,M
            LD      E,00FH
            JP      C,BC.J010
            CALL    BC.C068
            POP     DE
            CALL    BC.C085
            EX      (SP),HL
            CALL    BC.C084
            PUSH    HL
            LD      HL,(BC.D011)
            EX      DE,HL
            CALL    BC.C080
            CALL    BC.C080
            LD      HL,BC.D080
            EX      (SP),HL
            PUSH    HL
            JP      BC.J054

BC.C080:    POP     HL
            EX      (SP),HL
            LD      C,M
            INC     HL
            LD      B,M
            INC     HL
            LD      A,M
            INC     HL
            LD      H,M
            LD      L,A
            LD      A,B
            OR      C
            RET     Z
            LDIR
            RET

BC.C081:    LD      H,B
            LD      L,C
            LD      C,A
            LD      B,0
            JR      $-11

BC.C082:    CALL    BC.C053+1
BC.C083:    LD      HL,(BC.D029)
BC.C084:    EX      DE,HL
BC.C085:    CALL    BC.C086
            EX      DE,HL
            RET     NZ
            PUSH    DE
            LD      D,B
            LD      E,C
            DEC     DE
            LD      C,M
            LD      HL,(BC.D012)
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            JR      NZ,$+07
            LD      B,A
            ADD     HL,BC
            LD      (BC.D012),HL
            POP     HL
            RET

BC.C086:    LD      HL,(BC.D007)
            DEC     HL
            DEC     HL
            DEC     HL
            LD      B,M
            DEC     HL
            LD      C,M
            DEC     HL
            DEC     HL
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            RET     NZ
            LD      (BC.D007),HL
            RET

BC.LEN:     LD      BC,BC.D089          ;TOKEN:  L E N
            PUSH    BC
BC.C087:    CALL    BC.C082
            XOR     A
            LD      D,A
            LD      (BC.D004),A
            LD      A,M
            OR      A
            RET

BC.ASC:     CALL    BC.C087             ;TOKEN:  A S C
            JR      Z,$+90
            INC     HL
            INC     HL
            LD      E,M
            INC     HL
            LD      D,M
            LD      A,(DE)
            JP      BC.C064

BC.CHRD:    LD      A,001H              ;TOKEN:  C H R $
            CALL    BC.C068
            CALL    BC.C092
            LD      HL,(BC.D011)
            LD      M,E
BC.D093:    POP     BC
            JP      BC.J054

BC.LEFTD:   CALL    BC.C088             ;TOKEN:  L E F T $
            XOR     A
            EX      (SP),HL
            LD      C,A
            DB      03EH                ;LD  A,0E5H
BC.LFTD:    PUSH    HL
            PUSH    HL
            LD      A,M
            CP      B
            JR      C,$+04
            LD      A,B
            LD      DE,0000EH
            PUSH    BC
            CALL    BC.C077
            POP     BC
            POP     HL
            PUSH    HL
            INC     HL
            INC     HL
            LD      B,M
            INC     HL
            LD      H,M
            LD      L,B
            LD      B,000H
            ADD     HL,BC
            LD      B,H
            LD      C,L
            CALL    BC.C069
            CALL    BC.C081
            POP     DE
            CALL    BC.C085
            JP      BC.J054

BC.RGHTD:   CALL    BC.C088             ;TOKEN:  R I G H T $
            POP     DE
            PUSH    DE
            LD      A,(DE)
            SUB     B
            JR      $-51

BC.MIDD:    EX      DE,HL               ;TOKEN:  M I D $
            LD      A,M
            POP     DE
            LD      B,E
            INC     B
            DEC     B
            JP      Z,BC.J033
            PUSH    BC
            LD      E,0FFH
            CP      029H
            JR      Z,$+10
            LD      A,02CH
            CALL    BC.C006
            CALL    BC.C091
            LD      A,029H
            CALL    BC.C006
            POP     AF
            EX      (SP),HL
BC.D094:    DEC     A
            CP      M
            LD      B,000H
            JR      NC,$-84
            LD      C,A
            LD      A,M
            SUB     C
            CP      E
            LD      B,A
            JR      C,$-91
            LD      B,E
            JR      $-94

BC.INSTR:   POP     HL                  ;TOKEN:  I N S T R
            LD      A,028H
            CALL    BC.C006
            CALL    BC.C055
            LD      DE,(BC.D029)
            PUSH    DE
            LD      A,02CH
            CALL    BC.C006
            CALL    BC.C055
            LD      DE,(BC.D029)
            PUSH    DE
            LD      BC,BC.D001
            LD      A,M
            CP      02CH
            JR      NZ,$+23
            PUSH    BC
            CALL    BC.C090
            POP     BC
            DEC     E
            LD      B,E
            INC     E
            JR      Z,$-84
            LD      A,M
            CP      02CH
            JR      NZ,$+08
            PUSH    BC
            CALL    BC.C090
            POP     BC
            LD      C,E
            LD      A,029H
            CALL    BC.C006
            EX      (SP),HL
            PUSH    BC
            CALL    BC.C084
            POP     BC
            EX      DE,HL
            POP     HL
            EX      (SP),HL
            PUSH    DE
            PUSH    BC
            CALL    BC.C084
            POP     BC
            POP     DE
            LD      A,B
            SUB     M
            JP      NC,BC.J058
            NEG
            CP      C
            JR      NC,$+03
            LD      C,A
            INC     HL
            INC     HL
            LD      A,M
            INC     HL
            LD      H,M
            LD      L,A
            PUSH    HL
            PUSH    BC
            LD      C,B
            LD      B,000H
            ADD     HL,BC
            POP     BC
            EX      DE,HL
            LD      A,C
            SUB     M
            JR      C,$+58
            INC     A
            LD      C,A
            LD      B,M
            INC     HL
            INC     HL
            LD      A,M
            INC     HL
            LD      H,M
            LD      L,A
            EX      DE,HL
            LD      A,B
            OR      A
            JR      Z,$+31
            PUSH    BC
            LD      B,000H
            LD      A,(DE)
            CPIR
            LD      A,C
            POP     BC
            JR      NZ,$+34
            LD      C,A
            PUSH    BC
            PUSH    DE
            PUSH    HL
            JR      $+08
            INC     DE
            LD      A,(DE)
            CP      M
            JR      NZ,$+05
            INC     HL
            DJNZ    $-06
            POP     HL
            POP     DE
            POP     BC
            JR      NZ,$+11
            POP     DE
            SBC     HL,DE
            LD      A,L
            CALL    BC.C064
            POP     HL
            RET
            LD      A,C
            OR      A
            JR      NZ,$-40
            POP     DE
BC.J058:    XOR     A
            JR      $-11

BC.INP:     CALL    BC.C092             ;TOKEN:  I N P
            LD      C,A
            IN      A,(C)
            JP      BC.C064

BC.OUT:     CALL    BC.C089             ;TOKEN:  O U T
            OUT     (C),A
            RET

BC.WAIT:    CALL    BC.C089             ;TOKEN:  W A I T
            LD      B,A
            PUSH    BC
            LD      E,000H
            CALL    BC.C032
            JR      Z,$+10
            LD      A,02CH
            CALL    BC.C006
            CALL    BC.C091
            POP     BC
            IN      A,(C)
            XOR     E
            AND     B
            JR      Z,$-04
            RET

BC.C088:    EX      DE,HL
            LD      A,029H
            CALL    BC.C006
            POP     BC
            POP     DE
            PUSH    BC
            LD      B,E
            RET

BC.C089:    CALL    BC.C091
            PUSH    DE
            LD      A,02CH
            CALL    BC.C006
            JP      00003H              ;CALL    BC.C091
            POP     BC
            RET

BC.C090:    CALL    BC.C031
BC.C091:    CALL    BC.C052
BC.C092:    CALL    BC.C042
            LD      A,D
            OR      A
            JP      NZ,BC.J033
            CALL    BC.C032
            LD      A,E
            RET

BC.VAL:     CALL    BC.C087             ;TOKEN:  V A L
            JP      Z,BC.C112
            LD      E,A
            INC     HL
            INC     HL
            LD      A,M
            INC     HL
            LD      H,M
            LD      L,A
            PUSH    HL
            ADD     HL,DE
            LD      B,M
            LD      M,D
            EX      (SP),HL
            PUSH    BC
            LD      A,M
            CALL    BC.C141
            POP     BC
            POP     HL
            LD      M,B
            RET

BC.SWTCH:   JR      C,$+11              ;TOKEN:  S W I T C H
            CALL    BC.IOCHX
            XOR     003H
            LD      C,A
            JP      BC.IOSTX
            CALL    BC.C091
            CP      004H
            JP      NC,BC.J004
            LD      B,A
            CALL    BC.IOCHX
            AND     0FCH
            OR      B
            JR      $-19

BC.LWDTH:   CALL    BC.C097             ;TOKEN:  L W I D T H
BC.WIDTH:   CALL    BC.C091             ;TOKEN:  W I D T H
            CP      00EH
            JP      C,BC.J033
            LD      (IY+01),A
            LD      C,A
            SUB     00EH
            JR      NC,$-02
            ADD     A,01CH
            NEG
            ADD     A,C
            LD      (IY+02),A
            RET

BC.D095     EQU     $+1
BC.C093:    CALL    BC.C038
            JP      C,BC.J004
            LD      C,A
            LD      B,003H
            CALL    BC.RIV
            JR      C,$+29
            INC     A
            JR      NZ,$-08
            DJNZ    $-08
            CALL    BC.RIV
            JR      C,$+19
            INC     A
            JR      Z,$-06
            DEC     A
            CP      C
            JR      Z,$+07
            CALL    BC.C094
            JR      $-25
            LD      C,007H
            JP      BC.CON
            LD      E,013H
            JR      $+19

BC.C094:    LD      B,003H
            CALL    BC.C095
            OR      A
            JR      NZ,$-06
            DJNZ    $-06
            RET

BC.C095:    CALL    BC.RIV
            RET     NC
            LD      E,014H
            JP      BC.J010
            INC     D
            CALL    NZ,BC.C011
            JR      $-09

BC.SAVE:    CALL    BC.C038             ;TOKEN:  S A V E
            JP      C,BC.J004
            LD      C,A
            CALL    BC.C031
            JP      NZ,BC.J004
            PUSH    HL
            PUSH    BC
            LD      BC,BC.D073
            CALL    BC.WRTV
            DJNZ    $-03
            POP     BC
            CALL    BC.WRTV
            LD      HL,(BC.D024)
            EX      DE,HL
            LD      HL,(BC.D023)
            LD      C,M
            INC     HL
            CALL    BC.WRTV
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            JR      NZ,$-11
            LD      BC,BC.D073
BC.J059:    CALL    BC.WRTV
            DJNZ    $-03
            POP     HL
            RET

BC.LOAD:    CP      097H                ;TOKEN:  L O A D
            LD      D,0FFH
            JR      Z,$+13
            LD      (BC.D029),A
BC.J060:    CALL    BC.C011
            LD      D,000H
            LD      HL,BC.D028
            CALL    BC.C031
            CALL    BC.C093
            LD      HL,(BC.D023)
            LD      B,003H
            CALL    BC.RIV
            JR      C,$-94
            LD      E,A
            SUB     M
            AND     D
            JR      NZ,$+26
            LD      M,E
            CALL    BC.C005
            LD      A,M
            OR      A
            INC     HL
            JR      NZ,$-19
            DJNZ    $-19
            LD      (BC.D024),HL
            LD      A,(BC.D058)
            OR      A
            CALL    Z,BC.C047
            JP      BC.J017
            LD      E,015H
            JP      BC.J010

BC.ASAVE:   RET     NZ                  ;TOKEN:  A S A V E
            POP     HL
            LD      BC,BC.D073
            CALL    BC.WRTV
            DJNZ    $-03
            LD      HL,(BC.D023)
            LD      A,M
            INC     HL
            OR      M
            INC     HL
            JR      Z,$+51
            LD      E,M
            INC     HL
            LD      D,M
            INC     HL
            PUSH    HL
            CALL    BC.C062
            CALL    BC.C148
            INC     HL
            CALL    BC.C096
            POP     HL
            LD      A,M
            CP      009H
            JR      Z,$+07
            LD      C,020H
            CALL    BC.WRTV
            CALL    BC.C030
            PUSH    HL
            LD      HL,BC.D063
            CALL    BC.C096
            POP     HL
            LD      C,00DH
            CALL    BC.WRTV
            LD      C,00AH
            CALL    BC.WRTV
            JR      $-53
            LD      C,01AH
            CALL    BC.WRTV
            LD      BC,BC.D073
            CALL    BC.WRTV
            DJNZ    $-03
            JP      BC.J012

BC.C096:    LD      A,M
            OR      A
            RET     Z
            LD      C,A
            CALL    BC.WRTV
            INC     HL
            JR      $-08

BC.C097:    EX      DE,HL
            LD      HL,BC.D069
            EX      (SP),HL
            PUSH    HL
            EX      DE,HL
BC.C098:    LD      IY,BC.LISTX
            LD      (BC.D040),IY
            LD      IY,BC.D044
            RET

BC.RENB:    EX      AF,AF'              ;'TOKEN:  R E N U M B E R
            EX      DE,HL
            LD      HL,(BC.D019)
            LD      A,H
            AND     L
            INC     A
            JP      NZ,BC.J033
            LD      HL,(BC.D023)
            LD      A,M
            INC     HL
            OR      M
            EX      DE,HL
            JP      Z,BC.DATA+2
            LD      DE,0000AH
            PUSH    DE
            EX      AF,AF'              ;'
            CALL    C,BC.C034
            LD      (BC.D051),DE
            POP     DE
            CP      02CH
            JR      NZ,$+08
            CALL    BC.C031
            CALL    C,BC.C034
            LD      (BC.D050),DE
            PUSH    HL
            LD      HL,(BC.D023)
            INC     HL
            INC     HL
            LD      E,M
            INC     HL
            LD      D,M
            POP     HL
            CP      02CH
            JR      NZ,$+16
            CALL    BC.C031
            CALL    C,BC.C034
            LD      HL,(BC.D051)
            SBC     HL,DE
            JP      C,BC.J004
            LD      (BC.D059),DE
            OR      A
            JP      NZ,BC.J004
            CALL    BC.C009
            JP      NC,BC.J035
            LD      H,B
            LD      L,C
            EXX
            LD      DE,00001H
            LD      HL,00000H
            EXX
            LD      DE,0FFFFH
            CALL    BC.C010
            EXX
            DEC     HL
            EX      DE,HL
            LD      BC,(BC.D050)
            LD      A,B
            OR      C
            JP      Z,BC.J004
            CALL    BC.C140
            LD      DE,(BC.D051)
            ADD     HL,DE
            JP      C,BC.J049
            LD      HL,(BC.D023)
BC.J061:    INC     HL
            INC     HL
            LD      C,M
            INC     HL
            LD      B,M
            EX      DE,HL
            LD      HL,(BC.D059)
            SBC     HL,BC
            JR      C,$+08
            JR      Z,$+16
            LD      H,B
            LD      L,C
            JR      $+15

            LD      BC,(BC.D050)
            LD      HL,(BC.D047)
            ADD     HL,BC
            JR      $+05

            LD      HL,(BC.D051)
            LD      (BC.D047),HL
            EX      DE,HL
            CALL    BC.C031
BC.J062:    OR      A
            JP      Z,BC.J064
            CP      088H
            JR      Z,$+22
            CP      08CH
            JR      Z,$+18
            CP      0A2H
            JR      Z,$+14
            CP      0C9H
            JR      Z,$+10
            CP      09DH
            JR      Z,$+06
            CP      08BH
            JR      NZ,$-29
BC.J063:    CALL    BC.C031
            JR      NC,$-31
            LD      (BC.D048),HL
            DEC     HL
            LD      DE,00000H
            LD      C,000H
            CALL    BC.C031
            JR      NC,$+45
            PUSH    HL
            OR      A
            LD      HL,BC.D096
            SBC     HL,DE
            JR      NC,$+19
BC.D096     EQU     $+2
            LD      HL,BC.D125
            CALL    BC.C027
            CALL    BC.C099
            POP     HL
            CALL    BC.C031
            JR      C,$-03
            JR      $-71
            LD      H,D
            LD      L,E
            ADD     HL,HL
            ADD     HL,HL
            ADD     HL,DE
            ADD     HL,HL
            SUB     030H
            LD      E,A
            LD      D,000H
            ADD     HL,DE
            EX      DE,HL
            POP     HL
            INC     C
            JR      $-46
            LD      A,C
            LD      (BC.D049),A
            PUSH    HL
            LD      HL,(BC.D059)
            EX      DE,HL
            PUSH    HL
            SBC     HL,DE
            JR      C,$+44
            CALL    BC.C009
            LD      H,B
            LD      L,C
            POP     DE
            EXX
            LD      HL,(BC.D051)
            LD      DE,(BC.D050)
            EXX
            CALL    BC.C010
            JR      C,$+21
            LD      HL,BC.D124
            PUSH    DE
            CALL    BC.C027
            POP     HL
            CALL    BC.C147
            CALL    BC.C099
            POP     HL
            LD      A,M
            JP      BC.J062
            EXX
            PUSH    HL
            EXX
            POP     DE
            POP     HL
            XOR     A
            LD      B,098H
            CALL    BC.C124
            CALL    BC.C148
            LD      B,000H
            INC     HL
            PUSH    HL
            LD      A,M
            OR      A
            JR      Z,$+06
            INC     B
            INC     HL
            JR      $-06
            LD      A,(BC.D049)
            SUB     B
            JR      Z,$+62
            JR      C,$+30
            LD      C,A
            LD      B,000H
            LD      HL,(BC.D048)
            LD      D,H
            LD      E,L
            ADD     HL,BC
            PUSH    HL
            LD      HL,(BC.D024)
            SBC     HL,DE
            SBC     HL,BC
            LD      B,H
            LD      C,L
            POP     HL
            LDIR
            LD      (BC.D024),DE
            JR      $+32
            NEG
            LD      C,A
            LD      B,000H
            LD      HL,(BC.D024)
            LD      D,H
            LD      E,L
            ADD     HL,BC
            CALL    BC.C005
            LD      (BC.D024),HL
            EX      DE,HL
            PUSH    HL
            LD      BC,(BC.D048)
            SBC     HL,BC
            LD      B,H
            LD      C,L
            POP     HL
            LDDR
            POP     DE
            LD      HL,(BC.D048)
            LD      A,(DE)
            OR      A
            JR      Z,$+07
            LD      M,A
            INC     HL
            INC     DE
            JR      $-07
            PUSH    HL
            LD      HL,(BC.D023)
            EX      DE,HL
            CALL    BC.C007
            POP     HL
            LD      A,M
            CP      02CH
            JP      Z,BC.J063
            JP      BC.J062

BC.J064:    INC     HL
            OR      M
            INC     HL
            OR      M
            DEC     HL
            JP      NZ,BC.J061
            LD      DE,(BC.D059)
            CALL    BC.C009
            LD      H,B
            LD      L,C
            LD      BC,(BC.D050)
            LD      DE,(BC.D051)
            INC     HL
            INC     HL
            LD      M,E
            INC     HL
            LD      M,D
            INC     HL
            LD      A,M
            OR      A
            JR      NZ,$-03
            EX      DE,HL
            ADD     HL,BC
            EX      DE,HL
            INC     HL
            OR      M
            INC     HL
            OR      M
            JR      NZ,$-16
            CALL    BC.C013
            JP      BC.J012

BC.C099:    LD      HL,(BC.D047)
BC.C100:    CALL    BC.C146
            JP      BC.C048

BC.DELET:   CALL    BC.C008             ;TOKEN:  D E L E T E
            POP     DE
            PUSH    BC
            CALL    BC.C009
            JP      NC,BC.J033
            LD      D,H
            LD      E,L
            EX      (SP),HL
            PUSH    HL
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            JP      NC,BC.J033
            CALL    BC.C047
            POP     BC
            LD      HL,BC.D068
            EX      (SP),HL
            EX      DE,HL
            LD      HL,(BC.D024)
            LD      A,(DE)
            LD      (BC),A
            INC     BC
            INC     DE
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            JR      NZ,$-10
            LD      (BC.D024),BC
            RET

BC.LTRCE:   LD      A,07FH              ;TOKEN:  L T R A C E
            DB      1                   ;LD  BC,0BF3EH

BC.TRACE:   LD      A,0BFH
            PUSH    AF
            CALL    BC.C056
            CALL    BC.C032
            JR      NZ,$+22
            CALL    BC.C125
            DEC     A
            CPL
            LD      B,A
            POP     AF
            LD      C,A
            CPL
            AND     B
            LD      B,A
            LD      A,(BC.D052)
            AND     C
            OR      B
            LD      (BC.D052),A
            RET
            POP     AF
            JP      BC.J004

BC.EDIT:    CALL    BC.C034             ;TOKEN:  E D I T
            RET     NZ
            POP     HL
BC.J065:    CALL    BC.C009
            JP      NC,BC.J033
            LD      H,B
            LD      L,C
            INC     HL
            INC     HL
            LD      C,M
            INC     HL
            LD      B,M
            INC     HL
            PUSH    BC
            CALL    BC.C030
BC.J066:    POP     HL
            PUSH    HL
            CALL    BC.C147
            CALL    BC.C023
            LD      HL,BC.D063
            PUSH    HL
            LD      E,0FFH
            INC     E
            LD      A,M
            AND     07FH
            LD      M,A
            INC     HL
            JR      NZ,$-06
            POP     HL
            LD      D,A
BC.D097:    LD      B,000H
            CALL    BC.C028
            CP      03AH
            JR      NC,$+18
            CP      030H
            JR      C,$+14
            SUB     030H
            LD      C,A
            LD      A,B
            RLCA
            RLCA
            ADD     A,B
            RLCA
            ADD     A,C
            LD      B,A
            JR      $-21
            PUSH    HL
            LD      HL,BC.D097
            EX      (SP),HL
            DEC     B
            INC     B
            JR      NZ,$+03
            INC     B
            EXX
            LD      HL,BC.D098
            CP      M
            INC     HL
            LD      C,M
            INC     HL
            LD      B,M
            INC     HL
            PUSH    BC
            EXX
            RET     Z
            EXX
            POP     BC
            INC     M
            DEC     M
            JR      NZ,$-13
            CP      060H
            JR      C,$+06
            AND     05FH
            JR      $-24
            EXX
            LD      A,007H
            JP      BC.C026

            PAGE
BC.D098:    DB      ' '
            DW      BC.C101

            DB      'Q'                 ;QUIT
            DW      BC.EDQ

            DB      'L'                 ;LIST
            DW      BC.EDL

            DB      'F'                 ;FIND
            DW      BC.EDF

            DB      'I'                 ;INSERT
            DW      BC.EDI

            DB      'D'                 ;DELETE
            DW      BC.EDD

            DB      00DH                ;ET1  bzw.  POS_QUIT
            DW      BC.EDE1

            DB      'R'                 ;REPLACE
            DW      BC.EDR

            DB      'E'                 ;END
            DW      BC.EDE2

            DB      'X'                 ;am Ende anfuegen
            DW      BC.EDX

            DB      'K'                 ;KILL
            DW      BC.EDK

            DB      'H'                 ;ab Position loeschen und einfuegen
            DW      BC.EDH

            DB      7FH                 ;
            DW      BC.EDDEL

            DB      'A'                 ;edit_buf neu laden
            DW      BC.EDA

            DB      0

            PAGE
BC.EDA:     POP     BC
            POP     DE
            CALL    BC.C048
            JP      BC.J065

BC.C101:    LD      A,M
            OR      A
            RET     Z
            INC     D
            CALL    BC.C024
            INC     HL
            DJNZ    $-08
            RET

BC.EDK:     PUSH    HL
            LD      HL,BC.D100
            EX      (SP),HL
            SCF
BC.EDF:     PUSH    AF
            CALL    BC.C028
            LD      C,A
            POP     AF
            DEC     M
            INC     M
            RET     Z
            PUSH    AF
            CALL    C,BC.C102
            LD      A,M
            CALL    BC.C024
            POP     AF
            PUSH    AF
BC.D099     EQU     $+1
            JR      NC,$+07
            CALL    BC.C103
            JR      $+04
            INC     HL
            INC     D
            LD      A,M
            OR      A
            JR      Z,$+07
            CP      C
            JR      NZ,$-19
            DJNZ    $-21
            POP     AF
            RET

BC.EDL:     CALL    BC.C029
            CALL    BC.C048
            POP     BC
            JP      BC.J066

BC.EDD:     LD      A,M
            OR      A
            RET     Z
            LD      A,05CH
            CALL    BC.C026
            LD      A,M
            OR      A
            JR      Z,$+10
            CALL    BC.C024
            CALL    BC.C103
            DJNZ    $-10
BC.D100     EQU     $
BC.C102:    LD      A,05CH
            JP      BC.C026

BC.EDR:     LD      A,M
            OR      A
            RET     Z
            CALL    BC.C028
            CALL    BC.C024
            LD      M,A
            INC     HL
            INC     D
            DJNZ    $-12
            RET

BC.EDH:     LD      M,000H
            LD      E,D
BC.EDX:     LD      B,0FFH
            CALL    BC.C101
BC.EDI:     CALL    BC.C028
            CP      00DH
            JR      Z,$+74
            CP      01BH
            RET     Z
            CP      07FH
            JR      NZ,$+17
            DEC     D
            INC     D
            JR      Z,$+20
            DEC     HL
            DEC     D
            LD      A,M
            CALL    BC.C024
            CALL    BC.C103
            JR      $-27
            PUSH    AF
            LD      A,E
            CP      0FFH
            JR      C,$+10
            POP     AF
            LD      A,007H
            CALL    BC.C026
            JR      $-41
            SUB     D
            INC     E
            INC     D
            PUSH    DE
            EX      DE,HL
            LD      L,A
            LD      H,000H
            ADD     HL,DE
            LD      B,H
            LD      C,L
            INC     BC
            CALL    BC.C003
            POP     DE
            POP     AF
            CALL    BC.C024
            LD      M,A
            INC     HL
            JR      $-65

BC.EDDEL:   LD      A,D
            OR      A
            RET     Z
            DEC     D
            DEC     HL
            LD      A,M
            CALL    BC.C024
            DJNZ    $-09
            RET

BC.EDE1:    CALL    BC.C029
BC.EDE2:    CALL    BC.C048
            POP     BC
            POP     DE
            SCF
            PUSH    AF
            LD      HL,BC.D063
            JP      BC.J016

BC.C103:    PUSH    HL
            DEC     E
            LD      A,M
            OR      A
            JR      Z,$+09
            INC     HL
            LD      A,M
            DEC     HL
            LD      M,A
            INC     HL
            JR      $-09
            POP     HL
            RET

BC.RANDO:   RET     NZ                  ;TOKEN:  R A N D O M I Z E
            EX      DE,HL
            LD      HL,BC.D036
            LD      A,R
            LD      M,A
            INC     HL
            LD      M,A
            INC     HL
            LD      M,A
            INC     HL
            LD      M,A
            INC     HL
            AND     07FH
            LD      M,A
            INC     HL
            LD      M,080H
            EX      DE,HL
            RET

BC.LLVAR:   CALL    BC.C097             ;TOKEN:  L L V A R
BC.LVAR:    RET     NZ                  ;TOKEN:  L V A R
            PUSH    HL
            LD      HL,(BC.D024)
            CALL    BC.C048
            CALL    BC.C036
            LD      DE,(BC.D025)
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            JR      Z,$+61
            LD      C,M
            INC     HL
            LD      A,M
            INC     HL
            BIT     7,A
            JR      NZ,$+45
            CALL    BC.C026
            LD      A,C
            AND     07FH
            CALL    NZ,BC.C026
            LD      A,024H
            BIT     7,C
            CALL    NZ,BC.C026
            LD      A,03DH
            CALL    BC.C026
            LD      A,C
            RLA
            SBC     A,A
            LD      (BC.D029),HL
            PUSH    HL
            JR      NZ,$+11
            CALL    BC.C129
            CALL    BC.C148
            CALL    BC.C070
            CALL    BC.C076
            POP     HL
            INC     HL
            INC     HL
            INC     HL
            INC     HL
            INC     HL
            INC     HL
            JR      $-75
            POP     HL
            RET

BC.ALOAD:   CALL    BC.C011             ;TOKEN:  A L O A D
BC.AMRG:    LD      HL,(BC.D024)        ;TOKEN:  A M E R G E
            DEC     HL
            CALL    BC.C104
            JR      C,$+41
            JR      Z,$-05
            CP      07FH
            JR      Z,$-09
            INC     HL
            LD      M,A
            CALL    BC.C005
            LD      A,M
            SUB     00DH
            JR      NZ,$+21
            LD      M,A
            INC     HL
            LD      M,A
            INC     HL
            LD      M,A
            INC     HL
            LD      M,A
            CALL    BC.C104
            JR      C,$+13
            CP      00AH
            JR      Z,$-35
            OR      A
            JR      $-33
            CP      00DH
            JR      NZ,$-42
            LD      M,000H
            INC     HL
            LD      M,01AH
            LD      HL,(BC.D024)
BC.J067:    PUSH    HL
            LD      A,M
            SUB     01AH
            JR      NZ,$+11
            LD      (BC.D058),A
            CALL    BC.C012
            JP      BC.J012
            LD      A,M
            INC     HL
            OR      A
            JR      NZ,$-03
            LD      A,M
            INC     HL
            OR      A
            JR      Z,$-03
            DEC     HL
            LD      (BC.D047),HL
            POP     HL
            LD      A,0FFH
            LD      (BC.D058),A
            CALL    BC.C032
            INC     A
            DEC     A
            JP      Z,BC.J013
            JR      NC,$+07
            PUSH    AF
            XOR     A
            JP      BC.J015
            LD      E,018H
            JP      BC.J010

BC.C104:    CALL    BC.RIV
            RET     C
            AND     07FH
            RET

BC.ALODC:   CALL    BC.C011             ;TOKEN:  A L O A D C
BC.AMRGC:   LD      HL,BC.D062          ;TOKEN:  A M E R G E C
            LD      B,0
            CALL    BC.C104
            JR      C,$+52
            JR      Z,$-05
            CP      07FH
            JR      Z,$-09
            CP      01AH
            JR      Z,$+42
            CP      00AH
            JR      NZ,$+06
            INC     B
            DEC     B
            JR      Z,$-21
            LD      C,A
            LD      A,B
            CP      0FFH
            LD      A,C
            JR      Z,$+04
            INC     HL
            INC     B
            LD      M,A
            SUB     00DH
            JR      NZ,$-35
            LD      M,A
            LD      A,0FEH
            LD      (BC.D058),A
            LD      HL,BC.D062
            CALL    BC.C031
            INC     A
            DEC     A
            JR      Z,$-56
            JR      $-80
            CALL    BC.C012
            JP      BC.J012

BC.LOADG:   LD      (BC.D029),A         ;TOKEN:  L O A D G O
            CALL    BC.C031
            LD      DE,0FFFFH
            JR      Z,$+16
            LD      A,02CH
            CALL    BC.C006
            JP      NC,BC.J004
            CALL    BC.C034
            JP      NZ,BC.J004
            LD      (BC.D047),DE
            LD      A,0FDH
            LD      (BC.D058),A
            JP      BC.J060

BC.J068:    INC     A
            JP      Z,BC.J067
            INC     A
            JR      Z,$-108
            CALL    BC.C012
            XOR     A
            LD      (BC.D058),A
            LD      DE,(BC.D047)
            LD      A,D
            AND     E
            INC     A
            LD      BC,BC.D072
            PUSH    BC
            RET     Z
            JP      BC.J034

BC.COPY:    RET     Z                   ;TOKEN:  C O P Y
            JP      NC,BC.J033
            CALL    BC.C034
            LD      (BC.D047),DE
            LD      DE,0000AH
            CP      02CH
            JR      NZ,$+08
            CALL    BC.C031
            CALL    C,BC.C034
            LD      (BC.D048),DE
            LD      A,0ADH
            CALL    BC.C006
            CALL    BC.C008
            POP     DE
            PUSH    BC
            LD      H,B
            LD      L,C
            EXX
            LD      DE,00001H
            LD      HL,00000H
            EXX
            CALL    BC.C010
            JP      NC,BC.J033
            PUSH    HL
            EXX
            EX      DE,HL
            LD      BC,(BC.D048)
            LD      A,B
            OR      C
            JP      Z,BC.J004
            CALL    BC.C140
            LD      DE,(BC.D047)
            ADD     HL,DE
            JP      C,BC.J049
            PUSH    HL
            LD      DE,(BC.D047)
            CALL    BC.C009
            JP      C,BC.J033
            POP     DE
            PUSH    BC
            LD      H,B
            LD      L,C
            LD      A,M
            INC     HL
            OR      M
            JR      Z,$+12
            INC     HL
            LD      A,M
            INC     HL
            LD      H,M
            LD      L,A
            SBC     HL,DE
            JP      C,BC.J049
            POP     BC
            POP     HL
            POP     DE
            PUSH    HL
            SBC     HL,DE
            EX      (SP),HL
            DEC     HL
            SBC     HL,BC
            EX      DE,HL
            JR      C,$+12
            SBC     HL,BC
            JP      C,BC.J033
            ADD     HL,BC
            EX      DE,HL
            POP     HL
            PUSH    HL
            ADD     HL,DE
            EX      (SP),HL
            PUSH    HL
            LD      D,B
            LD      E,C
            LD      BC,(BC.D024)
            ADD     HL,BC
            PUSH    HL
            CALL    BC.C002
            POP     HL
            LD      (BC.D024),HL
            LD      H,B
            LD      L,C
            POP     BC
            EX      (SP),HL
            PUSH    DE
            LDIR
            POP     HL
            LD      BC,(BC.D047)
            INC     HL
            INC     HL
            LD      M,C
            INC     HL
            LD      M,B
            INC     HL
            LD      A,M
            OR      A
            JR      NZ,$-03
            INC     HL
            POP     DE
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            JR      Z,$+13
            PUSH    DE
            EX      DE,HL
            LD      HL,(BC.D048)
            ADD     HL,BC
            LD      B,H
            LD      C,L
            EX      DE,HL
            JR      $-29
            CALL    BC.C047
            JP      BC.J017

BC.EXCH:    CALL    BC.C060             ;TOKEN:  E X C H A N G E
            PUSH    DE
            PUSH    HL
            LD      HL,BC.D034
            CALL    BC.C134
            LD      HL,(BC.D025)
            EX      (SP),HL
            LD      A,(BC.D004)
            PUSH    AF
            LD      A,02CH
            CALL    BC.C006
            CALL    BC.C060
            POP     BC
            LD      A,(BC.D004)
            XOR     B
            RRA
            JP      C,BC.J042
            EX      (SP),HL
            EX      DE,HL
            PUSH    HL
            LD      HL,(BC.D025)
            LD      A,H
            SUB     D
            JR      NZ,$+04
            LD      A,L
            SUB     E
            JP      NZ,BC.J033
            POP     DE
            POP     HL
            EX      (SP),HL
            PUSH    DE
            CALL    BC.C134
            POP     HL
            LD      DE,BC.D034
            CALL    BC.C134
            POP     HL
            RET

BC.KILL:    LD      A,001H              ;TOKEN:  K I L L
            LD      (BC.D015),A
            JP      BC.C060

BC.J069:    PUSH    HL
            ADD     HL,DE
            EX      DE,HL
            LD      HL,(BC.D026)
            OR      A
            SBC     HL,DE
            EX      (SP),HL
            POP     BC
            EX      DE,HL
            DEC     DE
            DEC     DE
            DEC     DE
            DEC     DE
            JR      Z,$+04
            LDIR
            LD      (BC.D026),DE
BC.J070:    LD      (BC.D015),A
            POP     HL
            LD      A,M
            CP      02CH
            RET     NZ
            CALL    BC.C031
            JR      $-43

BC.CALL:    RET     Z                   ;TOKEN:  C A L L
            LD      (BC.D047),SP
            PUSH    HL
            LD      DE,BC.D101
            PUSH    DE
            CALL    BC.C041
            LD      C,000H
            PUSH    DE
            CALL    BC.C032
            JR      Z,$+18
            LD      A,02CH
            CALL    BC.C006
BC.CALL1:   INC     C
            PUSH    BC
            CALL    BC.C041
            POP     BC
            EX      DE,HL
            EX      (SP),HL
            EX      DE,HL
            JR      $-20

BC.CALL2:   PUSH    DE
            EX      DE,HL
            LD      HL,(BC.D047)
            DEC     HL
            LD      M,D
            DEC     HL
            LD      M,E
            DEC     HL
            DEC     HL
            RET

BC.D101:    POP     HL
            RET

BC.PREC:    LD      A,0                 ;TOKEN:  P R E C I S I O N
            CALL    NZ,BC.C091
            RET     NZ
            CP      00BH
            JR      Z,$-08
            JP      NC,BC.J033
            LD      (BC.D061),A
            RET

BC.PEEK:    CALL    BC.C042             ;TOKEN:  P E E K
            LD      A,(DE)
            JP      BC.C064

BC.POKE:    CALL    BC.C041             ;TOKEN:  P O K E
            PUSH    DE
            LD      A,02CH
            CALL    BC.C006
            CALL    BC.C091
            POP     DE
            LD      (DE),A
            RET

BC.C105:    LD      HL,BC.D114
BC.C106:    CALL    BC.C132
            JR      $+14

BC.D102     EQU     $
BC.C107:    CALL    BC.C132
            JR      $+06
            POP     BC
            POP     IX
            POP     DE
BC.C108:    CALL    BC.C126
BC.C109:    LD      A,B
            OR      A
            RET     Z
            LD      A,(BC.D032)
            OR      A
            JP      Z,BC.C130
            SUB     B
            JR      NC,$+19
            NEG
            EXX
            PUSH    IX
            CALL    BC.C131
            EXX
            EX      (SP),IX
            CALL    BC.C130
            EXX
            POP     IX
            CP      029H
            RET     NC
            PUSH    AF
            CALL    BC.C135
            LD      H,A
            POP     AF
            CALL    BC.C116
            OR      H
            LD      HL,BC.D029
            JP      P,BC.J071
            CALL    BC.C114
            JR      NC,$+107
            INC     HL
            INC     M
            JP      Z,BC.J075
            LD      L,001H
            CALL    BC.C117
            JR      $+95

BC.J071:    XOR     A
            SUB     B
            LD      B,A
            LD      A,M
            SBC     A,E
            LD      E,A
            INC     HL
            LD      A,M
            SBC     A,D
            LD      D,A
            INC     HL
            LD      A,M
            DB      0DDH,09DH           ; SBC     A,IXL
            DB      0DDH,06FH           ; LD      IXL,A
            INC     HL
            LD      A,M
            DB      0DDH,09CH           ; SBC     A,IXH
            DB      0DDH,067H           ; LD      IXH,A
            INC     HL
            LD      A,M
            SBC     A,C
            LD      C,A
BC.C110:    CALL    C,BC.C115
BC.D103     EQU     $
BC.C111:    LD      L,B
            LD      H,E
            XOR     A
            LD      B,A
            LD      A,C
            OR      A
            JR      NZ,$+41
            DB      0DDH,04CH           ; LD   C,IXH
            DB      0DDH,07DH           ; LD   A,IXL
            DB      0DDH,067H           ; LD   IXH,A
            DB      0DDH,06AH           ; LD   IXL,D
            XOR     A
            LD      D,H
            LD      H,L
            LD      L,A
            LD      A,B
            SUB     008H
            CP      0D0H
            JR      NZ,$-22
BC.C112:    XOR     A
BC.J072:    LD      (BC.D032),A
            RET

BC.J073:    DEC     B
            ADD     HL,HL
            RL      D
            EX      AF,AF'              ;'
            ADD     IX,IX
            EX      AF,AF'              ;'
            JR      NC,$+04
            INC     IX
            EX      AF,AF'              ;'
            RL      C
            JP      P,BC.J073
            LD      A,B
            LD      E,H
            LD      B,L
            OR      A
            JR      Z,$+10
            LD      HL,BC.D032
            ADD     A,M
            LD      M,A
            JR      NC,$-34
            RET     Z
            LD      A,B
BC.J074:    LD      HL,BC.D032
            OR      A
            CALL    M,BC.C113
            LD      B,M
            INC     HL
            LD      A,M
            AND     080H
            XOR     C
            LD      C,A
            JP      BC.C130

BC.C113:    INC     E
            RET     NZ
            INC     D
            RET     NZ
            DB      0DDH,02CH           ; INC  IXL
            RET     NZ
            DB      0DDH,024H           ; INC  IXH
            RET     NZ
            INC     C
            RET     NZ
            LD      C,080H
            INC     M
            RET     NZ
BC.J075:    LD      E,6
            JP      BC.J010

BC.C114:    LD      A,M
            ADD     A,E
            LD      E,A
            INC     HL
            LD      A,M
            ADC     A,D
            LD      D,A
            INC     HL
            LD      A,M
            DB      0DDH,08DH           ; ADC  A,IXL
            DB      0DDH,06FH           ; LD   IXL,A
            INC     HL
            LD      A,M
            DB      0DDH,08CH           ; ADC  A,IXH
            DB      0DDH,067H           ; LD   IXH,A
            INC     HL
            LD      A,M
            ADC     A,C
            LD      C,A
            RET

BC.C115:    LD      HL,BC.D033
            LD      A,M
            CPL
            LD      M,A
            XOR     A
            LD      L,A
            LD      H,A
            SUB     B
            LD      B,A
            LD      A,L
            SBC     HL,DE
            EX      DE,HL
            LD      L,A
            DB      0DDH,09DH           ; SBC  A,IXL
            DB      0DDH,06FH           ; LD   IXL,A
            LD      A,L
            DB      0DDH,09CH           ; SBC  A,IXH
            DB      0DDH,067H           ; LD   IXH,A
            LD      A,L
            SBC     A,C
            LD      C,A
            RET
;
BC.C116:    LD      B,0
            SUB     008H
            JR      C,$+18
            LD      B,E
            LD      E,D
            DB      0DDH,055H           ; LD   D,IXL
            EX      AF,AF'              ;'
            DB      0DDH,07CH           ; LD   A,IXH
            DB      0DDH,06FH           ; LD   IXL,A
            EX      AF,AF'              ;'
            DB      0DDH,061H           ; LD   IXH,C
            LD      C,0
            JR      $-18
;
            ADD     A,009H
            LD      L,A
            XOR     A
            DEC     L
            RET     Z
            LD      A,C
BC.C117:    RRA
            LD      C,A
            DB      0DDH,07CH           ; LD   A,IXH
            RRA
            DB      0DDH,067H           ; LD   IXH,A
            DB      0DDH,07DH           ; LD   A,IXL
            RRA
            DB      0DDH,06FH           ; LD   IXL,A
            RR      D
            RR      E
            RR      B
            JR      $-22

            PAGE
BC.D104:    DW      0
            DW      0
            DW      08100H


BC.D105:    DB      6                   ;Anzahl

            DW      08523H              ;erste Zahl
            DW      0C3ACH
            DW      07F11H

            DW      0CB53H              ;zweite
            DW      0B79EH
            DW      07F23H

            DW      0FECCH              ;dritte
            DW      00DA6H
            DW      07F53H

            DW      05CCBH              ;vierte
            DW      0BB60H
            DW      08013H

            DW      0E3DDH              ;fuenfte
            DW      0384EH
            DW      08076H

            DW      0295CH              ;sechste
            DW      0AA3BH
            DW      08238H

            PAGE
BC.LOG:     CALL    BC.C125             ;TOKEN:  L O G
            OR      A
            JP      PE,BC.J033
            LD      HL,BC.D032
            LD      A,M
            LD      BC,08035H
            LD      IX,BC.D067
            LD      DE,033FAH
            SUB     B
            PUSH    AF
            LD      M,B
            PUSH    DE
            PUSH    IX
            PUSH    BC
            CALL    BC.C109
            POP     BC
            POP     IX
            POP     DE
            INC     B
            CALL    BC.C120
            LD      HL,BC.D104
            CALL    BC.C107
            LD      HL,BC.D105
            CALL    BC.C164
            LD      BC,08080H
            LD      IX,00000H
            LD      DE,00000H
            CALL    BC.C109
            POP     AF
            CALL    BC.C142
            LD      BC,08031H
            LD      IX,07217H
            LD      DE,0F7D2H
            JR      $+06

BC.D106:    POP     BC
            POP     IX
            POP     DE
BC.C118:    CALL    BC.C125
            RET     Z
            LD      L,000H
            CALL    BC.C121
            LD      A,C
            PUSH    DE
            EXX
            LD      C,A
            POP     DE
            PUSH    IX
            POP     HL
            EXX
            LD      BC,00000H
            LD      D,B
            LD      E,B
            LD      IX,00000H
            LD      HL,BC.D103
            PUSH    HL
            LD      HL,BC.D107
            PUSH    HL
            PUSH    HL
            PUSH    HL
            PUSH    HL
            LD      HL,BC.D029
BC.D107:    LD      A,M
            INC     HL
            OR      A
            JR      NZ,$+16
            LD      B,E
            LD      E,D
            DB      0DDH,055H           ; LD   D,IXL
            EX      AF,AF'              ;'
            DB      0DDH,07CH           ; LD   A,IXH
            DB      0DDH,06FH           ; LD   IXL,A
            EX      AF,AF'              ;'
            DB      0DDH,061H           ; LD   IXH,C
            LD      C,A
            RET
            PUSH    HL
            EX      DE,HL
            LD      E,008H
            RRA
            LD      D,A
            LD      A,C
            JR      NC,$+20
            PUSH    HL
            EXX
            EX      (SP),HL
            ADD     HL,DE
            EX      (SP),HL
            EX      DE,HL
            PUSH    IX
            EX      (SP),HL
            ADC     HL,DE
            EX      (SP),HL
            POP     IX
            EX      DE,HL
            ADC     A,C
            EXX
            POP     HL
            RRA
            LD      C,A
            DB      0DDH,07CH           ; LD   A,IXH
            RRA
            DB      0DDH,067H           ; LD   IXH,A
            DB      0DDH,07DH           ; LD   A,IXL 
            RRA
            DB      0DDH,06FH           ; LD   IXL,A
            RR      H
            RR      L
            RR      B
            DEC     E
            LD      A,D
            JR      NZ,$-43
            EX      DE,HL
BC.J076:    POP     HL
            RET

BC.C119:    CALL    BC.C127
            LD      BC,08420H
            LD      IX,00000H
            LD      DE,00000H
            CALL    BC.C130
BC.J077:    POP     BC
            POP     IX
            POP     DE
BC.C120:    CALL    BC.C125
            JP      Z,BC.J005
            LD      L,0FFH
            CALL    BC.C121
            PUSH    IY
            INC     M
            INC     M
            DEC     HL
            PUSH    HL
            EXX
            POP     HL
            LD      C,M
            DEC     HL
            LD      D,M
            DEC     HL
            LD      E,M
            DEC     HL
            LD      A,M
            DEC     HL
            LD      L,M
            LD      H,A
            EX      DE,HL
            EXX
            LD      B,C
            EX      DE,HL
            PUSH    IX
            POP     IY
            XOR     A
            LD      C,A
            LD      D,A
            LD      E,A
            LD      IX,00000H
            LD      (BC.D060),A
            PUSH    HL
            PUSH    IY
            PUSH    BC
            PUSH    HL
            LD      A,B
            EXX
            EX      (SP),HL
            OR      A
            SBC     HL,DE
            EX      (SP),HL
            EX      DE,HL
            PUSH    IY
            EX      (SP),HL
            SBC     HL,DE
            EX      (SP),HL
            POP     IY
            EX      DE,HL
            SBC     A,C
            EXX
            POP     HL
            LD      B,A
            LD      A,(BC.D060)
            SBC     A,000H
            CCF
            JR      NC,$+11
            LD      (BC.D060),A
            POP     AF
            POP     AF
            POP     AF
            SCF
            JR      $+06
            POP     BC
            POP     IY
            POP     HL
            INC     C
            DEC     C
            RRA
            JP      M,BC.J078
            RLA
            RL      E
            RL      D
            EX      AF,AF'              ;'
            ADD     IX,IX
            EX      AF,AF'              ;'
            JR      NC,$+04
            INC     IX
            EX      AF,AF'              ;'
            RL      C
            ADD     HL,HL
            EX      AF,AF'              ;'
            ADD     IY,IY
            EX      AF,AF'              ;'
            JR      NC,$+04
            INC     IY
            EX      AF,AF'              ;'
            RL      B
            LD      A,(BC.D060)
            RLA
            LD      (BC.D060),A
            LD      A,C
            OR      D
            OR      E
            DB      0DDH,0B4H           ; OR   IXH
            DB      0DDH,0B5H           ; OR   IXL 
            JR      NZ,$-95
            PUSH    HL
            LD      HL,BC.D032
            DEC     M
            POP     HL
            JR      NZ,$-103
            JR      $+47

BC.J078:    POP     IY
            JP      BC.J074

BC.C121:    LD      A,B
            OR      A
            JR      Z,$+34
            LD      A,L
            LD      HL,BC.D032
            XOR     M
            ADD     A,B
            LD      B,A
            RRA
            XOR     B
            LD      A,B
            JP      P,BC.J080
            ADD     A,080H
            LD      M,A
            JP      Z,BC.J076
            CALL    BC.C135
            LD      M,A
            DEC     HL
            RET

BC.J079:    CALL    BC.C125
            CPL
            OR      A
            DB      21H
BC.J080:    OR      A
            POP     HL
            JP      P,BC.C112
            JP      BC.J075

BC.C122:    CALL    BC.C131
            LD      A,B
            OR      A
            RET     Z
            ADD     A,002H
            JR      C,$-11
            LD      B,A
            CALL    BC.C109
            LD      HL,BC.D032
            INC     M
            RET     NZ
            JR      $-22

BC.SGN:     CALL    BC.C125             ;TOKEN:  S G N
BC.C123:    LD      B,088H
            LD      DE,0
BC.C124:    LD      HL,BC.D032
            LD      C,A
            PUSH    DE
            POP     IX
            LD      DE,0
            LD      M,B
            LD      B,0
            INC     HL
            LD      M,080H
            RLA
            JP      BC.C110

BC.C125:    LD      A,(BC.D032)
            OR      A
            RET     Z
            LD      A,(BC.D031)
            DB      0FEH                ;CP   02FH
BC.J081:    CPL
            RLA
BC.J082:    SBC     A,A
            RET     NZ
            INC     A
            RET

BC.ABS:     CALL    BC.C125             ;TOKEN:  A B S
            RET     P
BC.D108     EQU     $
BC.C126:    LD      HL,BC.D031
            LD      A,M
            XOR     080H
            LD      M,A
            RET

BC.C127:    EX      DE,HL
BC.C128:    LD      HL,(BC.D029)
            EX      (SP),HL
            PUSH    HL
            LD      HL,(BC.D030)
            EX      (SP),HL
            PUSH    HL
            LD      HL,(BC.D031)
            EX      (SP),HL
            PUSH    HL
            EX      DE,HL
            RET

BC.C129:    LD      DE,BC.D029
            LD      BC,00006H
            LDIR
            RET

BC.C130:    LD      (BC.D029),DE
            LD      (BC.D030),IX
            LD      (BC.D031),BC
            RET

BC.C131:    LD      HL,BC.D029
BC.C132:    LD      E,M
            INC     HL
            LD      D,M
            INC     HL
            LD      C,M
            DB      0DDH,069H           ; LD   IXL,C 
            INC     HL
            LD      C,M
            DB      0DDH,061H           ; LD   IXH,C 
            INC     HL
            LD      C,M
            INC     HL
            LD      B,M
            INC     HL
            RET

BC.C133:    LD      DE,BC.D029
BC.C134:    LD      BC,00006H
            EX      DE,HL
            LDIR
            EX      DE,HL
            RET

BC.C135:    LD      HL,BC.D031
            LD      A,M
            RLCA
            SCF
            RRA
            LD      M,A
            CCF
            RRA
            INC     HL
            INC     HL
            LD      M,A
            LD      A,C
            RLCA
            SCF
            RRA
            LD      C,A
            RRA
            XOR     M
            RET

BC.C136:    LD      A,B
            OR      A
            JR      Z,$-121
            CALL    BC.C125
            LD      A,C
            JR      Z,$-118
            LD      HL,BC.D031
            XOR     M
            LD      A,C
            JP      M,BC.J081
            CALL    BC.C137
            RRA
            XOR     C
            JP      BC.J081

BC.C137:    INC     HL
            LD      A,B
            CP      M
            RET     NZ
            DEC     HL
            LD      A,C
            CP      M
            RET     NZ
            DEC     HL
            DB      0DDH,07CH           ; LD   A,IXH
            CP      (HL)
            RET     NZ
            DEC     HL
            DB      0DDH,07DH           ; LD   A,IXL 
            CP      (HL)
            RET     NZ
            DEC     HL
            LD      A,D
            CP      M
            RET     NZ
            DEC     HL
            LD      A,E
            SUB     M
            RET     NZ
            POP     HL
            RET

BC.C138:    LD      E,M
            INC     HL
            LD      D,M
            INC     HL
            LD      C,M
            INC     HL
            LD      B,M
            INC     HL
            RET

BC.C139:    LD      B,A
            LD      C,A
            LD      D,A
            LD      E,A
            DB      0DDH,067H           ; LD   IXH,A
            DB      0DDH,06FH           ; LD   IXL,A
            OR      A
            RET     Z
            PUSH    HL
            CALL    BC.C131
            CALL    BC.C135
            XOR     M
            LD      H,A
            JP      P,BC.J083
            DEC     DE
            LD      A,D
            AND     E
            INC     A
            JR      NZ,$+12
            DEC     IX
            DB      0DDH,07CH           ; LD   A,IXH
            DB      0DDH,0A5H           ; AND  IXL
            INC     A
            JR      NZ,$+03
            DEC     C
BC.J083:    LD      A,0A8H
            SUB     B
            CALL    BC.C116
            LD      A,H
            RLA
            CALL    C,BC.C113
            LD      B,000H
            CALL    C,BC.C115
            POP     HL
            RET

BC.D109     EQU     $
BC.INT:     LD      HL,BC.D032          ;TOKEN:  I N T
            LD      A,M
            CP      0A8H
            LD      A,(BC.D029)
            RET     NC
            LD      A,M
            CALL    BC.C139
            LD      M,0A8H
            LD      A,E
            PUSH    AF
            LD      A,C
            RLA
            CALL    BC.C110
            POP     AF
            RET

BC.C140:    LD      HL,0
            LD      A,B
            OR      C
BC.D110:    RET     Z
            LD      A,011H
            DEC     A
            RET     Z
            ADD     HL,HL
            JR      C,$+10
            EX      DE,HL
            ADD     HL,HL
            EX      DE,HL
            JR      NC,$-08
            ADD     HL,BC
            JR      NC,$-11
            JP      BC.J049

BC.C141:    CP      026H
            JP      Z,BC.J086
BC.J084:    CP      02DH
            PUSH    AF
            JR      Z,$+07
            CP      02BH
            JR      Z,$+03
            DEC     HL
            CALL    BC.C112
            LD      B,A
            LD      D,A
            LD      E,A
            CPL
            LD      C,A
            CALL    BC.C031
            JR      C,$+88
            CP      02EH
            JR      Z,$+40
            CP      045H
            JR      NZ,$+39
            CALL    BC.C031
            DEC     D
            CP      0A6H
            JR      Z,$+16
            CP      02DH
            JR      Z,$+12
            INC     D
            CP      02BH
            JR      Z,$+07
            CP      0A5H
            JR      Z,$+03
            DEC     HL
            CALL    BC.C031
            JR      C,$+75
            INC     D
            JR      NZ,$+09
            XOR     A
            SUB     E
            LD      E,A
            INC     C
            INC     C
            JR      Z,$-48
            PUSH    HL
            LD      A,E
            SUB     B
            JP      P,BC.J085
            CALL    BC.C127
            NEG
            LD      HL,BC.D104
            CALL    BC.C129
            SCF
BC.J085:    PUSH    AF
            CALL    BC.C143
            JR      NZ,$-03
            POP     AF
            JR      NC,$+09
            POP     BC
            POP     IX
            POP     DE
            CALL    BC.C120
            POP     DE
            POP     AF
            CALL    Z,BC.C126
            EX      DE,HL
            RET
            PUSH    DE
            LD      D,A
            LD      A,B
            ADC     A,C
            LD      B,A
            PUSH    BC
            PUSH    HL
            PUSH    DE
            CALL    BC.C122
            POP     AF
            SUB     030H
            CALL    BC.C142
            POP     HL
            POP     BC
            POP     DE
            JR      $-111
            LD      A,E
            ADD     A,A
            ADD     A,A
            ADD     A,E
            ADD     A,A
            ADD     A,M
            SUB     030H
            LD      E,A
            JR      $-87

BC.J086:    LD      DE,0
            CALL    BC.C031
            JR      Z,$+36
            JR      C,$+14
            SUB     041H
            JR      C,$+30
            CP      006H
            JR      NC,$+26
            ADD     A,00AH
            JR      $+04
            SUB     030H
            EX      AF,AF'              ;'
            LD      A,D
            CP      010H
            JP      NC,BC.J075
            EX      AF,AF'              ;'
            EX      DE,HL
            ADD     HL,HL
            ADD     HL,HL
            ADD     HL,HL
            ADD     HL,HL
            OR      L
            LD      L,A
            EX      DE,HL
            JR      $-37
            PUSH    HL
            CALL    BC.C062
            POP     HL
            RET

BC.C142:    CALL    BC.C127
            CALL    BC.C123
            POP     BC
            POP     IX
            POP     DE
            JP      BC.C109

BC.C143:    RET     Z
BC.C144:    PUSH    AF
            CALL    BC.C122
            POP     AF
            DEC     A
            RET

BC.C145:    PUSH    DE
            PUSH    HL
            PUSH    AF
            CALL    BC.C119
            POP     AF
            POP     HL
            POP     DE
            INC     A
            RET

BC.C146:    PUSH    HL
            LD      HL,BC.D127
            CALL    BC.C027
            POP     HL
BC.C147:    CALL    BC.C061
            LD      HL,BC.D061
            LD      A,M
            LD      M,000H
            PUSH    AF
            CALL    BC.C148
            POP     AF
            LD      (BC.D061),A
            JP      BC.J055

BC.C148:    XOR     A
BC.C149:    LD      (BC.D057),A
            LD      HL,BC.D035
            LD      M,020H
            AND     008H
            JR      Z,$+04
            LD      M,02BH
            CALL    BC.C125
            JP      P,BC.J087
            LD      M,02DH
            PUSH    HL
            CALL    BC.C126
            POP     HL
            OR      H
BC.J087:    INC     HL
            LD      M,030H
            LD      A,(BC.D057)
            LD      D,A
            RLA
            JP      C,BC.J092
            JP      Z,BC.J091
            PUSH    HL
            CALL    BC.C152
            LD      HL,BC.D061
            INC     M
            DEC     M
            JR      Z,$+83
            LD      D,A
            ADD     A,00BH
            JP      M,BC.J088
            CP      M
            JR      Z,$+04
            JR      NC,$+57
            LD      B,A
            LD      A,M
            SUB     B
            INC     A
            LD      C,A
            INC     B
            LD      A,D
            LD      D,00BH
            POP     HL
            INC     HL
            CALL    BC.C151
            PUSH    HL
            XOR     A
            LD      BC,00000H
            CPIR
            DEC     HL
            LD      BC,BC.D111
            PUSH    BC
            XOR     A
            PUSH    AF
            JR      $+73
BC.D111:    POP     HL
            LD      A,M
            CP      02DH
            RET     Z
            CP      020H
            RET     Z
            CP      030H
            JR      Z,$+12
            CP      025H
            JR      NZ,$+07
            INC     HL
            LD      A,M
            CP      02DH
            RET     Z
            DEC     HL
            LD      M,020H
            RET

BC.J088:    LD      C,M
            DEC     C
            JR      Z,$+03
            INC     C
            LD      B,002H
            POP     HL
            INC     HL
            LD      A,D
            LD      D,000H
            JP      BC.J098
            LD      BC,00300H
            ADD     A,00CH
            JP      M,BC.J089
            CP      00DH
            JR      NC,$+06
            INC     A
            LD      B,A
            LD      A,002H
BC.J089:    SUB     002H
            POP     HL
            PUSH    AF
            CALL    BC.C154
            LD      M,030H
            JR      NZ,$+03
            INC     HL
            CALL    BC.C156
            DEC     HL
            LD      A,M
            CP      030H
            JR      Z,$-04
            CP      02EH
            JR      Z,$+03
            INC     HL
            POP     AF
            JR      Z,$+28
BC.C150:    LD      M,'E'
            INC     HL
            LD      M,'+'
            JP      P,BC.J090
            LD      M,'-'
            NEG
BC.J090:    LD      B,02FH
            INC     B
            SUB     00AH
            JR      NC,$-03
            ADD     A,03AH
            INC     HL
            LD      M,B
            INC     HL
            LD      M,A
BC.J091:    INC     HL
            LD      M,000H
            EX      DE,HL
            LD      HL,BC.D035
            RET

BC.J092:    INC     HL
            PUSH    BC
            PUSH    HL
            LD      A,D
            RRA
            JP      C,BC.J097
            LD      BC,0B60EH
            LD      IX,BC.D099
            LD      DE,0BF04H
            CALL    BC.C136
            JP      M,BC.J093
            POP     HL
            POP     BC
            CALL    BC.C148
            DEC     HL
            LD      M,025H
            RET

BC.J093:    LD      D,00BH
            CALL    BC.C125
            CALL    NZ,BC.C152
            POP     HL
            POP     BC
            JP      M,BC.C151
            PUSH    BC
            LD      E,A
            LD      A,B
            SUB     D
            SUB     E
            CALL    P,BC.C157
            CALL    BC.C158
            CALL    BC.C156
            OR      E
            CALL    NZ,BC.C160
            OR      E
            CALL    NZ,BC.C154
            POP     DE
            LD      A,E
            OR      A
            JR      NZ,$+03
            DEC     HL
            DEC     A
            CALL    P,BC.C157
BC.J094:    PUSH    HL
            LD      HL,BC.D035
            LD      B,M
            LD      C,020H
            LD      A,(BC.D057)
            LD      E,A
            AND     020H
            JR      Z,$+09
            LD      A,B
            CP      C
            LD      C,02AH
            JR      NZ,$+03
            LD      B,C
            LD      M,C
            CALL    BC.C031
            JR      Z,$+18
            CP      045H
            JR      Z,$+14
            CP      030H
            JR      Z,$-12
            CP      02CH
            JR      Z,$-16
            CP      02EH
            JR      NZ,$+05
            DEC     HL
            LD      M,030H
            BIT     4,E
            JR      Z,$+05
            DEC     HL
            LD      M,024H
            BIT     2,E
            JR      NZ,$+04
            DEC     HL
            LD      M,B
            POP     HL
            JR      Z,$+04
            LD      M,B
            INC     HL
            LD      M,000H
            LD      HL,BC.D034
            INC     HL
            LD      A,(BC.D056)
            SUB     L
            SUB     D
            RET     Z
            LD      A,M
            CP      020H
            JR      Z,$-10
            CP      02AH
            JR      Z,$-14
            DEC     HL
            PUSH    HL
            PUSH    AF
            CALL    BC.C031
            CP      02DH
            JR      Z,$-06
            CP      02BH
            JR      Z,$-10
            CP      024H
            JR      Z,$-14
            CP      030H
            JR      NZ,$+18
            INC     HL
            CALL    BC.C031
            JR      NC,$+12
            DEC     HL
            LD      BC,0772BH
            POP     AF
            JR      Z,$-03
            POP     BC
            JR      $-51
            POP     AF
            JR      Z,$-01
            POP     HL
            LD      M,025H
            RET

BC.C151:    LD      E,A
            LD      A,C
            OR      A
            JR      Z,$+03
            DEC     A
            ADD     A,E
            JP      M,BC.J095
            XOR     A
BC.J095:    PUSH    BC
            PUSH    AF
            CALL    M,BC.C145
            JR      NZ,$-03
            POP     BC
            LD      A,E
            SUB     B
            POP     BC
            LD      E,A
            ADD     A,D
            LD      A,B
            JP      M,BC.J096
            SUB     D
            SUB     E
            CALL    P,BC.C157
            PUSH    BC
            CALL    BC.C158
            JR      $+19

BC.J096:    CALL    BC.C157
            LD      A,C
            CALL    BC.C155
            LD      C,A
            XOR     A
            SUB     D
            SUB     E
            CALL    BC.C157
            PUSH    BC
            LD      B,A
            LD      C,A
            CALL    BC.C156
            POP     BC
            OR      C
            JR      NZ,$+05
            LD      HL,(BC.D056)
            ADD     A,E
            DEC     A
            CALL    P,BC.C157
            LD      D,B
            JP      BC.J094

BC.J097:    CALL    BC.C125
            SCF
            CALL    NZ,BC.C152
            POP     HL
            POP     BC
BC.J098:    PUSH    AF
            LD      A,C
            OR      A
            PUSH    AF
            JR      Z,$+03
            DEC     A
            ADD     A,B
            LD      C,A
            LD      A,D
            AND     004H
            CP      001H
            SBC     A,A
            LD      D,A
            ADD     A,C
            LD      C,A
            SUB     00BH
            PUSH    AF
            PUSH    BC
BC.J099:    CALL    M,BC.C145
            JP      M,BC.J099
            POP     BC
            POP     AF
            PUSH    BC
            PUSH    AF
            JP      M,BC.J100
            XOR     A
BC.J100:    NEG
            ADD     A,B
            INC     A
            ADD     A,D
            LD      B,A
            LD      C,000H
            CALL    BC.C156
            POP     AF
            CALL    P,BC.C159
            POP     BC
            POP     AF
            JR      NZ,$+03
            DEC     HL
            POP     AF
            JR      C,$+06
            ADD     A,00BH
            SUB     B
            SUB     D
            PUSH    BC
            CALL    BC.C150
            EX      DE,HL
            POP     DE
            JP      BC.J094

BC.C152:    PUSH    DE
            XOR     A
            PUSH    AF
            CALL    BC.C153
BC.J101:    LD      BC,0A215H
            LD      IX,BC.D065
            LD      DE,0FFFDH
            CALL    BC.C136
            JP      P,BC.J103
            POP     AF
            CALL    BC.C144
            PUSH    AF
            JP      BC.J101

BC.J102:    POP     AF
            CALL    BC.C145
            PUSH    AF
            CALL    BC.C153
BC.J103:    POP     AF
            POP     DE
            RET

BC.C153:    LD      BC,0A53AH
            LD      IX,043B7H
            LD      DE,03FFCH
            CALL    BC.C136
            POP     HL
            JP      P,BC.J102
            JP      (HL)

BC.C154:    DEC     B
            JR      NZ,$+10
BC.C155:    LD      M,02EH
            LD      (BC.D056),HL
            INC     HL
            LD      C,B
            RET
            DEC     C
            RET     NZ
            LD      M,02CH
            INC     HL
            LD      C,003H
            RET

BC.C156:    PUSH    DE
            PUSH    BC
            PUSH    HL
            CALL    BC.C105
            INC     A
            CALL    BC.C139
            CALL    BC.C130
            POP     HL
            POP     BC
            LD      DE,BC.D112
            LD      A,00BH
            CALL    BC.C154
            PUSH    BC
            PUSH    AF
            PUSH    HL
            PUSH    DE
            CALL    BC.C131
            POP     HL
            LD      B,02FH
            INC     B
            LD      A,E
            SUB     M
            LD      E,A
            INC     HL
            LD      A,D
            SBC     A,M
            LD      D,A
            INC     HL
            DB      0DDH,07DH           ; LD   A,IXL 
            SBC     A,(HL)
            DB      0DDH,06FH           ; LD   IXL,A
            INC     HL
            DB      0DDH,07CH           ; LD   A,IXH
            SBC     A,(HL)
            DB      0DDH,067H           ; LD   IXH,A
            INC     HL
            LD      A,C
            SBC     A,M
            LD      C,A
            DEC     HL
            DEC     HL
            DEC     HL
            DEC     HL
            JR      NC,$-28
            CALL    BC.C114
            INC     HL
            CALL    BC.C130
            EX      DE,HL
            POP     HL
            LD      M,B
            INC     HL
            POP     AF
            POP     BC
            DEC     A
            JR      NZ,$-57
            CALL    BC.C154
            LD      M,A
            POP     DE
            RET

BC.D112:    DW      0E400H
            DW      0540BH
            DW      00002H

            DW      09ACAH
            DW      0003BH
            DW      0E100H

            DW      005F5H
            DW      08000H
            DW      09896H

            DW      00000H
            DW      04240H
            DW      0000FH

            DW      0A000H
            DW      00186H
            DW      00000H

            DW      02710H
            DW      00000H
            DW      0E800H

            DW      00003H
            DW      00000H
            DW      00064H

            DW      00000H
            DW      00A00H
            DW      00000H

            DW      00000H
            DW      00001H
            DW      00000H

            DB      0

BC.C157:    OR      A
            RET     Z
            DEC     A
            LD      M,030H
            INC     HL
            JR      $-06

BC.C158:    LD      A,E
            ADD     A,D
            INC     A
            LD      B,A
            INC     A
            SUB     003H
            JR      NC,$-02
            ADD     A,005H
            LD      C,A
            LD      A,(BC.D057)
            AND     040H
            RET     NZ
            LD      C,A
            RET

BC.C159:    JR      NZ,$+06
            RET     Z
            CALL    BC.C154
BC.C160:    LD      M,030H
            INC     HL
            DEC     A
            JR      $-08

BC.J104:    CALL    BC.C031
            JR      NC,$+32
            CALL    BC.C034
            PUSH    HL
            CALL    BC.C009
            JP      NC,BC.J035
            LD      H,B
            LD      L,C
            INC     HL
            INC     HL
            INC     HL
            CALL    BC.C031
            SUB     09CH
            JP      NZ,BC.J033
            LD      B,A
            CALL    BC.C072
            POP     HL
            JR      $+05
            CALL    BC.C055
            CALL    BC.C032
            SCF
            JR      Z,$+14
            CP      02CH
            JR      Z,$+07
            CP      03BH
            JP      NZ,BC.J004
            CALL    BC.C031
            EX      DE,HL
            LD      HL,(BC.D029)
            DB      1
BC.J105:    POP     DE
            EX      DE,HL
            PUSH    HL
            PUSH    AF
            PUSH    DE
            LD      B,M
            OR      B
            JP      Z,BC.J033
            INC     HL
            INC     HL
            LD      C,M
            INC     HL
            LD      H,M
            LD      L,C
            JP      BC.J107

BC.J106:    CALL    BC.C162
            CALL    BC.C026
BC.J107:    XOR     A
            LD      E,A
            LD      D,A
            CALL    BC.C162
            LD      D,A
            LD      A,M
            INC     HL
            CP      023H
            JP      Z,BC.J108
            CP      027H
            JP      Z,BC.J112
            DEC     B
            JP      Z,BC.J111
            CP      02BH
            LD      A,008H
            JR      Z,$-24
            DEC     HL
            LD      A,M
            INC     HL
            CP      02EH
            JP      Z,BC.J109
            CP      M
            JR      NZ,$-44
            CP      024H
            JR      Z,$+22
            CP      02AH
            JR      NZ,$-52
            LD      A,B
            CP      002H
            INC     HL
            JR      C,$+05
            LD      A,M
            CP      024H
            LD      A,020H
            JR      NZ,$+09
            DEC     B
            INC     E
            CP      0AFH
            ADD     A,010H
            INC     HL
            INC     E
            ADD     A,D
            LD      D,A
BC.J108:    INC     E
            LD      C,000H
            DEC     B
            JR      Z,$+72
            LD      A,M
            INC     HL
            CP      02EH
            JR      Z,$+25
            CP      023H
            JR      Z,$-14
            CP      02CH
            JR      NZ,$+27
            SET     6,D
            JR      $-22

BC.J109:    LD      A,M
            CP      023H
            LD      A,02EH
            JP      NZ,BC.J106
            LD      C,001H
            INC     HL
            INC     C
            DEC     B
            JR      Z,$+39
            LD      A,M
            INC     HL
            CP      023H
            JR      Z,$-08
            PUSH    DE
            LD      D,H
            LD      E,L
            CP      05EH
            JR      NZ,$+24
            CP      M
            JR      NZ,$+21
            INC     HL
            CP      M
            JR      NZ,$+17
            INC     HL
            CP      M
            JR      NZ,$+13
            INC     HL
            LD      A,B
            SUB     004H
            JR      C,$+07
            POP     DE
            LD      B,A
            INC     D
            INC     HL
            JP      Z,0D1EBH
            DEC     HL
            INC     E
            BIT     3,D
            JR      NZ,$+21
            DEC     E
            LD      A,B
            OR      A
            JR      Z,$+16
            LD      A,M
            SUB     02DH
            JR      Z,$+08
            CP      0FEH
            JR      NZ,$+07
            SET     3,D
            SET     2,D
            DEC     B
            POP     HL
            POP     AF
            JR      Z,$+83
            PUSH    BC
            PUSH    DE
            CALL    BC.C056
            POP     DE
            POP     BC
            PUSH    BC
            PUSH    HL
            LD      B,E
            LD      A,B
            ADD     A,C
            CP      019H
            JP      NC,BC.J033
            LD      A,D
            OR      080H
            CALL    BC.C149
            CALL    BC.C075
BC.J110:    POP     HL
            CALL    BC.C032
            SCF
            JR      Z,$+14
            CP      03BH
            JR      Z,$+07
            CP      02CH
            JP      NZ,BC.J004
            CALL    BC.C031
            POP     BC
            EX      DE,HL
            POP     HL
            PUSH    HL
            PUSH    AF
            PUSH    DE
            LD      A,M
            SUB     B
BC.D113:    INC     HL
            INC     HL
            LD      C,M
            INC     HL
            LD      H,M
            LD      L,C
            LD      D,000H
            LD      E,A
            ADD     HL,DE
            LD      A,B
            OR      A
            JP      NZ,BC.J107
            JR      $+08

BC.J111:    CALL    BC.C162
            CALL    BC.C026
            POP     HL
            POP     AF
            JP      NZ,BC.J105
            CALL    C,BC.C048
            EX      (SP),HL
            CALL    BC.C084
            POP     HL
            RET

BC.J112:    LD      C,001H
            LD      E,04CH
            DEC     B
            JR      Z,$+30
            LD      A,M
            INC     HL
            CP      045H
            JR      Z,$+14
            CP      052H
            JR      Z,$+10
            CP      04CH
            JR      Z,$+06
            CP      043H
            JR      NZ,$+12
            LD      E,A
            INC     C
            DEC     B
            JR      Z,$+07
            LD      A,M
            INC     HL
            CP      E
            JR      Z,$-07
            CALL    BC.C162
            POP     HL
            POP     AF
            JR      Z,$-49
            PUSH    BC
            PUSH    DE
            CALL    BC.C055
            POP     DE
            POP     BC
            PUSH    BC
            PUSH    HL
            LD      HL,(BC.D029)
            LD      B,C
            LD      C,000H
            LD      A,E
            CP      045H
            JR      Z,$+45
            PUSH    DE
            PUSH    BC
            CALL    BC.LFTD
            POP     BC
            POP     DE
            LD      A,B
            SUB     M
            LD      B,A
            LD      A,E
            CP      04CH
            JR      Z,$+16
            CP      052H
            JR      Z,$+23
            LD      A,B
            SRL     B
            SUB     B
            EX      AF,AF'              ;'
            CALL    BC.C161
            EX      AF,AF'              ;'
            LD      B,A
            PUSH    BC
            CALL    BC.C076
            POP     BC
            CALL    BC.C161
            JP      BC.J110

            XOR     A
            JR      $-18
            LD      A,B
            SUB     M
            JR      NC,$-17
            XOR     A
            JR      $-20

BC.C161:    INC     B
            DEC     B
            RET     Z
            CALL    BC.C023
            JR      $-05

BC.C162:    PUSH    AF
            LD      A,D
            OR      A
            LD      A,02BH
            CALL    NZ,BC.C026
            POP     AF
            RET

BC.C163:    LD      HL,BC.D108
            EX      (SP),HL
            JP      (HL)

BC.D114:    DW      00000H
            DW      00000H
            DW      08000H

BC.SQR:     CALL    BC.C127             ;TOKEN:  S Q R
            LD      HL,BC.D114
            CALL    BC.C129
            POP     BC
            POP     IX
            POP     DE
            CALL    BC.C125
            JR      Z,$+70
            LD      A,B
            OR      A
            JP      Z,BC.J072
            PUSH    DE
            PUSH    IX
            PUSH    BC
            LD      A,C
            OR      07FH
            CALL    BC.C131
            JP      P,BC.J113
            PUSH    DE
            PUSH    IX
            PUSH    BC
            CALL    BC.INT
            POP     BC
            POP     IX
            POP     DE
            PUSH    AF
            CALL    BC.C136
            POP     HL
            LD      A,H
            RRA
BC.J113:    POP     HL
            LD      (BC.D031),HL
            POP     HL
            LD      (BC.D030),HL
            POP     HL
            LD      (BC.D029),HL
            CALL    C,BC.C163
            CALL    Z,BC.C126
            PUSH    DE
            PUSH    IX
            PUSH    BC
            CALL    BC.LOG
            POP     BC
            POP     IX
            POP     DE
            CALL    BC.C118
BC.EXP:     LD      BC,08138H           ;TOKEN:  E X P
            LD      IX,0AA3BH
            LD      DE,BC.D113
            CALL    BC.C118
            LD      A,(BC.D032)
            CP      088H
            JP      NC,BC.J079
            CALL    BC.C127
            CALL    BC.INT
            POP     BC
            POP     IX
            POP     DE
            PUSH    AF
            CALL    BC.C108
            LD      HL,BC.D115
            CALL    BC.C165
            LD      HL,BC.D032
            POP     AF
            OR      A
            JP      M,BC.J114
            ADD     A,M
            DB      1
BC.J114:    ADD     A,(HL)
            CCF
            LD      M,A
            RET     NC
            JP      BC.J079


BC.D115:    DB      10

            DW      0D5CCH
            DW      05645H
            DW      06A15H

            DW      037CFH
            DW      092A0H
            DW      06D27H

            DW      095F5H
            DW      093EEH
            DW      07100H

            DW      0FCD0H
            DW      078A7H
            DW      07421H

            DW      021B1H
            DW      0C482H
            DW      0772EH

            DW      05882H
            DW      09558H
            DW      07A1DH

            DW      0CB6DH
            DW      05846H
            DW      07C63H

            DW      0FBE9H
            DW      0FDEFH
            DW      07E75H

            DW      0F7D2H
            DW      07217H
            DW      08031H

            DW      00000H
            DW      00000H
            DW      08100H


BC.C164:    CALL    BC.C127
            LD      DE,BC.D106
            PUSH    DE
            PUSH    HL
            CALL    BC.C131
            CALL    BC.C118
            POP     HL
BC.C165:    CALL    BC.C127
            LD      A,M
            INC     HL
            CALL    BC.C129
            CP      0F1H
            POP     BC
            POP     IX
            POP     DE
            DEC     A
            RET     Z
            PUSH    DE
            PUSH    IX
            PUSH    BC
            PUSH    AF
            PUSH    HL
            CALL    BC.C118
            POP     HL
            CALL    BC.C132
            PUSH    HL
            CALL    BC.C109
            POP     HL
            JR      $-25

BC.RND:     CALL    BC.C125             ;TOKEN:  R N D
            JP      M,BC.J115
            LD      HL,BC.D036
            CALL    BC.C129
            RET     Z
            LD      BC,09835H
            LD      IX,0447AH
            LD      DE,00000H
            CALL    BC.C118
            LD      BC,06828H
            LD      IX,0B146H
            LD      DE,00000H
            CALL    BC.C109
BC.J115:    CALL    BC.C131
            LD      A,E
            LD      E,C
            LD      C,A
            LD      M,080H
            DEC     HL
            LD      B,M
            LD      M,080H
            CALL    BC.C111
            LD      HL,BC.D036
            JP      BC.C133

BC.D116     EQU     $
BC.COS:     LD      HL,BC.D117          ;TOKEN:  C O S
            CALL    BC.C106
BC.SIN:     CALL    BC.C127             ;TOKEN:  S I N
            LD      BC,08349H
            LD      IX,BC.D083
            LD      DE,0A221H
            CALL    BC.C130
            POP     BC
            POP     IX
            POP     DE
            CALL    BC.C120
            CALL    BC.C127
            CALL    BC.INT
            POP     BC
            POP     IX
            POP     DE
            CALL    BC.C108
            LD      HL,BC.D118
            CALL    BC.C107
            CALL    BC.C125
            SCF
            JP      P,BC.J116
            CALL    BC.C105
            CALL    BC.C125
            OR      A
BC.J116:    PUSH    AF
            CALL    P,BC.C126
            LD      HL,BC.D118
            CALL    BC.C106
            POP     AF
            CALL    NC,BC.C126
            LD      HL,BC.D119
            JP      BC.C164


BC.D117:    DW      0A221H
            DW      00FDAH
            DW      08149H

BC.D118:    DW      00000H
            DW      00000H
            DW      07F00H



BC.D119:    DB      7


            DW      0BA90H
            DW      07634H
            DW      0826AH

            DW      0E9E4H
            DW      04BE7H
            DW      084F1H

            DW      04FB1H
            DW      03B7FH
            DW      08628H

            DW      0B631H
            DW      06964H
            DW      08799H

            DW      036E4H
            DW      035E3H
            DW      08723H

            DW      03124H
            DW      05DE7H
            DW      086A5H

            DW      0A221H
            DW      00FDAH
            DW      08349H



BC.TAN:     CALL    BC.C127             ;TOKEN:  T A N
            CALL    BC.SIN
            POP     BC
            POP     IX
            POP     DE
            CALL    BC.C128
            EX      DE,HL
            CALL    BC.C130
            CALL    BC.COS
            JP      BC.J077

BC.ATN:     CALL    BC.C125             ;TOKEN:  A T N
            CALL    M,BC.C163
            CALL    M,BC.C126
            LD      A,(BC.D032)
            CP      081H
            JR      C,$+18
            LD      BC,08100H
            LD      IX,00000H
            LD      D,C
            LD      E,C
            CALL    BC.C120
            LD      HL,BC.D102
            PUSH    HL
            LD      HL,BC.D120
            CALL    BC.C164
            LD      HL,BC.D117
            RET


BC.D120:    DB      13

            DW      00714H
            DW      0FEBAH
            DW      07562H

            DW      01651H
            DW      0D8CEH
            DW      078D6H

            DW      0BD4CH
            DW      0D17DH
            DW      07A3EH

            DW      0CB01H
            DW      0C423H
            DW      07BD7H

            DW      03ADCH
            DW      0170AH
            DW      07C34H

            DW      0C136H
            DW      081A3H
            DW      07CF7H

            DW      016EBH
            DW      0AE61H
            DW      07D19H

            DW      0785DH
            DW      0608FH
            DW      07DB9H

            DW      044A2H
            DW      07212H
            DW      07D63H

            DW      06216H
            DW      047FBH
            DW      07E92H

            DW      0F0C0H
            DW      0CCBFH
            DW      07E4CH

            DW      08E7EH
            DW      0AAAAH
            DW      07FAAH

            DW      0FFF6H
            DW      0FFFFH
            DW      0807FH

            PAGE
BC.D121:    DB      'EN'                ;"END"
            DB      44H+80H
            DB      'FO'                ;"FOR"
            DB      52H+80H
            DB      'NEX'               ;"NEXT"
            DB      54H+80H
            DB      'DAT'               ;"DATA"
            DB      41H+80H
            DB      'INPU'              ;"INPUT"
            DB      54H+80H
            DB      'DI'                ;"DIM"
            DB      4DH+80H
            DB      'REA'               ;"READ"
            DB      44H+80H
            DB      'LE'                ;"LET"
            DB      54H+80H
            DB      'GO T'              ;"GO TO"
            DB      4FH+80H
            DB      'FNEN'              ;"FNEND"
            DB      44H+80H
            DB      'I'                 ;"IF"
            DB      46H+80H
            DB      'RESTOR'            ;"RESTORE"
            DB      45H+80H
            DB      'GO SU'             ;"GO SUB"
            DB      42H+80H
            DB      'RETUR'             ;"RETURN"
            DB      4EH+80H
            DB      'RE'                ;"REM"
            DB      4DH+80H
            DB      'STO'               ;"STOP"
            DB      50H+80H
            DB      'OU'                ;"OUT"
            DB      54H+80H
            DB      'O'                 ;"ON"
            DB      4EH+80H
            DB      'NUL'               ;"NULL"
            DB      4CH+80H
            DB      'WAI'               ;"WAIT"
            DB      54H+80H
            DB      'DE'                ;"DEF"
            DB      46H+80H
            DB      'POK'               ;"POKE"
            DB      45H+80H
            DB      'PRIN'              ;"PRINT"
            DB      54H+80H
            DB      3FH+80H             ;"?"
BC.GRF2:    DB      'LISTE'             ;"LISTEN"
            DB      4EH+80H
            DB      'CLEA'              ;"CLEAR"
            DB      52H+80H
            DB      'FNRETUR'           ;"FNRETURN"
            DB      4EH+80H
            DB      'SAV'               ;"SAVE"
            DB      45H+80H
            DB      21H+80H             ;"!"
            DB      'USIN'              ;"USING"
            DB      47H+80H
            DB      'TAB'               ;"TAB("
            DB      28H+80H
            DB      'T'                 ;"TO"
            DB      4FH+80H
            DB      'F'                 ;"FN"
            DB      4EH+80H
            DB      'SPC'               ;"SPC("
            DB      28H+80H
            DB      'THE'               ;"THEN"
            DB      4EH+80H
            DB      'NO'                ;"NOT"
            DB      54H+80H
            DB      'STE'               ;"STEP"
            DB      50H+80H
            DB      2BH+80H             ;"+"
            DB      2DH+80H             ;"-"
            DB      2AH+80H             ;"*"
            DB      2FH+80H             ;"/"
            DB      5EH+80H             ;" "
            DB      'AN'                ;"AND"
            DB      44H+80H
            DB      'O'                 ;"OR"
            DB      52H+80H
            DB      3EH+80H             ;">"
            DB      3DH+80H             ;"="
            DB      3CH+80H             ;"<"
            DB      'SG'                ;"SGN"
            DB      4EH+80H
            DB      'IN'                ;"INT"
            DB      54H+80H
            DB      'AB'                ;"ABS"
            DB      53H+80H
            DB      'US'                ;"USR"
            DB      52H+80H
            DB      'FR'                ;"FRE"
            DB      45H+80H
            DB      'IN'                ;"INP"
            DB      50H+80H
            DB      'PO'                ;"POS"
            DB      53H+80H
            DB      'SQ'                ;"SQR"
            DB      52H+80H
            DB      'RN'                ;"RND"
            DB      44H+80H
            DB      'LO'                ;"LOG"
            DB      47H+80H
            DB      'EX'                ;"EXP"
            DB      50H+80H
            DB      'CO'                ;"COS"
            DB      53H+80H
            DB      'SI'                ;"SIN"
            DB      4EH+80H
            DB      'TA'                ;"TAN"
            DB      4EH+80H
            DB      'AT'                ;"ATN"
            DB      4EH+80H
            DB      'PEE'               ;"PEEK"
            DB      4BH+80H
            DB      'LE'                ;"LEN"
            DB      4EH+80H
            DB      'STR'               ;"STR$"
            DB      24H+80H
            DB      'VA'                ;"VAL"
            DB      4CH+80H
            DB      'AS'                ;"ASC"
            DB      43H+80H
            DB      'CHR'               ;"CHR$"
            DB      24H+80H
            DB      'LEFT'              ;"LEFT$"
            DB      24H+80H
            DB      'RIGHT'             ;"RIGHT$"
            DB      24H+80H
            DB      'MID'               ;"MID$"
            DB      24H+80H
            DB      'LPO'               ;"LPOS"
            DB      53H+80H
            DB      'INST'              ;"INSTR"
            DB      52H+80H
            DB      'ELS'               ;"ELSE"
            DB      45H+80H
            DB      'LPRIN'             ;"LPRINT"
            DB      54H+80H
            DB      'TRAC'              ;"TRACE"
            DB      45H+80H
            DB      'LTRAC'             ;"LTRACE"
            DB      45H+80H
            DB      'RANDOMIZ'          ;"RANDOMIZE"
            DB      45H+80H
            DB      'SWITC'             ;"SWITCH"
            DB      48H+80H
            DB      'LWIDT'             ;"LWIDTH"
            DB      48H+80H
            DB      'LNUL'              ;"LNULL"
            DB      4CH+80H
            DB      'WIDT'              ;"WIDTH"
            DB      48H+80H
            DB      'LVA'               ;"LVAR"
            DB      52H+80H
            DB      'LLVA'              ;"LLVAR"
            DB      52H+80H
BC.SVC2:    DB      'SPEA'              ;"SPEAK"
            DB      4BH+80H
            DB      27H+80H             ;"'"
            DB      'PRECISIO'          ;"PRECISION"
            DB      4EH+80H
            DB      'CAL'               ;"CALL"
            DB      4CH+80H
            DB      'KIL'               ;"KILL"
            DB      4CH+80H
            DB      'EXCHANG'           ;"EXCHANGE"
            DB      45H+80H
            DB      'LIN'               ;"LINE"
            DB      45H+80H
            DB      'LOADG'             ;"LOADGO"
            DB      4FH+80H
            DB      'RU'                ;"RUN"
            DB      4EH+80H
            DB      'LOA'               ;"LOAD"
            DB      44H+80H
            DB      'NE'                ;"NEW"
            DB      57H+80H
            DB      'AUT'               ;"AUTO"
            DB      4FH+80H
            DB      'COP'               ;"COPY"
            DB      59H+80H
            DB      'ALOAD'             ;"ALOADC"
            DB      43H+80H
            DB      'AMERGE'            ;"AMERGEC"
            DB      43H+80H
            DB      'ALOA'              ;"ALOAD"
            DB      44H+80H
            DB      'AMERG'             ;"AMERGE"
            DB      45H+80H
            DB      'ASAV'              ;"ASAVE"
            DB      45H+80H
            DB      'LIS'               ;"LIST"
            DB      54H+80H
            DB      'LLIS'              ;"LLIST"
            DB      54H+80H
            DB      'RENUMBE'           ;"RENUMBER"
            DB      52H+80H
            DB      'DELET'             ;"DELETE"
            DB      45H+80H
            DB      'EDI'               ;"EDIT"
            DB      54H+80H
            DB      'CON'               ;"CONT"
            DB      54H+80H
            NOP
BC.D122:    DW      537CH
BC.D123:    DB      'NEXT W/O FO'       ;"NEXT W/O FOR"
            DB      52H+80H
            DB      'SYNTAX ERRO'       ;"SYNTAX ERROR"
            DB      52H+80H
            DB      'RETURN W/O GOSU'   ;"RETURN W/O GOSUB"
            DB      42H+80H
            DB      'OUT OF DAT'        ;"OUT OF DATA"
            DB      41H+80H
            DB      'ILLEGAL FUNCTIO'   ;"ILLEGAL FUNCTION"
            DB      4EH+80H
            DB      'ARITHMETIC OVERFLO'
            DB      57H+80H
            DB      'OUT OF MEMOR'      ;"OUT OF MEMORY"
            DB      59H+80H
BC.D124:    DB      'UNDEFINED STATEMENT'
            DB      20H+80H
BC.D125:    DB      'SUBSCRIPT OUT OF RANG'
            DB      45H+80H
            DB      'RE-DIMENSIONED ARRA'
            DB      59H+80H
            DB      'CAN'
            DB      27H
            DB      'T /'
            DB      30H+80H
            DB      'ILLEGAL DIREC'
            DB      54H+80H
            DB      'TYPE MIS-MATC'
            DB      48H+80H
            DB      'NO STRING SPAC'
            DB      45H+80H
            DB      'STRING TOO LON'
            DB      47H+80H
            DB      'TOO COMPLE'
            DB      58H+80H
            DB      'CAN'
            DB      27H
            DB      'T CONTINU'
            DB      45H+80H
            DB      'UNDEFINED USER CAL'
            DB      4CH+80H
            DB      'FILE NOT FOUN'
            DB      44H+80H
            DB      'ILLEGAL EO'
            DB      46H+80H
            DB      'FILES DIFFEREN'
            DB      54H+80H
            DB      'RECOVERE'
            DB      44H+80H
            DB      'FNRETURN W/O FUNCTION CAL'
            DB      4CH+80H
            DB      'MISSING STATEMENT NUMBE'
            DB      52H+80H
BC.D126:    DB      '*INVALID INPUT'
            DB      0AH+80H
BC.D127:    DB      '   LINE'
            DB      20H+80H
BC.D128:    DB      0AH
            DB      'READY:'
            DB      0AH+80H
BC.D129:    DB      '*EXTRA LOST'
            DB      0AH+80H
BC.D130:    DB      0AH
            DB      '*BREA'
            DB      4BH+80H
            NOP

            PAGE
;****************************************************************
;*               Initialisierungsteil                           *
;****************************************************************
BC.D131     EQU     $
BC.J117:    CALL    BC.C048
            LD      HL,(BC.D122)
            CALL    BC.C147
            CALL    BC.C048
            LD      HL,BC.D133
            CALL    BC.C027
BC.D132     EQU     $
BC.J118:    XOR     A
            LD      HL,BC.D002
            CCF
            LD      M,A
            INC     L
            JR      NZ,$-02
            INC     H
            JR      C,$-06
            DEC     HL
            LD      SP,HL
            LD      (BC.D022),HL
            LD      HL,0FFFFH
            LD      (BC.D019),HL
            LD      A,02CH
            LD      (BC.D062),A
            LD      A,0C3H
            LD      (00000H),A
            LD      (BC.D039),A
            LD      (BC.D053),A
            LD      HL,BC.D132
            LD      (BC.D054),HL
            LD      IY,BC.D041
            LD      HL,BC.CON
            LD      (BC.D040),HL
            LD      A,048H
            LD      (BC.D042),A
            LD      (BC.D045),A
            LD      A,038H
            LD      (BC.D043),A
            LD      (BC.D046),A
BC.RECOV1:  LD      HL,BC.RECOV
            LD      (00001H),HL
            LD      HL,BC.D008
            LD      (BC.D007),HL
            LD      HL,08000H
            LD      (BC.D036),HL
            LD      (BC.D037),HL
            LD      (BC.D038),HL
            LD      HL,BC.D134
            CALL    BC.C027
            CALL    BC.C019
            CALL    BC.C031
            CP      041H
            JR      Z,$-115
            CPL
            CP      0ACH
            JP      Z,BC.J117
            INC     A
            JR      NZ,$+09
            CALL    BC.MEMCK
            LD      H,B
            LD      L,A
            JR      $+22                ;305C
;            
            LD      HL,BC.D063
            CALL    BC.C032
            CALL    BC.C141
            LD      A,M
            OR      A
            JP      NZ,BC.J004
            CALL    BC.C042
            EX      DE,HL
            DEC     HL
            DEC     HL
;305C            
            LD      (BC.D006),HL
            LD      (BC.D012),HL
            PUSH    HL
            LD      DE,00300H
            OR      A
            SBC     HL,DE
            POP     HL
;306A            
            JP      C,BC.J002
            LD      DE,0FF9CH           ;???
            ADD     HL,DE
            LD      DE,00300H
            LD      A,H
            SUB     D
            JR      NZ,$+04             ;307A
            LD      A,L
            SUB     E
;307A            
            LD      DE,BC.D131
            JR      NC,$+05             ;3082
            LD      DE,00300H
;3082            
            LD      A,H
            SUB     D
            JR      NZ,$+04             ;3088
            LD      A,L
            SUB     E
;3088            
            JR      C,$-30              ;306A
            LD      SP,HL
            LD      (BC.D022),HL
            EX      DE,HL
            LD      (BC.D023),HL
            CALL    BC.C005
            OR      A
            EX      DE,HL
            SBC     HL,DE
            LD      BC,0FFF0H
            ADD     HL,BC
            CALL    BC.C048
            CALL    BC.C147
            LD      HL,BC.D135
            CALL    BC.C027
            LD      HL,BC.D070
            LD      (BC.D054),HL
            CALL    BC.C011
BC.ANF:     JP      START               ;BC.J012

            PAGE
BC.D133:    DB      'DEG 2000  B  A  S  I  C   [K EAW  IfR/Fm]  '
            DB      'Stand: 10.82  '
            DB      0AH+80H
BC.D134:    DB      0AH
            DB      'max. Speicher'
            DB      20H+80H
BC.D135:    DB      ' Bytes frei            '
            DB      0AH
            DB      'DEG 2000  B A S I C         , Version 2.1'
            DB      '                 '
            DB      0AH+80H
            DS      0AFH,0
            DB      004H
            DS      00FH,0FFH
;
START:      LD      HL,ST01
            LD      DE,BC.D131
            LD      BC,000C0H
            LDIR
            JP      ST02
;            
            DS      2,0FFH
;            
ST01:       DB      4,030H,1,0
            DB      'OPEN'
            DB      '-'+080H
            DB      '&EAB6:CLOSE'
            DB      '-'+080H
            DB      '&EBB9:EIN'
            DB      '-'+080H
            DB      '73:AUS'
            DB      '-'+080H
            DB      '79:LESEN'
            DB      '-'+080H
            DB      '&EC1F:SCHREIBEN'
            DB      '-'+080H
            DB      '&EC4D:BLD'
            DB      '-'+080H
            DB      '&80',0
            DB      'j0',00AH,0,084H
            DB      '"Quell-/Ladedatei (Q/L)";A$:'
            DB      08AH
            DB      'A$',0AEH,0ACH
            DB      '"Q"',0AAH
            DB      'A$',0AEH,0ACH
            DB      '"L"',0A2H
            DB      '10:',0C9H,084H
            DB      '"Geraet,Label";G,L:',0D7H
            DB      'OPEN,G,EIN,L:',08AH
            DB      'A$',0ADH
            DB      '"Q"',0A2H,0E1H,':',0C9H
            DB      0DDH,041H,0,0,0,0
            DS      00AH,0FFH
;
ST02:       LD      HL,0306BH
            LD      (00150H),HL
            INC     HL
            LD      (0015EH),HL
            LD      (00160H),HL
            LD      (00162H),HL
            LD      HL,GRANA
            CALL    007BDH
            CALL    00309H
            LD      C,A
            CP      'J'
            JR      Z,ST04
ST03:       LD      C,'N'
            CALL    0030FH
            JP      BC.J012
;
ST04:       LD      A,(0010DH)
            CP      09CH
            JR      NC,ST03
            CALL    0030FH
            LD      A,081H
            OUT     (0C1H),A            ;!!! ???
            LD      A,0B3H
            OUT     (0C0H),A            ;!!! ???
            LD      HL,07400H
            LD      DE,09C00H
            LD      BC,00400H
            LDIR
            LD      A,0B7H
            OUT     (0C0H),A
            LD      A,085H
            OUT     (0C1H),A
            JP      BC.J012
;
GRANA:      DB      00AH,'Grafik nachladen ?',0A0H
            

            DS      0BEH,0FFH

            .DEPHASE

            END

